Repository cloudfoundry/stratos, pull requests merged in 2018-04, with the labels that each got.

#1841 Improve cf/org/space filters
  src/frontend/app/features/applications/create-application/create-application-step1/create-application-step1.component.html
  src/frontend/app/features/applications/create-application/create-application-step1/create-application-step1.component.scss
  src/frontend/app/features/applications/create-application/create-application-step1/create-application-step1.component.ts
  src/frontend/app/features/applications/create-application/create-application.component.html
  src/frontend/app/features/applications/create-application/create-application.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.module.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organizations.component.ts
  src/frontend/app/shared/components/cards/card-app-usage/card-app-usage.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/stateful-icon/stateful-icon.component.ts
  src/frontend/app/shared/components/stepper/step/step.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
  src/frontend/app/store/helpers/reducer.helper.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
Labels: ready for review

#1827 Ensure we retain the result of missing inline data that was fetched during an api call
  src/frontend/app/shared/components/cards/card-app-usage/card-app-usage.component.spec.ts
  src/frontend/app/store/helpers/reducer.helper.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
Labels: ready for review

#1820 List ux tweaks
  src/frontend/app/shared/components/list/list-cards/card/card.component.ts
  src/frontend/app/shared/components/list/list-cards/cards.component.html
  src/frontend/app/shared/components/list/list-cards/cards.component.spec.ts
  src/frontend/app/shared/components/list/list-cards/cards.component.ts
  src/frontend/app/shared/components/list/list-cards/cards.components.theme.scss
  src/frontend/app/shared/components/list/list-cards/custom-cards/endpoint-card/endpoint-card.component.ts
  src/frontend/app/shared/components/list/list-table/app-table-cell-default/app-table-cell-default.component.ts
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.ts
  src/frontend/app/shared/components/list/list-table/table-cell-edit/table-cell-edit.component.ts
  src/frontend/app/shared/components/list/list-table/table-cell-select/table-cell-select.component.ts
  src/frontend/app/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/app/shared/components/list/list-table/table-header-select/table-header-select.component.ts
  src/frontend/app/shared/components/list/list-table/table.types.ts
  src/frontend/app/shared/components/list/list-types/app-event/table-cell-event-action/table-cell-event-action.component.ts
  src/frontend/app/shared/components/list/list-types/app-event/table-cell-event-detail/table-cell-event-detail.component.ts
  src/frontend/app/shared/components/list/list-types/app-event/table-cell-event-timestamp/table-cell-event-timestamp.component.ts
  src/frontend/app/shared/components/list/list-types/app-event/table-cell-event-type/table-cell-event-type.component.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-instance/table-cell-usage/table-cell-usage.component.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-app-route/table-cell-app-route.component.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-radio/table-cell-radio.component.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-route/table-cell-route.component.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-tcproute/table-cell-tcproute.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/app/shared/components/list/list-types/app-variables/table-cell-edit-variable/table-cell-edit-variable.component.ts
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-instances/table-cell-app-instances.component.ts
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-name/table-cell-app-name.component.ts
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-status/table-cell-app-status.component.ts
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpack-card/cf-buildpack-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-card/cf-stacks-card.component.ts
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-status/table-cell-endpoint-status.component.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/components/list/list.types.ts
Labels: ready for review

#1843 Fix app-code-block copy
  src/frontend/app/shared/components/code-block/code-block.component.html
Labels: bug, ready for review

#1847 Stepper style tweaks
  src/frontend/app/shared/components/stepper/stepper-form/stepper-form.component.scss
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
Labels: ready for review

#1633 Minor fixes and table selection changes
  package-lock.json
  package.json
  src/frontend/app/features/applications/routes/map-routes/map-routes.component.ts
  src/frontend/app/features/applications/routes/routes.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-pagination-controller.ts
  src/frontend/app/shared/components/list/list-table/table-cell-edit/table-cell-edit.component.html
  src/frontend/app/shared/components/list/list-table/table-cell-edit/table-cell-edit.component.scss
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-map-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-data-source.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-radio/table-cell-radio.component.html
  src/frontend/app/shared/components/list/list-types/app-variables/cf-app-variables-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-reset-pagination.ts
Labels: ready for review

#1886 Fix service instances breadcrumb
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.ts
Labels: in review, ready for review

#1854 Removed all sharedReplay and replaced them with publishReplay(1) refCount.
  package.json
  src/frontend/app/core/entity-service.ts
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry.service.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/shared/monitors/entity-monitor.ts
  src/frontend/app/shared/monitors/pagination-monitor.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
Labels: in review, ready for review

#1888 Skip CF selection screen when redeploying
  src/frontend/app/features/applications/deploy-application/deploy-application.component.html
Labels: in review, ready for review

#1892 Show space roles
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.html
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-permission-cell/cf-user-permission-cell.component.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/actions/users.actions.ts
  src/frontend/app/store/reducers/users.reducer.ts
  src/frontend/app/store/types/user.types.ts
Labels: in review, ready for review

#1851 Alpha releases pipeline
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-nightly-releases.yml
  deploy/ci/tasks/dev-releases/create-chart-helper.sh
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/ci/tasks/dev-releases/create-nightly-chart.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
  deploy/ci/tasks/dev-releases/nightly-release-description
  deploy/ci/tasks/dev-releases/nightly-release-name
  deploy/ci/tasks/dev-releases/nightly-tag
  deploy/ci/tasks/dev-releases/update-gh-nightly-release.yml
  deploy/ci/tasks/dev-releases/update-gh-release.yml
  deploy/kubernetes/README.md
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#1903 Minor changes
  src/frontend/app/core/core.module.ts
  src/frontend/app/core/dot-content/dot-content.component.html
  src/frontend/app/core/dot-content/dot-content.component.scss
  src/frontend/app/core/dot-content/dot-content.component.spec.ts
  src/frontend/app/core/dot-content/dot-content.component.theme.scss
  src/frontend/app/core/dot-content/dot-content.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/app/features/uaa-setup/uaa-wizard/console-uaa-wizard.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpack-card/cf-buildpack-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpack-card/cf-buildpack-card.component.scss
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
  src/frontend/app/shared/components/stepper/steppers/steppers.component.theme.scss
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#1885 Empty list message - bugs and improvements
  src/frontend/app/features/applications/application-wall/application-wall.component.scss
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/applications/application/application-base.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/events-tab/events-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/github-tab/github-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/instances-tab/instances-tab.component.scss
  src/frontend/app/features/applications/application/application-tabs-base/tabs/instances-tab/instances-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/log-stream-tab/log-stream-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/services-tab/services-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/services-tab/services-tab.component.scss
  src/frontend/app/features/applications/application/application-tabs-base/tabs/services-tab/services-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.ts
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.scss
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/styles.scss
Labels: ready for review

#1852 Small improvements, bugs, tweaks
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/shared/components/boolean-indicator/boolean-indicator.component.scss
  src/frontend/app/shared/components/chips/chips.component.html
  src/frontend/app/shared/components/chips/chips.component.scss
  src/frontend/app/shared/components/chips/chips.component.theme.scss
  src/frontend/app/shared/components/chips/chips.component.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.theme.scss
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#1922 Reset Helm repository
  index.yaml
Labels: cowbell, ready for review

#1891 Modify org space fixes
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.html
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.scss
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.html
  src/frontend/app/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.html
  src/frontend/app/shared/components/cards/card-app-usage/card-app-usage.component.html
  src/frontend/app/shared/components/cards/card-app-usage/card-app-usage.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
Labels: ready for review

#1897 Fix two cf/org/space select bugs in deploy modal
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/applications/create-application/create-application-step1/create-application-step1.component.ts
  src/frontend/app/features/applications/create-application/create-application.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.ts
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
Labels: ready for review

#1756 Log Viewer: Towards V1 parity
  src/frontend/app/core/utils.service.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/log-stream-tab/log-stream-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/log-stream-tab/log-stream-tab.component.scss
  src/frontend/app/features/applications/application/application-tabs-base/tabs/log-stream-tab/log-stream-tab.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.scss
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.theme.scss
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose-formatter.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose.component.scss
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose.component.theme.scss
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose.component.ts
  src/frontend/app/shared/components/log-viewer/ansi-colorizer.ts
  src/frontend/app/shared/components/log-viewer/ansi-colors.ts
  src/frontend/app/shared/components/log-viewer/log-viewer.component.html
  src/frontend/app/shared/components/log-viewer/log-viewer.component.scss
  src/frontend/app/shared/components/log-viewer/log-viewer.component.theme.scss
  src/frontend/app/shared/components/log-viewer/log-viewer.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
  src/frontend/assets/fonts/SourceCodePro-Bold.woff2
  src/frontend/assets/fonts/SourceCodePro-Regular.woff2
  src/frontend/sass/_all-theme.scss
  src/frontend/sass/ansi-colors.scss
  src/frontend/sass/fonts.scss
Labels: ready for review

#1926 Fix modal sizing with css
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/applications/application/application-base.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/events-tab/events-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/github-tab/github-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/instances-tab/instances-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/log-stream-tab/log-stream-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/services-tab/services-tab.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.ts
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.scss
  src/frontend/styles.scss
Labels: ready for review

#1928 Service catalogue fixes
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-services-list-config.service.ts
Labels: ready for review

#1930 Fix issue with compilation on newer SCSS parser
  src/frontend/app/shared/components/log-viewer/log-viewer.component.theme.scss
Labels: ready for review

#1902 Display Space Users
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-users/cloud-foundry-space-users.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-users/cloud-foundry-space-users.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-users/cloud-foundry-space-users.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-users/cloud-foundry-organization-users.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-users/cloud-foundry-organization-users.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-users/cloud-foundry-organization-users.component.ts
  src/frontend/app/shared/components/list/list-types/cf-org-users/cf-org-users-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-org-users/cf-org-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-users/cf-space-users-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-space-users/cf-space-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/store/actions/organization.actions.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/test-framework/cloud-foundry-organization.service.mock.ts
  src/frontend/app/test-framework/cloud-foundry-space.service.mock.ts
Labels: blocked-pr, cowbell, ready for review

#1899 Show splash screen
  src/frontend/app/core/auth-guard.service.ts
  src/frontend/app/features/login/login-page/login-page.component.html
  src/frontend/app/features/login/login-page/login-page.component.scss
  src/frontend/app/features/login/login-page/login-page.component.ts
Labels: in review, ready for review

#1900 Local pagination performance
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-list-controller.helpers.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-list-controller.spec.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-list-controller.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/monitors/pagination-monitor.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-set-result-count.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination.reducer.ts
Labels: cowbell, ready for review

#1850 List Animations
  package-lock.json
  package.json
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.spec.ts
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.ts
  src/frontend/app/shared/components/list/list-table/table.component.html
  src/frontend/app/shared/components/list/list-table/table.component.ts
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/polyfills.ts
Labels: cowbell, ready for review

#1883 Fix Breadcrumb links for compact-app-card component
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/shared/components/cards/card-cf-recent-apps/compact-app-card/compact-app-card.component.html
  src/frontend/app/shared/components/cards/card-cf-recent-apps/compact-app-card/compact-app-card.component.ts
Labels: ready for review

#1932 Add Upgrade notice and tweaks to setup screen
  src/frontend/app/app.module.ts
  src/frontend/app/app.routing.ts
  src/frontend/app/core/auth-guard.service.ts
  src/frontend/app/features/login/login-page/login-page.component.html
  src/frontend/app/features/login/login-page/login-page.component.scss
  src/frontend/app/features/login/login-page/login-page.component.ts
  src/frontend/app/features/setup/setup.module.ts
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.scss
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.spec.ts
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.ts
  src/frontend/app/features/setup/upgrade-page/upgrade-page.component.html
  src/frontend/app/features/setup/upgrade-page/upgrade-page.component.scss
  src/frontend/app/features/setup/upgrade-page/upgrade-page.component.spec.ts
  src/frontend/app/features/setup/upgrade-page/upgrade-page.component.ts
  src/frontend/app/features/uaa-setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/app/features/uaa-setup/uaa-wizard/console-uaa-wizard.component.scss
  src/frontend/app/shared/components/intro-screen/intro-screen.component.html
  src/frontend/app/shared/components/intro-screen/intro-screen.component.scss
  src/frontend/app/shared/components/intro-screen/intro-screen.component.spec.ts
  src/frontend/app/shared/components/intro-screen/intro-screen.component.ts
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/page-header/page-header.component.html
  src/frontend/app/shared/components/page-header/page-header.component.ts
  src/frontend/app/shared/components/stratos-title/stratos-title.component.html
  src/frontend/app/shared/components/stratos-title/stratos-title.component.scss
  src/frontend/app/shared/components/stratos-title/stratos-title.component.spec.ts
  src/frontend/app/shared/components/stratos-title/stratos-title.component.theme.scss
  src/frontend/app/shared/components/stratos-title/stratos-title.component.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/auth.actions.ts
  src/frontend/app/store/effects/auth.effects.ts
  src/frontend/app/store/reducers/auth.reducer.ts
  src/frontend/app/store/types/auth.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#1844 Ensure the side nav is correctly set to the mobile state
  src/frontend/app/app.component.ts
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.ts
Labels: ready for review

#1940 Handle '+' character
  src/frontend/app/helper.ts
  src/frontend/app/store/effects/endpoint.effects.ts
Labels: P1, ready for review

#1939 Use custom Echo logger to hide query params
  deploy/tools/restart_proxy.sh
  src/backend/app-core/main.go
Labels: P1, ready for review

#1948 App metrics updates
  src/frontend/app/app.routing.ts
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/app/features/metrics/metrics.routing.ts
  src/frontend/app/features/metrics/metrics/metrics.component.html
  src/frontend/app/features/metrics/metrics/metrics.component.ts
  src/frontend/app/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-name/table-cell-endpoint-name.component.html
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-name/table-cell-endpoint-name.component.scss
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-name/table-cell-endpoint-name.component.spec.ts
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-name/table-cell-endpoint-name.component.ts
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-status/table-cell-endpoint-status.component.spec.ts
Labels: in review, ready for review

#1949 Support new scf-config-values format
  deploy/kubernetes/console/templates/__helpers.tpl
  deploy/kubernetes/console/templates/service.yaml
  deploy/kubernetes/console/values.yaml
Labels: V2, ready for review

#1953 Fixed recently connected endpoints not showing up in the cf endpoint list
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry.service.ts
  src/frontend/app/shared/monitors/entity-monitor.ts
  src/frontend/app/shared/monitors/pagination-monitor.ts
Labels: ready for review

#1739 Fix width of top nav bar menu's bottom border
  components/app-core/frontend/src/view/navbar/navbar.scss
Labels: V1, ready for review

#1951 About page
  src/frontend/app/app.module.ts
  src/frontend/app/app.routing.ts
  src/frontend/app/features/about/about-page/about-page.component.html
  src/frontend/app/features/about/about-page/about-page.component.scss
  src/frontend/app/features/about/about-page/about-page.component.spec.ts
  src/frontend/app/features/about/about-page/about-page.component.ts
  src/frontend/app/features/about/about.module.ts
  src/frontend/app/features/about/about.routing.ts
  src/frontend/app/shared/components/page-header/page-header.component.html
  src/frontend/app/shared/components/page-header/page-header.component.scss
  src/frontend/app/shared/components/page-header/page-header.component.theme.scss
  src/frontend/sass/_all-theme.scss
Labels: in review, ready for review

#1958 Fix typo in setup screen
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.html
Labels: ready for review

#1960 Fix the position of the buildpack number
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpack-card/cf-buildpack-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpack-card/cf-buildpack-card.component.scss
Labels: ready for review

#1966 Fix the dot indicator component to use the standard status colors fro…
  src/frontend/app/shared/components/boolean-indicator/boolean-indicator.component.theme.scss
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#1956 CF Push Fixes
  build/bk-prepare-build.js
  deploy/Dockerfile.all-in-one
  deploy/cloud-foundry/build.sh
  deploy/cloud-foundry/package.sh
  manifest.yml
  package.json
  package.json.combined
  src/backend/app-core/datastore/database_cf_config.go
  src/backend/app-core/main.go
  src/backend/app-core/migrator.go
Labels: ready for review

#1957 Ensure we don't replace the noramlized org space param with the denormalized object
  src/frontend/app/store/helpers/entity-factory.ts
Labels: ready for review

#1969 Address setup screen bugs
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.scss
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.spec.ts
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.ts
  src/frontend/app/shared/components/loading-page/loading-page.component.html
  src/frontend/app/shared/components/loading-page/loading-page.component.scss
  src/frontend/app/shared/components/loading-page/loading-page.component.ts
Labels: ready for review

#1967 CF connect -> app wall, no cf endpoints messages and list alignment fixes.
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/services-tab/services-tab.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry.service.ts
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/app/features/endpoints/endpoints-page/endpoints-page.component.html
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.html
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.ts
  src/frontend/app/shared/components/endpoints-missing/endpoints-missing.component.html
  src/frontend/app/shared/components/endpoints-missing/endpoints-missing.component.scss
  src/frontend/app/shared/components/endpoints-missing/endpoints-missing.component.spec.ts
  src/frontend/app/shared/components/endpoints-missing/endpoints-missing.component.ts
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/components/no-content-message/no-content-message.component.scss
  src/frontend/app/shared/data-services/cloud-foundry.service.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/test-framework/cloud-foundry-endpoint-service.helper.ts
Labels: in review, ready for review

#1954 Ensure we add guid/cfGuid to items in an entity's arrays
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/types/api.types.ts
Labels: ready for review

#1968 App Instance Fixes
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/shared/components/cards/card-app-instances/card-app-instances.component.ts
  src/frontend/app/shared/components/cards/card-app-usage/card-app-usage.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-list-controller.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/monitors/pagination-monitor.ts
  src/frontend/app/store/effects/update-app-effects.ts
  src/frontend/app/store/reducers/app-stats-request.reducer.ts
Labels: ready for review

#1947 App Link should not have hover state
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.scss
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.scss
Labels: in review, ready for review

#1982 Full height fix for create routes
  src/frontend/app/features/applications/routes/add-route-stepper/add-route-stepper.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
Labels: in review, ready for review

#1977 Fixes for a few small UX issues
  src/frontend/app/features/applications/ssh-application/ssh-application.component.html
  src/frontend/app/shared/components/dialog-confirm/dialog-confirm.component.scss
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/components/ssh-viewer/ssh-viewer.component.theme.scss
Labels: in review, ready for review

#1859 Basic script to setup cf environment
  deploy/tools/populate-cf/cf-summit-april-2018.sh
  deploy/tools/populate-cf/create-many-apps.sh
  deploy/tools/populate-cf/create-many-spaces.sh
Labels: ready for review

#1983 Tidy about page
  src/frontend/app/features/about/about-page/about-page.component.html
  src/frontend/app/features/about/about-page/about-page.component.scss
  src/frontend/app/shared/components/page-header/page-header.component.html
  src/frontend/app/shared/components/page-header/page-header.component.scss
  src/frontend/app/shared/components/page-header/page-header.component.theme.scss
  src/frontend/app/shared/components/page-header/page-header.component.ts
  src/frontend/sass/components/hyperlinks.theme.scss
  src/frontend/sass/oss-theme.scss
Labels: in review, ready for review

#1989 Stratos Helm chart: Make UAA_HOST optional to support new SCF Values format
  deploy/kubernetes/console/templates/__helpers.tpl
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
Labels: V1, ready for review

#1988 Stratos Helm chart: Make UAA_HOST optional to support new SCF Values format
  deploy/kubernetes/console/templates/__helpers.tpl
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
Labels: V2, ready for review

#1995 Fix UAA Endpoint typo in Helm chart
  deploy/kubernetes/console/templates/__helpers.tpl
Labels: V1, ready for review

#1994 Fix UAA Endpoint typo in Helm chart
  deploy/kubernetes/console/templates/__helpers.tpl
Labels: V2, ready for review

#1980 Move Routes from App Summary tab to its own tab
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.scss
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/routes-tab/routes-tab/routes-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/routes-tab/routes-tab/routes-tab.component.scss
  src/frontend/app/features/applications/application/application-tabs-base/tabs/routes-tab/routes-tab/routes-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/routes-tab/routes-tab/routes-tab.component.ts
  src/frontend/app/features/applications/applications.module.ts
  src/frontend/app/features/applications/applications.routing.ts
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.html
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/app/features/applications/routes/routes.component.html
  src/frontend/app/features/applications/routes/routes.component.scss
  src/frontend/app/features/applications/routes/routes.component.spec.ts
  src/frontend/app/features/applications/routes/routes.component.ts
  src/frontend/app/features/applications/routes/routes.helper.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
Labels: in review, ready for review

#1990 Orgs/Spaces: Add color status bar and change value color when limits are reached
  src/frontend/app/shared/components/application-state/application-state.service.ts
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.html
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.spec.ts
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.ts
Labels: ready for review

#2013 Fix for cf/org/space filters in production mode
  src/frontend/app/shared/components/list/list.component.ts
Labels: ready for review

#1979 Ensure we clear service catalog on cf connect, disconnect and unregister
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/app/features/endpoints/endpoint-helpers.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/store/actions/endpoint.actions.ts
  src/frontend/app/store/effects/endpoint.effects.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-clear-pagination-type.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/app/store/types/endpoint.types.ts
Labels: ready for review

#2012 Update schema for Metrics
  src/backend/app-core/datastore/20180413135700_MetricsSchema.go
Labels: P1, ready for review

#2015 When sorting, avoid casting numbers to strings
  src/frontend/app/shared/components/list/data-sources-controllers/local-filtering-sorting.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
Labels: ready for review

#2018 Fix missing buildpacks due to page size.
  src/frontend/app/store/actions/buildpack.action.ts
  src/frontend/app/store/actions/stack.action.ts
Labels: ready for review

#1996 Button blur, singular card metrics labels + top align user roles
  src/frontend/app/core/button-blur-on-click.directive.spec.ts
  src/frontend/app/core/button-blur-on-click.directive.ts
  src/frontend/app/core/core.module.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-users/cloud-foundry-space-users.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.html
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.html
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.ts
  src/frontend/app/shared/components/list/list-table/table.component.html
  src/frontend/app/shared/components/list/list-table/table.types.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.types.ts
Labels: ready for review

#2020 Add list filtering/sorting where possible
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpacks-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpacks-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-orgs-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-orgs-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-spaces-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-spaces-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/store/actions/application-service-routes.actions.ts
  src/frontend/app/store/actions/buildpack.action.ts
  src/frontend/app/store/actions/feature-flags.actions.ts
  src/frontend/app/store/actions/organization.actions.ts
  src/frontend/app/store/actions/security-groups-actions.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/actions/stack.action.ts
  src/frontend/app/store/actions/users.actions.ts
Labels: ready for review

#1993 Fix exception thrown when polling on app summary
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.ts
  src/frontend/app/store/effects/api.effects.ts
Labels: ready for review

#2021 Fix when we set the page count in lists.
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-list-controller.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
Labels: in review, ready for review

#2027 Remove fdescribe
  src/frontend/app/core/button-blur-on-click.directive.spec.ts
Labels: ready for review

#2023 Firehose: Fix creation of empty divs when a filter is applied
  src/frontend/app/shared/components/log-viewer/log-viewer.component.ts
Labels: ready for review

#2026 Fix Space Services app link
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.ts
Labels: in review, ready for review

#2031 Disable SSH action if disabled at the App level
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.html
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/shared/components/list/list.component.types.ts
Labels: in review, ready for review

#2045 Only enable the close button when the app has been created
  src/frontend/app/features/applications/deploy-application/deploy-application.component.html
  src/frontend/app/shared/components/stepper/step/step.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
Labels: ready for review

#2038 Guard against spaces being null in recent-apps component
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/reducers/organization-space.reducer.ts
Labels: in review, ready for review

#2037 Update app name validation when we enter the step
  src/frontend/app/features/applications/create-application/create-application-step2/create-application-step2.component.html
  src/frontend/app/features/applications/create-application/create-application-step2/create-application-step2.component.ts
  src/frontend/app/features/applications/create-application/create-application.component.html
  src/frontend/app/shared/components/stepper/step/step.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
Labels: ready for review

#2047 Support deploying from a commit in a branch
  src/backend/cfapppush/deploy.go
  src/backend/cfapppush/vcs.go
Labels: ready for review

#2029 V1 Parity - Add CF App CLI Command help
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/applications/applications.module.ts
  src/frontend/app/features/applications/applications.routing.ts
  src/frontend/app/features/applications/cli-info-application/cli-info-application.component.html
  src/frontend/app/features/applications/cli-info-application/cli-info-application.component.scss
  src/frontend/app/features/applications/cli-info-application/cli-info-application.component.spec.ts
  src/frontend/app/features/applications/cli-info-application/cli-info-application.component.ts
  src/frontend/app/shared/components/code-block/code-block.component.html
  src/frontend/app/shared/components/code-block/code-block.component.scss
  src/frontend/app/shared/components/code-block/code-block.component.ts
Labels: comments-addressed, ready for review

#2049 Ensure close button is enabled when there is an error. Refresh app li…
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.html
  src/frontend/app/shared/components/list/list-types/app/cf-apps-data-source.ts
  src/frontend/app/shared/components/stepper/step/step.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
  src/test-e2e/screenshots/screenshots.e2e-spec.ts
Labels: in review, ready for review

#2039 Fix stepper layout issues - content will now scroll
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.scss
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
Labels: in review, ready for review

#2064 Log Viewer: Fix duplicate websocket connections
  src/frontend/app/shared/components/log-viewer/log-viewer.component.ts
Labels: ready for review

#2057 Handle special characters when logging in
  src/frontend/app/store/effects/auth.effects.ts
Labels: ready for review

#2035 Small ux fixes
  src/frontend/app/features/applications/app-name-unique.directive/app-name-unique.directive.ts
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/applications/create-application/create-application-step2/create-application-step2.component.html
  src/frontend/app/features/applications/create-application/create-application-step3/create-application-step3.component.html
  src/frontend/app/features/applications/create-application/create-application-step3/create-application-step3.component.ts
  src/frontend/app/features/applications/create-application/create-application.component.html
  src/frontend/app/features/applications/ssh-application/ssh-application.component.html
  src/frontend/app/features/applications/ssh-application/ssh-application.component.ts
  src/frontend/app/shared/components/cards/card-app-instances/card-app-instances.component.html
  src/frontend/app/shared/components/cards/card-app-instances/card-app-instances.component.ts
  src/frontend/app/shared/components/cards/card-app-uptime/card-app-uptime.component.html
  src/frontend/app/shared/components/cards/card-app-uptime/card-app-uptime.component.ts
  src/frontend/app/shared/components/cards/card-app-usage/card-app-usage.component.ts
  src/frontend/app/shared/components/code-block/code-block.component.html
  src/frontend/app/shared/components/code-block/code-block.component.scss
  src/frontend/app/test-framework/application-service-helper.ts
Labels: comments-addressed, in review, ready for review

#2054 Internal app events
  package-lock.json
  src/frontend/app/features/about/about-page/about-page.component.scss
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.html
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.html
  src/frontend/app/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.html
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.ts
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.spec.ts
  src/frontend/app/shared/components/list/list-table/table-row/table-row-state-manager.spec.ts
  src/frontend/app/shared/components/list/list-table/table-row/table-row-state-manager.ts
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.scss
  src/frontend/app/shared/components/list/list-types/endpoint/endpoint-data-source.helpers.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-data-source.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/page-header/page-header-events/page-header-events.component.html
  src/frontend/app/shared/components/page-header/page-header-events/page-header-events.component.scss
  src/frontend/app/shared/components/page-header/page-header-events/page-header-events.component.spec.ts
  src/frontend/app/shared/components/page-header/page-header-events/page-header-events.component.theme.scss
  src/frontend/app/shared/components/page-header/page-header-events/page-header-events.component.ts
  src/frontend/app/shared/components/page-header/page-header.component.html
  src/frontend/app/shared/components/page-header/page-header.component.scss
  src/frontend/app/shared/components/page-header/page-header.component.spec.ts
  src/frontend/app/shared/components/page-header/page-header.component.theme.scss
  src/frontend/app/shared/components/page-header/page-header.component.ts
  src/frontend/app/shared/components/page-header/page-header.module.ts
  src/frontend/app/shared/components/page-header/page-header.types.ts
  src/frontend/app/shared/components/page-subheader/page-subheader.component.scss
  src/frontend/app/shared/components/page-subheader/page-subheader.component.theme.scss
  src/frontend/app/shared/monitors/internal-event-monitor.factory.spec.ts
  src/frontend/app/shared/monitors/internal-event-monitor.factory.ts
  src/frontend/app/shared/monitors/internal-event.monitor.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/application.actions.ts
  src/frontend/app/store/actions/dashboard-actions.ts
  src/frontend/app/store/actions/internal-events.actions.ts
  src/frontend/app/store/app-state.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/effects/set-client-filter.effect.ts
  src/frontend/app/store/reducers.module.ts
  src/frontend/app/store/reducers/dashboard-reducer.ts
  src/frontend/app/store/reducers/internal-events.reducer.ts
  src/frontend/app/store/selectors/internal-events.selectors.ts
  src/frontend/app/store/types/internal-events.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
  src/frontend/sass/_all-theme.scss
Labels: in review, ready for review

#2060 Add User Profile to app menu and show same metadata as V1
  src/frontend/app/app.routing.ts
  src/frontend/app/features/user-profile/profile-info/profile-info.component.html
  src/frontend/app/features/user-profile/profile-info/profile-info.component.scss
  src/frontend/app/features/user-profile/profile-info/profile-info.component.spec.ts
  src/frontend/app/features/user-profile/profile-info/profile-info.component.ts
  src/frontend/app/features/user-profile/user-profile.module.ts
  src/frontend/app/features/user-profile/user-profile.routing.ts
  src/frontend/app/shared/components/chips/chips.component.html
  src/frontend/app/shared/components/chips/chips.component.ts
  src/frontend/app/shared/components/metadata-item/metadata-item.component.scss
  src/frontend/app/shared/components/page-header/page-header.component.html
  src/frontend/app/shared/components/user-profile-banner/user-profile-banner.component.html
  src/frontend/app/shared/components/user-profile-banner/user-profile-banner.component.scss
  src/frontend/app/shared/components/user-profile-banner/user-profile-banner.component.spec.ts
  src/frontend/app/shared/components/user-profile-banner/user-profile-banner.component.theme.scss
  src/frontend/app/shared/components/user-profile-banner/user-profile-banner.component.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/user-profile.actions.ts
  src/frontend/app/store/app-state.ts
  src/frontend/app/store/effects/user-profile.effects.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/reducers/api-request-reducers.generator.ts
  src/frontend/app/store/store.module.ts
  src/frontend/app/store/types/user-profile.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#2087 Update readme for switching default branch to v2-master
  README.md
  docs/images/screenshots/app-summary.png
Labels: ready for review
