Repository cloudfoundry/stratos, pull requests merged in 2018-12, with the labels that each got.

#3133 Update app instance cell data when scaling up
  src/frontend/app/features/endpoints/endpoint-helpers.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/store/effects/app.effects.ts
  src/frontend/app/store/reducers/routes.reducer.ts
Labels: comments-addressed, ready for review

#3161 Fix issue where only first 100 services were shown in service marketplace
  src/frontend/app/store/actions/pagination.actions.ts
  src/frontend/app/store/actions/service.actions.ts
Labels: bug, ready for review

#3231 Add Route: Use correct label for submit button
  src/frontend/app/features/applications/routes/add-route-stepper/add-route-stepper.component.html
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/app/store/types/route.types.ts
Labels: in review, ready for review

#3237 Fix CLI info formatting
  src/frontend/app/shared/components/cli-info/cli-info.component.html
  src/frontend/app/shared/components/code-block/code-block.component.html
  src/frontend/app/shared/components/code-block/code-block.component.scss
  src/frontend/app/shared/components/code-block/code-block.component.theme.scss
Labels: in review, ready for review

#3246 Improve resilience of a couple of e2e tests
  src/frontend/app/shared/components/chips/chips.component.html
  src/test-e2e/cloud-foundry/users-list-e2e.helper.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
  src/test-e2e/po/chips.po.ts
Labels: ready for review

#3235 Show better error message on login screen when account locked
  src/frontend/app/features/login/login-page/login-page.component.ts
  src/jetstream/auth.go
Labels: in review, ready for review

#2968 Extensions: Add support for custom card in the About page
  examples/custom-src/frontend/app/custom/acme-login/acme-login.component.ts
  examples/custom-src/frontend/app/custom/acme-support-info/acme-support-info.component.html
  examples/custom-src/frontend/app/custom/acme-support-info/acme-support-info.component.scss
  examples/custom-src/frontend/app/custom/acme-support-info/acme-support-info.component.spec.ts
  examples/custom-src/frontend/app/custom/acme-support-info/acme-support-info.component.ts
  examples/custom-src/frontend/app/custom/custom.module.ts
  src/frontend/app/core/customizations.types.ts
  src/frontend/app/features/about/about-page/about-page.component.html
  src/frontend/app/features/about/about-page/about-page.component.scss
  src/frontend/app/features/about/about-page/about-page.component.ts
Labels: ready for review

#3241 Limit card titles to two-lines with ellipsis/fade out
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.spec.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-title/meta-card-title.component.scss
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.html
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpack-card/cf-buildpack-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpack-card/cf-buildpack-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-card/cf-stacks-card.component.html
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.scss
  src/frontend/app/shared/components/multiline-title/multiline-title.component.html
  src/frontend/app/shared/components/multiline-title/multiline-title.component.scss
  src/frontend/app/shared/components/multiline-title/multiline-title.component.spec.ts
  src/frontend/app/shared/components/multiline-title/multiline-title.component.theme.scss
  src/frontend/app/shared/components/multiline-title/multiline-title.component.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/test-framework/cloud-foundry-endpoint-service.helper.ts
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#3242 Deploy App: Add notification toast
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
Labels: ready for review

#3243 App Wall filter and sort controls size tweaks
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/frontend/app/features/applications/application-wall/application-wall.component.theme.scss
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/sass/_all-theme.scss
  src/test-e2e/applications/application-wall-e2e.spec.ts
Labels: ready for review

#3261 Reduce size of Docker All-in-one image
  deploy/Dockerfile.all-in-one
  deploy/all-in-one/README.md
  deploy/all-in-one/config.all-in-one.properties
  src/jetstream/plugins/cloudfoundryhosting/main.go
Labels: ready for review

#3236 Merged SUSE/v2-master into incubator/v2-master
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
  src/frontend/app/core/core.module.ts
  src/frontend/app/core/endpoints-health-checks.ts
  src/frontend/app/core/endpoints.service.ts
  src/frontend/app/features/applications/application/application-base.component.ts
  src/frontend/app/features/applications/applications.routing.ts
  src/frontend/app/features/cloud-foundry/add-organization/add-organization.component.ts
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/add-space/add-space.component.ts
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry-base/cloud-foundry-base.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.routing.ts
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/app/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/app/features/service-catalog/service-catalog.routing.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/features/services/detach-service-instance/detach-service-instance.component.ts
  src/frontend/app/features/services/services.routing.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-list-controller.ts
  src/frontend/app/shared/components/list/list-table/table-row/table-row-state-manager.spec.ts
  src/frontend/app/shared/components/list/list-table/table.types.ts
  src/frontend/app/shared/components/list/list-types/detach-apps/detach-apps-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-data-source.ts
  src/frontend/app/shared/components/page-header/page-header-events/page-header-events.component.ts
  src/frontend/app/store/actions/internal-events.actions.ts
  src/frontend/app/store/effects/action-history.effects.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/effects/cloud-foundry.effects.ts
  src/frontend/app/store/effects/endpoint-api-errors.effects.ts
  src/frontend/app/store/effects/endpoint.effects.ts
  src/frontend/app/store/effects/metrics.effects.ts
  src/frontend/app/store/reducers/api-request-reducer/request-helpers.ts
  src/frontend/app/store/reducers/internal-events.reducer.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-clear-pagination-type.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/app/store/store.module.ts
  src/frontend/app/store/types/request.types.ts
  src/jetstream/auth.go
  src/jetstream/passthrough.go
  src/jetstream/plugins/cloudfoundry/main.go
  src/jetstream/plugins/metrics/main.go
  src/jetstream/repository/interfaces/endpoints.go
  src/jetstream/repository/interfaces/portal_proxy.go
  src/test-e2e/check/check-login-e2e.spec.ts
  src/test-e2e/login/login.po.ts
  src/test-e2e/login/sso-login.po.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
Labels: ready for review

#3263 Add confirmation dialog to `Restage` app
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
Labels: ready for review

#3204 Update Base Images script to inject private repositories
  deploy/stratos-base-images/Dockerfile.stratos-bk-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-go-build-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-mariadb-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-ui-build-base.tmpl
  deploy/stratos-base-images/build-base-images.sh
Labels: ready for review

#3273 Fix for title fade on firefox
  src/frontend/app/shared/components/multiline-title/multiline-title.component.scss
  src/frontend/app/shared/components/multiline-title/multiline-title.component.theme.scss
Labels: ready for review

#3193 Make Auth Type extensible with custom form component
  src/frontend/app/app.module.ts
  src/frontend/app/core/extension/extension-service.ts
  src/frontend/app/core/extension/extension-types.ts
  src/frontend/app/features/endpoints/connect-endpoint-dialog/auth-forms/credentials-auth-form.component.html
  src/frontend/app/features/endpoints/connect-endpoint-dialog/auth-forms/credentials-auth-form.component.scss
  src/frontend/app/features/endpoints/connect-endpoint-dialog/auth-forms/credentials-auth-form.component.ts
  src/frontend/app/features/endpoints/connect-endpoint-dialog/auth-forms/sso-auth-form.component.html
  src/frontend/app/features/endpoints/connect-endpoint-dialog/auth-forms/sso-auth-form.component.scss
  src/frontend/app/features/endpoints/connect-endpoint-dialog/auth-forms/sso-auth-form.component.ts
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.html
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/app/features/endpoints/endpoint-helpers.ts
  src/frontend/app/features/endpoints/endpoints.module.ts
  src/frontend/app/store/actions/endpoint.actions.ts
  src/frontend/app/store/effects/endpoint.effects.ts
  src/frontend/app/store/types/endpoint.types.ts
Labels: ready for review

#3268 Add service provider name to marketplace service card
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
Labels: ready for review

#3267 Add link to dashboard in service instance table
  src/frontend/app/shared/components/list/list-table/app-table-cell-default/app-table-cell-default.component.html
  src/frontend/app/shared/components/list/list-table/app-table-cell-default/app-table-cell-default.component.scss
  src/frontend/app/shared/components/list/list-table/app-table-cell-default/app-table-cell-default.component.ts
  src/frontend/app/shared/components/list/list-table/table.types.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
Labels: ready for review

#3258 Add user has roles filter to users tables
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/app/cf-apps-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-org-users/cf-org-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-services-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-users/cf-space-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-permission-cell.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-helpers.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instances-wall-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/shared/components/list/list.helper.ts
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/test-e2e/cloud-foundry/cf-level/cf-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/org-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/users-list-e2e.helper.ts
  src/test-e2e/po/component.po.ts
Labels: ready for review

#3041 Show app chip list for space routes list bound apps
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-route/table-cell-route.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/table-cell-route-apps-attached/table-cell-route-apps-attached.component.html
  src/frontend/app/shared/components/list/list-types/cf-space-routes/table-cell-route-apps-attached/table-cell-route-apps-attached.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/table-cell-route-apps-attached/table-cell-route-apps-attached.component.ts
Labels: ready for review

#3281 Fix test failure on faster system
  src/test-e2e/marketplace/services-helper-e2e.ts
Labels: ready for review

#2921 Update side nav logo with light version of new logo
  .gitignore
  docs/customizing.md
  src/frontend/app/features/dashboard/side-nav/side-nav.component.html
  src/frontend/app/features/dashboard/side-nav/side-nav.component.scss
  src/frontend/misc/custom/custom.yaml
  src/frontend/misc/custom/nav-logo.png
Labels: ready for review

#3247 Hide app vars tab if user is not a space developer
  src/frontend/app/core/current-user-permissions.config.ts
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/shared/components/page-subheader/page-subheader.component.html
  src/frontend/app/shared/components/page-subheader/page-subheader.component.scss
Labels: ready for review

#3274 Ensure we don't try to get length of undefined endpoint description
  src/frontend/app/shared/components/cards/card-cf-info/card-cf-info.component.ts
Labels: bug, ready for review

#3090 Fixes Async Service Provisioning Bug
  src/frontend/app/store/actions/service-instances.actions.ts
Labels: bug, community, ready for review

#3259 Remove global manage apps link
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.html
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users.component.html
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users.component.ts
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
Labels: ready for review
