Repository cloudfoundry/stratos, pull requests merged in 2018-11, with the labels that each got.

#3135 Show table of cell health state changes instead of chart
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-summary/cloud-foundry-cell-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-summary/cloud-foundry-cell-summary.component.scss
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-summary/cloud-foundry-cell-summary.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-summary/cloud-foundry-cell-summary.component.ts
  src/frontend/app/shared/components/boolean-indicator/boolean-indicator.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list-types/base-cf/base-cf-list-config.ts
  src/frontend/app/shared/components/list/list-types/cf-cell-apps/cf-cell-apps-source.ts
  src/frontend/app/shared/components/list/list-types/cf-cell-health/cf-cell-health-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-cell-health/cf-cell-health-source.ts
  src/frontend/app/shared/components/list/list-types/cf-cells/cf-cells-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/shared/components/metrics-range-selector/metrics-range-selector.component.scss
  src/frontend/app/shared/components/start-end-date/start-end-date.component.ts
Labels: ready for review

#3165 Fix issue where system shared endpoints weren't retrieved when required
  src/jetstream/plugins/metrics/main.go
Labels: ready for review

#3168 Helm Chart: Fix service selectors for nginx service
  deploy/kubernetes/console/templates/service.yaml
Labels: ready for review

#3170 Added update for week ending 2nd November 2018
  docs/status_updates.md
Labels: ready for review

#3167 Tidy up CI pipelines
  deploy/ci/build-images.yml
  deploy/ci/concourse-update-images.yml
  deploy/ci/console-bosh-tests.yml
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-nightly-releases.yml
  deploy/ci/console-test-git.yml
  deploy/ci/console-tests-git.yml
  deploy/ci/console-tests-pr.yml
  deploy/ci/tasks/bosh/compile.yml
  deploy/ci/tasks/stratos-ui/prep-proxy-image.yml
  deploy/ci/tasks/stratos-ui/run-tests.yml
  deploy/ci/tasks/stratos-ui/run-unit-tests.yml
Labels: ready for review

#3179 Improved dev guide doc
  docs/developers-guide.md
Labels: ready for review

#2959 Show Service plan cost when selecting a service plan (if not free)
  src/frontend/app/core/cf-api-svc.types.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.html
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.html
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.scss
Labels: in review, ready for review

#3044 Add support for Browserstack
  docs/developers-guide-e2e-tests.md
  package.json
  protractor.conf.js
  src/test-e2e/browserstack-helper.js
Labels: in review

#3191 Fix folder upload. Add E2E test
  src/frontend/app/core/utils.service.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.html
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/jetstream/plugins/cfapppush/deploy.go
  src/test-e2e/application/application-deploy-local-e2e.spec.ts
  src/test-e2e/resources/go-env.zip
Labels: ready for review

#3194 Weekly update
  docs/status_updates.md
Labels: ready for review

#3185 Always serve the backend under /pp to avoid config issues when developing
  deploy/containers/nginx/conf/nginx.dev.conf
  deploy/containers/nginx/conf/nginx.k8s.conf
  deploy/stratos-ui-release/jobs/frontend/templates/nginx.conf.erb
  docs/developers-guide.md
  src/jetstream/main.go
Labels: ready for review

#3159 Helm chart: Fix http port config
  deploy/kubernetes/console/templates/service.yaml
Labels: ready for review

#3200 Fixed prometheus typo in metrics info page
  src/frontend/app/features/metrics/metrics/metrics.component.html
Labels: ready for review

#3207 12 November update
  docs/status_updates.md
Labels: ready for review

#3199 Split travis e2e tests into two
  .travis.yml
  deploy/ci/travis/job-e2e-before_script.sh
  deploy/ci/travis/job-e2e-script.sh
  deploy/ci/travis/run-e2e-tests.sh
  protractor.conf.js
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-deploy-local-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/application/po/deploy-app.po.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/cf-org-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-e2e.spec.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/helpers/secrets-helpers.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/po/boolean-indicator.po.ts
  src/test-e2e/po/form.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/meta-data-item.po.ts
Labels: in progress

#3208 Update references to cf-stratos
  Gopkg.lock
  deploy/fissile/build-release.sh
  deploy/tools/populate-cf/cf-summit-april-2018.sh
  deploy/tools/populate-cf/create-services.sh
  src/frontend/app/test-framework/store-test-helper.ts
  src/jetstream/main.go
  src/test-e2e/config-cf.sh
Labels: ready for review

#3217 Improve e2e tests
  src/test-e2e/cloud-foundry/cf-level/cf-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/org-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-users-list-e2e.spec.ts
  src/test-e2e/helpers/extend-test-helpers.ts
  src/test-e2e/marketplace/create-service-instances-bind-app-e2e.spec.ts
  src/test-e2e/marketplace/edit-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
Labels: ready for review

#3214 Fix display of generic error bar
  src/frontend/app/store/effects/api.effects.ts
Labels: ready for review

#3218 Improve paginated/pagination action naming
  src/frontend/app/store/actions/pagination.actions.ts
  src/frontend/app/store/actions/service-broker.actions.ts
  src/frontend/app/store/actions/service-instances.actions.ts
  src/frontend/app/store/actions/service-plan-visibility.actions.ts
  src/frontend/app/store/actions/service-plan.actions.ts
  src/frontend/app/store/actions/service.actions.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/actions/system.actions.ts
  src/frontend/app/store/helpers/store-helpers.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-update.ts
  src/frontend/app/store/types/pagination.types.ts
Labels: ready for review

#3220 Improve e2e tests
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/marketplace/marketplace-create-service-instances-e2e.spec.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
  src/test-e2e/marketplace/services-wall.po.ts
  src/test-e2e/po/chips.po.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/stepper.po.ts
Labels: ready for review

#2971 E2E: Script to setup CF for E2E tests and script to cleanup test reminants
  deploy/ci/automation/e2e-clean-remnants.sh
  deploy/tools/init-cf-for-e2e.sh
  deploy/tools/populate-cf/create-services.sh
Labels: ready for review

#3227 Improve cf user role table tests
  src/test-e2e/cloud-foundry/cf-level/cf-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/org-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-users-list-e2e.spec.ts
  src/test-e2e/cloud-foundry/users-list-e2e.helper.ts
Labels: ready for review

#3223 Add stricter check for jetstream error object
  src/frontend/app/core/jetstream.helpers.ts
  src/frontend/app/store/effects/api.effects.ts
Labels: community, ready for review

#3224 Speed up Services Wall and Marketplace E2E Tests
  src/test-e2e/marketplace/marketplace-e2e.spec.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
Labels: in review, ready for review

#3233 Fix reliability of marketplace tests
  src/test-e2e/marketplace/marketplace-e2e.spec.ts
Labels: ready for review

#3232 Run customize when prebuild and log node and npm versions
  build/customize-build.js
  package.json
Labels: ready for review

#3211 Only show + icon when we have at least one connected CF
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/services/services-wall/services-wall.component.html
  src/frontend/app/features/services/services-wall/services-wall.component.ts
  src/frontend/app/shared/components/page-header/page-header.component.html
Labels: ready for review

#3226 Port log in page waitForLoading fix
  src/frontend/app/features/login/login-page/login-page.component.html
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/login/login.po.ts
Labels: ready for review

#3240 Weekly update
  docs/status_updates.md
Labels: ready for review

#3178 Backend: Merge back changes from SUSE repository
  src/jetstream/auth.go
  src/jetstream/auth_providers.go
  src/jetstream/cnsi.go
  src/jetstream/http_basic_requests.go
  src/jetstream/main.go
  src/jetstream/oauth_requests.go
  src/jetstream/oidc_requests.go
  src/jetstream/passthrough.go
  src/jetstream/plugins/metrics/cloud_foundry.go
  src/jetstream/plugins/metrics/kubernetes.go
  src/jetstream/plugins/metrics/main.go
  src/jetstream/portal_proxy.go
  src/jetstream/repository/interfaces/portal_proxy.go
  src/jetstream/repository/interfaces/structs.go
Labels: ready for review
