Repository cloudfoundry/stratos, pull requests merged in 2018-03, with the labels that each got.

#1668 Console release pipeline: Remove unnecessary dependency
  deploy/ci/console-release.yml
Labels: V1, ready for review

#1596 Fix US localisation
  components/cloud-foundry/frontend/i18n/en_US/cloud-foundry.json
Labels: V1, ready for review

#1447 Fix issue around apps and routes missing from space entity
  components/cloud-foundry/frontend/src/model/organization-model.factory.js
  components/cloud-foundry/frontend/src/model/space.model.js
  components/cloud-foundry/frontend/src/view/dashboard/cluster/cluster.module.js
  components/cloud-foundry/frontend/src/view/dashboard/cluster/organization/cluster-organization.module.js
Labels: V1, ready for review

#1625 Show memory and disk usage with respect to number of running instances
  components/cloud-foundry/frontend/src/model/application/application.model.js
  components/cloud-foundry/frontend/src/model/organization-model.factory.js
  components/cloud-foundry/frontend/src/model/space.model.js
  components/cloud-foundry/frontend/src/view/applications/application/summary/summary.html
  components/cloud-foundry/frontend/src/view/applications/list/gallery-view/application-gallery-card/application-gallery-card.html
  components/cloud-foundry/frontend/src/view/applications/list/table-view/table-view.html
Labels: V1, blocked-pr, ready for review

#1690 Fix e2e tests
  components/cloud-foundry/frontend/test/e2e/application.spec.js
Labels: V1

#1688 Bump version number and update change log
  CHANGELOG.md
  package-lock.json
  package.json
Labels: V1

#1669 Space summary: Service instances
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organisation.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-service-instances/cloud-foundry-space-service-instances.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-service-instances/cloud-foundry-space-service-instances.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-service-instances/cloud-foundry-space-service-instances.component.ts
  src/frontend/app/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.scss
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.scss
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.scss
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.scss
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/action-types.ts
  src/frontend/app/store/actions/service-instances.actions.ts
  src/frontend/app/store/reducers/api-request-reducers.generator.ts
  src/frontend/app/store/reducers/users.reducer.ts
  src/frontend/app/store/types/entity.types.ts
  src/frontend/app/store/types/org-and-space.types.ts
  src/frontend/app/store/types/service.types.ts
  src/frontend/app/test-framework/cloud-foundry-endpoint-service.helper.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: comments-addressed, cowbell, ready for review

#1675 CF Space actions Part 1: Create space in org
  src/frontend/app/features/cloud-foundry/add-space/add-space.component.html
  src/frontend/app/features/cloud-foundry/add-space/add-space.component.scss
  src/frontend/app/features/cloud-foundry/add-space/add-space.component.spec.ts
  src/frontend/app/features/cloud-foundry/add-space/add-space.component.ts
  src/frontend/app/features/cloud-foundry/add-space/create-space-step/create-space-step.component.html
  src/frontend/app/features/cloud-foundry/add-space/create-space-step/create-space-step.component.scss
  src/frontend/app/features/cloud-foundry/add-space/create-space-step/create-space-step.component.spec.ts
  src/frontend/app/features/cloud-foundry/add-space/create-space-step/create-space-step.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.html
  src/frontend/app/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
  src/frontend/app/store/actions/space.actions.ts
Labels: comments-addressed, cowbell, ready for review, v1 parity

#1692 Change the navbar-brand to match the same colour as the rest of the nav…
  components/app-core/frontend/src/view/navbar/navbar.scss
Labels: V1, ready for review

#1682 CF Space actions Part 2: Edit Space Action
  src/frontend/app/core/cf-api.types.ts
  src/frontend/app/features/cloud-foundry/add-edit-space-step-base.ts
  src/frontend/app/features/cloud-foundry/add-organisation/create-organization-step/create-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/add-space/create-space-step/create-space-step.component.ts
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.routing.ts
  src/frontend/app/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.html
  src/frontend/app/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.scss
  src/frontend/app/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.spec.ts
  src/frontend/app/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.ts
  src/frontend/app/features/cloud-foundry/edit-space/edit-space.component.html
  src/frontend/app/features/cloud-foundry/edit-space/edit-space.component.scss
  src/frontend/app/features/cloud-foundry/edit-space/edit-space.component.spec.ts
  src/frontend/app/features/cloud-foundry/edit-space/edit-space.component.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organisation.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-organization-spaces.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-space-apps/cf-space-apps-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-space-apps/cf-space-apps-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/store/actions/application.actions.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/types/application.types.ts
  src/frontend/app/store/types/org-and-space.types.ts
  src/frontend/app/store/types/route.types.ts
  src/frontend/app/test-framework/cloud-foundry-space.service.mock.ts
Labels: comments-addressed, ready for review

#1678 Fix endpoint token update query
  src/backend/app-core/repository/tokens/pgsql_tokens.go
Labels: ready for review

#1689 CF Stacks list
  src/frontend/app/core/cf-api.types.ts
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-stacks/cloud-foundry-stacks.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-stacks/cloud-foundry-stacks.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-stacks/cloud-foundry-stacks.component.ts
  src/frontend/app/shared/components/list/list-cards/card/card.component.ts
  src/frontend/app/shared/components/list/list-types/base-cf/base-cf-list-config.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-card/cf-stacks-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-card/cf-stacks-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-card/cf-stacks-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-card/cf-stacks-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-list-config.service.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/stack.action.ts
Labels: comments-addressed, ready for review, v1 parity

#1691 CF security groups
  src/frontend/app/core/cf-api.types.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-security-groups/cloud-foundry-security-groups.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-security-groups/cloud-foundry-security-groups.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-security-groups/cloud-foundry-security-groups.component.ts
  src/frontend/app/shared/components/chips/chips.component.html
  src/frontend/app/shared/components/chips/chips.component.ts
  src/frontend/app/shared/components/list/list-cards/card/card.component.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.html
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-value/meta-card-value.component.scss
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.theme.scss
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-list-config.service.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/security-groups-actions.ts
  src/frontend/app/store/reducers/api-request-reducers.generator.ts
  src/frontend/app/store/types/entity.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
  src/frontend/sass/_all-theme.scss
Labels: comments-addressed, ready for review

#1695 Add missing fields to Endpoint usage card
  src/frontend/app/core/cf-api.types.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/shared/components/cards/card-cf-usage/card-cf-usage.component.html
  src/frontend/app/shared/components/cards/card-cf-user-info/card-cf-user-info.component.html
Labels: comments-addressed, ready for review

#1744 Fix SQL statement error
  src/backend/app-core/repository/tokens/pgsql_tokens.go
Labels: ready for review

#1745 Fix for github tab not showing on first load
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/shared/components/page-subheader/page-subheader.component.html
  src/frontend/app/shared/components/page-subheader/page-subheader.component.scss
  src/frontend/app/shared/components/page-subheader/page-subheader.component.ts
  src/frontend/app/shared/components/page-subheader/page-subheader.types.ts
Labels: ready for review

#1750 Clear App Wall Pagination when a new CF endpoint is connected
  src/frontend/app/store/effects/endpoint.effects.ts
  src/frontend/app/store/reducers/system-endpoints.reducer.ts
  src/frontend/app/store/types/endpoint.types.ts
Labels: comments-addressed, cowbell

#1748 Breadcrumbs
  src/frontend/app/core/cf-api.types.ts
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/features/no-endpoints-non-admin/no-endpoints-non-admin.component.spec.ts
  src/frontend/app/features/service-catalogue/service-catalogue-page/service-catalogue-page.component.ts
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-name/table-cell-app-name.component.html
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-name/table-cell-app-name.component.ts
  src/frontend/app/shared/components/list/list-types/cf-space-apps/cf-space-apps-list-config.service.ts
  src/frontend/app/shared/components/page-header/page-header.component.html
  src/frontend/app/shared/components/page-header/page-header.component.scss
  src/frontend/app/shared/components/page-header/page-header.component.spec.ts
  src/frontend/app/shared/components/page-header/page-header.component.ts
  src/frontend/app/shared/components/page-header/page-header.types.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/selectors/endpoint.selectors.ts
  src/frontend/app/store/types/entity.types.ts
  src/frontend/app/store/types/user.types.ts
Labels: ready for review

#1746 Hide dashboard sidenav item
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/app/features/dashboard/side-nav/side-nav.component.html
  src/frontend/app/features/dashboard/side-nav/side-nav.component.ts
Labels: comments-addressed, ready for review

#1755 List Views: Hide paginator if not needed
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
Labels: ready for review

#1760 MetaCard Improvements
  src/frontend/app/core/click-stop-propagation.ts
  src/frontend/app/core/core.module.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.html
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
Labels: ready for review

#1754 CF Tabs: Small UX improvements
  src/frontend/app/shared/components/boolean-indicator/boolean-indicator.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.html
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-card/cf-security-groups-card.component.theme.scss
Labels: ready for review

#1751 List View: Only show top header bar if there are controls to go in it
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
Labels: comments-addressed, ready for review

#1743 Stepper fixes to align with Material Design spec
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
  src/frontend/app/shared/components/stepper/steppers/steppers.component.theme.scss
Labels: ready for review

#1752 Service Catalogue card view
  src/frontend/app/core/cf-api-svc.types.ts
  src/frontend/app/core/cf-api.types.ts
  src/frontend/app/core/core.module.ts
  src/frontend/app/core/endpoints.service.ts
  src/frontend/app/core/safe-img.pipe.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organisation.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/features/service-catalogue/service-catalogue-page/service-catalogue-page.component.html
  src/frontend/app/features/service-catalogue/service-catalogue-page/service-catalogue-page.component.spec.ts
  src/frontend/app/features/service-catalogue/service-catalogue-page/service-catalogue-page.component.ts
  src/frontend/app/features/service-catalogue/service-catalogue.routing.ts
  src/frontend/app/shared/components/chips/chips.component.ts
  src/frontend/app/shared/components/list/list-cards/card/card.component.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-services-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-services-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-services-list-config.service.ts
  src/frontend/app/shared/components/list/list.helper.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/service.actions.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: ready for review

#1742 Show message when no endpoints are connected
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.html
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
Labels: ready for review

#1738 Fix bug where all organisations across all endpoints were retrieved
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
Labels: ready for review

#1747 Return user to the previous state in Stepper forms
  src/frontend/app/app.module.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/github-tab/github-tab.component.ts
  src/frontend/app/features/applications/edit-application/edit-application.component.ts
  src/frontend/app/shared/components/stepper/step/step.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.spec.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/app/store/actions/router.actions.ts
  src/frontend/app/store/app-state.ts
  src/frontend/app/store/effects/router.effects.ts
  src/frontend/app/store/reducers.module.ts
  src/frontend/app/store/reducers/routing.reducer.ts
  src/frontend/app/store/types/routing.type.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: ready for review

#1763 Docker Compose: Fix for stuck at 'UI is building' message
  deploy/containers/nginx/conf/nginx.dev.conf
  deploy/docker-compose/building.html
  deploy/stand-up-dev-env.sh
Labels: ready for review

#1736 Tidy up text in `Edit Organisation`
  src/frontend/app/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.html
Labels: ready for review

#1737 Set CF Feature-flags page size to 25 and update page-size options to [10, 25, 50]
  src/frontend/app/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-list-config.service.ts
  src/frontend/app/store/actions/feature-flags.actions.ts
Labels: ready for review

#1774 Convert references of `organisation` to `organization`
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/applications/create-application/create-application-step3/create-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/features/cloud-foundry/add-edit-space-step-base.ts
  src/frontend/app/features/cloud-foundry/add-organization/add-organization.component.html
  src/frontend/app/features/cloud-foundry/add-organization/add-organization.component.scss
  src/frontend/app/features/cloud-foundry/add-organization/add-organization.component.spec.ts
  src/frontend/app/features/cloud-foundry/add-organization/add-organization.component.ts
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.html
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.scss
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.spec.ts
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.routing.ts
  src/frontend/app/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-organization-spaces.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.ts
  src/frontend/app/shared/components/cards/card-cf-org-usage/card-cf-org-usage.component.spec.ts
  src/frontend/app/shared/components/cards/card-cf-org-usage/card-cf-org-usage.component.ts
  src/frontend/app/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.spec.ts
  src/frontend/app/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.ts
  src/frontend/app/shared/components/cf-auth/checkers/organization-access.ts
  src/frontend/app/shared/components/cf-auth/principal.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-orgs-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-spaces-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-spaces-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
  src/frontend/app/store/actions/organization.actions.ts
  src/frontend/app/store/actions/users.actions.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/helpers/entity-relations.ts
  src/frontend/app/store/helpers/entity-relations.types.ts
  src/frontend/app/store/reducers/api-request-data-reducer/request-data-reducer.factory.ts
  src/frontend/app/store/reducers/api-request-reducers.generator.ts
  src/frontend/app/store/reducers/organization-space.reducer.ts
  src/frontend/app/store/types/entity.types.ts
  src/frontend/app/test-framework/cloud-foundry-organisation.service.mock.ts
  src/frontend/app/test-framework/cloud-foundry-organization.service.mock.ts
Labels: ready for review

#1766 Fix create route after entity change
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/app/store/helpers/entity-factory.ts
Labels: ready for review

#1770 Fix three list bugs
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
Labels: in review

#1778 Ensure we're more null safe to catch case where entities of a certain type are missing
  src/frontend/app/store/helpers/entity-relations.ts
Labels: ready for review

#1769 Fix CF User Service
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/actions/users.actions.ts
Labels: ready for review

#1812 App Wall: Remove call to action to conform to Material design
  src/frontend/app/features/applications/application-wall/application-wall.component.html
Labels: ready for review

#1735 Fix for the "App Summary" button not being enabled
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.spec.ts
Labels: in review, ready for review

#1814 Rename catalogue > catalog
  src/frontend/app/app.module.ts
  src/frontend/app/app.routing.ts
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.html
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.scss
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.spec.ts
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.ts
  src/frontend/app/features/service-catalog/service-catalog.module.ts
  src/frontend/app/features/service-catalog/service-catalog.routing.ts
  src/frontend/app/features/service-catalogue/service-catalogue.module.ts
  src/frontend/app/features/service-catalogue/service-catalogue.routing.ts
Labels: ready for review

#1772 Add custom 'There are no x' text for each table
  src/frontend/app/shared/components/list/list-table/table.types.ts
  src/frontend/app/shared/components/list/list-types/app-event/cf-app-events-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-map-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-variables/cf-app-variables-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpacks-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-endpoints/cf-endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-orgs-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-services-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-apps/cf-space-apps-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-spaces-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.html
Labels: ready for review

#1818 Hide the users tabs that are not implemented
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
Labels: ready for review

#1773 Fix application instances table on stats change
  src/frontend/app/core/entity-service.ts
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/shared/components/list/list-table/app-table-cell-default/app-table-cell-default.component.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/monitors/pagination-monitor.ts
  src/frontend/app/store/actions/application.actions.ts
  src/frontend/app/store/effects/app-variables.effects.ts
  src/frontend/app/store/reducers/api-request-reducers.generator.ts
  src/frontend/app/store/reducers/app-stats-request.reducer.ts
Labels: in review, ready for review

#1819 Fix App Card running instances count
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.html
Labels: ready for review

#1823 Fix decimal place values when calculating average
  src/frontend/app/features/applications/application-monitor.service.ts
Labels: in review, ready for review

#1837 Fix redirect on delete app
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/store/helpers/entity-relations.ts
  src/frontend/app/store/reducers/api-request-reducer/fail-request.ts
Labels: ready for review

#1817 Tweak app actions
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
Labels: ready for review

#1830 Ensure we don't display error message from previous endpoint connect failure
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
Labels: ready for review
