Repository cloudfoundry/stratos, pull requests merged in 2018-06, with the labels that each got.

#2244 Update to latest node LTS for angular 6 migration
  deploy/stratos-base-images/Dockerfile.stratos-aio-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-bk-build-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-ui-build-base.tmpl
  deploy/stratos-base-images/build-base-images.sh
Labels: ready for review

#2248 Fix compression issue
  src/backend/app-core/passthrough.go
Labels: ready for review

#2238 Fix application issue on reload when served by backend
  src/backend/app-core/main.go
Labels: ready for review

#2188 App Services tab: Allow user to bind a service instance
  src/frontend/app/features/applications/applications.routing.ts
  src/frontend/app/features/applications/cli-info-application/cli-info-application.component.ts
  src/frontend/app/features/applications/create-application/create-application.component.spec.ts
  src/frontend/app/features/applications/create-application/create-application.module.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/features/service-catalog/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/app/features/service-catalog/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/select-service/select-service.component.scss
  src/frontend/app/features/service-catalog/add-service-instance/specify-details-step/specify-details-step.component.html
  src/frontend/app/features/service-catalog/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/features/service-catalog/service-catalog.module.ts
  src/frontend/app/features/service-catalog/service-catalog.routing.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/features/services/services.routing.ts
  src/frontend/app/features/services/services/services-wall.service.ts
  src/frontend/app/features/user-profile/user-profile.service.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.scss
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.html
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.scss
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.ts
  src/frontend/app/shared/components/add-service-instance/create-service-instance-helper-service-factory.service.ts
  src/frontend/app/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/app/shared/components/add-service-instance/csi-guids.service.spec.ts
  src/frontend/app/shared/components/add-service-instance/csi-guids.service.ts
  src/frontend/app/shared/components/add-service-instance/no-service-plans/no-service-plans.component.html
  src/frontend/app/shared/components/add-service-instance/no-service-plans/no-service-plans.component.scss
  src/frontend/app/shared/components/add-service-instance/no-service-plans/no-service-plans.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/no-service-plans/no-service-plans.component.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.html
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.scss
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.html
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.scss
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.html
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.scss
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/shared/components/cards/card-cf-info/card-cf-info.component.ts
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.html
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.scss
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.spec.ts
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/service-instances/service-instances-data-source.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/application-service-routes.actions.ts
  src/frontend/app/store/actions/create-service-instance.actions.ts
  src/frontend/app/store/actions/service-instances.actions.ts
  src/frontend/app/store/actions/service-plan.actions.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/reducers/create-service-instance.reducer.ts
Labels: needs attention

#2141 Fix application/services pages when there are no endpoints
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/app/cf-apps-data-source.ts
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
  src/frontend/app/store/effects/api.effects.ts
Labels: V2, bug, ready for review

#2215 Fix multiple add/deploy app icons on app wall after fresh stepper visit
  src/frontend/app/core/current-user-permissions.service.ts
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/frontend/app/shared/user-permission.directive.ts
Labels: ready for review

#2194 Re-enable detach service action from App Services tab
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.html
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.scss
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
Labels: in review

#2250 Fix App SSH (Broken when auth and token endpoints are different)
  src/backend/cfappssh/app_ssh.go
Labels: V2, bug, ready for review

#2252 Fix for permissions issue with node
  deploy/stratos-base-images/Dockerfile.stratos-bk-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-bk-build-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-ui-build-base.tmpl
Labels: V2, ready for review

#2219 Service Summary tab
  src/frontend/app/core/cf-api-svc.types.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/features/service-catalog/service-catalog.module.ts
  src/frontend/app/features/service-catalog/service-catalog.routing.ts
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.html
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.scss
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.spec.ts
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.ts
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.html
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/features/service-catalog/services.service.mock.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/shared/components/cards/compact-service-instance-card/compact-service-instance-card.component.html
  src/frontend/app/shared/components/cards/compact-service-instance-card/compact-service-instance-card.component.scss
  src/frontend/app/shared/components/cards/compact-service-instance-card/compact-service-instance-card.component.spec.ts
  src/frontend/app/shared/components/cards/compact-service-instance-card/compact-service-instance-card.component.ts
  src/frontend/app/shared/components/cards/service-broker-card/service-broker-card.component.html
  src/frontend/app/shared/components/cards/service-broker-card/service-broker-card.component.scss
  src/frontend/app/shared/components/cards/service-broker-card/service-broker-card.component.spec.ts
  src/frontend/app/shared/components/cards/service-broker-card/service-broker-card.component.ts
  src/frontend/app/shared/components/cards/service-recent-instances-card/service-recent-instances-card.component.html
  src/frontend/app/shared/components/cards/service-recent-instances-card/service-recent-instances-card.component.scss
  src/frontend/app/shared/components/cards/service-recent-instances-card/service-recent-instances-card.component.spec.ts
  src/frontend/app/shared/components/cards/service-recent-instances-card/service-recent-instances-card.component.ts
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.html
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.scss
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.spec.ts
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.spec.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: in review

#2249 Added theming section to developer guide readme
  docs/developers-guide.md
Labels: ready for review

#2221 Update permissions when when entities are updated
  angular.json
  package-lock.json
  package.json
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/github-commits/github-commits-list-config-app-tab.service.ts
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/store/actions/endpoint.actions.ts
  src/frontend/app/store/actions/organization.actions.ts
  src/frontend/app/store/actions/permissions.actions.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/effects/endpoint.effects.ts
  src/frontend/app/store/effects/permissions.effect.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-cf-roles.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-reducer.helpers.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-role-session.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-clear.reducers.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-space.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-spaces.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.spec.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.ts
  src/frontend/app/store/reducers/endpoint-disconnect-application.reducer.ts
  src/frontend/app/store/types/auth.types.ts
  src/frontend/app/store/types/current-user-roles.types.ts
  src/frontend/app/store/types/endpoint.types.ts
Labels: comments-addressed, ready for review

#2216 Fix app map existing route table sort
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-data-source.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-app-route/table-cell-app-route.component.html
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-app-route/table-cell-app-route.component.ts
Labels: in review, ready for review

#2243 Fix issues with the JSON serialization of some error responses
  src/backend/app-core/passthrough.go
Labels: bug, ready for review

#2278 Only allow password change if user has password.write scope
  src/frontend/app/features/user-profile/edit-profile-info/edit-profile-info.component.html
  src/frontend/app/features/user-profile/edit-profile-info/edit-profile-info.component.ts
Labels: ready for review

#2236 Fix skipped step
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
Labels: comments-addressed, ready for review

#2258 Endpoint confirmation modals
  src/frontend/app/shared/components/dialog-confirm/dialog-confirm.component.html
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/test-e2e/endpoints/endpoints-connect.e2e-spec.ts
  src/test-e2e/endpoints/endpoints-unregister.e2e-spec.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/confirm-dialog.ts
Labels: in review, ready for review

#2288 Wire in actions to app state
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.scss
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/shared/components/application-state/application-state.service.ts
Labels: in review, ready for review

#2267 Backend logging improvements
  src/backend/app-core/auth.go
  src/backend/app-core/datastore/datastore.go
  src/backend/app-core/middleware.go
  src/backend/app-core/repository/cnsis/pgsql_cnsis.go
  src/backend/app-core/repository/console_config/psql_console_config.go
  src/backend/app-core/repository/crypto/aes.go
  src/backend/app-core/repository/goose-db-version/pgsql_goose_db_version.go
  src/backend/app-core/repository/interfaces/errors.go
  src/backend/app-core/repository/tokens/pgsql_tokens.go
Labels: ready for review

#2260 Use local fonts
  .gitattributes
  angular.json
  src/frontend/assets/fonts/iconfont/LICENSE
  src/frontend/assets/fonts/iconfont/MaterialIcons-Regular.eot
  src/frontend/assets/fonts/iconfont/MaterialIcons-Regular.ijmap
  src/frontend/assets/fonts/iconfont/MaterialIcons-Regular.svg
  src/frontend/assets/fonts/iconfont/MaterialIcons-Regular.ttf
  src/frontend/assets/fonts/iconfont/MaterialIcons-Regular.woff
  src/frontend/assets/fonts/iconfont/MaterialIcons-Regular.woff2
  src/frontend/assets/fonts/iconfont/codepoints
  src/frontend/assets/fonts/iconfont/material-icons.css
  src/frontend/assets/fonts/lato/OFL.txt
  src/frontend/assets/fonts/lato/lato-v14-latin-300.eot
  src/frontend/assets/fonts/lato/lato-v14-latin-300.svg
  src/frontend/assets/fonts/lato/lato-v14-latin-300.ttf
  src/frontend/assets/fonts/lato/lato-v14-latin-300.woff
  src/frontend/assets/fonts/lato/lato-v14-latin-300.woff2
  src/frontend/assets/fonts/lato/lato-v14-latin-700.eot
  src/frontend/assets/fonts/lato/lato-v14-latin-700.svg
  src/frontend/assets/fonts/lato/lato-v14-latin-700.ttf
  src/frontend/assets/fonts/lato/lato-v14-latin-700.woff
  src/frontend/assets/fonts/lato/lato-v14-latin-700.woff2
  src/frontend/assets/fonts/lato/lato-v14-latin-900.eot
  src/frontend/assets/fonts/lato/lato-v14-latin-900.svg
  src/frontend/assets/fonts/lato/lato-v14-latin-900.ttf
  src/frontend/assets/fonts/lato/lato-v14-latin-900.woff
  src/frontend/assets/fonts/lato/lato-v14-latin-900.woff2
  src/frontend/assets/fonts/lato/lato-v14-latin-regular.eot
  src/frontend/assets/fonts/lato/lato-v14-latin-regular.svg
  src/frontend/assets/fonts/lato/lato-v14-latin-regular.ttf
  src/frontend/assets/fonts/lato/lato-v14-latin-regular.woff
  src/frontend/assets/fonts/lato/lato-v14-latin-regular.woff2
  src/frontend/assets/fonts/roboto/LICENSE.txt
  src/frontend/assets/fonts/roboto/roboto-v18-latin-300.eot
  src/frontend/assets/fonts/roboto/roboto-v18-latin-300.svg
  src/frontend/assets/fonts/roboto/roboto-v18-latin-300.ttf
  src/frontend/assets/fonts/roboto/roboto-v18-latin-300.woff
  src/frontend/assets/fonts/roboto/roboto-v18-latin-300.woff2
  src/frontend/assets/fonts/roboto/roboto-v18-latin-500.eot
  src/frontend/assets/fonts/roboto/roboto-v18-latin-500.svg
  src/frontend/assets/fonts/roboto/roboto-v18-latin-500.ttf
  src/frontend/assets/fonts/roboto/roboto-v18-latin-500.woff
  src/frontend/assets/fonts/roboto/roboto-v18-latin-500.woff2
  src/frontend/assets/fonts/roboto/roboto-v18-latin-700.eot
  src/frontend/assets/fonts/roboto/roboto-v18-latin-700.svg
  src/frontend/assets/fonts/roboto/roboto-v18-latin-700.ttf
  src/frontend/assets/fonts/roboto/roboto-v18-latin-700.woff
  src/frontend/assets/fonts/roboto/roboto-v18-latin-700.woff2
  src/frontend/assets/fonts/roboto/roboto-v18-latin-regular.eot
  src/frontend/assets/fonts/roboto/roboto-v18-latin-regular.svg
  src/frontend/assets/fonts/roboto/roboto-v18-latin-regular.ttf
  src/frontend/assets/fonts/roboto/roboto-v18-latin-regular.woff
  src/frontend/assets/fonts/roboto/roboto-v18-latin-regular.woff2
  src/frontend/index.html
  src/frontend/sass/fonts.scss
  src/frontend/sass/icons.scss
  src/frontend/styles.scss
Labels: V2, in review, ready for review

#2301 Ensure all go tests are run. Fix failures.
  build/bk-build-utils.js
  package.json
  src/backend/app-core/datastore/datastore.go
  src/backend/app-core/repository/cnsis/pgsql_cnsis_test.go
  src/backend/app-core/repository/interfaces/structs.go
  src/backend/app-core/repository/tokens/pgsql_tokens_test.go
Labels: in review, ready for review

#2291 Add Permissions to CF Users tables
  src/frontend/app/core/current-user-permissions.checker.ts
  src/frontend/app/core/current-user-permissions.config.ts
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.html
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/cf-roles.service.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-modify/space-roles-list-wrapper/space-roles-list-wrapper.component.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-select/manage-users-select.component.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.ts
  src/frontend/app/shared/components/cf-role-checkbox/cf-role-checkbox.component.ts
  src/frontend/app/shared/components/chips/chips.component.html
  src/frontend/app/shared/components/chips/chips.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/app/shared/components/list/list-types/cf-org-users/cf-org-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-select-users/cf-select-users-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-select-users/cf-select-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-space-users/cf-space-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users-org-space-roles/cf-users-space-roles-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users-org-space-roles/cf-users-space-roles-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users-org-space-roles/table-cell-org-space-role/table-cell-org-space-role.component.html
  src/frontend/app/shared/components/list/list-types/cf-users-org-space-roles/table-cell-select-org/table-cell-select-org.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-org-permission-cell/cf-org-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-permission-cell.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/actions/permissions.actions.ts
  src/frontend/app/store/actions/users.actions.ts
  src/frontend/app/store/effects/permissions.effect.ts
  src/frontend/app/store/effects/users.effects.ts
  src/frontend/app/store/helpers/store-helpers.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-base-cf-role.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-request-state.reducers.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.spec.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.ts
  src/frontend/app/store/selectors/current-user-roles-permissions-selectors/role.selectors.ts
  src/frontend/app/store/store.module.ts
  src/frontend/app/store/types/current-user-roles.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: blocked-pr, ready for review

#2285 Only show add and deploy buttons when there is at least 1 connected CF
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
Labels: in review, ready for review

#2306 Show whether user is an admin on the about page
  src/frontend/app/features/about/about-page/about-page.component.html
  src/frontend/app/features/about/about-page/about-page.component.scss
  src/frontend/app/features/about/about-page/about-page.component.theme.scss
  src/frontend/app/features/about/about-page/about-page.component.ts
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#2296 Add support for improving description and detect PCF Dev
  src/frontend/app/shared/components/cards/card-cf-info/card-cf-info.component.html
  src/frontend/app/shared/components/cards/card-cf-info/card-cf-info.component.ts
Labels: in review, ready for review

#2297 Fix Marketplace service cards tags list fails to expand
  src/frontend/app/shared/components/chips/chips.component.html
Labels: in review, ready for review

#2305 Two minor css fixes
  src/frontend/app/shared/components/chips/chips.component.scss
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
Labels: ready for review

#2266 Unbind from service instances that have multiple service bindings
  src/frontend/app/features/services/detach-service-instance/detach-apps/detach-apps.component.html
  src/frontend/app/features/services/detach-service-instance/detach-apps/detach-apps.component.scss
  src/frontend/app/features/services/detach-service-instance/detach-apps/detach-apps.component.spec.ts
  src/frontend/app/features/services/detach-service-instance/detach-apps/detach-apps.component.ts
  src/frontend/app/features/services/detach-service-instance/detach-service-instance.component.html
  src/frontend/app/features/services/detach-service-instance/detach-service-instance.component.scss
  src/frontend/app/features/services/detach-service-instance/detach-service-instance.component.spec.ts
  src/frontend/app/features/services/detach-service-instance/detach-service-instance.component.ts
  src/frontend/app/features/services/services.module.ts
  src/frontend/app/features/services/services.routing.ts
  src/frontend/app/shared/components/app-action-monitor/app-action-monitor.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/detach-apps/detach-apps-data-source.ts
  src/frontend/app/shared/components/list/list-types/detach-apps/detach-apps-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/detach-apps/detach-apps-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/app/shared/data-services/service-action-helper.service.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/service-bindings.actions.ts
  src/frontend/app/store/actions/service-instances.actions.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/reducers/service-instance.reducer.ts
Labels: comments-addressed, ready for review

#2271 Fix front-end user tests and a few other tests issues
  angular.json
  karma.conf.js
  package-lock.json
  src/frontend/app/app.component.spec.ts
  src/frontend/app/app.component.ts
  src/frontend/app/logged-in.service.spec.ts
  src/frontend/app/logged-in.service.ts
  src/frontend/app/shared/components/list/list-cards/custom-cards/card-app-event/app-event-detail-dialog-component/app-event-detail-dialog-component.component.spec.ts
  src/frontend/app/shared/shared.module.ts
Labels: V2, ready for review

#2280 Service Instance creation: Remove request to fetch service broker
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.html
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/cards/service-broker-card/service-broker-card.component.ts
  src/frontend/app/store/actions/service.actions.ts
Labels: in review, ready for review

#2170 Updated Build-images pipeline and refactor build scripts
  deploy/ci/build-images.yml
  deploy/ci/tasks/build-images/build-dc.yml
  deploy/ci/tasks/build-images/build-helm.yml
  deploy/ci/tasks/build-images/generate-certs.yml
  deploy/common-build.sh
  deploy/docker-compose/build.sh
  deploy/docker-compose/docker-compose.yml
  deploy/kubernetes/build.sh
Labels: ready for review

#2286 Ensure at least git 2.17.1 is installed
  deploy/stratos-base-images/Dockerfile.stratos-bk-base.tmpl
Labels: V2, in progress, in review

#2293 Add basic 404 page
  src/frontend/app/app.module.ts
  src/frontend/app/app.routing.ts
  src/frontend/app/core/page-not-found-component/page-not-found-component.component.html
  src/frontend/app/core/page-not-found-component/page-not-found-component.component.scss
  src/frontend/app/core/page-not-found-component/page-not-found-component.component.spec.ts
  src/frontend/app/core/page-not-found-component/page-not-found-component.component.ts
  src/frontend/app/core/page-not-found-component/page-not-found-component.theme.component.scss
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#2294 Remove CF Users when an endpoint is disconnected
  src/frontend/app/store/reducers/api-request-reducers.generator.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-clear-pagination-type.ts
  src/frontend/app/store/reducers/users.reducer.ts
Labels: in review, ready for review

#2223 Handle async request progress/success/failure in modals
  src/frontend/app/features/applications/application-delete/application-delete.component.html
  src/frontend/app/features/applications/create-application/create-application-step2/create-application-step2.component.ts
  src/frontend/app/features/applications/create-application/create-application-step3/create-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step-source-upload/deploy-application-step-source-upload.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2-1/deploy-application-step2-1.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.ts
  src/frontend/app/features/applications/edit-application/edit-application.component.html
  src/frontend/app/features/applications/edit-application/edit-application.component.ts
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/app/features/cloud-foundry/add-edit-space-step-base.ts
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/add-space/create-space-step/create-space-step.component.ts
  src/frontend/app/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users.component.html
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.ts
  src/frontend/app/features/user-profile/edit-profile-info/edit-profile-info.component.html
  src/frontend/app/features/user-profile/edit-profile-info/edit-profile-info.component.ts
  src/frontend/app/features/user-profile/user-profile.service.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.ts
  src/frontend/app/shared/components/endpoints-missing/endpoints-missing.component.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-map-routes-list-config.service.ts
  src/frontend/app/shared/components/stepper/step/step.component.ts
  src/frontend/app/shared/components/stepper/stepper-form/stepper-form.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/effects/uaa-setup.effects.ts
Labels: ready for review

#2292 Fix for two app headers on the CF View
  src/frontend/app/features/cloud-foundry/cloud-foundry.routing.ts
Labels: in review, ready for review

#2261 App create: Ensure we only show spaces we're a dev of
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.html
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-cf-roles.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.spec.ts
  src/frontend/app/store/selectors/current-user-roles-permissions-selectors/role.selectors.ts
  src/frontend/app/store/types/current-user-roles.types.ts
Labels: in review, ready for review

#2233 Edit service instance from Services Wall
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/features/services/services.routing.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/create-service-instance-helper-service-factory.service.ts
  src/frontend/app/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/app/shared/components/add-service-instance/csi-mode.service.spec.ts
  src/frontend/app/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.html
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.html
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/app/shared/components/stepper/step/step.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/app/shared/data-services/service-action-helper.service.ts
  src/frontend/app/store/actions/create-service-instance.actions.ts
  src/frontend/app/store/actions/service-instances.actions.ts
  src/frontend/app/store/reducers/service-instance.reducer.ts
Labels: needs attention, ready for review

#2284 Services permissions
  src/frontend/app/core/current-user-permissions.config.ts
  src/frontend/app/features/applications/application-delete/delete-app-instances/app-delete-instances-routes-list-config.service.ts
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.html
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/features/services/services-wall/services-wall.component.html
  src/frontend/app/features/services/services-wall/services-wall.component.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
Labels: ready for review

#2316 V1 e2e fix
  deploy/db/Dockerfile.goose.dev
  deploy/db/Dockerfile.k8s.postflight-job
  deploy/docker-compose/build.sh
Labels: V1

#2153 Add support for Angular XSRF protection
  package.json
  src/backend/app-core/auth.go
  src/backend/app-core/main.go
  src/backend/app-core/middleware.go
  src/backend/app-core/mock_server_test.go
  src/backend/app-core/portal_proxy.go
  src/backend/app-core/repository/interfaces/structs.go
  src/frontend/app/app.module.ts
  src/frontend/app/store/effects/auth.effects.ts
  src/frontend/app/xsrf.module.ts
Labels: V2, comments-addressed, in review, ready for review

#2277 Quicker e2e tests for PRs
  .travis.yml
  deploy/ci/travis/run-e2e-tests.sh
Labels: ready for review

#2247 Add Org & Space to Applications in card/Table view
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.html
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.spec.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
Labels: in review, ready for review

#2318 Log stream fixes
  src/backend/cloudfoundry/cf_websocket_streams.go
  src/frontend/app/shared/components/log-viewer/log-viewer.component.html
  src/frontend/app/shared/components/log-viewer/log-viewer.component.theme.scss
  src/frontend/app/shared/components/log-viewer/log-viewer.component.ts
Labels: ready for review

#2329 Fix missing header on some CF pages
  src/frontend/app/features/cloud-foundry/cloud-foundry.routing.ts
Labels: ready for review

#2355 Ensure we don't do aot when we serve and clean up config
  angular.json
  package.json
Labels: ready for review

#2345 Ensure we don't overwrite internal scopes with endpoint scopes
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-role-session.reducer.ts
Labels: ready for review

#2363 Add XSRF Support including for the legacy angular http library
  package.json
  src/backend/app-core/auth.go
  src/backend/app-core/main.go
  src/backend/app-core/middleware.go
  src/backend/app-core/mock_server_test.go
  src/backend/app-core/portal_proxy.go
  src/backend/app-core/repository/interfaces/structs.go
  src/frontend/app/app.module.ts
  src/frontend/app/store/effects/auth.effects.ts
  src/frontend/app/xsrf.module.ts
Labels: V2, in review, ready for review

#2365 SSH fixes
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.ts
  src/frontend/app/shared/components/cards/card-cf-space-details/card-cf-space-details.component.html
  src/frontend/app/shared/components/cards/card-cf-space-details/card-cf-space-details.component.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/test-framework/cloud-foundry-space.service.mock.ts
Labels: V2, in review, ready for review

#2368 Fix duplicate deploy info when local folder
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
Labels: V2, ready for review

#2326 Fix service binding count
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/effects/request.effects.ts
  src/frontend/app/store/reducers/service-instance.reducer.ts
  src/frontend/app/store/types/request.types.ts
Labels: ready for review

#2381 Fix env var modal exception after a service binding has been created
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.html
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
Labels: ready for review

#2379 Fix for App bound service is shown in services to bind to list
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.html
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
Labels: V2, ready for review

#2380 Tidy up the bind app step
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.ts
Labels: ready for review

#2375 Ensure the list paginator is shown when row is selected
  src/frontend/app/shared/components/list/list.component.html
Labels: ready for review

#2364 Display broker card if data is available without distorting app-tiles grid
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.html
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.ts
Labels: in review, ready for review

#2371 Fix app launch action display delay
  src/frontend/app/features/applications/application.service.ts
Labels: V2, ready for review

#2374 Setup: Add skip ssl option and improve error handling
  src/backend/app-core/auth.go
  src/backend/app-core/repository/interfaces/errors.go
  src/backend/app-core/setup_console.go
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.scss
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.ts
Labels: V2, in review, ready for review

#2376 Skip CF/Org selection when creating a space-scoped service
  deploy/tools/populate-cf/create-services.sh
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.html
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.ts
  src/frontend/app/features/service-catalog/services.service.mock.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/app/shared/components/cards/service-broker-card/service-broker-card.component.html
  src/frontend/app/shared/components/cards/service-broker-card/service-broker-card.component.ts
Labels: in review, ready for review

#2399 Ignore cookie domain for now
  deploy/kubernetes/console/templates/deployment.yaml
Labels: V2, ready for review

#2385 Fix issue where circular reference failed to denormalize an app's space
  src/frontend/app/store/helpers/entity-factory.ts
Labels: ready for review

#2391 Tidy up pagination key creation
  src/frontend/app/features/cloud-foundry/add-edit-space-step-base.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/services/services-wall/services-wall.component.ts
  src/frontend/app/features/services/services/services-wall.service.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-data-source.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-variables/cf-app-variables-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-services-data-source.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instances-wall-data-source.ts
  src/frontend/app/store/actions/app-metadata.actions.ts
  src/frontend/app/store/actions/application-service-routes.actions.ts
  src/frontend/app/store/actions/pagination.actions.ts
  src/frontend/app/store/helpers/entity-relations.types.ts
Labels: ready for review

#2398 Update release pipeline
  deploy/ci/console-dev-releases.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
Labels: in progress

#2377 Add more confirmation dialogs
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-spaces-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-org-permission-cell/cf-org-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-permission-cell.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  tslint.json
Labels: V2, question, ready for review

#2392 Fix bad error formatting on the backend
  src/backend/app-core/passthrough.go
Labels: V2, needs attention

#2389 Fix space selection when user returns to CFOrgSpace selector
  src/frontend/app/features/services/services/services-wall.service.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.html
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.scss
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.ts
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
Labels: in review, ready for review

#2400 Weekly update
  docs/roadmap.md
  docs/status_updates.md
Labels: ready for review

#2403 Fix not detecting admin user is admin scope is not stratos.admin
  src/frontend/app/core/current-user-permissions.config.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-role-session.reducer.ts
Labels: V2, ready for review

#2394 Fix a few UX issues
  src/frontend/app/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.html
  src/frontend/app/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.spec.ts
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.scss
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.scss
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
  src/frontend/app/shared/pipes/capitalizeFirstLetter.pipe.ts
  src/frontend/app/shared/shared.module.ts
Labels: V2, in review, ready for review

#2388 Fix TCP route creation and improve UI
  src/frontend/app/core/entity-service.spec.ts
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.html
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.scss
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/app/features/home/home/home-page.component.ts
  src/frontend/app/store/actions/domains.actions.ts
  src/frontend/app/store/actions/route.actions.ts
  src/frontend/app/store/effects/snackBar.effects.spec.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/types/route.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: V2, needs attention, ready for review

#2397 CfOrgSpace Selector: Fix overzealous `no orgs` error message
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.html
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.ts
Labels: in review, ready for review

#2409 Fix errors when multiple cf's are connected as both admin and non-admin users
  src/frontend/app/store/effects/permissions.effect.ts
Labels: P1, V2, ready for review

#2407 Fix and improve backend error handling with passthrough
  src/backend/app-core/passthrough.go
Labels: V2, in review, ready for review

#2413 Harden API error handling in case string is returned
  src/frontend/app/store/effects/api.effects.ts
Labels: V2, ready for review

#2378 Enable unbind operation in space-services
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/data-services/service-action-helper.service.ts
  src/frontend/app/store/actions/router.actions.ts
Labels: in review, ready for review

#2415 Show an overlay and deleting message when deleting from a card or table action.
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.spec.ts
  src/frontend/app/shared/components/cards/card-cf-space-details/card-cf-space-details.component.spec.ts
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.spec.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.html
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.spec.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.theme.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.html
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.scss
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.spec.ts
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.html
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpack-card/cf-buildpack-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-endpoints/cf-endpoint-card/endpoint-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-endpoints/cf-endpoint-card/endpoint-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-card/cf-stacks-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/shared.types.ts
  src/frontend/sass/_all-theme.scss
Labels: in review, ready for review

#2423 V2 Beta 1 Change Log
  CHANGELOG.md
Labels: V2, ready for review

#2259 E2e - Create Application
  package.json
  protractor.conf.js
  src/backend/app-core/passthrough.go
  src/frontend/app/store/types/api.types.ts
  src/frontend/app/store/types/app-metadata.types.ts
  src/test-e2e/application/application-create-e2e.spec.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/application/application-summary.po.ts
  src/test-e2e/application/application-view-e2e.spec.ts
  src/test-e2e/application/create-application-stepper.po.ts
  src/test-e2e/applications/application-wall-e2e.spec.ts
  src/test-e2e/applications/applications.po.ts
  src/test-e2e/cloud-foundry/cloud-foundry.po.ts
  src/test-e2e/cloud-foundry/endpoints-list-cf-e2e.spec.ts
  src/test-e2e/dashboard/dashboard-e2e.spec.ts
  src/test-e2e/e2e.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-register-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-unregister-e2e.spec.ts
  src/test-e2e/endpoints/endpoints.po.ts
  src/test-e2e/endpoints/register-dialog.po.ts
  src/test-e2e/helpers/cf-request-helpers.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/helpers/request-helpers.ts
  src/test-e2e/helpers/reset-helpers.ts
  src/test-e2e/helpers/screenshots-helper.ts
  src/test-e2e/login/login-e2e.spec.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/form.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/meta-card.po.ts
  src/test-e2e/po/page-header.po.ts
  src/test-e2e/po/page.po.ts
  src/test-e2e/po/stepper.po.ts
Labels: V2, ready for review

#2372 Fix various application deploy bugs
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application.component.ts
  src/frontend/app/shared/components/list/list-types/github-commits/github-commits-list-config-app-tab.service.ts
  src/frontend/app/shared/components/list/list-types/github-commits/github-commits-list-config-deploy.service.ts
  src/frontend/app/store/actions/deploy-applications.actions.ts
  src/frontend/app/store/reducers/deploy-app.reducer.ts
  src/frontend/app/store/selectors/deploy-application.selector.ts
  src/frontend/app/store/types/deploy-application.types.ts
Labels: V2, in review, ready for review

#2383 Validate host/path pattern in Create Route form
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.html
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.ts
Labels: comments-addressed, ready for review

#2416 Display commit SHA/ Release tag in the About page
  build/bk-build-utils.js
  deploy/Dockerfile.bk
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-nightly-releases.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
  deploy/ci/tasks/dev-releases/nightly-release-name
  deploy/common.yml
  deploy/stand-up-dev-env.sh
  deploy/tools/restart_proxy.sh
Labels: comments-addressed

#2393 Org space list - Deleting causes exceptions in other parts of the org page.
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
Labels: blocked-pr, ready for review

#2412 Table loading init
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
Labels: V2, in review, ready for review

#2430 Fix exception thrown when only assign an org user role
  src/frontend/app/store/effects/users-roles.effects.ts
Labels: ready for review

#2401 Add support for longer timeout for mutating operations (POST etc)
  build/dev/config.properties
  deploy/all-in-one/config.all-in-one.properties
  deploy/cloud-foundry/config.properties
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/proxy.env
  deploy/stratos-ui-release/jobs/backend/templates/config.properties.erb
  src/backend/app-core/auth.go
  src/backend/app-core/development.rc.sample
  src/backend/app-core/http_basic_requests.go
  src/backend/app-core/main.go
  src/backend/app-core/main_test.go
  src/backend/app-core/oauth_requests.go
  src/backend/app-core/oidc_requests.go
  src/backend/app-core/repository/interfaces/portal_proxy.go
  src/backend/app-core/repository/interfaces/structs.go
Labels: V2, ready for review

#2433 Fix exception when a space is added to an empty org
  src/frontend/app/shared/components/cards/card-cf-recent-apps/card-cf-recent-apps.component.ts
Labels: ready for review

#2390 Fix infinite user list's loading indicator when connected as user with no roles
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/effects/users.effects.ts
Labels: needs attention, ready for review

#2429 Fix pagination of space level routes and service instance tables
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/service-instances/service-instances-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instances-wall-list-config.service.ts
  src/frontend/app/store/actions/service-instances.actions.ts
  src/frontend/app/store/actions/space.actions.ts
Labels: ready for review

#2439 Fix issue where space count is wrong after deleting a space
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
Labels: V2, ready for review

#2402 Users Table: Restrict org/space roles and prefix space name with org... depending on depth
  src/frontend/app/core/current-user-permissions.checker.ts
  src/frontend/app/core/current-user-permissions.service.ts
  src/frontend/app/features/applications/application-delete/application-delete.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-users/cloud-foundry-space-users.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-users/cloud-foundry-users.component.ts
  src/frontend/app/shared/components/list/list-types/cf-org-users/cf-org-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-users/cf-space-users-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-space-users/cf-space-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-org-permission-cell/cf-org-permission-cell.component.html
  src/frontend/app/shared/components/list/list-types/cf-users/cf-org-permission-cell/cf-org-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-permission-cell.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.html
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
Labels: ready for review

#2367 Add situational 'cf' to 'org/space' value in app wall app card/table
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/shared/components/list/list-table/table-cell/table-cell.component.html
  src/frontend/app/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/app/shared/components/list/list-types/app/TableCellAppCfOrgSpaceBase.ts
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.html
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.spec.ts
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-cforgspace-header/table-cell-app-cforgspace-header.component.html
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-cforgspace-header/table-cell-app-cforgspace-header.component.scss
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-cforgspace-header/table-cell-app-cforgspace-header.component.spec.ts
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-cforgspace-header/table-cell-app-cforgspace-header.component.ts
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-cforgspace/table-cell-app-cforgspace.component.html
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-cforgspace/table-cell-app-cforgspace.component.scss
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-cforgspace/table-cell-app-cforgspace.component.spec.ts
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-cforgspace/table-cell-app-cforgspace.component.ts
Labels: ready for review

#2441 Fix for panic when res is not set in error logging
  src/backend/app-core/passthrough.go
Labels: P1, V2, bug

#2434 Fix list state (deleting/etc)
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-config.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.html
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-route-row-state.helper.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-data-source.ts
  src/frontend/app/shared/components/list/list-types/github-commits/github-commits-data-source.ts
  src/frontend/app/shared/components/list/list.component.ts
Labels: P1, ready for review

#2442 Update v2 info on readme, fix typo in roadmap doc
  README.md
  docs/roadmap.md
Labels: V2

#2435 Update the connected user roles section of store on roles change
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-confirm/manage-users-confirm.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-org-permission-cell/cf-org-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-permission-cell.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/store/actions/users.actions.ts
  src/frontend/app/store/effects/users-roles.effects.ts
  src/frontend/app/store/reducers/auth.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-changed.reducers.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.ts
  src/frontend/app/store/reducers/users.reducer.ts
Labels: ready for review

#2443 Users tables: Only show org/space name in pills when needed
  src/frontend/app/shared/components/list/list-types/cf-users/cf-org-permission-cell/cf-org-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-permission-cell.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
Labels: P1, ready for review

#2427 Disable removal of `org user` role if user has others
  src/frontend/app/shared/components/list/list-types/cf-users/cf-org-permission-cell/cf-org-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-permission-cell.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
Labels: in review, ready for review

#2283 Allow metrics endpoint token to be shared
  src/backend/app-core/auth.go
  src/backend/app-core/info.go
  src/backend/app-core/middleware.go
  src/backend/app-core/mock_server_test.go
  src/backend/app-core/oauth_requests_test.go
  src/backend/app-core/passthrough_test.go
  src/backend/app-core/repository/interfaces/portal_proxy.go
  src/backend/app-core/repository/interfaces/structs.go
  src/backend/app-core/repository/tokens/pgsql_tokens.go
  src/backend/app-core/repository/tokens/pgsql_tokens_test.go
  src/backend/app-core/repository/tokens/tokens.go
  src/backend/cloudfoundry/main.go
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.html
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.scss
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/app/features/endpoints/endpoint-helpers.ts
  src/frontend/app/shared/components/list/list-types/cf-endpoints/cf-endpoint-card/endpoint-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-data-source.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-name/table-cell-endpoint-name.component.html
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-name/table-cell-endpoint-name.component.scss
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-name/table-cell-endpoint-name.component.ts
  src/frontend/app/store/actions/endpoint.actions.ts
  src/frontend/app/store/effects/endpoint.effects.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-role-session.reducer.ts
  src/frontend/app/store/types/endpoint.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: V2, in review

#2432 Add back in Cookie Domain support
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
  src/backend/app-core/middleware.go
  src/frontend/app/app.routing.ts
  src/frontend/app/features/login/login-page/login-page.component.ts
  src/frontend/app/features/setup/domain-mismatch/domain-mismatch.component.html
  src/frontend/app/features/setup/domain-mismatch/domain-mismatch.component.scss
  src/frontend/app/features/setup/domain-mismatch/domain-mismatch.component.spec.ts
  src/frontend/app/features/setup/domain-mismatch/domain-mismatch.component.ts
  src/frontend/app/features/setup/setup.module.ts
  src/frontend/app/store/actions/auth.actions.ts
  src/frontend/app/store/effects/auth.effects.ts
  src/frontend/app/store/reducers/auth.reducer.ts
  src/frontend/app/store/types/auth.types.ts
Labels: V2, comments-addressed

#2484 Fix backend error logging
  src/backend/app-core/passthrough.go
Labels: P1, V2, bug, ready for review

#2487 Improved fix for exception on org screen after fresh load on create space
  src/frontend/app/store/helpers/entity-relations.ts
  src/frontend/app/store/reducers/api-request-data-reducer/request-data-reducer.factory.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
Labels: ready for review

#2488 Fixed exception after unmapping routes
  src/frontend/app/features/applications/application.service.ts
Labels: ready for review

#2491 SSO Login Support
  src/backend/app-core/auth.go
  src/backend/app-core/config/config.go
  src/backend/app-core/glide.lock
  src/backend/app-core/main.go
  src/backend/app-core/middleware.go
  src/backend/app-core/repository/interfaces/portal_proxy.go
  src/backend/app-core/repository/interfaces/structs.go
  src/backend/cloudfoundry/main.go
  src/frontend/app/features/login/login-page/login-page.component.html
  src/frontend/app/features/login/login-page/login-page.component.scss
  src/frontend/app/features/login/login-page/login-page.component.ts
  src/frontend/app/store/actions/auth.actions.ts
  src/frontend/app/store/effects/auth.effects.ts
  src/frontend/app/store/reducers/auth.reducer.ts
  src/frontend/app/store/types/auth.types.ts
Labels: V2, ready for review

#2494 Ensure we only raise internal errors on fetch api requests
  src/frontend/app/store/effects/api.effects.ts
Labels: ready for review

#2481 Service Catalog UI Tweaks
  src/frontend/app/shared/components/boolean-indicator/boolean-indicator.component.html
  src/frontend/app/shared/components/boolean-indicator/boolean-indicator.component.theme.scss
  src/frontend/app/shared/components/boolean-indicator/boolean-indicator.component.ts
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.html
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-title/meta-card-title.component.html
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-title/meta-card-title.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-title/meta-card-title.component.ts
  src/frontend/app/shared/components/list/list-types/cf-endpoints/cf-endpoint-card/endpoint-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.scss
  src/frontend/app/shared/components/service-icon/service-icon.component.html
  src/frontend/app/shared/components/service-icon/service-icon.component.ts
Labels: V2, in review, ready for review

#2485 Center align icon and align text to it
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.scss
Labels: V2, in review, ready for review

#2489 Fix issue timing issue resulting in invalid Space Service request
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.ts
  src/frontend/app/store/actions/service-instances.actions.ts
  src/frontend/app/store/actions/space.actions.ts
Labels: in review, ready for review

#2499 Fix smaller UI issues
  src/frontend/app/shared/components/dialog-confirm/dialog-confirm.component.scss
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.html
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-cforgspace-header/table-cell-app-cforgspace-header.component.html
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/index.html
  src/frontend/sass/components/mat-popup.scss
  src/frontend/styles.scss
Labels: V2, ready for review

#2498 Ensure requests to multiple endpoints continue if one fails
  src/frontend/app/store/effects/api.effects.ts
Labels: in review, ready for review

#2501 Provide Create Service Instance its own CfOrgSpaceDataService instance
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
Labels: ready for review

#2496 Show users without usernames
  README.md
  deploy/cloud-foundry/README.md
  docs/developers-guide.md
  docs/troubleshooting.md
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.scss
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-data-source.service.ts
  src/frontend/app/store/helpers/entity-factory.ts
Labels: ready for review

#2503 Build-args file should be JSON
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
Labels: ready for review

#2507 Beta 2 Changelog
  CHANGELOG.md
Labels: ready for review

#2508 Ensure remove user confirmation modal contains correct role prefix
  src/frontend/app/shared/components/list/list-types/cf-users/cf-permission-cell.ts
Labels: ready for review

#2512 Update Pipeline for CAP releases
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-release.yml
  deploy/ci/scripts/build_dcind_image.sh
  deploy/ci/tasks/release/build-helm.yml
  deploy/ci/tasks/release/create-chart-sle.yml
  deploy/ci/tasks/release/create-chart.yml
  deploy/ci/tasks/release/update-gh-release.yml
Labels: ready for review

#2513 Fixed issue where we failed to store response from 1 or more endpoints
  src/frontend/app/store/effects/api.effects.ts
Labels: P1, ready for review

#2510 Add ingress example and docs for kubernetes deloyment
  deploy/kubernetes/README.md
  deploy/kubernetes/ingress/README.md
  deploy/kubernetes/ingress/ingress.yml
Labels: V2, ready for review

#2506 Fix route schema
  src/frontend/app/store/helpers/entity-factory.ts
Labels: in review, ready for review

#2511 Fix for app count being stuck after add in org card
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/store/reducers/api-request-reducers.generator.ts
  src/frontend/app/store/reducers/application-add-remove-reducer.ts
Labels: V2, ready for review

#2515 Fixes state reset issue when creating a service instance from different modes
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/app/store/actions/create-service-instance.actions.ts
  src/frontend/app/store/actions/service-instances.actions.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/reducers/create-service-instance.reducer.ts
Labels: ready for review

#2528 Minor tweaks to the Release pipeline
  deploy/ci/console-dev-releases.yml
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
Labels: ready for review

#2530 Remove base git package
  deploy/stratos-base-images/Dockerfile.stratos-bk-base.tmpl
Labels: ready for review

#2486 Entity deletion: Remove child entities
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.ts
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.html
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/app/store/actions/application.actions.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/effects/recursive-entity-delete.effect.ts
  src/frontend/app/store/effects/snackBar.effects.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/helpers/schema-tree-traverse.spec.ts
  src/frontend/app/store/helpers/schema-tree-traverse.ts
  src/frontend/app/store/reducers/api-request-data-reducer/request-data-reducer.factory.ts
  src/frontend/app/store/reducers/api-request-reducer/deleting-child-entities.ts
  src/frontend/app/store/reducers/api-request-reducer/request-helpers.ts
  src/frontend/app/store/reducers/api-request-reducer/request-reducer.factory.ts
  src/frontend/app/store/store.module.ts
Labels: V2, needs attention

#2533 Configurable backend log level
  deploy/development.rc.template
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
  deploy/proxy.env
  src/backend/app-core/main.go
  src/backend/app-core/repository/interfaces/structs.go
Labels: comments-addressed, ready for review

#2544 Update `tokens` table to fix issue affecting upgrades
  deploy/proxy.env
  src/backend/app-core/datastore/20180627111300_UpdateMetadata.go
  src/backend/app-core/repository/tokens/pgsql_tokens.go
Labels: P1, V2, comments-addressed

#2547 Postflight script times out if it can not connect
  deploy/db/scripts/run-postflight-job.k8s.sh
Labels: V2, ready for review

#2553 Fix client and client secret issues when pushing apps
  src/backend/cfapppush/deploy.go
Labels: V2, ready for review

#2552 Fix Docker All-in-one image build
  deploy/Dockerfile.all-in-one
  deploy/all-in-one/Dockerfile
  deploy/all-in-one/README.md
Labels: V2, ready for review

#2517 Use consistent icons
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/routes-tab/routes-tab/routes-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/services-tab/services-tab.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.html
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/app/features/dashboard/side-nav/side-nav.component.html
  src/frontend/app/features/dashboard/side-nav/side-nav.component.scss
  src/frontend/app/features/dashboard/side-nav/side-nav.component.ts
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.html
  src/frontend/app/features/services/services-wall/services-wall.component.html
  src/frontend/app/shared/components/cards/card-cf-info/card-cf-info.component.html
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.html
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.ts
  src/frontend/app/shared/components/metadata-item/metadata-item.component.html
  src/frontend/app/shared/components/metadata-item/metadata-item.component.ts
  src/frontend/app/shared/components/no-content-message/no-content-message.component.html
  src/frontend/app/shared/components/no-content-message/no-content-message.component.ts
  src/frontend/app/shared/components/service-icon/service-icon.component.html
  src/frontend/assets/fonts/stratos/LICENSE
  src/frontend/assets/fonts/stratos/stratos-icons.eot
  src/frontend/assets/fonts/stratos/stratos-icons.svg
  src/frontend/assets/fonts/stratos/stratos-icons.ttf
  src/frontend/assets/fonts/stratos/stratos-icons.woff
  src/frontend/assets/fonts/stratos/stratos-icons.woff2
  src/frontend/sass/icons.scss
Labels: V2, comments-addressed, ready for review

#2521 Update to newer UAA version for test/dev
  deploy/uaa/Dockerfile.dev
  deploy/uaa/prepare.sh
  deploy/uaa/uaa.yml
Labels: V2, ready for review

#2564 Fix exception thrown when creating new space
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
Labels: ready for review

#2565 Update Build Images concourse pipeline
  deploy/Dockerfile.bk
  deploy/ci/build-images.yml
Labels: ready for review

#2576 Add e2e-tests branch to travis
  .travis.yml
Labels: V2

#2562 Fix assign role for non-admin connected user
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/store/actions/users.actions.ts
  src/frontend/app/store/effects/users-roles.effects.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-changed.reducers.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-org.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-space.reducer.ts
Labels: P1, V2, ready for review

#2566 Fix create app step 'valid' which disabled stepper next in production
  src/frontend/app/shared/components/create-application/create-application-step1/create-application-step1.component.ts
Labels: V2, ready for review

#2583 Fix E2E Tests
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  protractor.conf.js
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/test-e2e/applications/applications.po.ts
Labels: V2, in review, ready for review

#2548 Update App Summary entity after carrying out App Route actions
  src/frontend/app/core/cf-api.types.ts
  src/frontend/app/core/entity-service.ts
  src/frontend/app/features/applications/application-delete/application-delete.component.ts
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-list-config.service.ts
  src/frontend/app/store/actions/route.actions.ts
  src/frontend/app/store/effects/app.effects.ts
  src/frontend/app/store/reducers/api-request-reducers.generator.ts
  src/frontend/app/store/reducers/routes.reducer.ts
  src/frontend/app/store/store.module.ts
Labels: P2, in review, ready for review

#2584 Clear service instances pagination after disconnecting an endpoint
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.ts
  src/frontend/app/features/services/services-wall/services-wall.component.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-clear-pagination-type.ts
Labels: bug, in review, ready for review

#2586 RC2 Changelog
  CHANGELOG.md
Labels: ready for review

#2596 Docs update for observeOn(asapScheduler) about ExpressionChangedAfterItHasBeenCheckedError
  docs/developers-guide-env-tech.md
Labels: ready for review
