Repository cloudfoundry/stratos, pull requests merged in 2018-08, with the labels that each got.

#2784 Fail requests to fetch arbitrary files
  src/backend/app-core/main.go
  src/backend/app-core/middleware.go
Labels: in review, ready for review

#2731 Deploy App E2E Test
  src/frontend/app/features/applications/deploy-application/deploy-application.component.html
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-summary.po.ts
  src/test-e2e/application/deploy-app.po.ts
  src/test-e2e/applications/applications.po.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/stepper.po.ts
  src/test-e2e/secrets.yaml.example
Labels: V2-next, in review, ready for review

#2789 Add x-frame header to static file servers
  deploy/containers/nginx/conf/nginx.dev.conf
  deploy/containers/nginx/conf/nginx.k8s.conf
  deploy/stratos-ui-release/jobs/frontend/templates/nginx.conf.erb
  src/backend/app-core/main.go
Labels: ready for review

#2794 Docs: Rename potral-proxy to Jet Stream
  docs/developers-guide.md
  docs/issue_template.md
Labels: ready for review

#2790 Restrict number of calls to app stats on app wall
  src/frontend/app/core/dispatch-sequencer.ts
  src/frontend/app/core/utils.service.ts
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/applications/create-application/create-application.component.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/app/cf-apps-data-source.ts
Labels: ready for review

#2741 Api reducers tests
  src/frontend/app/store/reducers/api-request-data-reducer/request-data-reducer.factory.spec.ts
  src/frontend/app/store/reducers/api-request-data-reducer/request-data-reducer.factory.ts
  src/frontend/app/store/types/api.types.ts
Labels: in review, ready for review

#2799 Exclude stopped app's from instance counts used with instance quotas
  src/frontend/app/core/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
Labels: ready for review

#2796 Add unit tests for entity relations/validation
  .gitignore
  karma.conf.js
  src/frontend/app/store/helpers/entity-relations-from-parent.spec.ts
  src/frontend/app/store/helpers/entity-relations-list.spec.ts
  src/frontend/app/store/helpers/entity-relations-validate.spec.ts
  src/frontend/app/store/helpers/entity-relations.spec.ts
  src/frontend/app/store/helpers/entity-relations.tree.spec.ts
  src/frontend/app/store/helpers/entity-relations.tree.ts
  src/frontend/app/store/helpers/entity-relations.ts
  src/frontend/app/store/helpers/entity-relations.types.ts
Labels: ready for review

#2801 Fix sort in app list component
  src/frontend/app/core/utils.service.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
Labels: ready for review

#2776 Fix redirect with SSO and Fix bug caused by extra slash in AutoRegUrl
  src/backend/app-core/auth.go
  src/backend/cloudfoundry/main.go
  src/frontend/app/features/login/login-page/login-page.component.ts
Labels: in progress

#2804 Deploy e2e test fixes
  src/test-e2e/application/application-summary.po.ts
  src/test-e2e/po/page-header.po.ts
  src/test-e2e/po/page.po.ts
Labels: ready for review

#2802 replace random cnsi guid with sha1 hash
  src/backend/app-core/cnsi.go
Labels: enhancement, needs attention

#2808 Ensure only space devs can manage an application
  package-lock.json
  src/frontend/app/core/current-user-permissions.config.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
Labels: in review, ready for review

#2811 Remove fdescribe
  src/frontend/app/store/helpers/entity-relations/entity-relations-from-parent.spec.ts
  src/frontend/app/store/helpers/entity-relations/entity-relations-validate.spec.ts
  src/frontend/app/store/helpers/entity-relations/entity-relations.types.ts
Labels: ready for review

#2818 Update index.yaml in gh-pages
  index.yaml
Labels: ready for review

#2819 Update nigthly release pipeline to allow helm repo configuration
  deploy/ci/console-nightly-releases.yml
  deploy/ci/tasks/dev-releases/create-nightly-chart.yml
Labels: ready for review

#2817 Update README travis badge link to avoid `current` tab confusion
  README.md
Labels: ready for review

#2777 E2e: Basic e2e tests for cf/org/space pages of Cloud Foundry section
  src/frontend/app/shared/components/loading-page/loading-page.component.ts
  src/frontend/app/shared/user-permission.directive.ts
  src/frontend/app/store/types/api.types.ts
  src/test-e2e/application/application-create-e2e.spec.ts
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-page.po.ts
  src/test-e2e/cloud-foundry/cloud-foundry-list-cf-e2e.spec.ts
  src/test-e2e/cloud-foundry/cloud-foundry.po.ts
  src/test-e2e/cloud-foundry/org-level/cf-org-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/cf-org-level-page.po.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-page.po.ts
  src/test-e2e/e2e.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-register-e2e.spec.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/helpers/cf-request-helpers.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/helpers/secrets-helpers.ts
  src/test-e2e/login/login-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance-stepper.po.ts
  src/test-e2e/marketplace/marketplace-summary-e2e.spec.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
  src/test-e2e/po/breadcrumbs.po.ts
  src/test-e2e/po/cf-page.po.ts
  src/test-e2e/po/loading-indicator.po.ts
  src/test-e2e/po/meta-data-time.po.ts
  src/test-e2e/po/page-header.po.ts
  src/test-e2e/po/page-subheader.po.ts
  src/test-e2e/po/page.po.ts
  src/test-e2e/po/snackbar.po.ts
  src/test-e2e/po/stepper.po.ts
  src/test-e2e/secrets.yaml.example
Labels: ready for review

#2844 Update Changelog for 2.0.1
  CHANGELOG.md
Labels: ready for review

#2823 Added word break to the log viewer
  src/frontend/app/shared/components/log-viewer/log-viewer.component.scss
Labels: in review, ready for review

#2800 Refactor out CF Push handling to a separate package
  src/backend/app-core/cnsi.go
  src/backend/cfapppush/deploy.go
  src/backend/cfapppush/main.go
  src/backend/cfapppush/pushapp/pushapp.go
Labels: in review, ready for review

#2838 Allow front-end to be pre-built
  .gitignore
  build/fe-build.js
  deploy/cloud-foundry/README.md
  deploy/cloud-foundry/build.sh
  package-lock.json
  package.json
Labels: in review, ready for review, review

#2726 App Variables Tab: Split variables out into their CF defined buckets
  src/frontend/app/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.scss
  src/frontend/app/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.ts
Labels: ready for review

#2821 Remove all tokens associated with a cnsi on unregister, also fix e2e
  deploy/ci/travis/run-e2e-tests.sh
  protractor.conf.js
  src/backend/app-core/cnsi.go
  src/backend/app-core/datastore/20180813110300_RemoveStaleTokens.go
  src/backend/app-core/repository/tokens/pgsql_tokens.go
  src/backend/app-core/repository/tokens/pgsql_tokens_test.go
  src/backend/app-core/repository/tokens/tokens.go
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/test-e2e/application/application-create-e2e.spec.ts
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/application/application-summary.po.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-page.po.ts
  src/test-e2e/e2e.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/helpers/cf-request-helpers.ts
  src/test-e2e/helpers/reset-helpers.ts
  src/test-e2e/marketplace/create-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance-stepper.po.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/page-header.po.ts
  src/test-e2e/po/page-subheader.po.ts
  src/test-e2e/po/page.po.ts
  src/test-e2e/po/snackbar.po.ts
  src/test-e2e/po/stepper.po.ts
Labels: ready for review

#2857 Fix bug in `generate-tag-files` concourse task
  deploy/ci/console-nightly-releases.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
Labels: ready for review

#2859 Specify imagePullPolicy in nightly builds
  deploy/ci/console-nightly-releases.yml
  deploy/ci/tasks/dev-releases/create-chart-helper.sh
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/ci/tasks/dev-releases/create-nightly-chart.yml
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#2860 Fixes and improvement for the diagnostics page
  package.json
  src/frontend/app/features/about/diagnostics-page/diagnostics-page.component.html
  src/frontend/app/features/about/diagnostics-page/diagnostics-page.component.scss
  src/frontend/app/features/about/diagnostics-page/diagnostics-page.component.ts
  src/frontend/app/shared/components/metadata-item/metadata-item.component.html
  src/frontend/app/shared/components/metadata-item/metadata-item.component.scss
  src/jetstream/diagnostics.go
  src/jetstream/main.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/repository/interfaces/structs.go
Labels: in review, ready for review

#2911 Fix issues with cookie not being marked as secure or http only with sqlite session store
  Gopkg.lock
  src/jetstream/main.go
Labels: ready for review

#2910 Update cache-control header
  src/jetstream/main.go
  src/jetstream/middleware.go
Labels: ready for review

#2876 Fix for base image dockerfile missing wget
  deploy/stratos-base-images/Dockerfile.stratos-go-build-base.tmpl
Labels: ready for review

#2861 Improvements to simplify dev experience with go backend
  .gitignore
  build/bk-build.sh
  build/fe-build.js
  build/gulp.config.js
  build/legacy/bk-conf.js
  build/proxy.conf.localdev.js
  deploy/Dockerfile.all-in-one
  deploy/Dockerfile.bk
  deploy/ci/travis/config.properties
  deploy/ci/travis/run-e2e-tests.sh
  deploy/cloud-foundry/build.sh
  deploy/cloud-foundry/start.sh
  deploy/containers/proxy/entrypoint.sh
  deploy/db/scripts/development.sh
  deploy/db/scripts/run-postflight-job.k8s.sh
  docs/developers-guide.md
  package.json
  src/jetstream/default.config.properties
  src/jetstream/main.go
Labels: in review, ready for review

#2923 Fix code cov button
  README.md
Labels: ready for review

#2903 First round of go lint fixes
  .travis.yml
  README.md
  deploy/ci/travis/create-pr-branch.sh
  deploy/ci/travis/run-e2e-tests.sh
  deploy/ci/travis/update-go-report-card.sh
  src/jetstream/main.go
  src/jetstream/plugins/cfapppush/app-repository.go
  src/jetstream/plugins/cfapppush/deploy.go
  src/jetstream/plugins/cfapppush/main.go
  src/jetstream/plugins/cfapppush/pushapp/pushapp.go
  src/jetstream/plugins/cfappssh/app_ssh.go
  src/jetstream/plugins/cfappssh/main.go
  src/jetstream/plugins/cloudfoundry/main.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/plugins/metrics/cloud_foundry.go
  src/jetstream/plugins/metrics/main.go
  src/jetstream/plugins/userinfo/main.go
  src/jetstream/plugins/userinfo/user_info.go
Labels: ready for review

#2908 Harden the service wall instance card
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/features/services/services/services-wall.service.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/app/shared/components/list/list-cards/card/card.component.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
Labels: ready for review

#2931 Fix application deploy
  README.md
  src/jetstream/plugins/cfapppush/deploy.go
Labels: ready for review

#2827 Endpoint list: Show logged in user's username and whether they're an admin or not.
  src/frontend/app/features/endpoints/endpoint-helpers.ts
  src/frontend/app/shared/components/cards/card-cf-info/card-cf-info.component.html
  src/frontend/app/shared/components/cards/card-cf-info/card-cf-info.component.spec.ts
  src/frontend/app/shared/components/cards/card-cf-info/card-cf-info.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-filtering-sorting.ts
  src/frontend/app/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-is-admin/table-cell-endpoint-is-admin.component.html
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-is-admin/table-cell-endpoint-is-admin.component.scss
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-is-admin/table-cell-endpoint-is-admin.component.spec.ts
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-is-admin/table-cell-endpoint-is-admin.component.ts
Labels: ready for review

#2788 Add metrics to Stratos helm chart
  deploy/ci/tasks/dev-releases/create-chart-helper.sh
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/ci/tasks/dev-releases/create-nightly-chart.yml
  deploy/kubernetes/README.md
  deploy/kubernetes/build.sh
  deploy/kubernetes/console/requirements.lock
  deploy/kubernetes/console/requirements.yaml
  deploy/kubernetes/console/values.yaml
Labels: in review, ready for review

#2935 Fix broken e2e tests [e2e]
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-page.po.ts
  src/test-e2e/cloud-foundry/org-level/cf-org-level-page.po.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-page.po.ts
  src/test-e2e/endpoints/endpoints.po.ts
  src/test-e2e/po/boolean-indicator.po.ts
  src/test-e2e/po/meta-data-item.po.ts
Labels: ready for review

#2826 Fix several manage user role bugs
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-modify/manage-users-modify.component.html
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-modify/manage-users-modify.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-permission-cell.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/helpers/entity-relations/entity-relations.ts
Labels: ready for review

#2940 Weekly update
  docs/status_updates.md
Labels: ready for review

#2932 Fix E2E Test report upload
  .travis.yml
  deploy/ci/travis/upload-e2e-test-report.sh
Labels: ready for review

#2919 Use new Stratos logo on splash/login and about page
  src/frontend/app/features/dashboard/side-nav/side-nav.component.ts
  src/frontend/app/shared/components/stratos-title/stratos-title.component.html
  src/frontend/app/shared/components/stratos-title/stratos-title.component.scss
  src/frontend/app/shared/components/stratos-title/stratos-title.component.ts
  src/frontend/assets/stratos-logo.png
Labels: ready for review
