Repository cloudfoundry/stratos, pull requests merged in 2018-05, with the labels that each got.

#2085 Return better error information from API passthroughs
  src/backend/app-core/passthrough.go
  src/backend/app-core/repository/interfaces/structs.go
  src/frontend/app/shared/monitors/internal-event.monitor.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/types/internal-events.types.ts
Labels: in review, ready for review

#2086 Create & List Service Instances
  src/frontend/app/core/cf-api-svc.types.ts
  src/frontend/app/features/cloud-foundry/add-space/create-space-step/create-space-step.component.html
  src/frontend/app/features/cloud-foundry/add-space/create-space-step/create-space-step.component.scss
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/service-catalog/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/features/service-catalog/add-service-instance/add-service-instance/add-service-instance.component.scss
  src/frontend/app/features/service-catalog/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/app/features/service-catalog/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/bind-apps-step/bind-apps-step.component.html
  src/frontend/app/features/service-catalog/add-service-instance/bind-apps-step/bind-apps-step.component.scss
  src/frontend/app/features/service-catalog/add-service-instance/bind-apps-step/bind-apps-step.component.spec.ts
  src/frontend/app/features/service-catalog/add-service-instance/bind-apps-step/bind-apps-step.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/select-plan-step/select-plan-step.component.html
  src/frontend/app/features/service-catalog/add-service-instance/select-plan-step/select-plan-step.component.scss
  src/frontend/app/features/service-catalog/add-service-instance/select-plan-step/select-plan-step.component.spec.ts
  src/frontend/app/features/service-catalog/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/specify-details-step/specify-details-step.component.html
  src/frontend/app/features/service-catalog/add-service-instance/specify-details-step/specify-details-step.component.scss
  src/frontend/app/features/service-catalog/add-service-instance/specify-details-step/specify-details-step.component.spec.ts
  src/frontend/app/features/service-catalog/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/features/service-catalog/service-base/service-base.component.html
  src/frontend/app/features/service-catalog/service-base/service-base.component.scss
  src/frontend/app/features/service-catalog/service-base/service-base.component.spec.ts
  src/frontend/app/features/service-catalog/service-base/service-base.component.ts
  src/frontend/app/features/service-catalog/service-catalog.helpers.ts
  src/frontend/app/features/service-catalog/service-catalog.module.ts
  src/frontend/app/features/service-catalog/service-catalog.routing.ts
  src/frontend/app/features/service-catalog/service-instances/service-instances.component.html
  src/frontend/app/features/service-catalog/service-instances/service-instances.component.scss
  src/frontend/app/features/service-catalog/service-instances/service-instances.component.spec.ts
  src/frontend/app/features/service-catalog/service-instances/service-instances.component.ts
  src/frontend/app/features/service-catalog/services.service.mock.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/shared/components/cards/card-cf-recent-apps/card-cf-recent-apps.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.ts
  src/frontend/app/shared/components/list/list-types/service-instances/service-instances-data-source.ts
  src/frontend/app/shared/components/list/list-types/service-instances/service-instances-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/service-instances/service-instances-list-config.service.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/app/shared/monitors/entity-monitor.ts
  src/frontend/app/store/actions/create-service-instance.actions.ts
  src/frontend/app/store/actions/domains.actions.ts
  src/frontend/app/store/actions/service-bindings.actions.ts
  src/frontend/app/store/actions/service-instances.actions.ts
  src/frontend/app/store/actions/service.actions.ts
  src/frontend/app/store/app-state.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/reducers.module.ts
  src/frontend/app/store/reducers/create-service-instance.reducer.ts
  src/frontend/app/store/selectors/create-service-instance.selectors.ts
  src/frontend/app/store/types/create-service-instance.types.ts
  src/frontend/app/store/types/entity.types.ts
  src/frontend/app/store/types/service.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: in review, ready for review

#1366 Add support for building back-end on non-linux platforms
  build/bk-build-utils.js
  build/bk-build.js
  components/app-core/backend/load_plugins.go
  components/app-core/backend/load_plugins.static.go
  docs/development.md
Labels: V1, in review

#2119 Add slack badge to readme
  README.md
Labels: ready for review

#2127 Fix update of endpoints table on register endpoint
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint.component.ts
  src/frontend/app/store/effects/endpoint.effects.ts
Labels: ready for review

#2102 Update services planning document with service instance creation details
  docs/planning/services.md
Labels: ready for review

#2111 Service Instance creation: Support space-scoped broker provided plans
  src/frontend/app/core/cf-api-svc.types.ts
  src/frontend/app/features/service-catalog/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/bind-apps-step/bind-apps-step.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/features/service-catalog/service-base/service-base.component.ts
  src/frontend/app/features/service-catalog/services.service.mock.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/store/actions/create-service-instance.actions.ts
  src/frontend/app/store/actions/service-broker.actions.ts
  src/frontend/app/store/actions/service-plan-visibility.actions.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/helpers/entity-relations.ts
  src/frontend/app/store/reducers/api-request-reducers.generator.ts
  src/frontend/app/store/reducers/create-service-instance.reducer.ts
  src/frontend/app/store/types/create-service-instance.types.ts
  src/frontend/app/store/types/entity.types.ts
  src/frontend/app/store/types/request.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: ready for review

#2132 CF Push: Increase memory in order to speed up build
  manifest.yml
  package.json
Labels: ready for review

#1997 Fix Helm chart linting
  deploy/kubernetes/console/templates/secrets.yaml
Labels: ready for review

#2138 Update uaa config
  deploy/uaa/uaa.yml
Labels: ready for review

#2059 Update App manifest interface used for Deploys
  src/backend/cfapppush/deploy.go
  src/backend/cfapppush/types.go
Labels: ready for review

#2140 Remove multi select in endpoints + Add restart app button
  src/frontend/app/features/applications/application/application-base.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.html
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
Labels: V2, ready for review

#2014 Improve handling of clientPagination
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-pagination-controller.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-clear-pagination-of-entity.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-create-pagination.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-set-client-filter.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-set-client-page-size.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-set-client-page.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-set-result-count.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-success.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/app/store/types/pagination.types.ts
Labels: ready for review

#2154 This week's status updates
  docs/status_updates.md
Labels: ready for review

#2152 Fix stepper issue with redirect not working
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
Labels: in review, ready for review

#2082 User profile edit
  src/frontend/app/app.routing.ts
  src/frontend/app/features/user-profile/edit-profile-info/edit-profile-info.component.html
  src/frontend/app/features/user-profile/edit-profile-info/edit-profile-info.component.scss
  src/frontend/app/features/user-profile/edit-profile-info/edit-profile-info.component.spec.ts
  src/frontend/app/features/user-profile/edit-profile-info/edit-profile-info.component.ts
  src/frontend/app/features/user-profile/profile-info/profile-info.component.html
  src/frontend/app/features/user-profile/profile-info/profile-info.component.spec.ts
  src/frontend/app/features/user-profile/profile-info/profile-info.component.ts
  src/frontend/app/features/user-profile/user-profile.module.ts
  src/frontend/app/features/user-profile/user-profile.routing.ts
  src/frontend/app/features/user-profile/user-profile.service.ts
  src/frontend/app/shared/components/page-header/page-header.component.html
  src/frontend/app/store/actions/user-profile.actions.ts
  src/frontend/app/store/effects/user-profile.effects.ts
  src/frontend/app/store/types/user-profile.types.ts
Labels: V2, comments-addressed, in review

#2115 Add snackbar for registration errors
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
  src/frontend/app/store/effects/endpoint.effects.ts
Labels: ready for review

#2089 Deploy from archive file or folder
  src/backend/cfapppush/deploy.go
  src/backend/cfapppush/types.go
  src/frontend/app/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-ignorefiles.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step-source-upload/deploy-application-step-source-upload.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step-source-upload/deploy-application-step-source-upload.component.scss
  src/frontend/app/features/applications/deploy-application/deploy-application-step-source-upload/deploy-application-step-source-upload.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step-source-upload/deploy-application-step-source-upload.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs-scanner.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs-utils.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs.component.scss
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs.component.theme.scss
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.scss
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.module.ts
  src/frontend/app/shared/components/stepper/step/step.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/app/shared/components/upload-progress-indicator/upload-progress-indicator.component.html
  src/frontend/app/shared/components/upload-progress-indicator/upload-progress-indicator.component.scss
  src/frontend/app/shared/components/upload-progress-indicator/upload-progress-indicator.component.spec.ts
  src/frontend/app/shared/components/upload-progress-indicator/upload-progress-indicator.component.theme.scss
  src/frontend/app/shared/components/upload-progress-indicator/upload-progress-indicator.component.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/types/deploy-application.types.ts
  src/frontend/sass/_all-theme.scss
Labels: comments-addressed, ready for review

#2113 E2e tests
  .gitignore
  .travis.yml
  build/legacy/protractor.conf.js
  deploy/ci/travis/docker-compose.yml
  deploy/ci/travis/run-e2e-tests.sh
  deploy/docker-compose/build.sh
  package-lock.json
  package.json
  protractor.conf.js
  src/frontend/app/app.component.ts
  src/frontend/app/logged-in.service.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.html
  src/frontend/app/shared/monitors/internal-event-monitor.factory.ts
  src/frontend/app/shared/monitors/internal-event.monitor.ts
  src/test-e2e/applications/applications.po.ts
  src/test-e2e/cloud-foundry/cloud-foundry.po.ts
  src/test-e2e/dashboard/dashboard.e2e-spec.ts
  src/test-e2e/e2e.secrets.ts.example
  src/test-e2e/e2e.types.ts
  src/test-e2e/endpoints/connect-dialog.po.ts
  src/test-e2e/endpoints/endpoints-connect.e2e-spec.ts
  src/test-e2e/endpoints/endpoints-register.e2e-spec.ts
  src/test-e2e/endpoints/endpoints-unregister.e2e-spec.ts
  src/test-e2e/endpoints/endpoints.e2e-spec.ts
  src/test-e2e/endpoints/endpoints.po.ts
  src/test-e2e/endpoints/register-dialog.po.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/helpers/reset-helpers.ts
  src/test-e2e/helpers/secrets-helpers.ts
  src/test-e2e/login/login.e2e-spec.ts
  src/test-e2e/login/login.po.ts
  src/test-e2e/po/cf-page.po.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/form.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/menu.po.ts
  src/test-e2e/po/no-content.po.ts
  src/test-e2e/po/page-header.po.ts
  src/test-e2e/po/page.po.ts
  src/test-e2e/po/side-nav.po.ts
  src/test-e2e/po/snackbar.po.ts
  src/test-e2e/po/stepper.po.ts
  src/test-e2e/secrets.yaml.example
  src/test-e2e/services/services.po.ts
Labels: comments-addressed, ready for review

#2050 Improvement for when app stats count and summary count don't match
  src/frontend/app/shared/components/application-state/application-state.service.spec.ts
  src/frontend/app/shared/components/application-state/application-state.service.ts
Labels: comments-addressed, ready for review

#2147 User permissions
  deploy/docker-compose.no-ui.development.yml
  package.json
  src/backend/app-core/auth.go
  src/backend/app-core/auth_test.go
  src/backend/app-core/datastore/20180413135700_MetricsSchema.go
  src/backend/app-core/info.go
  src/backend/app-core/repository/interfaces/structs.go
  src/frontend/app/core/core.module.ts
  src/frontend/app/core/current-user-permissions.checker.spec.ts
  src/frontend/app/core/current-user-permissions.checker.ts
  src/frontend/app/core/current-user-permissions.config.ts
  src/frontend/app/core/current-user-permissions.service.spec.ts
  src/frontend/app/core/current-user-permissions.service.ts
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/frontend/app/features/applications/application-wall/application-wall.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.html
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/app/features/endpoints/endpoints-page/endpoints-page.component.html
  src/frontend/app/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/app/shared/components/cf-auth/cf-auth.service.ts
  src/frontend/app/shared/components/cf-auth/cf-auth.types.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.html
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-data-source.helpers.ts
  src/frontend/app/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/shared/user-permission.directive.spec.ts
  src/frontend/app/shared/user-permission.directive.ts
  src/frontend/app/store/actions/auth.actions.ts
  src/frontend/app/store/actions/permissions.actions.ts
  src/frontend/app/store/actions/users.actions.ts
  src/frontend/app/store/app-state.ts
  src/frontend/app/store/effects/permissions.effect.ts
  src/frontend/app/store/reducers.module.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-base-cf-role.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-cf-roles.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-reducer.helpers.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-role-session.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-org.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-orgs.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-space.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-spaces.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.spec.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.ts
  src/frontend/app/store/selectors/current-user-roles-permissions-selectors/role.selectors.ts
  src/frontend/app/store/selectors/endpoint.selectors.ts
  src/frontend/app/store/store.module.ts
  src/frontend/app/store/types/auth.types.ts
  src/frontend/app/store/types/current-user-roles.types.ts
  src/frontend/app/store/types/request.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: in progress

#2133 Customizations
  .gitignore
  build/fe-build.js
  docs/customizing.md
  package-lock.json
  package.json
  src/frontend/app/app.module.ts
  src/frontend/app/app.routing.ts
  src/frontend/app/core/core.module.ts
  src/frontend/app/core/customizations.types.ts
  src/frontend/app/features/about/about.module.ts
  src/frontend/app/features/dashboard/side-nav/side-nav.component.html
  src/frontend/app/features/dashboard/side-nav/side-nav.component.scss
  src/frontend/app/features/dashboard/side-nav/side-nav.component.spec.ts
  src/frontend/app/features/dashboard/side-nav/side-nav.component.theme.scss
  src/frontend/app/features/dashboard/side-nav/side-nav.component.ts
  src/frontend/app/shared/components/stratos-title/stratos-title.component.html
  src/frontend/app/store/effects/permissions.effect.ts
  src/frontend/assets/suse-logo-white.png
  src/frontend/index.html
  src/frontend/misc/custom/custom.module.ts_
  src/frontend/misc/custom/custom.scss
  src/frontend/misc/custom/custom.yaml
  src/frontend/misc/custom/favicon.ico
  src/frontend/misc/custom/login-bg.jpg
  src/frontend/misc/custom/logo.png
  src/frontend/sass/oss-theme.scss
  src/frontend/sass/suse-theme.scss
  src/frontend/sass/theme.scss
  src/frontend/styles.scss
  src/frontend/tsconfig.app.json
  src/tsconfig.json
Labels: ready for review

#2196 Ensure that the customize task is run
  deploy/cloud-foundry/build.sh
  deploy/provision.sh
Labels: ready for review

#2174 Improve Backend start-up logging
  src/backend/app-core/datastore/datastore.go
  src/backend/app-core/load_plugins.go.tmpl
  src/backend/app-core/main.go
  src/backend/userinfo/main.go
Labels: ready for review

#2183 E2e tidy up
  package-lock.json
  package.json
  src/test-e2e/cloud-foundry/endpoints-list-cf.e2e-spec.ts
  src/test-e2e/e2e.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/endpoints/endpoints-connect.e2e-spec.ts
  src/test-e2e/endpoints/endpoints-register.e2e-spec.ts
  src/test-e2e/endpoints/endpoints-unregister.e2e-spec.ts
  src/test-e2e/endpoints/endpoints.e2e-spec.ts
  src/test-e2e/endpoints/endpoints.po.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/helpers/request-helpers.ts
  src/test-e2e/helpers/reset-helpers.ts
  src/test-e2e/helpers/secrets-helpers.ts
  src/test-e2e/login/login.e2e-spec.ts
  src/test-e2e/login/login.po.ts
Labels: in review, ready for review

#2193 Remove deprecated API & Add confirmation dialogs when detaching/removing service bindings
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/service-instances/service-instances-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instances-wall-list-config.service.ts
  src/frontend/app/shared/data-services/service-action-helper.service.spec.ts
  src/frontend/app/shared/data-services/service-action-helper.service.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/application-service-routes.actions.ts
Labels: in review, ready for review

#2148 Service Market place improvements
  src/frontend/app/app.routing.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/features/service-catalog/add-service-instance/bind-apps-step/bind-apps-step.component.ts
  src/frontend/app/features/service-catalog/service-base/service-base.component.html
  src/frontend/app/features/service-catalog/service-base/service-base.component.ts
  src/frontend/app/features/service-catalog/service-catalog.module.ts
  src/frontend/app/features/service-catalog/service-catalog.routing.ts
  src/frontend/app/features/service-catalog/service-plans/service-plans.component.html
  src/frontend/app/features/service-catalog/service-plans/service-plans.component.scss
  src/frontend/app/features/service-catalog/service-plans/service-plans.component.spec.ts
  src/frontend/app/features/service-catalog/service-plans/service-plans.component.ts
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.html
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.scss
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.spec.ts
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.ts
  src/frontend/app/features/service-catalog/services.service.mock.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: comments-addressed, ready for review

#2205 Remove fdescribe
  src/frontend/app/shared/data-services/service-action-helper.service.spec.ts
Labels: ready for review

#2207 Fix 2 unit test failures
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.spec.ts
Labels: ready for review

#2198 Apply user permissions to CF pages
  src/frontend/app/core/current-user-permissions.checker.ts
  src/frontend/app/core/current-user-permissions.config.ts
  src/frontend/app/core/current-user-permissions.service.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/app/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.html
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.spec.ts
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.ts
  src/frontend/app/shared/components/list/list-table/table.component.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-variables/cf-app-variables-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/base-cf/base-cf-list-config.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/github-commits/github-commits-list-config-app-tab.service.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/shared/user-permission.directive.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: in review, ready for review

#2203 Add an Optional EULA
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  src/frontend/app/features/about/about-page/about-page.component.html
  src/frontend/app/features/about/about-page/about-page.component.scss
  src/frontend/app/features/about/about-page/about-page.component.ts
  src/frontend/app/features/about/about.module.ts
  src/frontend/app/features/about/about.routing.ts
  src/frontend/app/features/about/eula-page/eula-page.component.html
  src/frontend/app/features/about/eula-page/eula-page.component.scss
  src/frontend/app/features/about/eula-page/eula-page.component.spec.ts
  src/frontend/app/features/about/eula-page/eula-page.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.spec.ts
  src/frontend/app/shared/components/ssh-viewer/ssh-viewer.component.spec.ts
  src/frontend/app/shared/data-services/service-action-helper.service.spec.ts
  src/frontend/app/test-framework/spec-helper.spec.ts
  src/frontend/misc/custom/custom.yaml
  src/frontend/misc/custom/eula.html
Labels: ready for review

#2213 Add user info to the response when connecting an endpoint
  src/backend/app-core/auth.go
  src/backend/app-core/repository/interfaces/structs.go
Labels: ready for review

#2218 Add code coverage config file
  .codecov.yaml
Labels: ready for review

#2204 Overflow table row select's selection animation
  src/frontend/app/shared/components/list/list-table/table.component.scss
Labels: in review, ready for review

#2212 Apply user permissions to CF pages - 2
  src/frontend/app/core/current-user-permissions.checker.ts
  src/frontend/app/core/current-user-permissions.config.ts
  src/frontend/app/features/cloud-foundry/cli-info-cloud-foundry/cli-info-cloud-foundry.component.html
  src/frontend/app/features/cloud-foundry/cli-info-cloud-foundry/cli-info-cloud-foundry.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/service-instances/service-instances-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/services-wall/service-instances-wall-list-config.service.ts
  src/frontend/app/shared/components/page-subheader/page-subheader.component.html
  src/frontend/app/shared/components/page-subheader/page-subheader.types.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-base-cf-role.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-cf-roles.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-reducer.helpers.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-org.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.spec.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles.reducer.ts
  src/frontend/app/store/selectors/current-user-roles-permissions-selectors/role.selectors.ts
  src/frontend/app/store/types/auth.types.ts
  src/frontend/app/store/types/current-user-roles.types.ts
Labels: ready for review

#2172 Fix map/unmap/delete route in app + space
  src/frontend/app/features/applications/application-delete/application-delete.component.ts
  src/frontend/app/features/applications/application-delete/delete-app-routes/delete-app-routes.component.ts
  src/frontend/app/features/applications/routes/add-route-stepper/add-route-stepper.component.ts
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/app/features/applications/routes/map-routes/map-routes.component.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-map-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-data-source.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-app-route/table-cell-app-route.component.ts
  src/frontend/app/shared/components/list/list-types/cf-buildpacks/cf-buildpacks-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-security-groups/cf-security-groups-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-space-apps/cf-space-apps-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/cf-space-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-data-source.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/store/actions/application-service-routes.actions.ts
  src/frontend/app/store/actions/route.actions.ts
  src/frontend/app/store/reducers/api-request-reducer/update-request.ts
  src/frontend/app/store/reducers/application-route.reducer.ts
  src/frontend/app/store/reducers/routes.reducer.ts
Labels: in review, ready for review

#2217 Add support for backend custom plugins
  build/bk-build.js
  build/customize-build.js
  build/fe-build.js
  build/proxy.conf.localdev.js
  package.json
Labels: needs attention, ready for review
