Repository cloudfoundry/stratos, pull requests merged in 2018-07, with the labels that each got.

#2561 Pagination obs performance
  src/frontend/app/shared/monitors/entity-monitor.ts
  src/frontend/app/shared/monitors/pagination-monitor.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
Labels: comments-addressed, ready for review

#2595 Ensure auth data is updated on sys info call
  src/frontend/app/store/reducers/auth.reducer.ts
Labels: in review, ready for review

#2611 Don't copy auth and refresh tokens unless using SSO
  src/backend/cloudfoundry/main.go
Labels: V2, ready for review

#2604 Fix timing issue resulting in an endpoint warning
  src/frontend/app/store/effects/api.effects.ts
Labels: ready for review

#2602 Ensure that the org spaceGuids list is updated when roles are changed
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-changed.reducers.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-org.reducer.ts
  src/frontend/app/store/reducers/current-user-roles-reducer/current-user-roles-space.reducer.ts
Labels: ready for review

#2593 Small layout changes
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.scss
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.scss
Labels: comments-addressed, ready for review

#2609 Fix missing space in script
  deploy/ci/travis/run-e2e-tests.sh
Labels: V2, ready for review

#2630 Fix update of User roles table after a role has been removed
  src/frontend/app/shared/monitors/pagination-monitor.ts
Labels: ready for review

#2621 Use a better test reporter for E2E tests
  package-lock.json
  package.json
  protractor.conf.js
Labels: V2, in review, ready for review

#2652 Select current service plan when editing a service instance
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/store/actions/create-service-instance.actions.ts
Labels: ready for review

#2631 Table unit tests
  src/frontend/app/shared/components/list/list-table/table.component.spec.ts
  src/frontend/app/shared/components/list/list-table/table.component.ts
Labels: ready for review

#2653 Fix unmap route action removing route from all lists
  src/frontend/app/store/effects/request.effects.ts
  src/frontend/app/store/effects/route.effects.ts
  src/frontend/app/store/store.module.ts
Labels: ready for review

#2613 Fix three issues around 100+ roles
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/store/reducers/api-request-data-reducer/request-data-reducer.factory.ts
  src/frontend/app/test-framework/cloud-foundry-organization.service.mock.ts
  src/frontend/app/test-framework/cloud-foundry-space.service.mock.ts
Labels: ready for review

#2658 Fixed exception that made it's way onto master
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
Labels: in review, ready for review

#2651 Don't validate individual org users requests
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/actions/organization.actions.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/actions/users.actions.ts
  src/frontend/app/store/effects/request.effects.ts
  src/frontend/app/store/effects/users.effects.ts
  src/frontend/app/store/types/pagination.types.ts
  src/frontend/app/store/types/request.types.ts
Labels: ready for review

#2627 Use correct log level when looking up Endpoints
  src/backend/app-core/repository/tokens/pgsql_tokens.go
Labels: V2, ready for review

#2660 Fix routing to appropriate CF view after connecting/disconnecting an endpoint
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.spec.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.ts
  src/frontend/app/features/metrics/services/metrics-service.ts
  src/frontend/app/shared/data-services/cloud-foundry.service.ts
  src/frontend/app/store/actions/endpoint.actions.ts
  src/frontend/app/store/effects/endpoint.effects.ts
Labels: comments-addressed

#2526 Add Dashboard URL to services view
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
Labels: comments-addressed, ready for review

#2668 Weekly status update
  docs/status_updates.md
Labels: ready for review

#2657 Fix create org and create space validation
  src/frontend/app/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/add-space/create-space-step/create-space-step.component.ts
Labels: V2, bug, ready for review

#2659 Update parent entities at validation time - the end of partial entities
  src/frontend/app/core/entity-service.ts
  src/frontend/app/store/effects/request.effects.ts
  src/frontend/app/store/helpers/entity-relations.ts
  src/frontend/app/store/helpers/entity-relations.types.ts
  src/frontend/app/store/reducers/api-request-data-reducer/request-data-reducer.factory.ts
Labels: ready for review

#2654 Restrict non-admin user functions at cf level
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.html
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-users/cloud-foundry-users.component.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/cf-roles.service.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-select/manage-users-select.component.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users.component.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-select-users/cf-select-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/effects/request.effects.ts
  src/frontend/app/store/effects/users.effects.ts
  src/frontend/app/store/helpers/entity-factory.ts
  src/frontend/app/test-framework/cloud-foundry-endpoint-service.helper.ts
Labels: blocked-pr, ready for review

#2669 Add support for new SCF Config LB property
  deploy/kubernetes/console/templates/service.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#2673 Fix App Chips not collapsing long lists
  src/frontend/app/shared/components/chips/chips.component.html
  src/frontend/app/shared/components/chips/chips.component.scss
Labels: ready for review

#2670 Use subtle mode by default for the boolean indicator
  src/frontend/app/shared/components/boolean-indicator/boolean-indicator.component.ts
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-confirm-roles/table-cell-confirm-role-add-rem/table-cell-confirm-role-add-rem.component.html
  src/frontend/app/shared/components/list/list-types/cf-endpoints/cf-endpoint-card/endpoint-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
Labels: ready for review

#2665 Use different env var for test checker. Remove fdescribe
  build/karma.test.reporter.js
  src/frontend/app/shared/components/list/list-table/table.component.spec.ts
Labels: V2, ready for review

#2667 Tweak presentation of dashboard url for consistency
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.scss
Labels: V2, ready for review

#2675 Fix unit tests
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.spec.ts
  src/frontend/app/features/applications/edit-application/edit-application.component.spec.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/cf-roles.service.spec.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-confirm/manage-users-confirm.component.spec.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-modify/manage-users-modify.component.spec.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-select/manage-users-select.component.spec.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users.component.spec.ts
  src/frontend/app/shared/components/cf-role-checkbox/cf-role-checkbox.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-users-org-space-roles/table-cell-org-space-role/table-cell-org-space-role.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-users-org-space-roles/table-cell-select-org/table-cell-select-org.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-org-permission-cell/cf-org-permission-cell.component.spec.ts
  src/frontend/app/shared/data-services/cf-org-space-service.service.spec.ts
  src/frontend/app/shared/data-services/cf-user.service.spec.ts
  src/frontend/app/test-framework/cloud-foundry-endpoint-service.helper.ts
  src/frontend/app/test-framework/user-service-helper.ts
Labels: ready for review

#2677 Fix for add org button vanishing
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
Labels: ready for review

#2685 Ensure lists with no entities populate pagination section correctly
  src/frontend/app/store/helpers/entity-relations.ts
Labels: ready for review

#2678 Fix incorrect empty page message on local tables
  src/frontend/app/shared/monitors/pagination-monitor.ts
Labels: ready for review

#2686 Permission fetch fix
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/effects/permissions.effect.ts
  src/frontend/app/store/helpers/paginated-request-helpers.ts
Labels: ready for review

#2691 Update build badge to use v2-master
  README.md
Labels: ready for review

#2687 Services Marketplace E2E (Part 1)
  src/test-e2e/marketplace/marketplace-e2e.spec.ts
  src/test-e2e/marketplace/marketplace.po.ts
  src/test-e2e/po/list.po.ts
Labels: ready for review

#2699 Fix app instance sorting
  src/frontend/app/shared/components/list/data-sources-controllers/local-filtering-sorting.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
Labels: P1, V2, in review

#2681 Add e2e tests for create/delete org and space
  src/frontend/app/shared/components/list/list.component.html
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/cloud-foundry/cloud-foundry.po.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/e2e.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/helpers/cf-request-helpers.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/helpers/reset-helpers.ts
  src/test-e2e/po/breadcrumbs.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/meta-card.po.ts
  src/test-e2e/po/page-subheader.po.ts
  src/test-e2e/po/page.po.ts
Labels: V2, comments-addressed, in review

#2694 Add E2E tests for delete app
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/application/application-summary.po.ts
  src/test-e2e/application/delete-app.po.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/paginator.po.ts
  src/test-e2e/po/stepper.po.ts
  src/test-e2e/po/table.po.ts
Labels: V2, ready for review

#2697 Fix handling of exception when editing a service instance
  src/frontend/app/features/services/services-wall/services-wall.component.html
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
Labels: P1, ready for review

#2701 Fixed bad imports
  src/frontend/app/features/applications/application/application-tabs-base/tabs/github-tab/github-tab.component.ts
  src/frontend/app/features/applications/create-application/create-application.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.ts
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/app/features/applications/routes/map-routes/map-routes.component.ts
  src/frontend/app/features/login/login-page/login-page.component.ts
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.ts
  src/frontend/app/store/reducers.module.ts
Labels: ready for review

#2702 Build doc fix
  docs/developers-guide.md
Labels: ready for review

#2700 Fix nightly release pipeline
  deploy/ci/console-nightly-releases.yml
Labels: P1, ready for review

#2703 Fix broken aot with build optimizer
  package-lock.json
  package.json
  src/frontend/app/shared/components/ssh-viewer/ssh-viewer.component.ts
Labels: V2, bug, ready for review

#2706 Weekly status update for Week ending 20 July
  docs/status_updates.md
Labels: ready for review

#2707 Updated homepage screenshot
  docs/images/screenshots/app-summary.png
Labels: ready for review

#2711 Fix marketplace e2e test
  src/test-e2e/po/list.po.ts
Labels: ready for review

#2713 Changelog for RC3
  CHANGELOG.md
Labels: ready for review

#2732 Fix issue where cookie domain name change can mean you can't log out
  src/backend/app-core/auth.go
  src/backend/app-core/main.go
  src/backend/app-core/portal_proxy.go
  src/backend/app-core/session.go
Labels: V2, ready for review

#2734 Changelog for 2.0.0
  CHANGELOG.md
Labels: ready for review

#2738 Re-jig readme and scale back v1 notice following 2.0 release
  README.md
Labels: ready for review

#2724 Remove Application `Production` from app summary and edit
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/app/features/applications/edit-application/edit-application.component.html
  src/frontend/app/features/applications/edit-application/edit-application.component.ts
Labels: V2-next, ready for review

#2601 Fix migrate script to work in Postgresql
  src/backend/app-core/datastore/20170818120003_InitialSchema.go
  src/backend/app-core/datastore/20170818162837_SetupSchema.go
  src/backend/app-core/datastore/20170829154900_TokenDisconnected.go
  src/backend/app-core/datastore/20171108102900_AuthType.go
  src/backend/app-core/datastore/20180413135700_MetricsSchema.go
  src/backend/app-core/datastore/20180627111300_UpdateMetadata.go
  src/backend/app-core/datastore/datastore.go
  src/backend/app-core/datastore/datastore_migrator.go
  src/backend/app-core/migrator.go
Labels: V2-next, comments-addressed

#2504 Ux improvements
  src/frontend/app/features/service-catalog/services.service.mock.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/shared/components/cards/service-summary-card/service-summary-card.component.html
Labels: V2, discussion, in review, ready for review

#2672 Display Service information when creating service instance and sort list
  src/frontend/app/features/services/services/services-wall.service.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.html
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.scss
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/select-service/select-service.component.ts
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/app/store/reducers/api-request-reducer/request-reducer.factory.ts
Labels: in review, ready for review

#2704 Remove unused deps from package.json
  package-lock.json
  package.json
Labels: in review, ready for review

#2721 Entity service tests
  src/frontend/app/core/entity-service.spec.ts
  src/frontend/app/core/entity-service.ts
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/instances-tab/instances-tab.component.spec.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.ts
  src/frontend/app/shared/components/list/list-types/github-commits/github-commits-list-config-app-tab.service.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/effects/cloud-foundry.effects.ts
  src/frontend/app/store/effects/deploy-app.effects.ts
  src/frontend/app/store/effects/endpoint.effects.ts
  src/frontend/app/store/effects/request.effects.ts
  src/frontend/app/store/reducers/api-request-reducer/request-helpers.ts
  src/frontend/app/store/reducers/api-request-reducer/succeed-request.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: in review, ready for review

#2757 Fix page loading indicator
  src/frontend/app/shared/components/routing-indicator/routing-indicator.component.ts
Labels: V2-next, bug, ready for review

#2739 Diagnostics: Add git and build date metadata
  .gitignore
  build/customize-build.js
  build/store-git-metadata.sh
  package.json
  src/frontend/misc/custom/index.html
Labels: V2-next, ready for review

#2740 Diagnostics: Add backend support
  src/backend/app-core/diagnostics.go
  src/backend/app-core/info.go
  src/backend/app-core/main.go
  src/backend/app-core/portal_proxy.go
  src/backend/app-core/repository/goose-db-version/goose-db-version.go
  src/backend/app-core/repository/goose-db-version/pgsql_goose_db_version.go
  src/backend/app-core/repository/goose-db-version/pgsql_goose_db_version_test.go
  src/backend/app-core/repository/interfaces/structs.go
Labels: V2-next, blocked-pr

#2762 Basic doc on E2E prequisites
  docs/developers-guide-e2e-tests.md
  docs/developers-guide.md
Labels: ready for review

#2761 Fixed store devtools when running aot
  src/frontend/app/store/reducers.module.ts
Labels: ready for review

#2764 Backend: Deal with NULL values when reading from the database
  src/backend/app-core/datastore/20180627111300_UpdateMetadata.go
  src/backend/app-core/repository/tokens/pgsql_tokens.go
Labels: V2, bug, ready for review

#2769 Fix timestamp in migration script
  src/backend/app-core/datastore/20180703142800_CFClient.go
Labels: ready for review

#2743 Diagnostics: Generate deployment info
  deploy/Dockerfile.all-in-one
  deploy/all-in-one/README.md
  deploy/all-in-one/config.all-in-one.properties
  deploy/common-build.sh
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/proxy.env
Labels: V2-next, ready for review

#2770 Weekly update
  docs/status_updates.md
Labels: ready for review

#2733 Fix validation of edit service instance
  src/frontend/app/shared/components/add-service-instance/create-service-instance-helper.service.ts
Labels: P3, V2-next, ready for review

#2771 Quote new properties & Update nightly chart
  deploy/ci/console-nightly-releases.yml
  deploy/ci/tasks/dev-releases/create-nightly-chart.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
  deploy/kubernetes/console/templates/deployment.yaml
Labels: ready for review

#2768 Allow e2e tests to be skipped based on secrets configuration
  .gitignore
  protractor.conf.js
  src/test-e2e/cloud-foundry/endpoints-list-cf-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-unregister-e2e.spec.ts
  src/test-e2e/helpers/secrets-helpers.ts
  src/test-e2e/skip-plugin.js
  src/test-e2e/types.d.ts
Labels: ready for review

#2728 Deploy App: Remove need to poll for application GUID
  src/backend/cfapppush/app-repository.go
  src/backend/cfapppush/deploy.go
  src/frontend/app/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/store/types/deploy-application.types.ts
Labels: V2-next, ready for review

#2775 Change shell in git-metadata
  build/store-git-metadata.sh
Labels: ready for review
