Repository cloudfoundry/stratos, pull requests merged in 2018-09, with the labels that each got.

#2943 Fix login e2e test
  src/test-e2e/login/login-e2e.spec.ts
Labels: ready for review

#2934 SSO: Add SSO Config options to Helm chart
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#2933 Add websocket support for app stream
  src/jetstream/plugins/cloudfoundry/cf_websocket_streams.go
  src/jetstream/plugins/cloudfoundry/main.go
Labels: ready for review

#2926 Fix gzip problem for non-static resources
  src/jetstream/main.go
Labels: bug

#2855 Services E2E: Service Instance creation with App Binding
  src/test-e2e/e2e.types.ts
  src/test-e2e/marketplace/create-service-instance-stepper.po.ts
  src/test-e2e/marketplace/create-service-instances-bind-app-e2e.spec.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/marketplace/services-wall.po.ts
  src/test-e2e/po/meta-card.po.ts
Labels: ready for review

#2522 SSO: Improvements/refinements
  src/frontend/app/core/auth-guard.service.ts
  src/frontend/app/features/login/login-page/login-page.component.ts
  src/frontend/app/store/actions/auth.actions.ts
  src/frontend/app/store/effects/auth.effects.ts
  src/frontend/app/store/reducers/auth.reducer.ts
  src/frontend/app/store/types/auth.types.ts
  src/jetstream/auth.go
  src/jetstream/main.go
  src/jetstream/middleware.go
  src/jetstream/repository/interfaces/errors.go
  src/jetstream/repository/interfaces/structs.go
  src/jetstream/setup_console.go
  src/jetstream/utils.go
Labels: in review, ready for review

#2949 E2E: Allow GitHub API URL to be configured in tests
  src/frontend/app/app.module.ts
  src/frontend/app/core/github.helpers.ts
  src/frontend/app/features/applications/app-name-unique.directive/app-name-unique.directive.spec.ts
  src/frontend/app/features/applications/application.service.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/github-tab/github-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/github-tab/github-tab.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.spec.ts
  src/frontend/app/store/actions/deploy-applications.actions.ts
  src/frontend/app/store/effects/deploy-app.effects.ts
  src/frontend/app/store/effects/github.effects.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/helpers/secrets-helpers.ts
Labels: ready for review

#2946 Improve GitHub error handling
  src/frontend/app/core/utils.service.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/github-tab/github-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/github-tab/github-tab.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.ts
  src/frontend/app/features/applications/deploy-application/github-project-exists.directive.ts
  src/frontend/app/store/actions/deploy-applications.actions.ts
  src/frontend/app/store/effects/deploy-app.effects.ts
  src/frontend/app/store/effects/github.effects.ts
  src/frontend/app/store/reducers/deploy-app.reducer.ts
  src/frontend/app/store/types/deploy-application.types.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: ready for review

#2856 E2E: Basic Application View tests
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-title/meta-card-title.component.ts
  src/test-e2e/application/application-create-e2e.spec.ts
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/application/application-page-events.po.ts
  src/test-e2e/application/application-page-github.po.ts
  src/test-e2e/application/application-page-instances.po.ts
  src/test-e2e/application/application-page-routes.po.ts
  src/test-e2e/application/application-page-summary.po.ts
  src/test-e2e/application/application-page-variables.po.ts
  src/test-e2e/application/application-page.po.ts
  src/test-e2e/application/application-summary.po.ts
  src/test-e2e/application/application-view-e2e.spec.ts
  src/test-e2e/application/po/card-app-build-info.po.ts
  src/test-e2e/application/po/card-app-cf-info.po.ts
  src/test-e2e/application/po/card-app-deploy-info.po.ts
  src/test-e2e/application/po/card-app-info.po.ts
  src/test-e2e/application/po/card-app-instances.po.ts
  src/test-e2e/application/po/card-app-status.po.ts
  src/test-e2e/application/po/card-app-uptime.po.ts
  src/test-e2e/application/po/card-app-usage.po.ts
  src/test-e2e/application/po/card-github-commit-info.po.ts
  src/test-e2e/application/po/card-github-deploy-info.po.ts
  src/test-e2e/application/po/card-github-repo-info.po.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-page.po.ts
  src/test-e2e/cloud-foundry/org-level/cf-org-level-page.po.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-page.po.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/marketplace/create-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance-private-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance-space-scoped-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instances-bind-app-e2e.spec.ts
  src/test-e2e/marketplace/edit-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/marketplace-create-service-instances-e2e.spec.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
  src/test-e2e/marketplace/services-wall.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/meta-card.po.ts
  src/test-e2e/po/meta-data-item.po.ts
  src/test-e2e/po/page-subheader.po.ts
  src/test-e2e/po/page.po.ts
Labels: ready for review

#2924 Deploy App Manifest overrides
  package-lock.json
  src/frontend/app/features/applications/application-delete/delete-app-instances/delete-app-instances.component.spec.ts
  src/frontend/app/features/applications/application-delete/delete-app-routes/delete-app-routes.component.spec.ts
  src/frontend/app/features/applications/application.service.spec.ts
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/applications/application/application-base.component.spec.ts
  src/frontend/app/features/applications/application/application-base.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/application-env-vars.service.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/application-env-vars.service.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/events-tab/events-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/instances-tab/instances-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/log-stream-tab/log-stream-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/metrics-tab/metrics-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/routes-tab/routes-tab/routes-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/services-tab/services-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.spec.ts
  src/frontend/app/features/applications/applications.module.ts
  src/frontend/app/features/applications/cli-info-application/cli-info-application.component.spec.ts
  src/frontend/app/features/applications/create-application/create-application-step3/create-application-step3.component.scss
  src/frontend/app/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.scss
  src/frontend/app/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application.module.ts
  src/frontend/app/features/applications/edit-application/edit-application.component.spec.ts
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.scss
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.spec.ts
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.spec.ts
  src/frontend/app/store/actions/deploy-applications.actions.ts
  src/frontend/app/store/reducers/deploy-app.reducer.ts
  src/frontend/app/store/types/deploy-application.types.ts
  src/frontend/app/test-framework/application-service-helper.ts
  src/jetstream/plugins/cfapppush/deploy.go
  src/jetstream/plugins/cfapppush/pushapp/pushapp.go
  src/jetstream/plugins/cfapppush/types.go
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/deploy-app.po.ts
Labels: ready for review

#2957 Fix CF troubleshooting link
  docs/troubleshooting.md
Labels: ready for review

#2862 E2E: Basic Application Routes tests
  src/frontend/app/features/applications/routes/add-route-stepper/add-route-stepper.component.html
  src/test-e2e/application/application-create-e2e.spec.ts
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/application/application-routes-e2e.spec.ts
  src/test-e2e/application/application-view-e2e.spec.ts
  src/test-e2e/application/po/application-page-events.po.ts
  src/test-e2e/application/po/application-page-github.po.ts
  src/test-e2e/application/po/application-page-instances.po.ts
  src/test-e2e/application/po/application-page-routes.po.ts
  src/test-e2e/application/po/application-page-summary.po.ts
  src/test-e2e/application/po/application-page-variables.po.ts
  src/test-e2e/application/po/application-page.po.ts
  src/test-e2e/application/po/create-application-stepper.po.ts
  src/test-e2e/application/po/delete-app.po.ts
  src/test-e2e/application/po/deploy-app.po.ts
  src/test-e2e/application/po/routes-create-page.po.ts
  src/test-e2e/applications/applications.po.ts
  src/test-e2e/e2e.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-unregister-e2e.spec.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/helpers/cf-request-helpers.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/po/form.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/page.po.ts
  src/test-e2e/po/radio-group.po.ts
Labels: ready for review

#2916 SSO: Link tokens rather than copying them
  src/jetstream/auth.go
  src/jetstream/auth_test.go
  src/jetstream/cnsi.go
  src/jetstream/datastore/20180824092600_LinkedTokens.go
  src/jetstream/mock_server_test.go
  src/jetstream/oauth_requests.go
  src/jetstream/oauth_requests_test.go
  src/jetstream/passthrough.go
  src/jetstream/repository/interfaces/structs.go
  src/jetstream/repository/tokens/pgsql_tokens.go
  src/jetstream/repository/tokens/pgsql_tokens_test.go
  src/jetstream/repository/tokens/tokens.go
  src/jetstream/setup_console.go
Labels: in review, ready for review

#2928 SSO: Allow a Cloud Foundry endpoint to be connected with SSO login
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.html
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.scss
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/app/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/app/store/effects/endpoint.effects.ts
  src/jetstream/auth.go
  src/jetstream/main.go
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
Labels: in review, ready for review

#2969 Add `acceptance` back to e2e entity prefix
  src/test-e2e/helpers/e2e-helpers.ts
Labels: ready for review

#2945 SSO: Add initial SSO doc
  deploy/cloud-foundry/README.md
  docs/sso.md
Labels: in review

#2864 Automated testing scripts and test improvements
  build/bk-fetch-deps.sh
  build/store-git-metadata.sh
  deploy/ci/automation/Dockerfile.cfcli
  deploy/ci/automation/README.md
  deploy/ci/automation/cfallinonetest.sh
  deploy/ci/automation/cfdockercomposetest.sh
  deploy/ci/automation/cfpushtest.sh
  deploy/ci/automation/cfutils.sh
  deploy/ci/automation/check-cf.sh
  deploy/ci/automation/check-docker-images.sh
  deploy/ci/automation/check-stratos.sh
  package.json
  protractor.conf.js
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/test-e2e/check/check-login-e2e.spec.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-register-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-unregister-e2e.spec.ts
  src/test-e2e/helpers/reset-helpers.ts
  src/test-e2e/login/login.po.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/snackbar.po.ts
Labels: in review, ready for review

#2942 Harden app delete e2e test to reduce chance of concurrency failures
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/login/login-e2e.spec.ts
Labels: ready for review

#2948 Extensions: Tidy up customisations and fix logo customisation
  .gitignore
  build/customize-build.js
  src/frontend/app/app.module.ts
  src/frontend/app/features/about/about.module.ts
  src/frontend/app/shared/components/stratos-title/stratos-title.component.html
  src/frontend/assets/stratos-logo.png
  src/frontend/misc/custom/custom-src.module.ts_
  src/frontend/misc/custom/custom.module.ts_
  src/frontend/misc/custom/custom.yaml
  src/frontend/misc/custom/logo.png
Labels: ready for review

#2950 Extensions: Allow new side nav items to be added
  src/frontend/app/app.routing.ts
  src/frontend/app/features/dashboard/dashboard-base/dashboard-base.component.ts
Labels: in review

#2963 SSO: Add an option to the setup screen to enable SSO
  .gitignore
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.scss
  src/frontend/app/features/setup/uaa-wizard/console-uaa-wizard.component.ts
  src/frontend/app/store/effects/uaa-setup.effects.ts
  src/frontend/app/store/types/uaa-setup.types.ts
  src/jetstream/auth.go
  src/jetstream/config/config.go
  src/jetstream/datastore/20180907123000_SSOSetupFlag.go
  src/jetstream/main.go
  src/jetstream/repository/console_config/psql_console_config.go
  src/jetstream/repository/interfaces/structs.go
  src/jetstream/setup_console.go
Labels: in review

#2973 Bug fix (service instance wall) + e2e hardening (edit service instance)
  src/frontend/app/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/marketplace/edit-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/marketplace-create-service-instances-e2e.spec.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
Labels: ready for review

#2970 E2E: Get default stack from CF. Set memory and disk on app.
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-view-e2e.spec.ts
  src/test-e2e/helpers/cf-helpers.ts
Labels: ready for review

#2920 Extend endpoint registration UI to support Client ID and Client Secret
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.html
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.scss
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
  src/frontend/app/store/actions/endpoint.actions.ts
  src/frontend/app/store/effects/endpoint.effects.ts
Labels: in review, ready for review

#2915 Scalability: Change application list in service instance table row from vertical to chip list
  src/frontend/app/shared/components/chips/chips.component.html
  src/frontend/app/shared/components/chips/chips.component.ts
  src/frontend/app/shared/components/list/list-types/cf-space-routes/table-cell-route-apps-attached/table-cell-route-apps-attached.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.spec.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.spec.ts
  src/frontend/app/shared/components/list/list-types/service-instances/service-instances-list-config.service.spec.ts
Labels: in review, ready for review

#2976 Fix migration script date
  src/jetstream/datastore/20180907123000_SSOSetupFlag.go
Labels: ready for review

#2918 Show 'other apps bound to service instance' warning on delete app service instance step
  src/frontend/app/features/applications/application-delete/delete-app-instances/app-delete-instances-routes-list-config.service.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/app/shared/components/list/list-table/table-cell-radio/table-cell-radio.component.ts
  src/frontend/app/shared/components/list/list-table/table-cell-select/table-cell-select.component.scss
  src/frontend/app/shared/components/list/list-table/table-header-select/table-header-select.component.scss
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.scss
  src/frontend/app/shared/components/list/list-table/table-row/table-row.component.theme.scss
  src/frontend/app/shared/components/list/list-table/table.component.ts
  src/frontend/app/store/actions/service-bindings.actions.ts
Labels: in review, ready for review

#2913 Scalability: Convert space apps list from local to remote
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-apps/cloud-foundry-space-apps.component.ts
  src/frontend/app/shared/components/list/list-types/cf-space-apps/cf-space-apps-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-apps/cf-space-apps-list-config.service.ts
  src/frontend/app/store/actions/space.actions.ts
Labels: in review, ready for review

#2977 Add check to make sure DB Schema migrations have completed
  src/jetstream/datastore/datastore.go
  src/jetstream/datastore/datastore_migrator.go
  src/jetstream/main.go
Labels: ready for review

#2907 E2E: Basic tests for manage users stepper
  src/frontend/app/shared/components/list/list-types/cf-users-org-space-roles/table-cell-select-org/table-cell-select-org.component.html
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-page.po.ts
  src/test-e2e/cloud-foundry/manage-users-page.po.ts
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
  src/test-e2e/cloud-foundry/users-list-e2e.helper.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/po/action-monitor.po.ts
  src/test-e2e/po/checkbox.po.ts
  src/test-e2e/po/form.po.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/po/page.po.ts
Labels: ready for review

#2981 E2E: Test Fix: Don't hardcode non-admin username
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
Labels: ready for review

#2982 SSO: Refinements
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.html
Labels: ready for review

#2986 Allow auto-registration name to be configured
  src/jetstream/plugins/cloudfoundry/main.go
  src/jetstream/repository/interfaces/structs.go
Labels: ready for review

#2990 Add Browerstack promo
  README.md
  docs/images/Browserstack-logo.svg
Labels: ready for review

#2984 SSO: E2E Tests: Make sure the right user is logged in.
  src/test-e2e/login/login-sso-e2e.spec.ts
  src/test-e2e/login/sso-login.po.ts
Labels: ready for review

#2991 E2E Test: Manage Users: Wait for Users tab to appear
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-page.po.ts
Labels: ready for review

#2996 Update for September 14th
  docs/status_updates.md
Labels: ready for review

#3001 Version number always reports 'dev'
  build/bk-build.sh
Labels: ready for review

#3005 Release pipeline fix
  deploy/ci/tasks/dev-releases/update-gh-release.yml
Labels: ready for review

#3004 Fix for Connect button not being enabled when SSO is the default
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
Labels: ready for review

#3008 Restore lost fix
  build/bk-build.sh
Labels: ready for review

#3007 Diagnostics does not show GitHub details when cloned via HTTPS
  src/frontend/app/features/about/diagnostics-page/diagnostics-page.component.ts
Labels: ready for review

#3012 Release Pipeline: Check that the release exists before creating
  deploy/ci/tasks/dev-releases/update-gh-release.yml
Labels: ready for review

#3009 Fix deploy application override section width
  src/frontend/app/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.scss
Labels: in progress

#3015 Fix for NULL Client Secret bug
  src/jetstream/repository/cnsis/pgsql_cnsis.go
Labels: ready for review

#3017 Fix bug where token IDs are not set properly when upgrading from a previous version
  src/jetstream/datastore/20180824092600_LinkedTokens.go
Labels: ready for review

#2978 Automated Test Script Improvements
  deploy/ci/automation/cfallinonetest.sh
  deploy/ci/automation/cfdockercomposetest.sh
  deploy/ci/automation/cfpushtest.sh
  deploy/ci/automation/cfutils.sh
  deploy/ci/automation/init-pcfdev-uaa.sh
  deploy/common-build.sh
  deploy/docker-compose/build.sh
Labels: ready for review

#3030 Docs: Add stable tag checkout and git metadata script run
  deploy/cloud-foundry/README.md
Labels: ready for review

#3036 Fix for metrics connection bug
  src/frontend/app/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.html
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
Labels: ready for review

#3038 Simple metrics registration e2e test
  src/test-e2e/metrics/metrics-registration-e2e.spec.ts
Labels: ready for review

#3040 Helm: Remove metrics sub-chart
  deploy/kubernetes/console/requirements.lock
  deploy/kubernetes/console/requirements.yaml
Labels: ready for review

#3037 E2E Test resilience
  src/test-e2e/marketplace/edit-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/services-wall.po.ts
  src/test-e2e/po/side-nav.po.ts
Labels: ready for review

#3043 Fix app wall filtering
  src/frontend/app/shared/components/list/data-sources-controllers/list-pagination-controller.ts
Labels: ready for review

#2997 Feature json schema
  package-lock.json
  package.json
  src/frontend/app/core/cf-api-svc.types.ts
  src/frontend/app/core/utils.service.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.html
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.scss
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.html
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.scss
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/shared/components/application-state/application-state-icon/application-state-icon.component.ts
  src/frontend/app/shared/components/schema-form/schema-form.component.html
  src/frontend/app/shared/components/schema-form/schema-form.component.scss
  src/frontend/app/shared/components/schema-form/schema-form.component.spec.ts
  src/frontend/app/shared/components/schema-form/schema-form.component.theme.scss
  src/frontend/app/shared/components/schema-form/schema-form.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#3051 E2E Tests: Improve resilience
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/e2e.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
Labels: ready for review

#3059 Ensure we don't fail e2e tests if S3 url is missing
  deploy/ci/travis/upload-e2e-test-report.sh
Labels: ready for review

#3013 Add stack, start command, health check and time to deploy overrides
  src/frontend/app/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.ts
  src/frontend/app/shared/components/list/list-types/cf-stacks/cf-stacks-data-source.ts
  src/frontend/app/store/actions/stack.action.ts
  src/frontend/app/store/types/deploy-application.types.ts
  src/jetstream/plugins/cfapppush/pushapp/pushapp.go
Labels: ready for review

#3057 Metrics: Fix issue where wrong job can be matched up when there are multiple jobs
  src/jetstream/plugins/metrics/main.go
Labels: ready for review

#3060 Update backend dependencies
  Gopkg.lock
Labels: ready for review

#3058 E2E Tests: More resilient snackbar check for endpoint connect
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/po/snackbar.po.ts
Labels: ready for review

#3061 E2E Tests: Capture video of E2E tests running in the browser
  .travis.yml
  deploy/ci/travis/run-e2e-tests.sh
  protractor.conf.js
Labels: ready for review

#3062 211 Release - Update changelog and github release task
  CHANGELOG.md
  deploy/ci/tasks/dev-releases/update-gh-release.yml
Labels: ready for review

#3064 Make release pipeline aware of requirements.yaml
  deploy/ci/tasks/dev-releases/create-chart-helper.sh
Labels: ready for review

#3071 Fix go-flags dependency pinned version broken
  CHANGELOG.md
  Gopkg.lock
  package-lock.json
  package.json
Labels: ready for review

#3072 E2E Tests: Make App Wall tests more resilient. Split out App Routes test.
  src/test-e2e/application/application-routes-e2e.spec.ts
  src/test-e2e/applications/application-wall-e2e.spec.ts
Labels: in review

#3073 Test automation fixes
  build/bk-build.sh
  build/bk-fetch-deps.sh
  deploy/ci/automation/cfutils.sh
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-routes-e2e.spec.ts
  src/test-e2e/applications/application-wall-e2e.spec.ts
Labels: ready for review

#3081 Metrics: Add support for query_range
  src/jetstream/plugins/metrics/cloud_foundry.go
Labels: ready for review

#3053 CF API v2 Usage
  docs/cf-api-v2-usage.md
Labels: ready for review

#3084 Weekly update
  docs/status_updates.md
Labels: ready for review
