Repository cloudfoundry/stratos, pull requests merged in 2018-02, with the labels that each got.

#1602 Firehose Tab
  src/frontend/app/features/applications/application/application-tabs-base/tabs/log-stream-tab/log-stream-tab.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-firehose/cloud-foundry-firehose.types.ts
  src/frontend/app/shared/components/log-viewer/log-viewer.component.ts
Labels: ready for review

#1603 Take user to CF summary if there is only one endpoint connected
  src/frontend/app/features/cloud-foundry/cloud-foundry-base/cloud-foundry-base.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.ts
Labels: bug, ready for review

#1610 Fix Cloud foundry Component unit tests
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.spec.ts
Labels: ready for review

#1608 Remove incorrect/missleading documentation left over from v1
  README.md
  deploy/cloud-foundry/README.md
  docs/developers-guide.md
  docs/development.md
  docs/features.md
  docs/i18n.md
Labels: ready for review

#1601 Fix org/space shemas
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/applications/create-application/create-application-step3/create-application-step3.component.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
  src/frontend/app/store/actions/action-types.ts
  src/frontend/app/store/actions/application.actions.ts
  src/frontend/app/store/actions/organisation.action.ts
  src/frontend/app/store/actions/organisation.actions.ts
  src/frontend/app/store/actions/organization.actions.ts
  src/frontend/app/store/actions/space.action.ts
  src/frontend/app/store/actions/space.actions.ts
Labels: ready for review

#1600 Fix unregister endpoint
  src/frontend/app/core/entity-service.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/monitors/pagination-monitor.ts
  src/frontend/app/store/effects/endpoint.effects.ts
Labels: ready for review

#1604 Stepper form visual fixes
  src/frontend/app/features/applications/create-application/create-application-step1/create-application-step1.component.html
  src/frontend/app/features/applications/create-application/create-application-step2/create-application-step2.component.html
  src/frontend/app/features/applications/create-application/create-application-step3/create-application-step3.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.html
  src/frontend/app/features/applications/edit-application/edit-application.component.html
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.html
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.scss
  src/frontend/app/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.html
  src/frontend/app/features/uaa-setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/app/shared/components/stepper/steppers/steppers.component.scss
Labels: ready for review

#1607 Convert routes lists (app summary + map) to use local pagination
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list-table/table.types.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-map-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-data-source.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-app-route/table-cell-app-route.component.ts
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-tcproute/table-cell-tcproute.component.html
  src/frontend/app/shared/components/list/list-types/app-route/table-cell-tcproute/table-cell-tcproute.component.ts
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/store/actions/route.actions.ts
Labels: in progress, ready for review

#1616 List header changes
  .gitignore
  src/frontend/app/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.html
  src/frontend/app/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.scss
  src/frontend/app/shared/components/list/list-table/table.component.html
  src/frontend/app/shared/components/list/list-table/table.component.scss
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/components/list/list.component.theme.scss
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#1585 Change name of backend builder image for v2
  .gitignore
  deploy/build_portal_proxy.sh
  deploy/ci/tasks/stratos-ui/prep-proxy-image.yml
  deploy/docker-compose/build.sh
  deploy/kubernetes/build.sh
  deploy/stratos-base-images/build-base-images.sh
  deploy/tools/build-push-proxy-builder-image.sh
Labels: V2, ready for review

#1620 Rough doc for cf user management
  docs/planning/cf-user-management.md
Labels: ready for review

#1622 Backend extensions
  build/bk-build.js
  build/bk-conf.js
  build/bk-prepare-build.js
Labels: ready for review

#1605 Better UX on the endpoint list
  src/frontend/app/core/endpoints.service.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-config.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.html
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.spec.ts
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.ts
  src/frontend/app/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoint-data-source.helpers.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-data-source.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-status/table-cell-endpoint-status.component.html
  src/frontend/app/shared/components/list/list-types/endpoint/table-cell-endpoint-status/table-cell-endpoint-status.component.ts
  src/frontend/app/shared/components/list/list.component.spec.ts
  src/frontend/app/store/effects/endpoint.effects.ts
  src/frontend/app/store/reducers/system-endpoints.reducer.ts
Labels: in review, ready for review

#1634 Fix add new route with path
  src/frontend/app/features/applications/routes/routes.helper.ts
  src/frontend/app/store/types/route.types.ts
Labels: ready for review

#1661 Fix bug that forwarded user to the first registered endpoint rather than first connected one
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.ts
Labels: ready for review

#1656 CF Space Applications list
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-apps/cloud-foundry-space-apps.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-apps/cloud-foundry-space-apps.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-apps/cloud-foundry-space-apps.component.ts
  src/frontend/app/shared/components/application-state/application-state.component.html
  src/frontend/app/shared/components/application-state/application-state.component.ts
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-status/table-cell-app-status.component.html
  src/frontend/app/shared/components/list/list-types/app/table-cell-app-status/table-cell-app-status.component.ts
  src/frontend/app/shared/components/list/list-types/cf-space-apps/cf-space-apps-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-space-apps/cf-space-apps-list-config.service.ts
  src/frontend/app/store/actions/space.actions.ts
Labels: ready for review

#1631 Fix issue where missing pageSizeOptions led to empty list
  src/frontend/app/shared/components/list/list-types/app-event/cf-app-events-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-map-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app-variables/cf-app-variables-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-endpoints/cf-endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/list/list.component.types.ts
Labels: ready for review

#1672 CF Organisations: `Create Org` action
  src/frontend/app/features/cloud-foundry/add-organisation/add-organisation.component.html
  src/frontend/app/features/cloud-foundry/add-organisation/add-organisation.component.scss
  src/frontend/app/features/cloud-foundry/add-organisation/add-organisation.component.spec.ts
  src/frontend/app/features/cloud-foundry/add-organisation/add-organisation.component.ts
  src/frontend/app/features/cloud-foundry/add-organisation/create-organization-step/create-organization-step.component.html
  src/frontend/app/features/cloud-foundry/add-organisation/create-organization-step/create-organization-step.component.scss
  src/frontend/app/features/cloud-foundry/add-organisation/create-organization-step/create-organization-step.component.spec.ts
  src/frontend/app/features/cloud-foundry/add-organisation/create-organization-step/create-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/app/store/actions/organisation.actions.ts
Labels: ready for review
