Repository cloudfoundry/stratos, pull requests merged in 2019-08, with the labels that each got.

#3739 More fixes to remove CFAppState references
  src/frontend/packages/cloud-foundry/src/store/cloud-foundry.store.module.ts
  src/frontend/packages/cloud-foundry/src/store/effects/cloud-foundry.effects.ts
  src/frontend/packages/cloud-foundry/src/store/effects/route.effects.ts
  src/frontend/packages/store/src/app-state.ts
  src/frontend/packages/store/src/effects/action-history.effects.ts
  src/frontend/packages/store/src/effects/app.effects.ts
  src/frontend/packages/store/src/effects/auth.effects.ts
  src/frontend/packages/store/src/effects/endpoint.effects.ts
  src/frontend/packages/store/src/effects/metrics.effects.ts
  src/frontend/packages/store/src/effects/uaa-setup.effects.ts
  src/frontend/packages/store/src/effects/update-app-effects.ts
  src/frontend/packages/store/src/effects/user-favorites-effect.ts
  src/frontend/packages/store/src/effects/user-profile.effects.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relations-validate.spec.ts
  src/frontend/packages/store/src/reducers/auth.reducer.ts
  src/frontend/packages/store/src/store.module.ts
Labels: entity-catalogue, ready for review

#3747 Update protractor to fix travis e2e tests
  package-lock.json
  package.json
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-view-e2e.spec.ts
  src/test-e2e/application/po/card-app-status.po.ts
  src/test-e2e/applications/applications.po.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/metrics/metrics-registration-e2e.spec.ts
  src/test-e2e/po/page.po.ts
  src/test-e2e/po/stepper.po.ts
Labels: ready for review

#3746 Fix cf init script given changes in broker service
  deploy/tools/populate-cf/create-services.sh
Labels: ready for review

#3748 Entity catalogue - Fix most unit tests
  src/frontend/packages/cf-autoscaler/src/cf-autoscaler-testing.module.ts
  src/frontend/packages/cf-autoscaler/src/core/autoscaler.module.ts
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-base.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-metric-page/autoscaler-metric-page.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-scale-history-page/autoscaler-scale-history-page.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-service.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step1/edit-autoscaler-policy-step1.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step2/edit-autoscaler-policy-step2.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step3/edit-autoscaler-policy-step3.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step4/edit-autoscaler-policy-step4.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/shared/card-autoscaler-default/card-autoscaler-default.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-event/cf-app-autoscaler-events-config.service.spec.ts
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-metric-chart/app-autoscaler-metric-chart-card/combo-chart/combo-series-vertical.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-metric-chart/app-autoscaler-metric-chart-list-config.service.spec.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler.store.module.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-types.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/application-poll/application-poll.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/events-tab/events-tab.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/github-project-exists.directive.spec.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/space-quota-definition/space-quota-definition.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-users/cf-user-list-config.service.spec.ts
  src/frontend/packages/core/src/core/cf-api.types.ts
  src/frontend/packages/core/src/core/current-user-permissions.checker.spec.ts
  src/frontend/packages/core/src/core/current-user-permissions.service.spec.ts
  src/frontend/packages/core/src/core/entity-catalogue-test.module.ts
  src/frontend/packages/core/src/core/entity-catalogue.module.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.service.spec.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.service.ts
  src/frontend/packages/core/src/shared/app-name-unique.directive/app-name-unique.directive.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-event/cf-app-events-config.service.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-instance/cf-app-instances-config.service.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-variables/cf-app-variables-list-config.service.spec.ts
  src/frontend/packages/core/src/shared/components/list/list.component.spec.ts
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/app-state.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relation-tree.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relations-from-parent.spec.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relations-list.spec.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relations-spec-helper.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relations-validate.spec.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relations.tree.spec.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relations.ts
  src/frontend/packages/store/src/helpers/entity-schema.ts
  src/frontend/packages/store/src/helpers/schema-tree-traverse.spec.ts
  src/frontend/packages/store/src/helpers/schema-tree-traverse.ts
  src/frontend/packages/store/src/reducers/api-request-data-reducer/request-data-reducer.factory.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/request-reducer.factory.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-roles.reducer.spec.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-create-pagination.spec.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination.reducer.spec.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/packages/store/src/types/entity.types.ts
Labels: entity-catalogue, ready for review

#3766 Helm: Add apache2 utils to nginx base image
  deploy/stratos-base-images/Dockerfile.stratos-nginx-base.tmpl
Labels: ready for review

#3768 Fix bug where setup is not saved and fix /uaa after setup
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/core.module.ts
  src/frontend/packages/core/src/core/not-setup-guard.service.ts
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.ts
  src/frontend/packages/store/src/actions/setup.actions.ts
  src/frontend/packages/store/src/effects/uaa-setup.effects.ts
  src/frontend/packages/store/src/reducers/uaa-setup.reducers.ts
  src/frontend/packages/store/src/types/uaa-setup.types.ts
  src/jetstream/main.go
  src/jetstream/setup_console.go
Labels: in review, ready for review

#3771 Don't send username/password in the URL
  src/frontend/packages/store/src/effects/endpoint.effects.ts
Labels: ready for review

#3777 Don't send registration info in query string
  src/frontend/packages/store/src/effects/endpoint.effects.ts
Labels: in review, ready for review

#3781 Fix SSO E2E tests
  src/test-e2e/login/sso-login.po.ts
Labels: ready for review

#3778 Remove demo plugin
  src/jetstream/load_plugins.go
  src/jetstream/plugins/demo/main.go
Labels: in review, ready for review

#3765 Bump version and add changelog for 2.5
  CHANGELOG.md
  build/tools/changelog.js
  package-lock.json
  package.json
Labels: comments-addressed, ready for review

#3782 Fix three quota issues
  src/frontend/packages/core/src/features/cloud-foundry/add-quota/create-quota-step/create-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-space-quota/create-space-quota-step/create-space-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-quota/edit-quota-step/edit-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-space-quota/edit-space-quota-step/edit-space-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/quota-definition-form/quota-definition-form.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/packages/store/src/actions/quota-definitions.actions.ts
Labels: ready for review

#3792 Fix imagelist generation in Concourse build
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/kubernetes/imagelist-gen.sh
Labels: ready for review

#3790 Remove duplicate current-user reducer
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-role-session.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-roles-changed.reducers.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-roles-orgs.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-roles-space.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-roles-spaces.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-roles.reducer.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-roles.reducer.ts
Labels: extensions, ready for review

#3788 Fix linting
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/components.module.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-cell-health/cf-cell-health-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-cells/cf-cells-list-config.service.ts
Labels: extensions, ready for review

#3791 Fix edit quota (includes v2-master merge with other quota fixes)
  CHANGELOG.md
  build/tools/changelog.js
  deploy/stratos-base-images/Dockerfile.stratos-nginx-base.tmpl
  package-lock.json
  package.json
  src/frontend/packages/cloud-foundry/src/actions/quota-definitions.actions.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/core.module.ts
  src/frontend/packages/core/src/core/not-setup-guard.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-quota/create-quota-step/create-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-space-quota/create-space-quota-step/create-space-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-quota/edit-quota-step/edit-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-space-quota/edit-space-quota-step/edit-space-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/quota-definition-form/quota-definition-form.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/space-quota-definition-form/space-quota-definition-form.component.ts
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.ts
  src/frontend/packages/store/src/actions/setup.actions.ts
  src/frontend/packages/store/src/effects/endpoint.effects.ts
  src/frontend/packages/store/src/effects/uaa-setup.effects.ts
  src/frontend/packages/store/src/reducers/uaa-setup.reducers.ts
  src/frontend/packages/store/src/types/uaa-setup.types.ts
  src/jetstream/load_plugins.go
  src/jetstream/main.go
  src/jetstream/plugins/demo/main.go
  src/jetstream/setup_console.go
  src/test-e2e/login/sso-login.po.ts
Labels: extensions, ready for review

#3785 Fix cf metrics & most of autoscaler
  src/frontend/packages/cf-autoscaler/src/cf-autoscaler.module.ts
  src/frontend/packages/cf-autoscaler/src/core/autoscaler.module.ts
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step2/edit-autoscaler-policy-step2.component.html
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step4/edit-autoscaler-policy-step4.component.ts
  src/frontend/packages/cf-autoscaler/src/store/app-autoscaler.actions.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/actions/cf-metrics.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/organization.actions.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-instance-chart/application-instance-chart.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/metrics-tab/metrics-tab.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell.service.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cells.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-cell-apps/cf-cell-apps-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-cell-health/cf-cell-health-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-cell-health/cf-cell-health-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-cells/cf-cells-data-source.ts
  src/frontend/packages/core/src/base-entity-types.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/packages/core/src/shared/components/metrics-chart/metrics-chart.component.ts
  src/frontend/packages/core/src/shared/components/metrics-range-selector/metrics-range-selector.component.ts
  src/frontend/packages/store/src/actions/metrics.actions.ts
  src/frontend/packages/store/src/effects/metrics.effects.ts
  src/frontend/packages/store/src/reducers/system-endpoints.reducer.ts
Labels: entity-catalogue, extensions, ready for review

#3798 Add support for tech preview flag
  src/frontend/packages/core/src/core/extension/extension-types.ts
  src/frontend/packages/core/src/features/about/diagnostics-page/diagnostics-page.component.html
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-base-step/create-endpoint-base-step.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoint-helpers.ts
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/reducers/auth.reducer.ts
  src/frontend/packages/store/src/types/auth.types.ts
  src/jetstream/auth_test.go
  src/jetstream/default.config.properties
  src/jetstream/info.go
  src/jetstream/repository/interfaces/structs.go
Labels: ready for review

#3800 Allow always showing cf endpoint nav items to be customized
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/customizations.types.ts
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
Labels: ready for review

#3804 Add flag to helm chart to enable tech preview
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#3805 Allow support for customization script to modify Helm Chart during build
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/kubernetes/build.sh
Labels: ready for review

#3808 Change x-frame-options to SAMEORIGIN
  deploy/containers/nginx/conf/nginx.dev.conf
  deploy/containers/nginx/conf/nginx.k8s.conf
  deploy/stratos-ui-release/jobs/frontend/templates/nginx.conf.erb
  src/jetstream/main.go
Labels: ready for review

#3812 Allow DB directory to be specified for SQLite
  src/jetstream/datastore/datastore.go
Labels: in review, ready for review

#3815 Docker AIO improvements
  build/customize-build.js
  deploy/Dockerfile.all-in-one
  deploy/all-in-one/README.md
  deploy/all-in-one/config.all-in-one.properties
  deploy/ci/build-aio-image-canary.yml
  deploy/ci/build-aio-image-stable.yml
  deploy/ci/tasks/dev-releases/docker-image-helper.sh
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
Labels: ready for review

#3814 Add support for a custom component for no endpoints (admin)
  src/frontend/packages/core/src/app.component.spec.ts
  src/frontend/packages/core/src/core/customizations.types.ts
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.html
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoints.module.ts
  src/frontend/packages/core/src/shared/components/cf-endpoints-missing/cf-endpoints-missing.component.spec.ts
  src/frontend/packages/core/src/shared/components/cf-endpoints-missing/cf-endpoints-missing.component.ts
  src/frontend/packages/core/src/shared/components/endpoints-missing/endpoints-missing.component.html
  src/frontend/packages/core/src/shared/components/endpoints-missing/endpoints-missing.component.ts
  src/test-e2e/endpoints/endpoints-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-unregister-e2e.spec.ts
  src/test-e2e/endpoints/endpoints.po.ts
Labels: in review, ready for review
