Repository cloudfoundry/stratos, pull requests merged in 2019-02, with the labels that each got.

#3376 Helm Chart Fix for --reuse-values
  deploy/ci/automation/helmtest.sh
  deploy/ci/tasks/dev-releases/create-chart-helper.sh
  deploy/kubernetes/console/templates/__helpers.tpl
  deploy/kubernetes/console/templates/service.yaml
Labels: ready for review

#3384 Weekly update
  docs/status_updates.md
Labels: ready for review

#3388 Weekly update: 8 Feb
  docs/status_updates.md
Labels: ready for review

#3216 Backend: Update to latest version of Echo Web Server
  Gopkg.lock
  Gopkg.toml
  src/jetstream/auth.go
  src/jetstream/auth_test.go
  src/jetstream/main.go
  src/jetstream/middleware.go
  src/jetstream/mock_server_test.go
  src/jetstream/passthrough.go
  src/jetstream/passthrough_test.go
  src/jetstream/plugins/cfapppush/deploy.go
  src/jetstream/plugins/cfapppush/vcs.go
  src/jetstream/plugins/cfappssh/app_ssh.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/plugins/metrics/cloud_foundry.go
  src/jetstream/plugins/metrics/kubernetes.go
  src/jetstream/plugins/userinfo/user_info.go
  src/jetstream/repository/console_config/psql_console_config.go
  src/jetstream/repository/interfaces/websocket.go
  src/jetstream/session.go
  src/jetstream/setup_console.go
  src/jetstream/version_info_test.go
Labels: ready for review

#3389 WIP: Echo 3 Update
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
  src/jetstream/auth.go
  src/jetstream/main.go
  src/jetstream/middleware.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/repository/interfaces/plugin.go
  src/jetstream/session.go
Labels: ready for review

#3392 Ensure we have same error output as V2
  src/jetstream/main.go
  src/test-e2e/endpoints/endpoints-register-e2e.spec.ts
  src/test-e2e/po/snackbar.po.ts
Labels: ready for review

#3372 Autocomplete git repository name
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.spec.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/gitscm-tab/gitscm-tab.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2-1/commit-list-wrapper/commit-list-wrapper.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.html
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.spec.ts
  src/frontend/app/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/app/features/applications/deploy-application/github-project-exists.directive.spec.ts
  src/frontend/app/shared/data-services/scm/github-scm.ts
  src/frontend/app/shared/data-services/scm/gitlab-scm.ts
  src/frontend/app/shared/data-services/scm/scm.service.ts
  src/frontend/app/shared/data-services/scm/scm.ts
Labels: comments-addressed, ready for review

#3403 Also show forked repos when suggesting github repos in deploy app
  src/frontend/app/shared/data-services/scm/github-scm.ts
Labels: ready for review

#3402 Automated test script improvements and fixes
  deploy/ci/automation/cfallinonetest.sh
  deploy/ci/automation/cfdockercomposetest.sh
  deploy/ci/automation/cfpushtest.sh
  deploy/ci/automation/cfutils.sh
  deploy/ci/automation/runandrecord.sh
Labels: ready for review

#3404 Publish release concourse pipeline fix
  deploy/ci/tasks/dev-releases/make-release.yml
Labels: ready for review

#3405 Envvars - updated PR with v2-master changes
  Gopkg.lock
  manifest.yml
  src/jetstream/config/config.go
  src/jetstream/datastore/database_cf_config.go
  src/jetstream/datastore/datastore.go
  src/jetstream/diagnostics.go
  src/jetstream/main.go
  src/jetstream/main_test.go
  src/jetstream/middleware.go
  src/jetstream/migrator.go
  src/jetstream/mock_server_test.go
  src/jetstream/plugins/cfapppush/deploy.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/plugins/metrics/main.go
  src/jetstream/portal_config.go
  src/jetstream/portal_proxy.go
  src/jetstream/repository/interfaces/plugin.go
  src/jetstream/repository/interfaces/portal_proxy.go
  src/jetstream/setup_console.go
Labels: ready for review

#2866 Update to use `env.VarSet`
  Gopkg.lock
  manifest.yml
  src/jetstream/config/config.go
  src/jetstream/datastore/database_cf_config.go
  src/jetstream/datastore/datastore.go
  src/jetstream/diagnostics.go
  src/jetstream/main.go
  src/jetstream/main_test.go
  src/jetstream/middleware.go
  src/jetstream/migrator.go
  src/jetstream/mock_server_test.go
  src/jetstream/plugins/cfapppush/deploy.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/plugins/metrics/main.go
  src/jetstream/portal_config.go
  src/jetstream/portal_proxy.go
  src/jetstream/repository/interfaces/portal_proxy.go
  src/jetstream/setup_console.go
Labels: community, in review

#3371 Scale Users in CF Summary section
  deploy/tools/populate-cf/create-many-users.sh
  src/frontend/app/features/applications/application.service.ts
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cf-admin-add-user-warning/cf-admin-add-user-warning.component.html
  src/frontend/app/features/cloud-foundry/tabs/cf-admin-add-user-warning/cf-admin-add-user-warning.component.scss
  src/frontend/app/features/cloud-foundry/tabs/cf-admin-add-user-warning/cf-admin-add-user-warning.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cf-admin-add-user-warning/cf-admin-add-user-warning.component.theme.scss
  src/frontend/app/features/cloud-foundry/tabs/cf-admin-add-user-warning/cf-admin-add-user-warning.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-users/cloud-foundry-space-users.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-users/cloud-foundry-space-users.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-users/cloud-foundry-organization-users.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-users/cloud-foundry-organization-users.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-users/cloud-foundry-users.component.html
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-modify/manage-users-modify.component.ts
  src/frontend/app/features/cloud-foundry/users/manage-users/manage-users-select/manage-users-select.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-pagination-controller.ts
  src/frontend/app/shared/components/list/list-types/cf-select-users/cf-select-users-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/store/actions/list.actions.ts
  src/frontend/app/store/actions/organization.actions.ts
  src/frontend/app/store/actions/space.actions.ts
  src/frontend/app/store/actions/users.actions.ts
  src/frontend/app/store/effects/set-client-filter.effect.ts
  src/frontend/app/store/effects/users.effects.ts
  src/frontend/app/store/helpers/entity-relations/processors/org-space-post-processor.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-create-pagination.spec.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-max-reached.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-reset-pagination.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/app/store/reducers/users.reducer.ts
  src/frontend/app/store/store.module.ts
  src/frontend/app/store/types/pagination.types.ts
  src/frontend/app/test-framework/cloud-foundry-organization.service.mock.ts
  src/frontend/app/test-framework/cloud-foundry-space.service.mock.ts
  src/frontend/sass/_all-theme.scss
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-e2e.spec.ts
Labels: in review, ready for review

#3399 Fix issue where org level user lists shows space roles from other orgs
  src/frontend/app/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
Labels: ready for review
