Repository cloudfoundry/stratos, pull requests merged in 2019-07, with the labels that each got.

#3684 Update v3 api doc with service info
  docs/cf-api-v3.md
Labels: ready for review

#3672 Entity catalogue: Fix app wall app card org/space values
  src/frontend/packages/cloud-foundry/src/selectors/api.selectors.ts
Labels: entity-catalogue, ready for review

#3692 Ensure we can communicate with github before starting e2e tests
  protractor.conf.js
Labels: ready for review

#3679 Fix connect endpoint issues in Firefox
  src/frontend/packages/core/src/core/browser-helper.ts
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs-utils.ts
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs.component.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-connect/create-endpoint-connect.component.html
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-connect/create-endpoint-connect.component.scss
  src/frontend/packages/core/src/shared/components/file-input/file-input.component.ts
Labels: in review, ready for review

#3690 CI: Add support for squashing docker image
  deploy/ci/scripts/build-docker-image-resource.sh
  deploy/ci/scripts/docker-image-common.sh
  deploy/ci/scripts/docker-image-out-asset
Labels: in review, ready for review

#3617 Fall back on credential's uri when we can't find db config in other credential values
  src/jetstream/datastore/database_cf_config.go
  src/jetstream/datastore/datastore.go
  src/jetstream/migrator.go
Labels: ready for review

#3632 Add support for local auth configuration
  src/jetstream/auth.go
  src/jetstream/auth_test.go
  src/jetstream/datastore/20190522121200_LocalUsers.go
  src/jetstream/default.config.properties
  src/jetstream/go.mod
  src/jetstream/go.sum
  src/jetstream/localusers.go
  src/jetstream/localusers_test.go
  src/jetstream/main.go
  src/jetstream/mock_server_test.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/repository/console_config/psql_console_config.go
  src/jetstream/repository/interfaces/localuser.go
  src/jetstream/repository/interfaces/portal_proxy.go
  src/jetstream/repository/interfaces/structs.go
  src/jetstream/repository/localusers/localusers.go
  src/jetstream/repository/localusers/psql_localusers.go
  src/jetstream/setup_console.go
Labels: ready for review

#3693 E2E Service Instances Tests: Increase time to back off
  src/test-e2e/marketplace/services-helper-e2e.ts
Labels: ready for review

#3671 Entity catalogue: List Fixes
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue-entity.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.service.ts
  src/frontend/packages/core/src/core/entity-service.spec.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/local-list-controller.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/local-list.helpers.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/base-endpoints-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list.component.ts
  src/frontend/packages/core/src/shared/monitors/entity-monitor.factory.service.ts
  src/frontend/packages/core/src/shared/monitors/pagination-monitor.factory.ts
  src/frontend/packages/core/src/shared/monitors/pagination-monitor.ts
  src/frontend/packages/store/src/actions/endpoint.actions.ts
  src/frontend/packages/store/src/effects/endpoint.effects.ts
  src/frontend/packages/store/src/effects/user-favorites-effect.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relations.ts
  src/frontend/packages/store/src/helpers/entity-schema.ts
  src/frontend/packages/store/src/reducers/api-request-data-reducer/request-data-reducer.factory.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-clear-pagination-of-entity.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-create-pagination.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-reset-pagination.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-start.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination.reducer.ts
Labels: entity-catalogue, ready for review

#3670 Entity catalogue: Service Instance Wall Fix #1
  src/frontend/packages/cloud-foundry/src/cf-entity-factory.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue-entity.ts
  src/frontend/packages/core/src/features/service-catalog/services-helper.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/service-instances-wall-list-config.service.ts
  src/frontend/packages/core/src/shared/monitors/pagination-monitor.ts
  src/frontend/packages/store/src/actions/service-instances.actions.ts
  src/frontend/packages/store/src/actions/space.actions.ts
Labels: entity-catalogue, ready for review

#3702 Add commented out defaults for cf dev & update local go-env to fetch latest changes
  deploy/ci/travis/upload-e2e-test-report.sh
  deploy/tools/init-cf-for-e2e.sh
Labels: ready for review

#3696 Fix local users for mysql
  src/jetstream/datastore/20190522121200_LocalUsers.go
Labels: ready for review

#3703 Jenkins: Ensure E2E tests have user invite configuration
  deploy/ci/automation/cfallinonetest.sh
  deploy/ci/automation/cfpushtest.sh
  deploy/ci/automation/helmtest.sh
  deploy/cloud-foundry/build.sh
  deploy/cloud-foundry/config.properties
  src/jetstream/plugins/cloudfoundryhosting/main.go
Labels: ready for review

#3709 User Invite E2E Tests: Improve reliability
  src/test-e2e/cloud-foundry/invite-users-e2e.helper.ts
Labels: ready for review

#3710 Test investigation for E2E user invite tests
  src/test-e2e/cloud-foundry/cf-level/cf-invite-config-e2e.spec.ts
  src/test-e2e/cloud-foundry/invite-users-e2e.helper.ts
Labels: ready for review

#3707 Improve user clean up
  deploy/ci/automation/e2e-clean-remnants.sh
Labels: ready for review

#3713 Fix e2e tests when running against a UAA with no explicit zone (cfdev)
  src/test-e2e/helpers/uaa-request-helpers.ts
Labels: ready for review

#3695 Ensure both private and shared domains are included in domain lists
  src/frontend/packages/core/src/core/cf-api.types.ts
  src/frontend/packages/core/src/features/applications/application.service.ts
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/tabs/routes-tab/routes-tab/routes-tab.component.ts
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.ts
  src/frontend/packages/core/src/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/packages/core/src/features/applications/routes/map-routes/map-routes.component.ts
  src/frontend/packages/core/test-framework/application-service-helper.ts
  src/frontend/packages/store/src/actions/domains.actions.ts
  src/frontend/packages/store/src/actions/organization.actions.ts
Labels: ready for review

#3694 Refactor setup config
  src/jetstream/datastore/20190621212700_ConfigSchema.go
  src/jetstream/datastore/datastore.go
  src/jetstream/datastore/datastore_migrator.go
  src/jetstream/main.go
  src/jetstream/plugins/cfappssh/app_ssh.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/plugins/userinvite/auth.go
  src/jetstream/plugins/userinvite/invite.go
  src/jetstream/portal_proxy.go
  src/jetstream/repository/console_config/console_config.go
  src/jetstream/repository/console_config/env_lookup.go
  src/jetstream/repository/console_config/psql_console_config.go
  src/jetstream/repository/interfaces/config/config.go
  src/jetstream/repository/interfaces/portal_proxy.go
  src/jetstream/repository/interfaces/structs.go
  src/jetstream/session_test.go
  src/jetstream/setup_console.go
  src/jetstream/setup_console_test.go
  src/jetstream/utils_test.go
Labels: ready for review

#3714 Jenkins: Fix docker AIO deployment tests
  deploy/Dockerfile.all-in-one
  deploy/all-in-one/config.all-in-one.properties
  deploy/ci/automation/cfallinonetest.sh
Labels: ready for review

#3716 Additional invite user logging and nav changes
  src/test-e2e/cloud-foundry/invite-users-e2e.helper.ts
  src/test-e2e/cloud-foundry/org-level/org-invite-user-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-invite-user-e2e.spec.ts
Labels: ready for review

#3715 Fix connect to IBM Cloud
  src/jetstream/auth.go
Labels: ready for review

#3683 Add app polling controller
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/application-poll/application-poll.component.html
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/application-poll/application-poll.component.scss
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/application-poll/application-poll.component.spec.ts
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/application-poll/application-poll.component.ts
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/application-polling.service.ts
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.scss
  src/frontend/packages/core/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.spec.ts
  src/frontend/packages/core/src/features/applications/applications.module.ts
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.html
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.ts
  src/frontend/packages/core/src/shared/components/list/list.component.html
  src/frontend/packages/core/src/shared/components/list/list.component.scss
  src/frontend/packages/core/src/shared/components/polling-indicator/polling-indicator.component.html
  src/frontend/packages/core/src/shared/components/polling-indicator/polling-indicator.component.scss
  src/frontend/packages/core/src/shared/components/polling-indicator/polling-indicator.component.spec.ts
  src/frontend/packages/core/src/shared/components/polling-indicator/polling-indicator.component.ts
  src/frontend/packages/core/src/shared/monitors/entity-monitor.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/actions/dashboard-actions.ts
  src/frontend/packages/store/src/reducers/dashboard-reducer.ts
  src/frontend/packages/store/src/types/dashboard.types.ts
Labels: ready for review

#3705 Entity catalogue codeclimate
  src/frontend/packages/cloud-foundry/src/actions/cloud-foundry.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/organization.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/permissions.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/service-instances.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/space.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/users.actions.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/cloud-foundry.module.ts
  src/frontend/packages/cloud-foundry/src/effects/permissions.effect.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/cf-info.action-builders.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue-entity.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.service.ts
  src/frontend/packages/core/src/features/applications/application.service.ts
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-space-routes/cf-space-route-row-state.helper.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces/cf-spaces-data-source.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users-org-space-roles/cf-users-space-roles-data-source.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/service-instances/service-instances-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list.component.ts
  src/frontend/packages/core/src/shared/monitors/pagination-monitor.ts
  src/frontend/packages/store/src/actions/auth.actions.ts
  src/frontend/packages/store/src/effects/cloud-foundry.effects.ts
  src/frontend/packages/store/src/helpers/entity-schema.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-reducer.helpers.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-roles-orgs.reducer.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-roles-spaces.reducer.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-start.ts
  src/frontend/packages/store/src/store.module.ts
Labels: entity-catalogue, ready for review

#3725 Entity catalogue - Tweaks after review
  src/frontend/packages/cloud-foundry/src/actions/user-provided-service.actions.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-types.ts
  src/frontend/packages/cloud-foundry/src/effects/permissions.effect.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/domin.action-builder.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/user-provided-service.action-builders.ts
  src/frontend/packages/core/src/core/entity-catalogue/action-dispatcher/action-dispatcher.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.helper.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.store-setup.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell.service.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint/connect-endpoint.component.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/packages/core/src/shared/components/page-subheader/page-subheader.component.ts
  src/frontend/packages/core/src/shared/data-services/service-action-helper.service.ts
  src/frontend/packages/core/src/shared/services/cf-org-space-label.service.ts
  src/frontend/packages/core/src/shared/services/cloud-foundry-user-provided-services.service.ts
  src/frontend/packages/store/src/actions/metrics.actions.ts
  src/frontend/packages/store/src/effects/request.effects.ts
  src/frontend/packages/store/src/reducers/endpoint-disconnect-application.reducer.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/packages/store/src/reducers/system-endpoints.reducer.ts
  src/frontend/packages/store/src/types/entity.types.ts
  src/frontend/packages/store/src/types/other-entity.types.ts
  src/frontend/packages/store/src/types/pagination.types.ts
  src/frontend/packages/store/src/types/request.types.ts
Labels: entity-catalogue, ready for review

#3726 Entity catalogue - Second round of todos, fixed user profile page and favourites
  src/frontend/packages/cloud-foundry/src/cloud-foundry.module.ts
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/base-entity-schemas.ts
  src/frontend/packages/core/src/core/current-user-permissions.config.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue-entity.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.store-setup.ts
  src/frontend/packages/core/src/core/user-favorite-manager.ts
  src/frontend/packages/core/src/features/service-catalog/services-helper.ts
  src/frontend/packages/core/src/features/user-profile/user-profile.service.ts
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorite-config-mapper.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list.component.ts
  src/frontend/packages/core/src/shared/monitors/pagination-monitor.ts
  src/frontend/packages/store/src/effects/api.effects.ts
  src/frontend/packages/store/src/effects/user-profile.effects.ts
  src/frontend/packages/store/src/helpers/entity-factory.ts
  src/frontend/packages/store/src/helpers/entity-relations/entity-relations.types.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/packages/store/src/selectors/api.selectors.ts
  src/frontend/packages/store/src/selectors/current-user-roles-permissions-selectors/role.selectors.ts
  src/frontend/packages/store/src/store.module.ts
  src/frontend/packages/store/src/types/user-profile.types.ts
Labels: blocked-pr, entity-catalogue

#3730 Fix persist of dashboard settings
  src/frontend/packages/store/src/effects/auth.effects.ts
  src/frontend/packages/store/src/reducers.module.ts
Labels: entity-catalogue, ready for review

#3732 Entity Catalog: Store: Move CF reducers (1)
  src/frontend/packages/cloud-foundry/src/cloud-foundry.module.ts
  src/frontend/packages/cloud-foundry/src/store/cloud-foundry.reducers.module.ts
  src/frontend/packages/cloud-foundry/src/store/cloud-foundry.store.module.ts
  src/frontend/packages/cloud-foundry/src/store/effects/create-app-effects.ts
  src/frontend/packages/cloud-foundry/src/store/effects/deploy-app.effects.ts
  src/frontend/packages/cloud-foundry/src/store/effects/github.effects.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/create-application.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/deploy-app.reducer.ts
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/features/applications/create-application/create-application-step3/create-application-step3.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.html
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.scss
  src/frontend/packages/core/src/shared/app-name-unique.directive/app-name-unique.directive.ts
  src/frontend/packages/store/src/reducers.module.ts
  src/frontend/packages/store/src/selectors/create-application.selectors.ts
  src/frontend/packages/store/src/store.module.ts
Labels: entity-catalogue, in review, ready for review

#3733 Entity Catalog: Store: Move CF reducers (2)
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/store/cloud-foundry.reducers.module.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/app-stats-request.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/application-add-remove-reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/application-route.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/create-service-instance.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/organization-quota.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/organization-space.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/routes.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/service-instance.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/space-quota.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/users-roles.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/users.reducer.ts
  src/frontend/packages/core/src/features/cloud-foundry/users/manage-users/cf-roles.service.ts
  src/frontend/packages/store/src/reducers.module.ts
  src/frontend/packages/store/src/reducers/api-request-reducers.generator.ts
Labels: entity-catalogue, ready for review

#3734 Entity Catalog: Store: Move CF reducers (3)
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-base-cf-role.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-cf-roles.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-roles-org.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-roles-orgs.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-roles-space.reducer.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/current-user-roles-reducer/current-user-roles-spaces.reducer.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-reducer.helpers.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-roles-changed.reducers.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-roles.reducer.spec.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-roles.reducer.ts
Labels: entity-catalogue, ready for review

#3729 Entity catalogue - Final round of identifying (and fixing minor) todos
  src/frontend/packages/cloud-foundry/src/cloud-foundry.module.ts
  src/frontend/packages/core/src/app.component.ts
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/base-entity-types.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.types.ts
  src/frontend/packages/core/src/core/entity-service-factory.service.ts
  src/frontend/packages/core/src/core/utils.service.ts
  src/frontend/packages/store/src/selectors/api.selectors.ts
  src/frontend/packages/store/src/selectors/current-user-roles-permissions-selectors/role.selectors.ts
  src/frontend/packages/store/src/selectors/favorite-groups.selectors.ts
  src/frontend/packages/store/src/selectors/internal-events.selectors.ts
  src/frontend/packages/store/src/types/entity.types.ts
Labels: entity-catalogue, ready for review

#3736 Entity Catalog: Store: Move CF selectors and tidy up
  src/frontend/packages/cloud-foundry/src/cf-app-state.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-factory.ts
  src/frontend/packages/cloud-foundry/src/store/cloud-foundry.store.module.ts
  src/frontend/packages/cloud-foundry/src/store/effects/create-app-effects.ts
  src/frontend/packages/cloud-foundry/src/store/effects/deploy-app.effects.ts
  src/frontend/packages/cloud-foundry/src/store/effects/permissions.effect.ts
  src/frontend/packages/cloud-foundry/src/store/selectors/api.selectors.ts
  src/frontend/packages/cloud-foundry/src/store/selectors/cf-current-user-role.selectors.ts
  src/frontend/packages/cloud-foundry/src/store/selectors/cloud-foundry.selector.ts
  src/frontend/packages/cloud-foundry/src/store/selectors/create-application.selectors.ts
  src/frontend/packages/cloud-foundry/src/store/selectors/create-service-instance.selectors.ts
  src/frontend/packages/cloud-foundry/src/store/selectors/deploy-application.selector.ts
  src/frontend/packages/cloud-foundry/src/store/selectors/pagination.selectors.ts
  src/frontend/packages/core/src/core/current-user-permissions.checker.ts
  src/frontend/packages/core/src/features/applications/application.service.ts
  src/frontend/packages/core/src/features/applications/create-application/create-application-step3/create-application-step3.component.ts
  src/frontend/packages/core/src/features/applications/create-application/create-application.component.ts
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.ts
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application.component.ts
  src/frontend/packages/core/src/features/applications/deploy-application/github-project-exists.directive.ts
  src/frontend/packages/core/src/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-space/create-space-step/create-space-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/cf.helpers.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/select-service/select-service.component.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/specify-user-provided-details/specify-user-provided-details.component.ts
  src/frontend/packages/core/src/shared/components/create-application/create-application-step1/create-application-step1.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/github-commits/github-commits-list-config-app-tab.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/github-commits/github-commits-list-config-deploy.service.ts
  src/frontend/packages/core/src/shared/data-services/cf-user.service.ts
  src/frontend/packages/core/src/shared/monitors/internal-event-monitor.factory.ts
  src/frontend/packages/core/src/shared/services/cf-org-space-label.service.ts
  src/frontend/packages/core/src/shared/services/cloud-foundry-user-provided-services.service.ts
  src/frontend/packages/store/src/app-state.ts
  src/frontend/packages/store/src/selectors/current-user-role.selectors.ts
  src/frontend/packages/store/src/selectors/favorite-groups.selectors.ts
  src/frontend/packages/store/src/selectors/internal-events.selectors.ts
  src/frontend/packages/store/src/store.module.ts
  src/frontend/packages/store/src/types/routing.type.ts
Labels: blocked-pr, entity-catalogue

#3737 Entity Catalog: Store: Fix CFAppState references in store module
  src/frontend/packages/cloud-foundry/src/store/effects/app-variables.effects.ts
  src/frontend/packages/cloud-foundry/src/store/effects/permissions.effect.ts
  src/frontend/packages/core/src/core/user-favorite-manager.ts
  src/frontend/packages/core/src/shared/components/favorites-global-list/favorites-global-list.component.ts
  src/frontend/packages/store/src/app-state.ts
  src/frontend/packages/store/src/effects/endpoint-api-errors.effects.ts
  src/frontend/packages/store/src/effects/set-client-filter.effect.ts
  src/frontend/packages/store/src/effects/snackBar.effects.spec.ts
  src/frontend/packages/store/src/effects/system.effects.ts
  src/frontend/packages/store/src/helpers/store-helpers.ts
  src/frontend/packages/store/src/reducers/list.reducer.ts
  src/frontend/packages/store/src/selectors/favorite-groups.selectors.ts
  src/frontend/packages/store/src/store.module.ts
Labels: blocked-pr, entity-catalogue
