Repository cloudfoundry/stratos, pull requests merged in 2019-04, with the labels that each got.

#3436 Add cf/org/space links to service instance table using common components
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/packages/core/src/shared/components/cf-org-space-links/cf-org-space-links.component.html
  src/frontend/packages/core/src/shared/components/cf-org-space-links/cf-org-space-links.component.scss
  src/frontend/packages/core/src/shared/components/cf-org-space-links/cf-org-space-links.component.spec.ts
  src/frontend/packages/core/src/shared/components/cf-org-space-links/cf-org-space-links.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell/table-cell.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app/TableCellAppCfOrgSpaceBase.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app/card/card-app.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app/table-cell-app-cforgspace-header/table-cell-app-cforgspace-header.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/app/table-cell-app-cforgspace-header/table-cell-app-cforgspace-header.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app/table-cell-app-cforgspace/table-cell-app-cforgspace.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/app/table-cell-app-cforgspace/table-cell-app-cforgspace.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/user-provided-service-instance-card/user-provided-service-instance-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/user-provided-service-instance-card/user-provided-service-instance-card.component.ts
  src/frontend/packages/core/src/shared/services/cf-org-space-label.service.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/applications/application-wall-e2e.spec.ts
  src/test-e2e/e2e.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/helpers/request-helpers.ts
  src/test-e2e/marketplace/create-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance-private-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance-space-scoped-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instances-bind-app-e2e.spec.ts
  src/test-e2e/marketplace/edit-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/marketplace-create-service-instances-e2e.spec.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
  src/test-e2e/po/confirm-dialog.ts
  src/test-e2e/po/snackbar.po.ts
Labels: ready for review

#3419 Hide favorites when using SQLite
  deploy/cloud-foundry/db-migration/README.md
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.html
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.ts
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/features/home/home/home-page.component.ts
  src/frontend/packages/store/src/reducers/auth.reducer.ts
  src/frontend/packages/store/src/reducers/dashboard-reducer.ts
  src/frontend/packages/store/src/types/auth.types.ts
  src/jetstream/plugins/cloudfoundryhosting/main.go
Labels: ready for review

#3448 Ensure Service Instance counts are correct
  src/frontend/packages/core/src/features/cloud-foundry/cli-info-cloud-foundry/cli-info-cloud-foundry.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.ts
  src/frontend/packages/core/src/features/service-catalog/services-helper.ts
  src/frontend/packages/core/src/shared/components/cards/card-cf-org-usage/card-cf-org-usage.component.html
  src/frontend/packages/core/src/shared/components/cards/card-cf-org-usage/card-cf-org-usage.component.scss
  src/frontend/packages/core/src/shared/components/cards/card-cf-org-usage/card-cf-org-usage.component.spec.ts
  src/frontend/packages/core/src/shared/components/cards/card-cf-org-usage/card-cf-org-usage.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces/cf-spaces-data-source.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-list.helpers.ts
  src/frontend/packages/core/src/shared/services/cloud-foundry-user-provided-services.service.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/actions/service-instances.actions.ts
  src/frontend/packages/store/src/actions/user-provided-service.actions.ts
Labels: ready for review

#3466 Fix unit tests
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.spec.ts
  src/frontend/packages/core/src/features/home/home/home-page.component.spec.ts
  src/frontend/packages/core/src/features/login/login-page/login-page.component.spec.ts
Labels: ready for review

#3460 organization/space: added created and updated dates to summary
  src/frontend/packages/core/src/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.html
  src/frontend/packages/core/src/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.scss
  src/frontend/packages/core/src/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.spec.ts
  src/frontend/packages/core/src/shared/components/cards/card-cf-space-details/card-cf-space-details.component.html
  src/frontend/packages/core/src/shared/components/cards/card-cf-space-details/card-cf-space-details.component.scss
  src/frontend/packages/core/src/shared/components/cards/card-cf-space-details/card-cf-space-details.component.spec.ts
Labels: ready for review

#3469 Fix Gitlab deploy step
  src/frontend/packages/core/src/core/utils.service.ts
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-step2.component.html
  src/frontend/packages/core/src/shared/data-services/scm/gitlab-scm.ts
  src/frontend/packages/store/src/effects/deploy-app.effects.ts
  src/frontend/packages/store/src/effects/github.effects.ts
Labels: ready for review

#3433 Add support for slide-in side help and write in to endpoint connect dialog
  package-lock.json
  package.json
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/src/core/extension/extension-types.ts
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.html
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.scss
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.spec.ts
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.html
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.scss
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/packages/core/src/shared/components/blur.directive.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/markdown-preview/markdown-content-observer.directive.ts
  src/frontend/packages/core/src/shared/components/markdown-preview/markdown-preview.component.html
  src/frontend/packages/core/src/shared/components/markdown-preview/markdown-preview.component.scss
  src/frontend/packages/core/src/shared/components/markdown-preview/markdown-preview.component.spec.ts
  src/frontend/packages/core/src/shared/components/markdown-preview/markdown-preview.component.theme.scss
  src/frontend/packages/core/src/shared/components/markdown-preview/markdown-preview.component.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/actions/dashboard-actions.ts
  src/frontend/packages/store/src/reducers/dashboard-reducer.ts
Labels: ready for review

#3450 User Favourites UI tweaks
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/core.module.ts
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.html
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.scss
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/features/home/home/home-page.component.html
  src/frontend/packages/core/src/features/home/home/home-page.component.scss
  src/frontend/packages/core/src/features/home/home/home-page.component.theme.scss
  src/frontend/packages/core/src/features/home/home/home-page.component.ts
  src/frontend/packages/core/src/shared/components/favorites-entity-list/favorites-entity-list.component.html
  src/frontend/packages/core/src/shared/components/favorites-entity-list/favorites-entity-list.component.scss
  src/frontend/packages/core/src/shared/components/favorites-entity-list/favorites-entity-list.component.ts
  src/frontend/packages/core/src/shared/components/favorites-global-list/favorites-global-list.component.html
  src/frontend/packages/core/src/shared/components/favorites-global-list/favorites-global-list.component.scss
  src/frontend/packages/core/src/shared/components/favorites-global-list/favorites-global-list.component.theme.scss
  src/frontend/packages/core/src/shared/components/favorites-global-list/favorites-global-list.component.ts
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.html
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.scss
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.ts
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.spec.ts
  src/frontend/packages/core/src/shared/components/recent-entities/recent-entities.component.html
  src/frontend/packages/core/src/shared/shared.module.ts
Labels: ready for review

#3476 Tweaks following project update
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application-steps.types.ts
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/service-instances-wall-data-source.ts
Labels: ready for review

#3463 Hide endpoints page when using SQLite
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/packages/core/src/shared/components/cf-endpoints-missing/cf-endpoints-missing.component.ts
  src/frontend/packages/core/src/shared/components/endpoints-missing/endpoints-missing.component.ts
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.ts
Labels: ready for review

#3470 Add an optional connect step to the register endpoint stepper
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.html
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.scss
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.spec.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint/connect-endpoint.component.html
  src/frontend/packages/core/src/features/endpoints/connect-endpoint/connect-endpoint.component.scss
  src/frontend/packages/core/src/features/endpoints/connect-endpoint/connect-endpoint.component.spec.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint/connect-endpoint.component.ts
  src/frontend/packages/core/src/features/endpoints/connect.service.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-connect/create-endpoint-connect.component.html
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-connect/create-endpoint-connect.component.scss
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-connect/create-endpoint-connect.component.spec.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-connect/create-endpoint-connect.component.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint.component.html
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint.component.spec.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint.module.ts
  src/frontend/packages/core/src/features/endpoints/endpoints.module.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-list.helpers.ts
  src/frontend/packages/core/src/shared/components/stepper/step/step.component.ts
  src/frontend/packages/core/src/shared/components/stepper/steppers/steppers.component.html
  src/frontend/packages/store/src/effects/endpoint.effects.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/succeed-request.ts
  src/frontend/packages/store/src/types/request.types.ts
  src/jetstream/auth.go
  src/test-e2e/e2e.ts
  src/test-e2e/endpoints/connect-dialog.po.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-register-e2e.spec.ts
  src/test-e2e/endpoints/endpoints.po.ts
  src/test-e2e/endpoints/register-dialog.po.ts
  src/test-e2e/helpers/reset-helpers.ts
  src/test-e2e/metrics/metrics-registration-e2e.spec.ts
  src/test-e2e/po/snackbar.po.ts
Labels: ready for review

#3479 Improved user invite html email template
  src/jetstream/templates/user-invite-email.html
  src/jetstream/templates/user-invite-email.txt
Labels: ready for review

#3481 Update version number and add release notes for 2.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready for review

#3483 Improvements for automated testing on Jenkins
  deploy/ci/automation/cfpushtest.sh
  deploy/ci/automation/init-pcfdev-uaa.sh
  deploy/ci/automation/init-uaa-for-sso.sh
Labels: ready for review

#3491 Use Go modules for backend dependencies
  .gitignore
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  build/bk-build.sh
  build/bk-fetch-deps.sh
  deploy/ci/travis/depcache.sh
  deploy/ci/travis/fetch-depcache.sh
  deploy/ci/travis/run-e2e-tests.sh
  docs/developers-guide.md
  src/jetstream/datastore/datastore_test.go
  src/jetstream/go.mod
  src/jetstream/go.sum
  src/jetstream/plugins/cfapppush/deploy.go
  src/jetstream/repository/interfaces/go.mod
  src/jetstream/repository/interfaces/go.sum
Labels: in review, ready for review

#3493 Update all go references to 12.4
  build/update-tools-versions.sh
  deploy/Dockerfile.bk
  deploy/ci/scripts/Dockerfile.bosh
  deploy/fissile/Dockerfile.bosh-cli
  deploy/stratos-base-images/Dockerfile.stratos-go-build-base.tmpl
  deploy/stratos-ui-release/config/blobs.yml
  deploy/stratos-ui-release/packages/golang/packaging
  deploy/stratos-ui-release/packages/golang/spec
  manifest.yml
  src/frontend/packages/core/test-framework/store-test-helper.ts
Labels: ready for review

#3497 Fix issue with spaces in folders with backend build
  build/bk-build.sh
Labels: ready for review

#3503 Helm Chart: Fix issue with loadBalancerSourceRanges
  deploy/kubernetes/console/templates/service.yaml
  deploy/kubernetes/console/tests/service_test.yaml
Labels: ready for review

#3480 User Invite tweaks and helm support
  .gitignore
  deploy/Dockerfile.bk
  deploy/common-build.sh
  deploy/kubernetes/build.sh
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/tests/user_invite_test.yaml
  deploy/kubernetes/console/values.yaml
  deploy/kubernetes/values.yaml.tmpl
  docs/invite-user-guide.md
  src/jetstream/plugins/userinvite/config.go
  src/jetstream/plugins/userinvite/email.go
Labels: ready for review

#3511 Fix all-in-one image build
  deploy/Dockerfile.all-in-one
Labels: ready for review

#3510 SSO E2E Tests: Fix login page detection - different with SCF than PCFDEV
  src/test-e2e/login/sso-login.po.ts
Labels: ready for review

#3498 Helm chart: Add migration of volume data to secrets
  deploy/Dockerfile.bk
  deploy/db/scripts/migrate-volumes.sh
  deploy/db/scripts/run-postflight-job.k8s.sh
  deploy/kubernetes/console/templates/__helpers.tpl
  deploy/kubernetes/console/templates/secrets.yaml
  deploy/kubernetes/console/templates/volume-migration.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#3505 Fix Helm UAA_HOST bug
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/tests/deployment_test.yaml
  src/jetstream/plugins/cloudfoundry/main.go
Labels: bug, ready for review

#3515 Concourse pipeline updates
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-make-release.yml
  deploy/ci/tasks/dev-releases/check-gh-release.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
  deploy/ci/tasks/dev-releases/make-release.yml
Labels: ready for review

#3517 Fix exception when generating unknown endpoint type details
  src/frontend/packages/core/src/features/endpoints/endpoint-helpers.ts
Labels: ready for review

#3542 Fix SSO connect button not enabled
  src/frontend/packages/core/src/features/endpoints/connect-endpoint/connect-endpoint.component.ts
Labels: in review, ready for review

#3545 Fix three user provided service create/edit stepper bugs
  src/frontend/packages/core/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/packages/core/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/specify-user-provided-details/specify-user-provided-details.component.ts
Labels: ready for review

#3541 When no space quota has been assigned fall back on more realistive quota
  src/frontend/packages/core/src/features/cloud-foundry/edit-space/edit-space.component.spec.ts
  src/frontend/packages/core/src/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/packages/core/src/shared/components/cards/card-cf-space-details/card-cf-space-details.component.html
  src/frontend/packages/core/src/shared/components/cards/card-cf-space-details/card-cf-space-details.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
Labels: ready for review

#3548 Concourse Pipeline: Fix to ensure "make-release" works with a private GitHub Repository
  deploy/ci/tasks/dev-releases/github-helper.sh
  deploy/ci/tasks/dev-releases/make-release.yml
Labels: ready for review
