Repository cloudfoundry/stratos, pull requests merged in 2019-11, with the labels that each got.

#3882 Auth jetstream refactor
  src/jetstream/auth.go
  src/jetstream/auth_test.go
  src/jetstream/authcnsi.go
  src/jetstream/authlocal.go
  src/jetstream/authuaa.go
  src/jetstream/crypto/aes.go
  src/jetstream/crypto/crypto.go
  src/jetstream/crypto/crypto_test.go
  src/jetstream/info.go
  src/jetstream/localusers.go
  src/jetstream/localusers_test.go
  src/jetstream/main.go
  src/jetstream/middleware.go
  src/jetstream/mock_server_test.go
  src/jetstream/oauth_requests_test.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/plugins/userinfo/main.go
  src/jetstream/plugins/userinfo/uaa_user.go
  src/jetstream/portal_proxy.go
  src/jetstream/repository/cnsis/pgsql_cnsis.go
  src/jetstream/repository/cnsis/pgsql_cnsis_test.go
  src/jetstream/repository/interfaces/auth.go
  src/jetstream/repository/interfaces/errors.go
  src/jetstream/repository/interfaces/portal_proxy.go
  src/jetstream/repository/tokens/pgsql_tokens.go
  src/jetstream/session.go
  src/jetstream/setup_console.go
  src/jetstream/stringutils/utils.go
  src/jetstream/stringutils/utils_test.go
Labels: jetstream, ready for review

#4007 Add clean routes to e2e-clean-remnants
  deploy/ci/automation/e2e-clean-remnants.sh
Labels: ready for review

#4009 Update metric used for cells
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/cf-cell.helpers.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cells.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoint-helpers.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/base-cf/base-cf-list-config.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-cell-health/cf-cell-health-list-config.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-cells/cf-cells-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-cells/cf-cells-list-config.service.ts
  src/jetstream/plugins/metrics/cloud_foundry.go
Labels: ready for review

#4015 Fix incorrect SSO behaviour following 2.4.0 --> 2.6.0 upgrade
  src/jetstream/repository/console_config/env_lookup.go
Labels: ready for review

#3991 Add endpoint error page
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/features/error-page/error-page.module.ts
  src/frontend/packages/core/src/features/error-page/error-page.routing.ts
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.html
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.scss
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.spec.ts
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.theme.scss
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/base-endpoints-data-source.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header-events/page-header-events.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header-events/page-header-events.component.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header-events/page-header-events.component.theme.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header-events/page-header-events.component.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/core/src/shared/monitors/internal-event.monitor.ts
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/actions/dashboard-actions.ts
  src/frontend/packages/store/src/actions/internal-events.actions.ts
  src/frontend/packages/store/src/effects/endpoint-api-errors.effects.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/endpoint-errors.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/jetstream-error.handler.ts
  src/frontend/packages/store/src/reducers/dashboard-reducer.ts
  src/frontend/packages/store/src/reducers/internal-events.reducer.ts
  src/frontend/packages/store/src/types/internal-events.types.ts
Labels: ready for review

#4011 Allow notifications to be marked as 'read'
  src/frontend/packages/core/src/features/event-page/events-page/events-page.component.html
  src/frontend/packages/core/src/features/event-page/events-page/events-page.component.scss
  src/frontend/packages/core/src/features/event-page/events-page/events-page.component.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/core/src/shared/global-events.service.ts
Labels: ready for review

#4012 Wire in endpoint errors to notification process
  package-lock.json
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.html
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.scss
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.ts
  src/frontend/packages/core/src/features/event-page/event-page.routing.ts
  src/frontend/packages/core/src/features/event-page/events-page/events-page.component.html
  src/frontend/packages/core/src/features/event-page/events-page/events-page.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/base-endpoints-data-source.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header-events/page-header-events.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header-events/page-header-events.component.ts
  src/frontend/packages/core/src/shared/global-events.service.ts
  src/frontend/packages/core/src/shared/monitors/internal-event.monitor.ts
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/actions/internal-events.actions.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/endpoint-errors.handler.spec.ts
  src/frontend/packages/store/src/reducers/dashboard-reducer.ts
  src/frontend/packages/store/src/reducers/internal-events.reducer.ts
  src/frontend/packages/store/src/types/internal-events.types.ts
Labels: blocked-pr, ready for review

#4010 Initial prototype for custom, entity based views
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/features/applications/ssh-application/ssh-application.component.ts
  src/frontend/packages/core/src/api-driven-views/api-drive-views.types.ts
  src/frontend/packages/core/src/api-driven-views/api-driven-views-routing.module.ts
  src/frontend/packages/core/src/api-driven-views/api-driven-views.module.ts
  src/frontend/packages/core/src/api-driven-views/components/api-entity-list/api-entity-list.component.html
  src/frontend/packages/core/src/api-driven-views/components/api-entity-list/api-entity-list.component.scss
  src/frontend/packages/core/src/api-driven-views/components/api-entity-list/api-entity-list.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/components/api-entity-list/api-entity-list.component.ts
  src/frontend/packages/core/src/api-driven-views/components/api-type-selector/api-entity-type-selector.component.html
  src/frontend/packages/core/src/api-driven-views/components/api-type-selector/api-entity-type-selector.component.scss
  src/frontend/packages/core/src/api-driven-views/components/api-type-selector/api-entity-type-selector.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/components/api-type-selector/api-entity-type-selector.component.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-select-page/api-endpoint-select-page.component.html
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-select-page/api-endpoint-select-page.component.scss
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-select-page/api-endpoint-select-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-select-page/api-endpoint-select-page.component.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.html
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.scss
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.ts
  src/frontend/packages/core/src/api-driven-views/features/api-entity-list-page/api-entity-list-page.component.html
  src/frontend/packages/core/src/api-driven-views/features/api-entity-list-page/api-entity-list-page.component.scss
  src/frontend/packages/core/src/api-driven-views/features/api-entity-list-page/api-entity-list-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-entity-list-page/api-entity-list-page.component.ts
  src/frontend/packages/core/src/api-driven-views/features/api-entity-type-select-page/api-entity-type-select-page.component.html
  src/frontend/packages/core/src/api-driven-views/features/api-entity-type-select-page/api-entity-type-select-page.component.scss
  src/frontend/packages/core/src/api-driven-views/features/api-entity-type-select-page/api-entity-type-select-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-entity-type-select-page/api-entity-type-select-page.component.ts
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.types.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table.types.ts
  src/frontend/packages/core/src/shared/components/list/simple-list/entity-catalogue-datasource.ts
  src/frontend/packages/core/src/shared/components/list/simple-list/simple-list.component.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/core/src/shared/components/tile-selector/tile-selector.component.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/frontend/packages/core/tab-nav.service.ts
Labels: blocked-pr, ready for review

#4020 Release 2.6.1 Release Notes and Version bump
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready for review

#4024 Ingress fix
  CHANGELOG.md
  deploy/kubernetes/build.sh
  deploy/kubernetes/console/templates/__helpers.tpl
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/templates/ingress.yaml
  deploy/kubernetes/console/tests/ingress_test.yaml
  deploy/kubernetes/console/tests/kube_version_test.yaml
Labels: ready for review
