Repository cloudfoundry/stratos, pull requests merged in 2019-10, with the labels that each got.

#3938 Add debug info for manage users e2e tests
  protractor.conf.js
  src/test-e2e/cloud-foundry/users-list-e2e.helper.ts
  src/test-e2e/cloud-foundry/users-removal-e2e.helper.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/helpers/request-helpers.ts
  src/test-e2e/helpers/uaa-helpers.ts
  src/test-e2e/helpers/uaa-request-helpers.ts
Labels: ready for review

#3933 Gate SSO redirect on optional state whitelist
  deploy/kubernetes/console/templates/deployment.yaml
  docs/sso.md
  src/jetstream/auth.go
  src/jetstream/default.config.properties
  src/jetstream/main.go
  src/jetstream/repository/interfaces/structs.go
  src/jetstream/utils.go
Labels: ready for review

#3939 Fix for local user update profile
  .gitignore
  build/tools/mysqldb-dev.sh
  build/tools/postgres-dev.sh
  deploy/db/dbconf.yml
  src/jetstream/datastore/20190930092500_LocalUsersTriggerFix.go
  src/jetstream/default.config.properties
  src/jetstream/repository/localusers/psql_localusers.go
Labels: ready for review

#3947 Fix metrics issue with multiple k8s endpoints
  src/jetstream/plugins/metrics/main.go
Labels: ready for review

#3961 Remove old ingress docs and add new
  deploy/kubernetes/README.md
  deploy/kubernetes/ingress/README.md
  deploy/kubernetes/ingress/ingress.yml
Labels: ready for review

#3899 Fix npm audit vulnerabilities
  package-lock.json
  package.json
Labels: question

#3964 Convert CustomizationsMetadata inject into singleton CustomizationService
  examples/custom-src/frontend/app/custom/acme-login/acme-login.component.ts
  examples/custom-src/frontend/app/custom/app-tab-extension/app-tab-extension.component.ts
  examples/custom-src/frontend/app/custom/custom.module.ts
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/core/core.module.ts
  src/frontend/packages/core/src/core/customizations.types.ts
  src/frontend/packages/core/src/features/about/about-page/about-page.component.ts
  src/frontend/packages/core/src/features/about/about.module.ts
  src/frontend/packages/core/src/features/about/diagnostics-page/diagnostics-page.component.ts
  src/frontend/packages/core/src/features/applications/application-delete/application-delete.component.spec.ts
  src/frontend/packages/core/src/features/applications/applications.module.ts
  src/frontend/packages/core/src/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/packages/core/src/features/cloud-foundry/users/manage-users/cf-roles.service.spec.ts
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.spec.ts
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoints.module.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-event/cf-app-events-config.service.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-instance/cf-app-instances-config.service.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-variables/cf-app-variables-list-config.service.spec.ts
Labels: ready for review

#3967 Endpoint register tiles render priority
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/core/src/base-entity-types.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-base-step/create-endpoint-base-step.component.ts
Labels: in review, ready for review

#3971 Space User Service List: Ensure we're passing the correct params to action builders.
  src/frontend/packages/cloud-foundry/src/entity-action-builders/user-provided-service.action-builders.ts
  src/frontend/packages/cloud-foundry/src/entity-relations/entity-relations.tree.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-user-service-instances-data-source.ts
  src/frontend/packages/core/src/shared/services/cloud-foundry-user-provided-services.service.ts
Labels: ready for review

#3953 Entity catalogue driven lists
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application-wall/application-wall.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/application-wall/application-wall.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue-entity.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.types.ts
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorite-config-mapper.ts
  src/frontend/packages/core/src/shared/components/list/simple-list/entity-catalogue-datasource.ts
  src/frontend/packages/core/src/shared/components/list/simple-list/list-host.directive.ts
  src/frontend/packages/core/src/shared/components/list/simple-list/simple-list.component.html
  src/frontend/packages/core/src/shared/components/list/simple-list/simple-list.component.scss
  src/frontend/packages/core/src/shared/components/list/simple-list/simple-list.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/simple-list/simple-list.component.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/handle-multi-endpoints.pipe.ts
  src/frontend/packages/store/src/entity-request-pipeline/pipeline.types.ts
Labels: ready for review

#3982 Fix self-signed certificate to support Mac OSX 10.15
  deploy/tools/generate_cert.sh
Labels: ready for review

#3983 Fix alignment of user button on newer Firefox
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.scss
Labels: comments-addressed

#3984 Preparation for 2.6.0 Release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready for review

#3980 Fix v2-master references and goreportcard link
  CHANGELOG.md
  README.md
  docs/cf-api-v2-usage.md
  docs/status_updates.md
Labels: ready for review

#3994 Travis update: don't fail if build cache upload fails
  deploy/ci/travis/e2e-build-script.sh
Labels: ready for review

#3986 Fix go mod files
  go.mod
  go.sum
  src/jetstream/go.mod
  src/jetstream/go.sum
  src/jetstream/repository/interfaces/go.mod
  src/jetstream/repository/interfaces/go.sum
Labels: ready for review

#3995 Update references following graduation
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  deploy/ci/automation/helmtest.sh
  deploy/cloud-foundry/README.md
  deploy/kubernetes/README.md
  docs/cf-api-v2-usage.md
  docs/cf-api-v3.md
  docs/contributing.md
  docs/developers-guide.md
  docs/features.md
  docs/planning/services.md
  docs/roadmap.md
  docs/status_updates.md
Labels: ready for review

#4002 E2E Tests: Manage users e2e test improvement
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
Labels: ready for review

#4001 Master sync with v2 master
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  deploy/all-in-one/README.md
  deploy/ci/automation/helmtest.sh
  deploy/cloud-foundry/README.md
  deploy/kubernetes/README.md
  deploy/tools/generate_cert.sh
  docs/access.md
  docs/cf-api-v2-usage.md
  docs/cf-api-v3.md
  docs/contributing.md
  docs/developers-guide.md
  docs/features.md
  docs/planning/services.md
  docs/roadmap.md
  docs/status_updates.md
  package-lock.json
  package.json
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.scss
Labels: ready for review
