Repository cloudfoundry/stratos, pull requests merged in 2019-06, with the labels that each got.

#3593 org/space: allowed quota to be specified on creation/edition
  src/frontend/packages/core/src/core/cf-api.types.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-edit-space-step-base.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.html
  src/frontend/packages/core/src/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.spec.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-space/create-space-step/create-space-step.component.html
  src/frontend/packages/core/src/features/cloud-foundry/add-space/create-space-step/create-space-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.html
  src/frontend/packages/core/src/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.html
  src/frontend/packages/core/src/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/services/cloud-foundry-space-quota.ts
  src/frontend/packages/core/src/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.html
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.html
  src/frontend/packages/core/src/shared/components/cards/card-cf-space-details/card-cf-space-details.component.html
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/actions/organization.actions.ts
  src/frontend/packages/store/src/actions/quota-definitions.actions.ts
  src/frontend/packages/store/src/actions/space.actions.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/start-request.ts
  src/frontend/packages/store/src/reducers/api-request-reducers.generator.ts
  src/frontend/packages/store/src/reducers/organization-quota.reducer.ts
  src/frontend/packages/store/src/reducers/organization-space.reducer.ts
  src/frontend/packages/store/src/reducers/space-quota.reducer.ts
  src/frontend/packages/store/src/types/entity.types.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-page.po.ts
  src/test-e2e/cloud-foundry/cf-level/manage-org-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/org-form-page.po.ts
  src/test-e2e/cloud-foundry/cf-level/org-form-stepper.po.ts
  src/test-e2e/cloud-foundry/org-level/cf-org-level-page.po.ts
  src/test-e2e/cloud-foundry/org-level/mange-space-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/space-form-page.po.ts
  src/test-e2e/cloud-foundry/org-level/space-form-stepper.po.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/helpers/secrets-helpers.ts
  src/test-e2e/po/cf-page.po.ts
Labels: ready for review

#3553 Update to latest version of js-yaml
  package-lock.json
  package.json
Labels: ready for review

#3586 Don't show cell metrics when they're not available
  src/frontend/packages/core/src/core/endpoints.service.spec.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.spec.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cells.component.html
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cells.component.spec.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cells.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
Labels: ready for review

#3595 Add a 'close' button to the notification page
  src/frontend/packages/core/src/features/event-page/events-page/events-page.component.html
  src/frontend/packages/core/src/features/event-page/events-page/events-page.component.ts
Labels: ready for review

#3596 Handle endpoint types that do no support connect
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint.component.html
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint.component.ts
  src/frontend/packages/store/src/effects/endpoint.effects.ts
Labels: ready for review

#3599 Fix stepper height on Chrome pre v72 & Bleeding of error style in stateful-icon
  src/frontend/packages/core/src/core/stateful-icon/stateful-icon.component.theme.scss
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.scss
Labels: ready for review

#3600 Improve failed connection message for cf & metrics endpoints
  src/jetstream/auth.go
  src/jetstream/plugins/metrics/main.go
Labels: ready for review

#3601 Fix missing org/space in cell app instances list
  src/frontend/packages/core/src/shared/components/list/list-types/cf-cell-apps/cf-cell-apps-list-config.service.ts
Labels: ready for review

#3629 Updates to base images
  deploy/stratos-base-images/Dockerfile.stratos-base.tmpl
  deploy/stratos-base-images/Dockerfile.stratos-ruby-build-base.tmpl
  deploy/stratos-base-images/build-base-images.sh
  deploy/stratos-base-images/install-ruby.sh
Labels: ready for review

#3634 Quick fix for failing e2e test
  src/test-e2e/helpers/cf-helpers.ts
Labels: ready for review

#3484 Added "remove from x" item from user's action menu
  deploy/tools/init-cf-for-e2e.sh
  src/frontend/packages/core/src/features/cloud-foundry/cf.helpers.ts
  src/frontend/packages/core/src/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/packages/core/src/features/cloud-foundry/cloud-foundry.routing.ts
  src/frontend/packages/core/src/features/cloud-foundry/users/manage-users/cf-roles.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/users/manage-users/manage-users-confirm/manage-users-confirm.component.html
  src/frontend/packages/core/src/features/cloud-foundry/users/manage-users/manage-users-confirm/manage-users-confirm.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/users/manage-users/manage-users-modify/manage-users-modify.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/users/remove-user/remove-user.component.html
  src/frontend/packages/core/src/features/cloud-foundry/users/remove-user/remove-user.component.scss
  src/frontend/packages/core/src/features/cloud-foundry/users/remove-user/remove-user.component.spec.ts
  src/frontend/packages/core/src/features/cloud-foundry/users/remove-user/remove-user.component.ts
  src/frontend/packages/core/src/shared/components/cf-role-checkbox/cf-role-checkbox.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users-org-space-roles/cf-users-space-roles-data-source.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users-org-space-roles/table-cell-org-space-role/table-cell-org-space-role.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users-org-space-roles/table-cell-select-org/table-cell-select-org.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users-org-space-roles/table-cell-select-org/table-cell-select-org.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/packages/core/src/shared/data-services/cf-user.service.ts
  src/frontend/packages/store/src/actions/users-roles.actions.ts
  src/frontend/packages/store/src/reducers/users-roles.reducer.ts
  src/frontend/packages/store/src/types/user.types.ts
  src/frontend/packages/store/src/types/users-roles.types.ts
  src/test-e2e/cloud-foundry/cf-level/cf-users-removal-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/org-users-removal-e2e.spec.ts
  src/test-e2e/cloud-foundry/remove-users-page.po.ts
  src/test-e2e/cloud-foundry/space-level/space-users-removal-e2e.spec.ts
  src/test-e2e/cloud-foundry/users-removal-e2e.helper.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/secrets.yaml.example
Labels: ready for review

#3591 Differentiate Disconnected Endpoint Cards
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.scss
Labels: in review

#3597 Show header in none dashboard pages
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.html
  src/frontend/packages/core/src/features/no-endpoints-non-admin/no-endpoints-non-admin.component.html
  src/frontend/packages/core/src/features/no-endpoints-non-admin/no-endpoints-non-admin.component.ts
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.module.ts
  src/frontend/packages/core/src/shared/components/page-header/show-page-header/show-page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/show-page-header/show-page-header.component.scss
  src/frontend/packages/core/src/shared/components/page-header/show-page-header/show-page-header.component.spec.ts
  src/frontend/packages/core/src/shared/components/page-header/show-page-header/show-page-header.component.ts
Labels: in review

#3646 Disable top level remove user tests to unblock pr's
  src/test-e2e/cloud-foundry/cf-level/cf-users-removal-e2e.spec.ts
Labels: ready for review

#3652 Remove ZenHub references from docs
  .cf-extensions
  README.md
  docs/roadmap.md
Labels: ready for review

#3644 E2E Tests: Update cleanup script to remove test users
  deploy/ci/automation/e2e-clean-remnants.sh
Labels: ready for review

#3638 Helm Chart: Add imagelist to the helm chart
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/kubernetes/build.sh
  deploy/kubernetes/imagelist-gen.sh
  deploy/kubernetes/imagelist.values.yaml
Labels: ready for review

#3648 Get default stack from the Stacks API
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-view-e2e.spec.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/helpers/cf-request-helpers.ts
Labels: ready for review

#3637 Allow appVersion in helm chart to be set to a product version
  deploy/ci/tasks/dev-releases/create-chart-helper.sh
  deploy/ci/tasks/dev-releases/create-chart.yml
Labels: ready for review

#3651 Add e2e uaa helpers, use to create/delete user for remove roles tests
  src/test-e2e/cloud-foundry/cf-level/cf-users-removal-e2e.spec.ts
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/org-users-removal-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-users-removal-e2e.spec.ts
  src/test-e2e/cloud-foundry/users-list-e2e.helper.ts
  src/test-e2e/cloud-foundry/users-removal-e2e.helper.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/helpers/request-helpers.ts
  src/test-e2e/helpers/secrets-helpers.ts
  src/test-e2e/helpers/uaa-helpers.ts
  src/test-e2e/helpers/uaa-request-helpers.ts
  src/test-e2e/po/list.po.ts
  src/test-e2e/secrets.yaml.example
Labels: ready for review

#3635 Support separate auth and token endpoints for the console
  src/jetstream/auth.go
  src/jetstream/datastore/20190515133200_AuthEndpoint.go
  src/jetstream/main.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/repository/console_config/psql_console_config.go
  src/jetstream/repository/interfaces/structs.go
  src/jetstream/setup_console.go
Labels: ready for review

#3382 Invite user e2e tests
  .travis.yml
  deploy/ci/travis/config.properties
  deploy/ci/travis/job-e2e-before_script.sh
  deploy/tools/init-cf-for-e2e.sh
  protractor.conf.js
  src/frontend/packages/core/src/shared/components/stacked-input-actions/stacked-input-action/stacked-input-action.component.html
  src/test-e2e/cloud-foundry/cf-level/cf-invite-config-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-page.po.ts
  src/test-e2e/cloud-foundry/cf-level/config-invite-client-dialog.po.ts
  src/test-e2e/cloud-foundry/invite-users-e2e.helper.ts
  src/test-e2e/cloud-foundry/org-level/org-invite-user-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-invite-user-e2e.spec.ts
  src/test-e2e/cloud-foundry/users-removal-e2e.helper.ts
  src/test-e2e/e2e.types.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/helpers/extend-test-helpers.ts
  src/test-e2e/helpers/uaa-helpers.ts
  src/test-e2e/helpers/uaa-request-helpers.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/po/cf-users-list.po.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/form.po.ts
  src/test-e2e/po/invite-users-stepper.po.ts
  src/test-e2e/po/stacked-input-actions.po.ts
  src/test-e2e/secrets.yaml.example
Labels: ready for review

#3660 Remove unused users.effetct.ts
  src/frontend/packages/store/src/effects/users.effects.ts
Labels: ready for review

#3666 Ensure we're not looking at production version of env file
  src/frontend/packages/core/src/main.ts
Labels: bug, in review, ready for review

#3669 Entity catalogue: Create selectors that work with entityKeys
  src/frontend/packages/cloud-foundry/src/selectors/api.selectors.ts
  src/frontend/packages/cloud-foundry/src/selectors/pagination.selectors.ts
  src/frontend/packages/core/src/core/entity-service.ts
  src/frontend/packages/core/src/features/applications/application.service.ts
  src/frontend/packages/core/src/features/applications/create-application/create-application-step3/create-application-step3.component.ts
  src/frontend/packages/core/src/features/applications/create-application/create-application.component.ts
  src/frontend/packages/core/src/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/packages/core/src/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-edit-space-step-base.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-space/create-space-step/create-space-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/cf.helpers.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/users/manage-users/manage-users-confirm/manage-users-confirm.component.ts
  src/frontend/packages/core/src/features/endpoints/connect.service.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users-org-space-roles/cf-users-space-roles-data-source.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users/cf-space-permission-cell/cf-space-permission-cell.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/github-commits/github-commits-list-config-app-tab.service.ts
  src/frontend/packages/core/src/shared/components/markdown-preview/markdown-preview.component.ts
  src/frontend/packages/core/src/shared/data-services/cf-org-space-service.service.ts
  src/frontend/packages/core/src/shared/monitors/entity-monitor.ts
  src/frontend/packages/core/src/shared/services/cf-org-space-label.service.ts
  src/frontend/packages/core/src/shared/services/cloud-foundry-user-provided-services.service.ts
  src/frontend/packages/store/src/selectors/api.selectors.ts
  src/frontend/packages/store/src/selectors/pagination.selectors.ts
Labels: entity-catalogue
