Repository cloudfoundry/stratos, pull requests merged in 2019-01, with the labels that each got.

#3251 Make the table multi actions more obvious
  src/frontend/app/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.html
  src/frontend/app/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.scss
  src/frontend/app/shared/components/list/list.component.types.ts
  src/test-e2e/po/list.po.ts
Labels: ready for review

#3301 Ensure an empty errorResponse gets picked up as a jetstream error
  src/frontend/app/core/jetstream.helpers.ts
Labels: ready for review

#3249 Use SHA256 to compare SSH public key fingerprint
  src/jetstream/plugins/cfappssh/app_ssh.go
Labels: ready for review

#3302 Minor v2/v3 cf api docus updates
  docs/cf-api-v2-usage.md
  docs/cf-api-v3.md
Labels: ready for review

#3050 Feature json schema
  package-lock.json
  package.json
  src/frontend/app/core/cf-api-svc.types.ts
  src/frontend/app/core/utils.service.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.html
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.html
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.scss
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.html
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.scss
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/shared/components/application-state/application-state-icon/application-state-icon.component.ts
  src/frontend/app/shared/components/schema-form/schema-form.component.html
  src/frontend/app/shared/components/schema-form/schema-form.component.scss
  src/frontend/app/shared/components/schema-form/schema-form.component.spec.ts
  src/frontend/app/shared/components/schema-form/schema-form.component.theme.scss
  src/frontend/app/shared/components/schema-form/schema-form.component.ts
  src/frontend/app/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#3270 List Multifilter Improvements
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.spec.ts
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
  src/test-e2e/applications/application-wall-e2e.spec.ts
  src/test-e2e/applications/applications.po.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/helpers/secrets-helpers.ts
  src/test-e2e/marketplace/marketplace-e2e.spec.ts
  src/test-e2e/marketplace/marketplace.po.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
  src/test-e2e/marketplace/services-wall.po.ts
  src/test-e2e/po/list.po.ts
Labels: ready for review

#3293 User-Provided Service Instance example, better migration error message
  deploy/cloud-foundry/db-migration/README.md
  src/jetstream/datastore/datastore_migrator.go
  src/jetstream/migrator.go
Labels: community, needs attention

#3295 Improvements for running automated tests
  deploy/ci/automation/cfdockercomposetest.sh
  deploy/ci/automation/cfpushtest.sh
  deploy/ci/automation/cfutils.sh
  deploy/ci/automation/check-stratos.sh
Labels: ready for review

#3286 Env Var fix & improvements
  src/frontend/app/shared/components/list/list-table/table-cell-edit/table-cell-edit.component.html
  src/frontend/app/shared/components/list/list-types/app-variables/cf-app-variables-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/list/list.component.types.ts
  src/frontend/app/store/effects/app.effects.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-view-e2e.spec.ts
  src/test-e2e/application/po/application-page-variables.po.ts
  src/test-e2e/po/list.po.ts
Labels: ready for review

#3296 Validate entity names locally
  src/frontend/app/features/applications/create-application/create-application-step3/create-application-step3.component.html
  src/frontend/app/features/applications/create-application/create-application-step3/create-application-step3.component.ts
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.html
  src/frontend/app/features/applications/routes/add-routes/add-routes.component.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.html
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
Labels: ready for review

#3275 Add service plan list to service pages
  src/frontend/app/core/cf-api-svc.types.ts
  src/frontend/app/core/utils.service.ts
  src/frontend/app/features/applications/application/application-base.component.spec.ts
  src/frontend/app/features/cloud-foundry/cloud-foundry/cloud-foundry.component.spec.ts
  src/frontend/app/features/service-catalog/service-catalog.routing.ts
  src/frontend/app/features/service-catalog/service-plans/service-plans.component.html
  src/frontend/app/features/service-catalog/service-plans/service-plans.component.spec.ts
  src/frontend/app/features/service-catalog/service-plans/service-plans.component.ts
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.html
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.spec.ts
  src/frontend/app/features/service-catalog/service-summary/service-summary.component.ts
  src/frontend/app/features/service-catalog/service-tabs-base/service-tabs-base.component.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/features/service-catalog/services.service.mock.ts
  src/frontend/app/features/service-catalog/services.service.ts
  src/frontend/app/shared/components/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/bind-apps-step/bind-apps-step.component.ts
  src/frontend/app/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.html
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.scss
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.spec.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/app/shared/components/cards/compact-service-instance-card/compact-service-instance-card.component.spec.ts
  src/frontend/app/shared/components/list/list-table/table-cell/table-cell.component.spec.ts
  src/frontend/app/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/app/shared/components/list/list-table/table.component.scss
  src/frontend/app/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.ts
  src/frontend/app/shared/components/list/list-types/service-plans/service-plans-data-source.ts
  src/frontend/app/shared/components/list/list-types/service-plans/service-plans-list-config.service.spec.ts
  src/frontend/app/shared/components/list/list-types/service-plans/service-plans-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-extras/table-cell-service-plan-extras.component.html
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-extras/table-cell-service-plan-extras.component.scss
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-extras/table-cell-service-plan-extras.component.spec.ts
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-extras/table-cell-service-plan-extras.component.ts
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-price/table-cell-service-plan-price.component.html
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-price/table-cell-service-plan-price.component.scss
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-price/table-cell-service-plan-price.component.spec.ts
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-price/table-cell-service-plan-price.component.ts
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-public/table-cell-service-plan-public.component.html
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-public/table-cell-service-plan-public.component.scss
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-public/table-cell-service-plan-public.component.spec.ts
  src/frontend/app/shared/components/list/list-types/service-plans/table-cell-service-plan-public/table-cell-service-plan-public.component.ts
  src/frontend/app/shared/components/metadata-item/metadata-item.component.ts
  src/frontend/app/shared/components/service-plan-price/service-plan-price.component.html
  src/frontend/app/shared/components/service-plan-price/service-plan-price.component.scss
  src/frontend/app/shared/components/service-plan-price/service-plan-price.component.spec.ts
  src/frontend/app/shared/components/service-plan-price/service-plan-price.component.ts
  src/frontend/app/shared/components/service-plan-public/service-plan-public.component.html
  src/frontend/app/shared/components/service-plan-public/service-plan-public.component.scss
  src/frontend/app/shared/components/service-plan-public/service-plan-public.component.spec.ts
  src/frontend/app/shared/components/service-plan-public/service-plan-public.component.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/service.actions.ts
  src/frontend/app/store/reducers/create-service-instance.reducer.ts
  src/frontend/app/store/types/create-service-instance.types.ts
  src/frontend/app/test-framework/cloud-foundry-endpoint-service.helper.ts
  src/frontend/app/test-framework/store-test-helper.ts
Labels: ready for review

#3264 Helm port configuration improvements and unit tests
  .travis.yml
  deploy/ci/travis/helm-chart-unit-tests.sh
  deploy/kubernetes/README.md
  deploy/kubernetes/console/.helmignore
  deploy/kubernetes/console/templates/__helpers.tpl
  deploy/kubernetes/console/templates/service.yaml
  deploy/kubernetes/console/tests/service_test.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#2961 Limit lists to a certain number of entities
  src/frontend/app/core/leaveEnterAngularZone.ts
  src/frontend/app/core/utils.service.ts
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-pagination-controller.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-filtering-sorting.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-list-controller.ts
  src/frontend/app/shared/components/list/list-table/table.types.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/app/cf-apps-data-source.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.spec.ts
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/monitors/internal-event.monitor.ts
  src/frontend/app/store/actions/application.actions.ts
  src/frontend/app/store/actions/pagination.actions.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/effects/pagination.effects.ts
  src/frontend/app/store/effects/permissions.effect.ts
  src/frontend/app/store/helpers/paginated-request-helpers.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-max-reached.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-set-params.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/app/store/types/pagination.types.ts
  src/test-e2e/e2e.ts
  src/test-e2e/helpers/reset-helpers.ts
  src/test-e2e/po/page.po.ts
Labels: ready for review

#3306 Fix auto select of single items in multi filter list
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/components/list/list.component.types.ts
Labels: ready for review

#3212 Scalability: Handle large number of apps in cf dashboards
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.scss
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.scss
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-users/cloud-foundry-organization-users.component.spec.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.scss
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.ts
  src/frontend/app/shared/components/cards/card-cf-recent-apps/card-cf-recent-apps.component.html
  src/frontend/app/shared/components/cards/card-cf-recent-apps/card-cf-recent-apps.component.spec.ts
  src/frontend/app/shared/components/cards/card-cf-recent-apps/card-cf-recent-apps.component.ts
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.ts
  src/frontend/app/shared/components/list/list-types/app/cf-apps-data-source.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-spaces-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-spaces-list-config.service.ts
  src/frontend/app/shared/components/loading-page/loading-page.component.scss
  src/frontend/app/store/actions/application.actions.ts
  src/frontend/app/store/effects/api.effects.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/app/test-framework/cloud-foundry-organization.service.mock.ts
  src/frontend/app/test-framework/cloud-foundry-space.service.mock.ts
  src/frontend/app/test-framework/user-service-helper.ts
  src/test-e2e/marketplace/marketplace-create-service-instances-e2e.spec.ts
Labels: ready for review

#3213 Show refresh button for latest modified application lists
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.html
  src/frontend/app/shared/components/cards/card-cf-recent-apps/card-cf-recent-apps.component.html
  src/frontend/app/shared/components/cards/card-cf-recent-apps/card-cf-recent-apps.component.scss
  src/frontend/app/shared/components/cards/card-cf-recent-apps/card-cf-recent-apps.component.ts
Labels: ready for review

#3202 Support prometheus-boshrelease as a metrics endpoint
  docs/bosh-metrics.md
  package-lock.json
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/features/endpoints/connect-endpoint-dialog/auth-forms/none-auth-form.component.html
  src/frontend/app/features/endpoints/connect-endpoint-dialog/auth-forms/none-auth-form.component.scss
  src/frontend/app/features/endpoints/connect-endpoint-dialog/auth-forms/none-auth-form.component.ts
  src/frontend/app/features/endpoints/endpoint-helpers.ts
  src/frontend/app/features/endpoints/endpoints.module.ts
  src/frontend/app/features/metrics/metrics/metrics.component.html
  src/frontend/app/features/metrics/metrics/metrics.component.scss
  src/frontend/app/store/types/endpoint.types.ts
  src/jetstream/plugins/metrics/cloud_foundry.go
  src/jetstream/plugins/metrics/main.go
  src/jetstream/repository/interfaces/structs.go
Labels: ready for review

#3265 Add Org and Space status bar to Org/Space Cards
  src/frontend/app/core/cf-api.types.ts
  src/frontend/app/core/cf.helpers.ts
  src/frontend/app/core/utils.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-org-space-quota.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization-quota.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space-quota.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-summary/cloud-foundry-cell-summary.component.ts
  src/frontend/app/features/service-catalog/services-helper.ts
  src/frontend/app/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/app/shared/components/application-state/application-state-icon/application-state-icon.component.ts
  src/frontend/app/shared/components/application-state/application-state.component.ts
  src/frontend/app/shared/components/application-state/application-state.service.ts
  src/frontend/app/shared/components/cards/card-app-instances/card-app-instances.component.ts
  src/frontend/app/shared/components/cards/card-app-status/card-app-status.component.ts
  src/frontend/app/shared/components/cards/card-app-usage/card-app-usage.component.ts
  src/frontend/app/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.html
  src/frontend/app/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.spec.ts
  src/frontend/app/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.ts
  src/frontend/app/shared/components/cards/card-cf-recent-apps/compact-app-card/compact-app-card.component.ts
  src/frontend/app/shared/components/cards/card-cf-space-details/card-cf-space-details.component.html
  src/frontend/app/shared/components/cards/card-cf-space-details/card-cf-space-details.component.spec.ts
  src/frontend/app/shared/components/cards/card-number-metric/card-number-metric.component.ts
  src/frontend/app/shared/components/cards/card-status/card-status.component.ts
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.html
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.scss
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/app/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/app/shared/components/list/list-types/cf-endpoints/cf-endpoint-card/endpoint-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-orgs-list-config.service.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/components/service-plan-public/service-plan-public.component.ts
  src/frontend/app/shared/shared.types.ts
Labels: ready for review

#3312 Fix nightly helm chart pipeline
  deploy/ci/tasks/dev-releases/create-chart-helper.sh
  deploy/ci/tasks/dev-releases/create-nightly-chart.yml
Labels: ready for review

#3294 Deploying Stratos as a CF App using docker image
  deploy/cloud-foundry/README.md
  manifest-docker.yml
Labels: blocked, community

#3314 Tweak cf push instructions
  deploy/cloud-foundry/README.md
Labels: ready for review

#3316 Helm Chart Upgrade fix
  deploy/ci/automation/helmtest.sh
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/templates/service.yaml
Labels: ready for review

#3317 Fix issues with automated helm test
  deploy/ci/automation/helmtest.sh
Labels: ready for review

#3321 Reduce weight of nav logo
  src/frontend/misc/custom/nav-logo.png
Labels: ready for review

#3315 Route & Card icon fixes
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.html
  src/frontend/app/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.scss
  src/frontend/app/shared/components/list/list-types/cf-routes/table-cell-route/table-cell-route.component.html
  src/test-e2e/application/application-routes-e2e.spec.ts
Labels: ready for review

#3354 Fix manager users space table search & improve 'too many x' text
  src/frontend/app/features/applications/application-wall/application-wall.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-routes/cloud-foundry-routes.component.html
  src/frontend/app/shared/components/list/list-types/cf-users-org-space-roles/cf-users-space-roles-data-source.service.ts
  src/frontend/app/shared/components/list/list-types/cf-users-org-space-roles/cf-users-space-roles-list-config.service.ts
  src/frontend/app/shared/components/list/list.component.html
Labels: ready for review

#3351 Fix null exception after creating a space in an new org
  src/frontend/app/core/cf-api.types.ts
  src/frontend/app/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/store/reducers/organization-space.reducer.ts
Labels: in review

#3358 Fix filter panel size on services and marketplace pages
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.html
  src/frontend/app/features/service-catalog/service-catalog-page/service-catalog-page.component.theme.scss
  src/frontend/app/features/services/services-wall/services-wall.component.html
  src/frontend/app/features/services/services-wall/services-wall.component.theme.scss
  src/frontend/sass/_all-theme.scss
Labels: ready for review

#3352 Manually make the date selector date a moment object
  src/frontend/app/shared/components/date-time/date-time.component.ts
Labels: in review, ready for review

#3353 Ensure the SCM type is included in store keys
  src/frontend/app/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/app/features/applications/application/application-tabs-base/tabs/gitscm-tab/gitscm-tab.component.ts
  src/frontend/app/shared/components/list/list-types/github-commits/github-commits-list-config-app-tab.service.ts
  src/frontend/app/shared/components/list/list-types/github-commits/github-commits-list-config-base.service.ts
  src/frontend/app/store/effects/deploy-app.effects.ts
  src/frontend/app/store/effects/github.effects.ts
Labels: in review, ready for review

#3361 Fix precision in display of percent tooltip on metrics chart
  src/frontend/app/features/applications/application/application-tabs-base/tabs/metrics-tab/metrics-tab.component.ts
  src/frontend/app/shared/components/metrics-chart/metrics.component.helpers.ts
Labels: ready for review

#3350 Fix app state to allow start action for offline while updating
  src/frontend/app/shared/components/application-state/application-state.service.spec.ts
  src/frontend/app/shared/components/application-state/application-state.service.ts
Labels: in review, ready for review

#3356 About Page Title customization support
  src/frontend/app/core/customizations.types.ts
  src/frontend/app/features/about/about-page/about-page.component.html
  src/frontend/app/features/about/about-page/about-page.component.ts
  src/frontend/app/features/about/diagnostics-page/diagnostics-page.component.html
  src/frontend/app/shared/components/stratos-title/stratos-title.component.html
  src/frontend/app/shared/components/stratos-title/stratos-title.component.ts
Labels: in review, ready for review

#3313 Fixes double requests when single cf connected for lists with cf filter
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/app/shared/components/list/list-types/app/cf-apps-data-source.ts
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/shared/data-services/cf-org-space-service.service.ts
  src/frontend/app/store/actions/application.actions.ts
  src/test-e2e/application/application-delete-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/applications/application-wall-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/org-spaces-e2e.spec.ts
  src/test-e2e/cloud-foundry/organizations-spaces-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-routes-e2e.spec.ts
  src/test-e2e/cloud-foundry/users-list-e2e.helper.ts
  src/test-e2e/helpers/cf-helpers.ts
  src/test-e2e/po/list.po.ts
Labels: ready for review

#3348 Fix CF-Level Metrics permissions check
  src/frontend/app/shared/components/list/list-types/cf-cells/cf-cells-data-source.ts
  src/frontend/app/store/actions/metrics.actions.ts
  src/jetstream/middleware.go
  src/jetstream/plugins/metrics/cloud_foundry.go
  src/jetstream/plugins/metrics/main.go
Labels: ready for review

#3360 Fix fetching of stats in app wall for some cases when list is maxed
  src/frontend/app/shared/components/list/list-types/app/cf-apps-data-source.ts
Labels: ready for review

#3363 Ensure the loading indicator and the refresh button animated at the correct time.
  src/frontend/app/shared/components/list/list.component.html
  src/frontend/app/shared/components/list/list.component.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-create-pagination.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-set-client-page-size.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-set-client-page.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-set-result-count.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-success.ts
Labels: ready for review

#3364 Change log for 2.3.0
  CHANGELOG.md
Labels: ready for review

#3365 Weekly update
  docs/status_updates.md
Labels: ready for review

#3366 Fix for bug causing intermittment E2E Test failures on org tests
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
Labels: ready for review

#3368 Only prevent copy & paste in confirm dialog for production
  src/frontend/app/shared/components/dialog-confirm/dialog-confirm.component.html
  src/frontend/app/shared/components/dialog-confirm/dialog-confirm.component.ts
Labels: ready for review

#3373 v2/v3 api docs updates
  docs/cf-api-v2-usage.md
  docs/cf-api-v3.md
Labels: ready for review

#3370 Improve handling of maxed state and observables
  src/frontend/app/features/cloud-foundry/cf.helpers.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-org-space-quota.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/app/features/cloud-foundry/services/cloud-foundry-space.service.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.ts
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.html
  src/frontend/app/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.ts
  src/frontend/app/shared/components/cards/card-cf-recent-apps/card-cf-recent-apps.component.html
  src/frontend/app/shared/components/cards/card-cf-usage/card-cf-usage.component.html
  src/frontend/app/shared/components/cards/card-cf-usage/card-cf-usage.component.scss
  src/frontend/app/shared/components/cards/card-cf-usage/card-cf-usage.component.spec.ts
  src/frontend/app/shared/components/cards/card-cf-usage/card-cf-usage.component.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/app/shared/components/list/data-sources-controllers/list-pagination-controller.ts
  src/frontend/app/shared/components/list/data-sources-controllers/local-list-controller.ts
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.html
  src/frontend/app/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/app/shared/data-services/cf-user.service.ts
  src/frontend/app/shared/monitors/pagination-monitor.ts
  src/frontend/app/shared/shared.module.ts
  src/frontend/app/store/actions/pagination.actions.ts
  src/frontend/app/store/helpers/paginated-request-helpers.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer-max-reached.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/app/store/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/app/store/types/pagination.types.ts
Labels: in review, ready for review

#3369 Fix helm repo link when geneating an RC
  deploy/ci/tasks/dev-releases/create-chart.yml
Labels: ready for review
