Repository cloudfoundry/stratos, pull requests merged in 2019-09, with the labels that each got.

#3803 Fix minor issues on v3-master
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/cf-roles.service.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/manage-users-confirm/manage-users-confirm.component.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-org-space-service.service.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.types.ts
  src/frontend/packages/store/src/actions/pagination.actions.ts
  src/frontend/packages/store/src/effects/users-roles.effects.ts
  src/frontend/packages/store/src/helpers/schema-tree-traverse.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination.reducer.ts
Labels: in review, ready for review

#3817 Autoscaler updates following UX review
  src/frontend/packages/cf-autoscaler/src/core/autoscaler-helpers/autoscaler-available.ts
  src/frontend/packages/cf-autoscaler/src/core/autoscaler-helpers/autoscaler-util.ts
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.html
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.scss
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-service.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step1/edit-autoscaler-policy-step1.component.html
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step2/edit-autoscaler-policy-step2.component.html
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step2/edit-autoscaler-policy-step2.component.scss
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step2/edit-autoscaler-policy-step2.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step3/edit-autoscaler-policy-step3.component.html
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step4/edit-autoscaler-policy-step4.component.html
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step4/edit-autoscaler-policy-step4.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy.component.html
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy.component.scss
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy.component.ts
  src/frontend/packages/cf-autoscaler/src/shared/card-autoscaler-default/card-autoscaler-default.component.html
  src/frontend/packages/cf-autoscaler/src/shared/card-autoscaler-default/card-autoscaler-default.component.scss
  src/frontend/packages/cf-autoscaler/src/store/app-autoscaler.actions.ts
  src/frontend/packages/cf-autoscaler/src/store/app-autoscaler.types.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler.effects.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler.store.module.ts
  src/frontend/packages/core/src/shared/components/cards/card-cf-info/card-cf-info.component.html
  src/frontend/packages/core/src/shared/components/cards/card-cf-info/card-cf-info.component.ts
  src/jetstream/plugins/autoscaler/autoscaler.go
  src/jetstream/plugins/autoscaler/main.go
Labels: ready for review

#3824 Handle autoscaler errors better
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.scss
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step4/edit-autoscaler-policy-step4.component.ts
  src/frontend/packages/cf-autoscaler/src/store/app-autoscaler.actions.ts
Labels: ready for review

#3832 Entity pipeline minor changes
  src/frontend/packages/cf-autoscaler/src/cf-autoscaler-testing.module.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/cloud-foundry-test.module.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-feature-flags/table-cell-feature-flag-state/table-cell-feature-flag-state.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-space-name/table-cell-space-name.component.spec.ts
  src/frontend/packages/cloud-foundry/src/store/effects/permissions.effect.ts
  src/frontend/packages/core/src/core/entity-service.spec.ts
  src/frontend/packages/core/test-framework/core-test.modules.ts
  src/frontend/packages/store/src/effects/old-api.effects.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/fail-entity-request.handler.spec.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/fail-entity-request.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/handle-multi-endpoints.pipe.spec.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/merge-multi-endpoint-data.pipe.spec.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/start-entity-request.handler.spec.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/current-user-roles.reducer.spec.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-remove-params.ts
Labels: extension-phase-2, extensions, extensions-store, in review, ready for review

#3823 Use getEntityKey instead of buildEntityKey
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-users/cf-user-list-config.service.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue-entity.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/local-list.helpers.ts
  src/frontend/packages/core/src/shared/monitors/pagination-monitor.ts
  src/frontend/packages/core/src/shared/services/cf-org-space-label.service.ts
  src/frontend/packages/core/test-framework/store-test-helper.ts
  src/frontend/packages/store/src/effects/endpoint.effects.ts
  src/frontend/packages/store/src/helpers/entity-schema.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-clear-pagination-of-entity.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-create-pagination.spec.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-create-pagination.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-reset-pagination.ts
  src/frontend/packages/store/src/selectors/api.selectors.ts
  src/frontend/packages/store/src/selectors/endpoint.selectors.ts
Labels: extensions, ready for review

#3842 Create new populate cf script for 2019 summit
  deploy/tools/populate-cf/cf-summit-eu-2019.sh
Labels: ready for review

#3886 Fix two autoscaler bugs
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-base-step.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step1/edit-autoscaler-policy-step1.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step2/edit-autoscaler-policy-step2.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step3/edit-autoscaler-policy-step3.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step4/edit-autoscaler-policy-step4.component.ts
  src/frontend/packages/cf-autoscaler/src/store/app-autoscaler.actions.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler.effects.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/request-helpers.ts
Labels: ready for review

#3879 Fix several service related bugs, some related to space scoped services
  src/frontend/packages/core/src/features/service-catalog/service-summary/service-summary.component.spec.ts
  src/frontend/packages/core/src/features/service-catalog/service-tabs-base/service-tabs-base.component.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/packages/core/src/shared/components/cards/service-broker-card/service-broker-card.component.html
  src/frontend/packages/core/src/shared/components/cards/service-broker-card/service-broker-card.component.ts
  src/frontend/packages/core/src/shared/components/cards/service-recent-instances-card/service-recent-instances-card.component.spec.ts
  src/frontend/packages/core/src/shared/components/cards/service-summary-card/service-summary-card.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-services/cf-user-service-instances-list-config.ts
  src/frontend/packages/core/src/shared/components/list/list-types/service-instances/service-instances-data-source.ts
  src/frontend/packages/core/src/shared/components/schema-form/schema-form.component.scss
  src/frontend/packages/core/src/shared/data-services/service-action-helper.service.ts
Labels: ready for review

#3844 spaces: fixed deletion in summary subheader
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-page.po.ts
Labels: ready for review

#3834 Fix unmape route action type
  src/frontend/packages/cloud-foundry/src/actions/route.actions.ts
  src/frontend/packages/core/src/core/entity-catalogue/action-dispatcher/action-dispatcher.ts
  src/frontend/packages/core/src/core/entity-catalogue/action-orchestrator/action-orchestrator.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue-entity.ts
  src/frontend/packages/core/src/core/entity-service.ts
  src/frontend/packages/store/src/effects/recursive-entity-delete.effect.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/endpoint-errors.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/fail-entity-request.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/start-entity-request.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/success-entity-request.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-pipeline.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/request-helpers.ts
Labels: extensions, ready for review

#3773 Reduce running time of `fullMinusLongSuite` e2e job
  .travis.yml
  protractor.conf.js
Labels: ready for review

#3900 Fix endpoint unregister
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/store/src/reducers/api-request-data-reducer/request-data-reducer.factory.ts
Labels: bug, extensions, ready for review

#3898 Fix cf url validation
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
Labels: bug, extensions, ready for review

#3894 E2E Test should run as user not admin
  src/test-e2e/cloud-foundry/space-level/cf-space-level-e2e.spec.ts
Labels: ready for review

#3890 Ensure stepper buttons are always visible and content scrolls
  src/frontend/packages/core/src/shared/components/stepper/steppers/steppers.component.scss
Labels: ready for review

#3888 Fix setup detection for local users
  src/jetstream/repository/interfaces/structs.go
Labels: ready for review

#3889 E2E: Add fix to wait until delete indicator has been removed
  src/test-e2e/cloud-foundry/cf-level/manage-quota-e2e.spec.ts
Labels: ready for review

#3883 Add support for view and edit profile for local user
  src/frontend/packages/core/src/features/user-profile/edit-profile-info/edit-profile-info.component.html
  src/frontend/packages/core/src/features/user-profile/edit-profile-info/edit-profile-info.component.ts
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.html
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.ts
  src/frontend/packages/core/src/shared/components/user-profile-banner/user-profile-banner.component.html
  src/frontend/packages/core/src/shared/components/user-profile-banner/user-profile-banner.component.ts
  src/frontend/packages/store/src/effects/user-profile.effects.ts
  src/jetstream/auth.go
  src/jetstream/datastore/20190918092300_LocalUsersUpdates.go
  src/jetstream/plugins/userinfo/local_user.go
  src/jetstream/plugins/userinfo/main.go
  src/jetstream/plugins/userinfo/types.go
  src/jetstream/plugins/userinfo/uaa_user.go
  src/jetstream/repository/interfaces/localuser.go
  src/jetstream/repository/localusers/psql_localusers.go
  src/jetstream/setup_console.go
Labels: in review, ready for review

#3892 Ensure MB is only shown for memory based quota values in edit quota forms
  src/frontend/packages/core/src/shared/components/unlimited-input/unlimited-input.component.html
Labels: ready for review

#3902 Tests: Improve user clean up
  deploy/ci/automation/e2e-clean-remnants.sh
Labels: ready for review

#3901 Travis: Build once and share build in e2e tests
  .travis.yml
  deploy/ci/travis/e2e-build-script.sh
  deploy/ci/travis/e2e-mc-helper.sh
  deploy/ci/travis/run-e2e-tests.sh
  deploy/ci/travis/upload-e2e-test-report.sh
Labels: ready for review

#3913 Fix two actionBuilder params issues
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-org-space-service.service.ts
  src/frontend/packages/store/src/entity-request-pipeline/base-single-entity-request.pipeline.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-pagination-request-pipeline.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/make-request-entity-request.pipe.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-pipeline.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-pipeline.types.ts
  src/frontend/packages/store/src/entity-request-pipeline/pagination-request-base-handlers/pagination-iterator.pipe.ts
  src/frontend/packages/store/src/entity-request-pipeline/pipline-http-client.service.ts
  src/frontend/packages/store/src/selectors/endpoint.selectors.ts
Labels: blocked-pr, ready for review

#3912 Ensure multi endpoint requests only go out to connected/unconnectable endpoints
  src/frontend/packages/store/src/entity-request-pipeline/base-single-entity-request.pipeline.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-pagination-request-pipeline.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/make-request-entity-request.pipe.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-pipeline.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-pipeline.types.ts
  src/frontend/packages/store/src/entity-request-pipeline/pagination-request-base-handlers/pagination-iterator.pipe.ts
  src/frontend/packages/store/src/entity-request-pipeline/pipline-http-client.service.ts
  src/frontend/packages/store/src/selectors/endpoint.selectors.ts
Labels: extensions, ready for review

#3917 Fix cf summary unit test failures
  src/frontend/packages/cloud-foundry/src/cloud-foundry-test.module.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-summary-tab/cloud-foundry-summary-tab.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.ts
Labels: ready for review

#3918 Fix quota update & apply action builder process to recently merged code
  src/frontend/packages/cloud-foundry/src/actions/quota-definitions.actions.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/quota-definition.action-builders.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/space-quota.action-builders.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-quota/create-quota-step/create-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-space-quota/create-space-quota-step/create-space-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-quota/edit-quota-step/edit-quota-step.component.html
  src/frontend/packages/core/src/features/cloud-foundry/edit-quota/edit-quota-step/edit-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/edit-space-quota/edit-space-quota-step/edit-space-quota-step.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/quota-definition-form/quota-definition-form.component.ts
Labels: ready for review

#3919 Application env vars fixes
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-variables/cf-app-variables-data-source.ts
Labels: in review, ready for review

#3922 Fix create service instance
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-event/cf-app-autoscaler-events-config.service.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
Labels: in review, ready for review

#3923 Fix setup bug
  src/jetstream/main.go
Labels: in review, ready for review

#3924 Remove unused legacy build scripts
  build/legacy/bk-build-utils.js
  build/legacy/bk-build.js
  build/legacy/bk-conf.js
  build/legacy/bk-prepare-build.js
  build/legacy/deploy-in-cf.js
  package-lock.json
  package.json
Labels: in review, ready for review

#3839 autoscaler: fixed scaling events history
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-event/cf-app-autoscaler-events-data-source.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler.effects.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source-config.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list.component.html
  src/frontend/packages/store/src/types/pagination.types.ts
Labels: discussion, extensions, question, ready for review

#3925 Ensure error messages are correctly saved to store
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/cf-error-helpers.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/edit-organization/edit-organization.component.ts
  src/frontend/packages/cloud-foundry/src/store/effects/permissions.effect.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue.types.ts
  src/frontend/packages/core/src/core/entity-service.spec.ts
  src/frontend/packages/core/src/jetstream.helpers.ts
  src/frontend/packages/store/src/entity-request-pipeline/base-single-entity-request.pipeline.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/endpoint-errors.handler.spec.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/endpoint-errors.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/fail-entity-request.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/handle-multi-endpoints.pipe.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/jetstream-error.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/map-multi-endpoint.pipes.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-pipeline.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-pipeline.types.ts
Labels: extensions, ready for review

#3926 Expression Changed Fix, Fix Create/Edit Org/Space & Allow guids of 0 (number)
  src/frontend/packages/cloud-foundry/src/entity-action-builders/quota-definition.action-builders.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/space-quota.action-builders.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/space.action-builders.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/add-edit-space-step-base.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/add-space/create-space-step/create-space-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/edit-space/edit-space-step/edit-space-step.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-list.helpers.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/fail-request.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/start-request.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/succeed-request.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/update-request.ts
Labels: blocked-pr, ready for review

#3927 Fix store permissions for non-cf admin
  src/frontend/packages/cloud-foundry/src/store/effects/permissions.effect.ts
  src/test-e2e/po/page-header-sub.po.ts
Labels: ready for review

#3929 Fix service instance issues
  src/frontend/packages/cloud-foundry/src/entity-action-builders/application-event.action-builders.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/application.action-builders.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/service-binding.action-builders.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/service-instance.action.builders.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/space.action-builders.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/user-provided-service.action-builders.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-event/cf-app-events-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/service-action-helper.service.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue-entity.ts
  src/frontend/packages/core/src/shared/services/cloud-foundry-user-provided-services.service.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
Labels: ready for review

#3932 Fix more v3-master e2e tests for quotas, orgs, spaces
  src/frontend/packages/cloud-foundry/src/entity-action-builders/user.action-builders.ts
  src/frontend/packages/core/src/shared/data-services/cf-user.service.ts
Labels: e2e, ready for review

#3934 Ensure we remove X-Forward-* HTTP headers that can cause problems proxying API requests
  src/jetstream/passthrough.go
Labels: ready for review

#3931 Backend update for cacheing compat for HTTP 1.0 clients
  src/jetstream/middleware.go
Labels: ready for review
