Repository cloudfoundry/stratos, pull requests merged in 2020-08, with the labels that each got.

#4496 Add typed entity access and `custom-src` removal to change log
  CHANGELOG.md
Labels: ready for review

#4478 Fix and update customization docs
  .gitignore
  docs/issue_template.md
  docs/pull_request_template.md
  src/frontend/packages/example-theme/_index.scss
  src/frontend/packages/example-theme/assets/core/nav-logo.png
  src/frontend/packages/example-theme/package.json
  src/frontend/packages/example-theme/sass/custom.scss
  src/frontend/packages/example-theme/sass/custom/acme-colors.scss
  src/frontend/packages/example-theme/sass/custom/acme.scss
  website/docs/extensions/backend.md
  website/docs/extensions/customizing.md
  website/docs/extensions/introduction.md
  website/docs/extensions/theming.md
  website/docs/extensions/v4-migration.md
  website/docs/status_updates.md
  website/package.json
  website/sidebars.js
  website/static/images/extensions/tab-example.png
Labels: blocked-pr, documentation, ready for review

#4488 Update base README, point to website
  README.md
  website/docs/extensions/v4-migration.md
  website/docs/introduction.md
Labels: blocked-pr, documentation, ready for review

#4489 Update developer docs
  website/docs/developer/backend.md
  website/docs/developer/developers-guide-e2e-tests.md
  website/docs/developer/frontend.md
  website/docs/developer/introduction.md
  website/sidebars.js
Labels: blocked-pr, documentation, ready for review

#4497 Fix docs
  docs/pull_request_template.md
  website/docs/developer/developers-guide-env-tech.md
  website/docs/developer/frontend.md
  website/docs/extensions/frontend.md
Labels: ready for review

#4500 Ensure images dependent on techPreview flag are included in imagelist.txt
  deploy/kubernetes/imagelist.values.yaml
Labels: ready for review

#4509 Improve clean-symlinks script
  build/clean-symlinks.js
Labels: ready for review

#4514 Update version to 4.0.1, add change log
  CHANGELOG.md
  deploy/kubernetes/console/README.md
  package-lock.json
  package.json
Labels: ready for review

#4479 Fix deploy from gitlab using a group's repo
  src/frontend/packages/cloud-foundry/src/shared/data-services/scm/gitlab-scm.ts
  src/frontend/packages/cloud-foundry/src/store/effects/deploy-app.effects.ts
Labels: ready for review

#4480 Add additional time ranges to base metrics range selector
  src/frontend/packages/core/src/shared/services/metrics-range-selector.service.ts
Labels: ready for review

#4508 Add some time saving comments to cf permissions checker
  src/frontend/packages/cloud-foundry/src/user-permissions/cf-user-permissions-checkers.ts
Labels: ready for review

#4510 Fix GitHub branch limit
  src/frontend/packages/cloud-foundry/src/actions/deploy-applications.actions.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/scm/github-pagination.helper.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/scm/github-scm.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/scm/gitlab-scm.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-pagination-request-pipeline.ts
  src/frontend/packages/store/src/helpers/paginated-request-helpers.ts
  src/frontend/packages/store/src/public-api.ts
Labels: ready for review

#4524 Fix the position of the header guide arrow
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.scss
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.ts
Labels: ready for review

#4527 Metrics: Ensure trailing slashes are ignored when comparing URLs
  src/frontend/packages/core/src/features/metrics/metrics.helpers.ts
  src/jetstream/plugins/metrics/main.go
  src/jetstream/plugins/metrics/main_test.go
Labels: ready for review

#4519 Remove imports of the form 'frontend/....'
  src/frontend/packages/cf-autoscaler/src/cf-autoscaler.module.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cf-organization-events/cloud-foundry-organization-events.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cf-organization-spaces/tabs/cloud-foundry-space-events/cloud-foundry-space-events.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cf-organization-spaces/tabs/cloud-foundry-space-users/cloud-foundry-space-users.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-feature-flags/table-cell-feature-flag-description/table-cell-feature-flag-description.component.ts
  src/frontend/packages/cloud-foundry/src/store/effects/users-roles.effects.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-select-page/api-endpoint-select-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-entity-type-select-page/api-entity-type-select-page.component.spec.ts
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/recent-entities/recent-entities.component.ts
  src/frontend/packages/core/src/shared/components/user-avatar/user-avatar.component.ts
  src/frontend/packages/core/src/shared/components/user-profile-banner/user-profile-banner.component.ts
Labels: ready for review

#4530 Move endpoints-health-check.ts
  src/frontend/packages/core/src/core/endpoints-health-checks.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
Labels: ready for review

#4522 Add UMD Ids to external modules in store package
  src/frontend/packages/store/ng-package.json
  src/frontend/packages/store/testing/ng-package.json
Labels: comments-addressed, ready for review

#4535 Improvements & more checks to autoscaler scheduled date tests
  src/test-e2e/application/application-autoscaler-e2e.spec.ts
  src/test-e2e/po/form.po.ts
Labels: ready for review

#4537 Remove api driven views
  src/frontend/packages/core/src/api-driven-views/api-drive-views.types.ts
  src/frontend/packages/core/src/api-driven-views/api-driven-views-routing.module.ts
  src/frontend/packages/core/src/api-driven-views/api-driven-views.module.ts
  src/frontend/packages/core/src/api-driven-views/components/api-entity-list/api-entity-list.component.html
  src/frontend/packages/core/src/api-driven-views/components/api-entity-list/api-entity-list.component.scss
  src/frontend/packages/core/src/api-driven-views/components/api-entity-list/api-entity-list.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/components/api-entity-list/api-entity-list.component.ts
  src/frontend/packages/core/src/api-driven-views/components/api-type-selector/api-entity-type-selector.component.html
  src/frontend/packages/core/src/api-driven-views/components/api-type-selector/api-entity-type-selector.component.scss
  src/frontend/packages/core/src/api-driven-views/components/api-type-selector/api-entity-type-selector.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/components/api-type-selector/api-entity-type-selector.component.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-select-page/api-endpoint-select-page.component.html
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-select-page/api-endpoint-select-page.component.scss
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-select-page/api-endpoint-select-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-select-page/api-endpoint-select-page.component.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.html
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.scss
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.ts
  src/frontend/packages/core/src/api-driven-views/features/api-entity-list-page/api-entity-list-page.component.html
  src/frontend/packages/core/src/api-driven-views/features/api-entity-list-page/api-entity-list-page.component.scss
  src/frontend/packages/core/src/api-driven-views/features/api-entity-list-page/api-entity-list-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-entity-list-page/api-entity-list-page.component.ts
  src/frontend/packages/core/src/api-driven-views/features/api-entity-type-select-page/api-entity-type-select-page.component.html
  src/frontend/packages/core/src/api-driven-views/features/api-entity-type-select-page/api-entity-type-select-page.component.scss
  src/frontend/packages/core/src/api-driven-views/features/api-entity-type-select-page/api-entity-type-select-page.component.spec.ts
  src/frontend/packages/core/src/api-driven-views/features/api-entity-type-select-page/api-entity-type-select-page.component.ts
  src/frontend/packages/core/src/app.routing.ts
Labels: ready for review

#4538 Remove logger service and action history
  src/frontend/packages/cloud-foundry/src/cloud-foundry-test.module.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/log-stream-tab/log-stream-tab.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/variables-tab/variables-tab.component.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-firehose/cloud-foundry-firehose-formatter.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-firehose/cloud-foundry-firehose.component.ts
  src/frontend/packages/cloud-foundry/src/features/cf/users/remove-user/remove-user.component.ts
  src/frontend/packages/cloud-foundry/src/store/effects/deploy-app.effects.ts
  src/frontend/packages/cloud-foundry/src/store/effects/github.effects.ts
  src/frontend/packages/cloud-foundry/src/store/effects/request.effects.ts
  src/frontend/packages/core/src/core/core.module.ts
  src/frontend/packages/core/src/core/logger.service.spec.ts
  src/frontend/packages/core/src/core/logger.service.ts
  src/frontend/packages/core/src/core/permissions/current-user-permissions.service.ts
  src/frontend/packages/core/src/environments/environment.prod.ts
  src/frontend/packages/core/src/environments/environment.ts
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.html
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.ts
  src/frontend/packages/core/src/features/endpoints/backup-restore/restore-endpoints.service.ts
  src/frontend/packages/core/src/features/home/home/home-page.component.ts
  src/frontend/packages/core/src/shared/components/copy-to-clipboard/copy-to-clipboard.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-list.helpers.ts
  src/frontend/packages/core/src/shared/components/markdown-preview/markdown-preview.component.spec.ts
  src/frontend/packages/core/src/shared/components/markdown-preview/markdown-preview.component.ts
  src/frontend/packages/core/src/shared/components/sidepanel-preview/sidepanel-preview.component.spec.ts
  src/frontend/packages/core/src/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/packages/store/src/actions/action-history.actions.ts
  src/frontend/packages/store/src/actions/log.actions.ts
  src/frontend/packages/store/src/actions/router.actions.ts
  src/frontend/packages/store/src/app-state.ts
  src/frontend/packages/store/src/effects/action-history.effects.ts
  src/frontend/packages/store/src/reducers.module.ts
  src/frontend/packages/store/src/reducers/action-history-reducer.ts
  src/frontend/packages/store/src/store.module.ts
  src/frontend/packages/store/testing/src/store-test-helper.ts
Labels: ready for review

#4515 Add support for API keys
  src/jetstream/apikeys.go
  src/jetstream/apikeys_test.go
  src/jetstream/datastore/20200814140918_ApiKeys.go
  src/jetstream/go.mod
  src/jetstream/go.sum
  src/jetstream/main.go
  src/jetstream/middleware.go
  src/jetstream/portal_proxy.go
  src/jetstream/repository/apikeys/apikeys.go
  src/jetstream/repository/apikeys/mock_apikeys.go
  src/jetstream/repository/apikeys/psql_apikeys.go
  src/jetstream/repository/apikeys/psql_apikeys_test.go
  src/jetstream/repository/interfaces/apikeys.go
Labels: ready for review

#4544 Fix Helm upgrade bug
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/tests/custom_annotations_test.yaml
Labels: ready for review
