Repository cloudfoundry/stratos, pull requests merged in 2020-03, with the labels that each got.

#4138 Only fetch first page of maxed lists
  src/frontend/packages/store/src/entity-request-pipeline/pagination-request-base-handlers/pagination-iterator.pipe.ts
Labels: bug, community, ready for review

#4128 Add change log for 3.0.0
  CHANGELOG.md
Labels: ready for review

#4014 Helm: Add chart icon and readme (+ other fixes)
  deploy/cap/bower.json
Labels: ready for review

#4146 Concourse pipeline fixes
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-nightly-releases.yml
Labels: ready for review

#4147 Helm upgrade fixes
  deploy/ci/automation/helmtest.sh
  deploy/ci/tasks/dev-releases/create-chart-helper.sh
  deploy/kubernetes/build.sh
  deploy/kubernetes/console/templates/secrets.yaml
Labels: P0, ready for review

#4127 Fix display of Space Roles in Org User list and other associated fixes
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.ts
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-metric-chart/app-autoscaler-metric-chart-card/app-autoscaler-metric-chart-card.component.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-schema-types.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application-delete/application-delete.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application-delete/delete-app-instances/app-delete-instances-routes-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application.service.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/application-env-vars.service.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/add-edit-space-step-base.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/add-space/create-space-step/create-space-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cf.helpers.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/cf-roles.service.ts
  src/frontend/packages/cloud-foundry/src/features/service-catalog/services-helper.ts
  src/frontend/packages/cloud-foundry/src/features/service-catalog/services.service.ts
  src/frontend/packages/cloud-foundry/src/features/services/services/services-wall.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-routes/cf-routes-data-source-base.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-select-users/cf-select-users-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/running-instances/running-instances.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/select-service/select-service.component.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-org-space-service.service.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-user.service.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cloud-foundry.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/cf-cell.helpers.ts
  src/frontend/packages/core/src/features/cloud-foundry/quota-definition-form/quota-definition-form.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/space-quota-definition-form/space-quota-definition-form.component.ts
  src/frontend/packages/core/src/features/metrics/services/metrics-service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/base-endpoints-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list.helper.ts
  src/frontend/packages/core/src/shared/services/cloud-foundry-user-provided-services.service.ts
  src/frontend/packages/store/src/monitors/pagination-monitor.factory.ts
  src/frontend/packages/store/src/monitors/pagination-monitor.ts
Labels: ready for review

#4129 UI Refinements
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/sass/mat-desktop.scss
  src/frontend/packages/core/src/app.component.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/core/log-out-dialog/log-out-dialog.component.html
  src/frontend/packages/core/src/core/log-out-dialog/log-out-dialog.component.scss
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.scss
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/packages/core/src/features/login/login-page/login-page.component.html
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-list.helpers.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.service.ts
Labels: ready for review

#4136 Auto login after local account setup
  src/jetstream/setup_console.go
Labels: ready for review

#4137 Ensure that the toolbar prompt is correctly aligned
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.html
  src/frontend/packages/core/src/shared/components/endpoints-missing/endpoints-missing.component.html
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.html
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.ts
Labels: ready for review

#4144 Optionally disable api logging
  src/jetstream/default.config.properties
  src/jetstream/main.go
Labels: ready for review

#4149 Fix build script spaces
  deploy/kubernetes/build.sh
Labels: ready for review

#4159 E2E Tests: Add test to delete space with app
  src/test-e2e/cloud-foundry/space-level/cf-space-delete-e2e.spec.ts
Labels: ready for review

#4145 Three Metrics Fixes
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/cf-cell.helpers.ts
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.html
  src/test-e2e/endpoints/connect-dialog.po.ts
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-e2e.spec.ts
  src/test-e2e/endpoints/endpoints-register-e2e.spec.ts
  src/test-e2e/endpoints/endpoints.po.ts
Labels: ready for review

#4156 Scaling Related & Minor Fixes
  deploy/tools/populate-cf/create-many-apps.sh
  deploy/tools/populate-cf/create-many-orgs.sh
  deploy/tools/populate-cf/create-many-services.sh
  deploy/tools/populate-cf/create-many-spaces.sh
  src/frontend/packages/cloud-foundry/src/actions/organization.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/route.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/users.actions.ts
  src/frontend/packages/cloud-foundry/src/cf-error-helpers.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/organization.action-builders.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/routes.action-builder.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cf.helpers.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/services/cloud-foundry-organization.service.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/manage-users-confirm/manage-users-confirm.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-routes/cf-routes-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instances-wall-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-user.service.ts
  src/frontend/packages/cloud-foundry/src/store/reducers/service-instance.reducer.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/local-list.helpers.ts
  src/frontend/packages/store/src/effects/request.effects.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/endpoint-errors.handler.spec.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/endpoint-errors.handler.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/success-entity-request.handler.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer.helper.ts
Labels: community, ready for review

#4134 User profile refinements
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/src/core/core.module.ts
  src/frontend/packages/core/src/core/user-profile.service.ts
  src/frontend/packages/core/src/features/user-profile/edit-profile-info/edit-profile-info.component.spec.ts
  src/frontend/packages/core/src/features/user-profile/edit-profile-info/edit-profile-info.component.ts
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.html
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.scss
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.spec.ts
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.ts
  src/frontend/packages/core/src/features/user-profile/user-profile.module.ts
  src/frontend/packages/core/src/shared/components/confirmation-dialog.service.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.theme.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/core/src/shared/components/user-avatar/md5.ts
  src/frontend/packages/core/src/shared/components/user-avatar/user-avatar.component.html
  src/frontend/packages/core/src/shared/components/user-avatar/user-avatar.component.scss
  src/frontend/packages/core/src/shared/components/user-avatar/user-avatar.component.spec.ts
  src/frontend/packages/core/src/shared/components/user-avatar/user-avatar.component.theme.scss
  src/frontend/packages/core/src/shared/components/user-avatar/user-avatar.component.ts
  src/frontend/packages/core/src/shared/components/user-profile-banner/user-profile-banner.component.html
  src/frontend/packages/core/src/shared/components/user-profile-banner/user-profile-banner.component.ts
  src/frontend/packages/store/src/actions/dashboard-actions.ts
  src/frontend/packages/store/src/reducers/dashboard-reducer.ts
  src/frontend/packages/store/testing/src/store-test-helper.ts
Labels: comments-addressed, ready for review

#4158 E2E Tests: Add delete org with space test
  src/test-e2e/cloud-foundry/org-level/cf-org-delete-e2e.spec.ts
Labels: ready for review

#4163 E2E Test for service instance bug and UPS deletion
  src/test-e2e/e2e.ts
  src/test-e2e/marketplace/base-create-service-instance-stepper.po.ts
  src/test-e2e/marketplace/create-service-instance.po.ts
  src/test-e2e/marketplace/create-ups-service-instance.po.ts
  src/test-e2e/marketplace/delete-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/delete-ups-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
Labels: needs attention, ready for review

#4162 Services Scaling and other Fixes
  src/frontend/packages/cloud-foundry/src/actions/application-service-routes.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/service-instances.actions.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-factory.ts
  src/frontend/packages/cloud-foundry/src/entity-action-builders/routes.action-builder.ts
  src/frontend/packages/cloud-foundry/src/entity-relations/entity-relations.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application-delete/application-delete.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application-delete/delete-app-instances/app-delete-instances-routes-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application.service.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/services-tab/services-tab.component.ts
  src/frontend/packages/cloud-foundry/src/features/service-catalog/services-helper.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instances-wall-data-source.ts
  src/frontend/packages/core/src/core/cf-api-svc.types.ts
  src/frontend/packages/core/src/shared/components/chips/chips.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service/table-cell-service.component.ts
  src/test-e2e/marketplace/create-service-instances-bind-app-e2e.spec.ts
Labels: comments-addressed, community, ready for review

#4177 Clean up isLocal pagination monitor values & fix toggle of disable polling
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.ts
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-metric-chart/app-autoscaler-metric-chart-card/app-autoscaler-metric-chart-card.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/application-env-vars.service.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-options-step/deploy-application-options-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/add-edit-space-step-base.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/add-organization/create-organization-step/create-organization-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cf.helpers.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/edit-organization/edit-organization-step/edit-organization-step.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/services/cloud-foundry-endpoint.service.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/cf-roles.service.ts
  src/frontend/packages/cloud-foundry/src/features/service-catalog/services-helper.ts
  src/frontend/packages/cloud-foundry/src/features/service-catalog/services.service.ts
  src/frontend/packages/cloud-foundry/src/features/services/services/services-wall.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-org-space-service.service.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-user.service.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cloud-foundry.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/cf-cell.helpers.ts
  src/frontend/packages/core/src/features/cloud-foundry/quota-definition-form/quota-definition-form.component.ts
  src/frontend/packages/core/src/features/cloud-foundry/space-quota-definition-form/space-quota-definition-form.component.ts
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.html
  src/frontend/packages/core/src/shared/services/cloud-foundry-user-provided-services.service.ts
Labels: ready for review

#4151 Jenkins Tests: Various reliability fixes
  deploy/ci/automation/helmtest.sh
  deploy/kubernetes/build.sh
  src/frontend/packages/core/src/shared/components/chips/chips.component.html
  src/frontend/packages/core/src/shared/components/chips/chips.component.scss
  src/jetstream/datastore/datastore.go
  src/test-e2e/application/application-autoscaler-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/manage-quota-e2e.spec.ts
  src/test-e2e/cloud-foundry/users-removal-e2e.helper.ts
  src/test-e2e/po/confirm-dialog.ts
  src/test-e2e/po/list.po.ts
Labels: ready for review

#4183 App Deploy: Tidy up UI
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.scss
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.scss
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-step3/deploy-application-step3.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application.component.html
  src/frontend/packages/core/sass/mat-desktop.scss
  src/frontend/packages/core/src/shared/components/list/list-types/github-commits/github-commits-list-config-deploy.service.ts
  src/frontend/packages/core/src/shared/components/log-viewer/log-viewer.component.scss
  src/test-e2e/application/application-deploy-helper.ts
Labels: ready for review

#4184 Fixes issue where long page header content pushes controls out of view
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.theme.scss
Labels: ready for review

#4164 Tidy request.effect after validation change
  src/frontend/packages/cloud-foundry/src/cloud-foundry.module.ts
  src/frontend/packages/core/src/shared/components/display-value/display-value.component.ts
  src/frontend/packages/core/src/shared/components/favorites-entity-list/favorites-entity-list.component.ts
  src/frontend/packages/core/src/shared/components/list/list.component.ts
  src/frontend/packages/core/src/shared/components/page-sub-nav/page-sub-nav.component.ts
  src/frontend/packages/store/src/actions/request.actions.ts
  src/frontend/packages/store/src/effects/request.effects.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/packages/store/src/store.module.ts
Labels: comments-addressed, ready for review

#4173 Fix for App Deploy does not support .yaml file extension for manifest
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-step2/deploy-application-fs/deploy-application-fs-utils.ts
  src/jetstream/plugins/cfapppush/deploy.go
Labels: comments-addressed, ready for review

#4192 Improve presentation of Recent Activity menu
  src/frontend/packages/core/src/features/home/home/home-page.component.html
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.html
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.scss
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.theme.scss
  src/frontend/packages/core/src/shared/components/recent-entities/recent-entities.component.html
  src/frontend/packages/core/src/shared/components/recent-entities/recent-entities.component.ts
Labels: ready for review

#4195 Add missing feature flag descriptions
  src/frontend/packages/cloud-foundry/src/shared/components/components.module.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-feature-flags/cf-feature-flags-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-feature-flags/table-cell-feature-flag-description/table-cell-feature-flag-description.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-feature-flags/table-cell-feature-flag-description/table-cell-feature-flag-description.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-feature-flags/table-cell-feature-flag-description/table-cell-feature-flag-description.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-feature-flags/table-cell-feature-flag-description/table-cell-feature-flag-description.component.ts
Labels: ready for review

#4193 Fix issue with 'go to summary' button not enabling
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application.component.html
  src/frontend/packages/core/src/shared/components/stepper/step/step.component.ts
  src/frontend/packages/core/src/shared/components/stepper/steppers/steppers.component.html
Labels: ready for review
