Repository cloudfoundry/stratos, pull requests merged in 2020-10, with the labels that each got.

#4596 Add support for env var for removing packages at build time
  .gitignore
  package.json
  src/frontend/packages/cf-autoscaler/package.json
  src/frontend/packages/cloud-foundry/package.json
  src/frontend/packages/devkit/src/backend.ts
  src/frontend/packages/devkit/src/lib/packages.ts
  src/frontend/packages/devkit/src/lib/stratos.config.ts
  src/jetstream/default_plugins.go
  src/jetstream/load_plugins.go
  src/jetstream/plugins/autoscaler/main.go
  src/jetstream/plugins/backup/main.go
  src/jetstream/plugins/cfapppush/main.go
  src/jetstream/plugins/cfappssh/main.go
  src/jetstream/plugins/cloudfoundry/main.go
  src/jetstream/plugins/cloudfoundryhosting/main.go
  src/jetstream/plugins/metrics/main.go
  src/jetstream/plugins/userfavorites/main.go
  src/jetstream/plugins/userinfo/main.go
  src/jetstream/plugins/userinvite/main.go
  src/jetstream/repository/interfaces/plugin.go
Labels: ready for review

#4614 Fix text clipping on app favourite card
  src/frontend/packages/core/src/shared/components/multiline-title/multiline-title.component.scss
Labels: ready for review

#4621 Remove note about Kubernetes not being available yet
  website/docs/introduction.md
Labels: ready for review

#4611 All-in-one Image: Add support for running as non-root user
  deploy/Dockerfile.all-in-one
  deploy/all-in-one/build.sh
  deploy/all-in-one/config.all-in-one.properties
  deploy/all-in-one/src-build.sh
  deploy/common-build.sh
  website/docs/deploy/access.md
  website/docs/deploy/all-in-one.md
  website/docs/introduction.md
Labels: ready for review

#4625 Bump base images to Leap 15.2
  .gitignore
  build/tools/scan-images.sh
  deploy/Dockerfile.all-in-one
  deploy/Dockerfile.bk
  deploy/Dockerfile.init
  deploy/Dockerfile.ui
  deploy/ci/scripts/Dockerfile.stratos-ci
  deploy/containers/nginx/Dockerfile.dc
  deploy/kubernetes/build.sh
  deploy/stratos-base-images/build-base-images.sh
  deploy/stratos-base-images/imagelist.txt
Labels: ready for review

#4616 Disable API Keys if persistence is disabled
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.spec.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
Labels: bug, needs attention, ready for review

#4617 Bump version number to 4.2.0
  build/tools/changelog.sh
  deploy/kubernetes/console/README.md
  package-lock.json
  package.json
Labels: comments-addressed, ready for review

#4634 Fix nightly docker AIO build
  deploy/ci/build-aio-image-canary.yml
  deploy/ci/build-aio-image-nightly.yml
  deploy/ci/build-aio-image-stable.yml
  deploy/ci/tasks/dev-releases/vars-helper.sh
Labels: ready for review

#4631 Tools to automate image scanning
  build/tools/scan-images.sh
Labels: ready for review

#4636 Fix cf push
  manifest.yml
Labels: ready for review

#4637 Kube Terminal: Bump kubectl and helm CLI packages
  deploy/containers/kube-terminal/Dockerfile.kubeterminal
Labels: ready for review

#4638 Bump downstream images to leap15_2
  deploy/containers/kube-terminal/Dockerfile.kubeterminal
  src/jetstream/plugins/analysis/container/Dockerfile
Labels: ready for review

#4635 Fix kube terminal button showing when not configured
  src/jetstream/plugins/kubernetes/main.go
Labels: ready for review

#4642 Fix kube analysis info assets
  src/frontend/packages/kubernetes/assets/custom/analysis/kubescore.md
  src/frontend/packages/kubernetes/assets/custom/analysis/kubescore.png
  src/frontend/packages/kubernetes/assets/custom/analysis/popeye.md
  src/frontend/packages/kubernetes/assets/custom/analysis/popeye.png
  src/frontend/packages/kubernetes/assets/custom/analysis/sonobuoy.md
  src/frontend/packages/kubernetes/assets/custom/analysis/sonobuoy.png
  src/frontend/packages/kubernetes/assets/custom/analysis/sonobuoy.svg
  src/frontend/packages/kubernetes/src/kubernetes/services/kubernetes.analysis.service.ts
Labels: ready for review

#4639 Make `Manage Roles` button more visible, also add tab icon only buttons hoverable
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.scss
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cf-organization-spaces/tabs/cloud-foundry-space-users/cloud-foundry-space-users.component.html
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cf-organization-users/cloud-foundry-organization-users.component.html
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.theme.scss
Labels: comments-addressed, ready for review

#4643 Optionally enable helm hub (disabled by default)
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-base-step/create-endpoint-base-step.component.ts
  src/frontend/packages/kubernetes/src/helm/helm-entity-generator.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.types.ts
  src/jetstream/config.example
  src/jetstream/plugins/monocular/20201007113503_RemoveHelmHub.go
  src/jetstream/plugins/monocular/main.go
Labels: comments-addressed, ready for review

#4644 Fix the alignment of the analysis buttons
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-runner/analysis-report-runner.component.html
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-runner/analysis-report-runner.component.scss
Labels: ready for review

#4648 Change log for 4.2
  CHANGELOG.md
Labels: ready for review

#4646 Add support for Artifact Hub
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
  src/frontend/packages/kubernetes/src/helm/helm-entity-generator.ts
  src/frontend/packages/kubernetes/src/helm/helm-hub-registration/helm-hub-registration.component.html
  src/frontend/packages/kubernetes/src/helm/helm-hub-registration/helm-hub-registration.component.ts
  src/frontend/packages/kubernetes/src/helm/monocular/chart-details/chart-details.component.ts
  src/frontend/packages/kubernetes/src/helm/monocular/shared/services/charts.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
  src/jetstream/config.example
  src/jetstream/plugins/monocular/artifacthub.go
  src/jetstream/plugins/monocular/cache.go
  src/jetstream/plugins/monocular/chart_svc.go
  src/jetstream/plugins/monocular/main.go
Labels: ready for review

#4653 Helm: Fix issue where relative chart URLs fail to sync
  src/jetstream/plugins/monocular/artifacthub.go
  src/jetstream/plugins/monocular/cache.go
  src/jetstream/plugins/monocular/chart_svc.go
  src/jetstream/plugins/monocular/sync_worker.go
Labels: ready for review

#4657 Fix analyzers build with echo v4
  src/jetstream/plugins/analysis/container/go.mod
  src/jetstream/plugins/analysis/container/go.sum
  src/jetstream/plugins/analysis/container/main.go
Labels: ready for review

#4659 Fix sql helm hub removal statement for mariadb
  src/jetstream/plugins/monocular/20201007113503_RemoveHelmHub.go
Labels: ready for review

#4661 Fix nginx config to include /api
  deploy/containers/nginx/conf/nginx.dev.conf
  deploy/containers/nginx/conf/nginx.k8s.conf
  deploy/stratos-ui-release/jobs/frontend/templates/nginx.conf.erb
Labels: ready for review

#4662 Fix issue where app wall list failed to filter spaces when in maxed state
  src/frontend/packages/cloud-foundry/src/shared/q-param.ts
Labels: ready for review

#4663 Update change log
  CHANGELOG.md
Labels: ready for review

#4667 Kube Terminal: Fix warning on launch
  deploy/common-build.sh
  deploy/containers/kube-terminal/kubeconsole.bashrc
Labels: ready for review

#4669 Fix broken workload upgrade
  src/frontend/packages/kubernetes/src/kubernetes/workloads/upgrade-release/upgrade-release.component.ts
Labels: ready for review

#4680 Fix helm chart artifact hub enabled property
  deploy/kubernetes/console/templates/deployment.yaml
  src/frontend/packages/kubernetes/src/helm/helm-entity-generator.ts
  src/jetstream/config.example
  src/jetstream/plugins/monocular/main.go
Labels: ready for review

#4690 k8s: Add support for service account tokens
  src/frontend/packages/kubernetes/sass/_all-theme.scss
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.html
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.spec.ts
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.theme.scss
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-serviceaccount-auth-form/kubernetes-serviceaccount-auth-form.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-entity-generator.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes.setup.module.ts
  src/jetstream/plugins/kubernetes/auth/token.go
Labels: ready for review

#4687 Travis: Tidy up go installation to ensure consistent version
  .travis.yml
  build/bk-build.sh
  deploy/ci/travis/e2e-build-script.sh
  deploy/ci/travis/install-go.sh
  deploy/ci/travis/run-backend-tests.sh
Labels: ready for review

#4694 Pin swag to 1.6.7
  build/bk-build.sh
Labels: ready for review

#4652 Update docs following upstreaming of kube
  docs/connecting-k8s.md
  website/docs/deploy/cloud-foundry/cloud-foundry.md
  website/docs/deploy/kubernetes/eksdeployment.md
  website/docs/developer/developers-guide-kube-local-dev.md
  website/docs/endpoints/cf/cf.md
  website/docs/endpoints/cf/invite-user-guide.md
  website/docs/endpoints/helm.md
  website/docs/endpoints/introduction.md
  website/docs/endpoints/k8s.md
  website/docs/endpoints/metrics/bosh-metrics.md
  website/docs/endpoints/metrics/metrics.md
  website/sidebars.js
Labels: documentation, ready for review

#4647 Make number of replicas configurable in the Helm chart
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.schema.json
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#4624 Enable Codecov reports for the backend
  .travis.yml
  build/bk-build.sh
  package.json
Labels: ready for review

#4660 Add docs for removing packages/plugins
  .cfignore
  src/jetstream/config.example
  website/docs/deploy/cloud-foundry/cloud-foundry.md
  website/docs/deploy/overview.md
  website/docs/deploy/tech-preview.md
  website/docs/extensions/disable-packages.md
  website/sidebars.js
Labels: documentation, ready for review

#4700 Add docs website 4.2 version, fix automation
  .github/workflows/documentation-versioning.yml
  website/add-version.sh
  website/internal-versions.json
Labels: ready for review

#4622 Always return code 200 in session verification endpoint
  src/frontend/packages/core/src/core/not-setup-guard.service.ts
  src/frontend/packages/store/src/effects/auth.effects.ts
  src/frontend/packages/store/src/types/auth.types.ts
  src/jetstream/auth_test.go
  src/jetstream/main.go
  src/jetstream/middleware.go
  src/jetstream/mock_server_test.go
  src/jetstream/repository/interfaces/errors.go
  src/jetstream/session.go
Labels: ready for review

#4697 Optimize image build sequence
  deploy/ci/console-dev-releases.yml
Labels: ready for review

#4698 Update DB container to 15.2 and use specific MariaDB version
  deploy/db/Dockerfile.mariadb
  deploy/stratos-base-images/Dockerfile.stratos-mariadb-base.tmpl
Labels: ready for review

#4705 Helm: Fix issue with console.tlsSecretName
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/tests/custom-cert_test.yaml
  deploy/kubernetes/console/tests/database_test.yaml
Labels: ready for review

#4709 Improve handling of tile selectors dynamic tile sizing
  src/frontend/packages/core/src/shared/components/tile-selector/tile-selector.component.ts
Labels: ready for review

#4710 Add new darker/lighter background colour to all textareas
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/specify-user-provided-details/specify-user-provided-details.component.html
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/sass/components/text-area.theme.scss
  src/frontend/packages/kubernetes/sass/_all-theme.scss
Labels: ready for review

#4719 Move GET `/tokens` into `api` group
  .travis.yml
  src/jetstream/main.go
Labels: ready for review

#4720 Update version, change log and package lock for 4.2.1
  CHANGELOG.md
  deploy/kubernetes/console/README.md
  package-lock.json
  package.json
Labels: ready for review
