Repository cloudfoundry/stratos, pull requests merged in 2020-07, with the labels that each got.

#4412 Move out remaining items in cf & autoscaler from core to own packages, improve code splitting
  angular.json
  src/frontend/packages/cf-autoscaler/package.json
  src/frontend/packages/cf-autoscaler/sass/_all-theme.scss
  src/frontend/packages/cf-autoscaler/src/cf-autoscaler-package.module.ts
  src/frontend/packages/cf-autoscaler/src/cf-autoscaler-routing.module.ts
  src/frontend/packages/cf-autoscaler/src/cf-autoscaler.module.ts
  src/frontend/packages/cf-autoscaler/src/core/autoscaler.module.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step4/edit-autoscaler-policy-step4.theme.scss
  src/frontend/packages/cf-autoscaler/src/public_api.ts
  src/frontend/packages/cloud-foundry/package.json
  src/frontend/packages/cloud-foundry/sass/_all-theme.scss
  src/frontend/packages/cloud-foundry/sass/mixins.scss
  src/frontend/packages/cloud-foundry/src/cloud-foundry-package.module.ts
  src/frontend/packages/cloud-foundry/src/cloud-foundry-routing.module.ts
  src/frontend/packages/cloud-foundry/src/cloud-foundry-test.module.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application-wall/application-wall.component.theme.scss
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-base.component.theme.scss
  src/frontend/packages/cloud-foundry/src/features/applications/applications.module.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cloud-foundry-section.module.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cloud-foundry-section.routing.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/cf-roles.service.spec.ts
  src/frontend/packages/cloud-foundry/src/features/service-catalog/service-catalog-page/service-catalog-page.component.theme.scss
  src/frontend/packages/cloud-foundry/src/features/service-catalog/service-catalog.module.ts
  src/frontend/packages/cloud-foundry/src/features/services/services-wall/services-wall.component.theme.scss
  src/frontend/packages/cloud-foundry/src/features/services/services.module.ts
  src/frontend/packages/cloud-foundry/src/public_api.ts
  src/frontend/packages/cloud-foundry/src/shared/cf-shared.module.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.ts
  src/frontend/packages/cloud-foundry/src/store/cloud-foundry.store.module.ts
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/extension/extension-service.ts
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.ts
  src/test-e2e/application/po/card-autoscaler-default.po.ts
  src/tsconfig.json
Labels: ready for review

#4418 Use smaller page header on desktop browsers
  src/frontend/packages/core/sass/mat-desktop.scss
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.html
Labels: ready for review

#4420 Fix issue where themeing is not applied to extensions
  src/frontend/packages/core/sass/theme.scss
Labels: in review, ready for review

#4422 Allow ng build to be run from any subfolder
  src/frontend/packages/devkit/src/build/extensions.ts
  src/frontend/packages/devkit/src/lib/stratos.config.ts
Labels: ready for review

#4423 Fix responsiveness of app instances card
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-app-instances/card-app-instances.component.scss
Labels: ready for review

#4425 Fix devkit build script to work with paths containing spaces
  src/frontend/packages/devkit/build.sh
Labels: ready for review

#4417 Fetch service in service instances card via store rather than inline
  src/frontend/packages/cloud-foundry/src/actions/service-instances.actions.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
Labels: ready for review

#4426 Remove old symlink files in pre-4.0 Stratos
  build/clean-symlinks.sh
  package.json
Labels: ready for review

#4432 Fix profile page banner
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.scss
Labels: ready for review

#4429 E2E: Improve reliability of tests that deploy applications
  package.json
  protractor.conf.js
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/packages/cloud-foundry/src/store/types/deploy-application.types.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.spec.ts
  src/jetstream/plugins/cfapppush/deploy.go
Labels: ready for review

#4436 Add support for including breaking changes in the changelog
  build/tools/changelog.sh
Labels: ready for review

#4421 Improve recent and favourites display
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/features/home/home/home-page.component.scss
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.html
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.scss
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.theme.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/core/src/shared/components/recent-entities/recent-entities.component.html
  src/frontend/packages/core/src/shared/components/recent-entities/recent-entities.component.scss
  src/frontend/packages/core/src/shared/components/recent-entities/recent-entities.component.ts
  src/frontend/packages/store/src/actions/recently-visited.actions.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.types.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/recently-visited.reducer.helpers.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/recently-visited.reducer.ts
  src/frontend/packages/store/src/types/recently-visited.types.ts
  src/frontend/packages/store/testing/src/store-test-helper.ts
Labels: ready for review

#4438 Add line-height to favourite and recent entity labels
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.scss
  src/frontend/packages/core/src/shared/components/recent-entities/recent-entities.component.scss
Labels: ready for review

#4424 Autoscaler e2e tests: Give better failure error when the test can't find the scaling row
  src/test-e2e/application/application-autoscaler-e2e.spec.ts
Labels: ready for review

#4355 Helm Chart: Remove encryption key volume
  deploy/containers/config-init/config-init.sh
  deploy/kubernetes/console/templates/config-init.yaml
  deploy/kubernetes/console/templates/volumes.yaml
Labels: ready for review

#4443 Add request for version info to github issues template
  docs/issue_template.md
Labels: documentation, ready for review

#4440 Show all favorites for an endpoint favorite if there is only one
  src/frontend/packages/core/src/shared/components/favorites-entity-list/favorites-entity-list.component.html
  src/frontend/packages/core/src/shared/components/favorites-entity-list/favorites-entity-list.component.ts
  src/frontend/packages/core/src/shared/components/favorites-global-list/favorites-global-list.component.html
Labels: ready for review

#4444 Merge downstream - JSON Viewer with dark mode & Header Fixes
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/sass/mat-desktop.scss
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.scss
  src/frontend/packages/core/src/shared/components/json-viewer/json-viewer.component.theme.scss
Labels: ready for review

#4453 Fix issues with tests not running if build upload fails
  deploy/ci/travis/e2e-build-script.sh
  deploy/ci/travis/e2e-mc-helper.sh
Labels: ready for review

#4456 Improve autoscaler e2e logging
  src/test-e2e/application/application-autoscaler-e2e.spec.ts
  src/test-e2e/po/form.po.ts
  src/test-e2e/po/list.po.ts
Labels: ready for review

#4459 Fix check-e2e-pr.sh for pr's from other repos
  deploy/ci/travis/check-e2e-pr.sh
Labels: ready for review

#4455 Convert Client Secret Input Fields to `password`
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/user-invites/configuration-dialog/user-invite-configuration-dialog.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/user-invites/configuration-dialog/user-invite-configuration-dialog.component.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.html
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint-step/edit-endpoint-step.component.html
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint-step/edit-endpoint-step.component.ts
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.ts
Labels: ready for review

#4460 Insecure tlsv10 and tlsv11 ciphers in Stratos UI, bsc#1173295
  deploy/containers/nginx/conf/nginx.dev.conf
  deploy/containers/nginx/conf/nginx.k8s.conf
Labels: ready for review

#4462 Convert scripts to nodejs so they work on Windows
  build/clean-symlinks.js
  build/clean-symlinks.sh
  build/dev-setup.js
  build/fe-build.js
  build/gulp.config.js
  build/prebuild-zip.js
  build/store-git-metadata.js
  deploy/stratos-ui-release/packages/backend/pre_packaging
  docs/developers-guide.md
  gulpfile.js
  package-lock.json
  package.json
  src/frontend/packages/devkit/build.js
  src/frontend/packages/devkit/build.sh
  src/frontend/packages/devkit/package.json
  src/frontend/packages/devkit/src/build/extensions.ts
  src/frontend/packages/devkit/src/build/sass.ts
  src/frontend/packages/devkit/src/lib/packages.ts
  src/jetstream/config.dev
  src/jetstream/config.example
  src/jetstream/main.go
Labels: ready for review

#4467 Fix log out page when there's a custom log in page
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/extension/extension-service.ts
  src/frontend/packages/core/src/features/login/login.module.ts
  src/frontend/packages/core/src/features/login/login.routing.ts
Labels: ready for review

#4463 Add service broker space scope information to service wall list
  src/frontend/packages/cloud-foundry/src/shared/cf-shared.module.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-services-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-broker/table-cell-service-broker.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-broker/table-cell-service-broker.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-broker/table-cell-service-broker.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-broker/table-cell-service-broker.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service/table-cell-service.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service/table-cell-service.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service/table-cell-service.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/test-e2e/marketplace/create-service-instances-bind-app-e2e.spec.ts
Labels: ready for review

#4431 Remove recents and favorites when entities are deleted
  src/frontend/packages/store/src/actions/entity.delete.actions.ts
  src/frontend/packages/store/src/effects/api.effects.ts
  src/frontend/packages/store/src/effects/user-favorites-effect.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/recently-visited.reducer.helpers.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/recently-visited.reducer.ts
Labels: comments-addressed, ready for review

#4469 Version bump and change log
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready for review

#4442 Add env var support for ssl mode
  src/jetstream/datastore/database_cf_config.go
Labels: blocked, community, ready for review

#4475 Update change log
  CHANGELOG.md
Labels: ready for review

#4474 Ensure filename/no filename text in connect by file dialog is aligned
  src/frontend/packages/core/src/shared/components/file-input/file-input.component.scss
Labels: ready for review
