Repository cloudfoundry/stratos, pull requests merged in 2020-06, with the labels that each got.

#4337 Merge v3.2.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/jetstream/authuaa.go
Labels: ready for review

#4321 Ensure the correct key is used for metacard favourite info
  src/frontend/packages/cloud-foundry/src/cf-favorites-helpers.ts
  src/frontend/packages/core/src/core/user-favorite-helpers.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
Labels: bug, ready for review

#4319 Fix display of details in endpoint card in endpoint list
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
Labels: bug, ready for review

#4320 Fix transition from space summary to app summary page
  src/frontend/packages/store/src/entity-service.ts
  src/frontend/packages/store/src/monitors/entity-monitor.factory.service.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/types.ts
  src/frontend/packages/store/testing/src/store-test-helper.ts
Labels: bug, ready for review

#4326 Fix issue where gitlab summary tab threw errors in console
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/scm/github-scm.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/scm/gitlab-scm.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/scm/scm.ts
Labels: bug, ready for review

#4334 Fix issue where default add/remove setting in change role by username was incorrect
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/manage-users-set-usernames/manage-users-set-usernames.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/manage-users-set-usernames/manage-users-set-usernames.component.ts
Labels: bug, ready for review

#4345 Helm: Change default image pull policy to Always
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#4344 Fix errors in console log during setup screens
  src/frontend/packages/core/src/core/user-profile.service.ts
Labels: ready for review

#4353 Use Recent Activity icon that is less easily confused with Refresh
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/recent-entities/recent-entities.component.html
Labels: ready for review

#4354 Fix for buildpack filename wrapping on card
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-buildpacks/cf-buildpack-card/cf-buildpack-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.scss
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-item/meta-card-item.component.ts
Labels: ready for review

#4350 Add copy address and edit to endpoint table view
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-list.helpers.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-address/table-cell-endpoint-address.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-address/table-cell-endpoint-address.component.scss
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-address/table-cell-endpoint-address.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-address/table-cell-endpoint-address.component.ts
Labels: ready for review

#4364 Fail Concourse CI build if imagelist generation fails
  deploy/kubernetes/imagelist-gen.sh
Labels: ready for review

#4362 Fix several space developer permission bugs
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-app-instances/card-app-instances.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-app-instances/card-app-instances.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-route/cf-app-routes-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/user-permissions/cf-user-permissions-checkers.ts
  src/frontend/packages/core/src/core/extension/extension-service.ts
  src/frontend/packages/core/src/features/dashboard/page-side-nav/page-side-nav.component.ts
  src/test-e2e/application/application-view-e2e.spec.ts
Labels: ready for review

#4366 Fix service stepper navigation
  src/frontend/packages/cloud-foundry/src/features/service-catalog/service-tabs-base/service-tabs-base.component.html
  src/frontend/packages/cloud-foundry/src/features/service-catalog/service-tabs-base/service-tabs-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/service-catalog/services.service.ts
  src/frontend/packages/cloud-foundry/src/features/services/services-wall/services-wall.component.html
  src/frontend/packages/cloud-foundry/src/features/services/services-wall/services-wall.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/add-service-instance-base-step/add-service-instance-base-step.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/add-service-instance-base-step/add-service-instance-base-step.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/specify-user-provided-details/specify-user-provided-details.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-service-instances-list-config.base.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-user-service-instances-list-config.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/cf-spaces-service-instances-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/service-instances/service-instances-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/service-instances/service-instances-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instances-wall-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/user-provided-service-instance-card/user-provided-service-instance-card.component.ts
  src/test-e2e/marketplace/create-marketplace-service-instance.po.ts
  src/test-e2e/marketplace/create-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance-private-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance-space-scoped-e2e.spec.ts
  src/test-e2e/marketplace/create-service-instance.po.ts
  src/test-e2e/marketplace/create-service-instances-bind-app-e2e.spec.ts
  src/test-e2e/marketplace/create-ups-service-instance.po.ts
  src/test-e2e/marketplace/delete-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/delete-ups-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/edit-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/marketplace-create-service-instances-e2e.spec.ts
  src/test-e2e/marketplace/marketplace-instances.po.ts
  src/test-e2e/marketplace/marketplace-summary-e2e.spec.ts
  src/test-e2e/marketplace/marketplace-summary.po.ts
  src/test-e2e/marketplace/services-wall-e2e.spec.ts
  src/test-e2e/marketplace/services-wall.po.ts
  src/test-e2e/po/page.po.ts
Labels: ready for review

#4371 Move base-entity-* to store package
  src/frontend/packages/cf-autoscaler/src/store/autoscaler-entity-factory.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-factory.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/cloud-foundry-test.module.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/space-quota-definition/space-quota-definition.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell-base/cloud-foundry-cell-base.component.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cloud-foundry.service.ts
  src/frontend/packages/cloud-foundry/src/shared/services/cf-org-space-label.service.ts
  src/frontend/packages/cloud-foundry/src/shared/services/current-user-permissions.service.spec.ts
  src/frontend/packages/cloud-foundry/test-framework/cf-test-helper.ts
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/core/permissions/current-user-permissions.service.spec.ts
  src/frontend/packages/core/src/core/permissions/current-user-permissions.service.ts
  src/frontend/packages/core/src/core/user-profile.service.ts
  src/frontend/packages/core/src/features/endpoints/connect.service.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.ts
  src/frontend/packages/core/src/features/metrics/services/metrics-service.ts
  src/frontend/packages/core/src/shared/components/app-action-monitor-icon/app-action-monitor-icon.component.spec.ts
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-request-monitor-icon/table-cell-request-monitor-icon.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/base-endpoints-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-list.helpers.ts
  src/frontend/packages/core/test-framework/core-test.modules.ts
  src/frontend/packages/store/src/actions/endpoint.actions.ts
  src/frontend/packages/store/src/actions/metrics.actions.ts
  src/frontend/packages/store/src/actions/user-profile.actions.ts
  src/frontend/packages/store/src/base-entity-schemas.ts
  src/frontend/packages/store/src/base-entity-types.ts
  src/frontend/packages/store/src/effects/endpoint.effects.ts
  src/frontend/packages/store/src/effects/system.effects.ts
  src/frontend/packages/store/src/effects/user-favorites-effect.ts
  src/frontend/packages/store/src/effects/user-profile.effects.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog-entity/entity-catalog-entity.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.spec.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.ts
  src/frontend/packages/store/src/entity-service.spec.ts
  src/frontend/packages/store/src/reducers/api-request-reducer/request-helpers.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/recently-visited.reducer.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination.reducer.spec.ts
  src/frontend/packages/store/src/selectors/endpoint.selectors.ts
  src/frontend/packages/store/src/selectors/favorite-groups.selectors.ts
  src/frontend/packages/store/testing/src/store-test-helper.ts
Labels: ready for review

#4378 Use snackbar service instead of using action dispatch via store
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-space-details/card-cf-space-details.component.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/long-running-cf-op.service.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/connect-endpoint-dialog.component.ts
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-list.helpers.ts
  src/frontend/packages/core/src/shared/services/snackbar.service.ts
  src/frontend/packages/store/src/actions/snackBar.actions.ts
  src/frontend/packages/store/src/effects/snackBar.effects.spec.ts
  src/frontend/packages/store/src/effects/snackBar.effects.ts
  src/frontend/packages/store/src/store.module.ts
Labels: ready for review

#4380 Move extension-types to store
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/auth-forms/credentials-auth-form.component.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/auth-forms/none-auth-form.component.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/auth-forms/sso-auth-form.component.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint/connect-endpoint.component.ts
  src/frontend/packages/core/src/features/endpoints/connect.service.ts
  src/frontend/packages/core/src/features/endpoints/endpoint-auth.ts
  src/frontend/packages/store/src/actions/endpoint.actions.ts
  src/frontend/packages/store/src/effects/endpoint.effects.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.types.ts
  src/frontend/packages/store/src/extension-types.ts
  src/frontend/packages/store/src/types/endpoint.types.ts
Labels: ready for review

#4381 Move favourite mgr and helper from core to store
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.spec.ts
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.ts
  src/frontend/packages/core/src/features/home/home/home-page.component.ts
  src/frontend/packages/core/src/shared/components/favorites-entity-list/favorites-entity-list.component.ts
  src/frontend/packages/core/src/shared/components/favorites-global-list/favorites-global-list.component.ts
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/packages/store/src/effects/user-favorites-effect.ts
  src/frontend/packages/store/src/helpers/store-helpers.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/user-favorites-groups.reducer.spec.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/user-favorites-groups.reducer.ts
  src/frontend/packages/store/src/selectors/favorite-groups.selectors.ts
  src/frontend/packages/store/src/user-favorite-helpers.ts
  src/frontend/packages/store/src/user-favorite-manager.ts
Labels: ready for review

#4365 Fix last two cf role permission bugs
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cf.helpers.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cf-role-checkbox/cf-role-checkbox.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-users-org-space-roles/table-cell-org-space-role/table-cell-org-space-role.component.html
  src/test-e2e/application/application-deploy-docker-e2e.spec.ts
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-e2e-helpers.ts
  src/test-e2e/application/application-routes-e2e.spec.ts
  src/test-e2e/application/application-view-e2e.spec.ts
  src/test-e2e/applications/application-wall-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/manage-org-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/manage-quota-e2e.spec.ts
  src/test-e2e/cloud-foundry/invite-users-e2e.helper.ts
  src/test-e2e/cloud-foundry/manage-users-by-username-stepper-e2e.spec.ts
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/cf-org-delete-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/manage-space-quota-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/mange-space-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/org-invite-user-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/org-spaces-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-delete-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/cf-space-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-invite-user-e2e.spec.ts
  src/test-e2e/cloud-foundry/space-level/space-routes-e2e.spec.ts
  src/test-e2e/cloud-foundry/users-list-e2e.helper.ts
  src/test-e2e/cloud-foundry/users-removal-e2e.helper.ts
  src/test-e2e/helpers/cf-e2e-helpers.ts
  src/test-e2e/marketplace/services-helper-e2e.ts
  src/test-e2e/po/invite-users-stepper.po.ts
Labels: ready for review

#4382 Fix more store -> core dependencies
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/cf-favorites-helpers.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/packages/core/endpoints-health-checks.ts
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.spec.ts
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.ts
  src/frontend/packages/core/src/core/utils.service.ts
  src/frontend/packages/core/src/features/endpoints/backup-restore/backup-endpoints.service.ts
  src/frontend/packages/core/src/features/endpoints/backup-restore/restore-endpoints.service.ts
  src/frontend/packages/core/src/features/endpoints/connect-endpoint/connect-endpoint.component.ts
  src/frontend/packages/core/src/shared/components/favorites-entity-list/favorites-entity-list.component.ts
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-favorite/table-cell-favorite.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/store/src/base-entity-types.ts
  src/frontend/packages/store/src/browser-encoder.ts
  src/frontend/packages/store/src/effects/auth.effects.ts
  src/frontend/packages/store/src/effects/endpoint.effects.ts
  src/frontend/packages/store/src/endpoint-auth.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog-entity/entity-catalog-entity.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog-entity/entity-catalog-entity.types.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog-entity/type.helpers.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.spec.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.types.ts
  src/frontend/packages/store/src/favorite-config-mapper.ts
  src/frontend/packages/store/src/reducers.module.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/packages/store/src/selectors/current-user-role.selectors.ts
  src/frontend/packages/store/src/types/auth.types.ts
  src/frontend/packages/store/src/types/endpoint.types.ts
  src/frontend/packages/store/src/user-favorite-helpers.ts
  src/frontend/packages/store/src/user-favorite-manager.ts
Labels: comments-addressed, ready for review

#4369 Merge downstream
  README.md
  angular.json
  build/combine-coverage.js
  build/karma.conf.creator.js
  build/karma.test.reporter.js
  build/tools/changelog.sh
  deploy/ci/console-dev-releases.yml
  docs/planning/metrics.md
  package-lock.json
  package.json
  protractor.conf.js
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-metric-chart/app-autoscaler-metric-chart-card/app-autoscaler-metric-chart-card.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-metric-chart/app-autoscaler-metric-chart-list-config.service.spec.ts
  src/frontend/packages/cloud-foundry/src/actions/buildpack.action.ts
  src/frontend/packages/cloud-foundry/src/actions/domains.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/relation.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/security-groups-actions.ts
  src/frontend/packages/cloud-foundry/src/actions/service-bindings.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/service-broker.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/service-plan-visibility.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/service-plan.actions.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cli-info-cloud-foundry/cli-info-cloud-foundry.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/cf-roles.service.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app/cf-apps-data-source.ts
  src/frontend/packages/core/sass/components/mat-table.scss
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/features/endpoints/backup-restore/backup-endpoints/backup-endpoints.component.html
  src/frontend/packages/core/src/features/metrics/metrics.helpers.ts
  src/frontend/packages/core/src/features/metrics/metrics/metrics.component.html
  src/frontend/packages/core/src/shared/components/entity-summary-title/entity-summary-title.component.scss
  src/frontend/packages/core/src/shared/components/ring-chart/ring-chart.component.html
  src/frontend/packages/core/src/shared/components/ring-chart/ring-chart.component.ts
  src/frontend/packages/store/src/base-entity-types.ts
  src/frontend/packages/store/src/effects/metrics.effects.ts
  src/frontend/packages/store/src/types/request.types.ts
  src/test-e2e/application/application-view-e2e.spec.ts
  src/test-e2e/cloud-foundry/cloud-foundry-list-cf-e2e.spec.ts
  src/test-e2e/e2e.ts
  src/test-e2e/endpoints/endpoints-e2e.spec.ts
  src/test-e2e/helpers/cf-e2e-helpers.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/list.po.ts
  src/tsconfig.spec.json
Labels: ready for review

#4390 Fix duplicated k8s docs
  deploy/kubernetes/README.md
Labels: ready for review

#4389 V4 Build Tweaks & Docs
  build/tools/v4-migration/migrate.sh
  docs/customizing.md
Labels: blocked, in progress

#4398 Build devkit outside of dist folder
  .gitignore
  angular.json
  src/frontend/packages/devkit/build.sh
  src/frontend/packages/devkit/tsconfig.json
Labels: ready for review

#4395 Theming improvements for page header
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.theme.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.theme.scss
  src/frontend/packages/theme/_helper.scss
Labels: ready for review

#4399 Ignore example packages when there's a stratos config file
  src/frontend/packages/devkit/src/lib/stratos.config.ts
Labels: ready for review

#4393 Fix CF App Restage
  src/frontend/packages/cloud-foundry/src/actions/app-metadata.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/application.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/feature-flags.actions.ts
  src/frontend/packages/cloud-foundry/src/actions/relation.actions.ts
  src/frontend/packages/cloud-foundry/src/entity-relations/entity-relations-validate.spec.ts
  src/frontend/packages/cloud-foundry/src/entity-relations/entity-relations.ts
  src/frontend/packages/cloud-foundry/src/entity-relations/processors/org-space-post-processor.ts
  src/frontend/packages/store/src/types/request.types.ts
Labels: ready for review

#4404 Update icons
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/routes-tab/routes-tab/routes-tab.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/quota-definition/quota-definition.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/space-quota-definition/space-quota-definition.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-spaces/tabs/cloud-foundry-space-summary/cloud-foundry-space-summary.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/packages/cloud-foundry/src/features/service-catalog/service-summary/service-summary.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-events/table-cell-event-actee/table-cell-event-actee.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-routes/cf-routes-list-config-base.ts
  src/frontend/packages/core/assets/endpoint-icons/cloudfoundry.png
  src/frontend/packages/core/assets/endpoint-icons/docker.png
  src/frontend/packages/core/assets/endpoint-icons/github-logo-light.png
  src/frontend/packages/core/assets/endpoint-icons/github-logo.png
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-status/table-cell-endpoint-status.component.html
  src/test-e2e/endpoints/endpoints.po.ts
Labels: ready for review

#4407 Theming improvements
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/sass/components/hyperlinks.theme.scss
  src/frontend/packages/core/src/features/dashboard/side-nav/side-nav.component.theme.scss
  src/frontend/packages/core/src/shared/components/intro-screen/intro-screen.component.theme.scss
  src/frontend/packages/core/src/shared/components/user-avatar/user-avatar.component.theme.scss
  src/frontend/packages/core/src/shared/components/user-profile-banner/user-profile-banner.component.theme.scss
  src/frontend/packages/devkit/src/lib/packages.ts
  src/frontend/packages/shared/src/components/stratos-title/stratos-title.component.theme.scss
  src/frontend/packages/theme/_helper.scss
Labels: ready for review

#4411 Reduce icon size in page sub-header (Desktop mode)
  src/frontend/packages/core/sass/mat-desktop.scss
Labels: ready for review
