Repository cloudfoundry/stratos, pull requests merged in 2020-05, with the labels that each got.

#4254 CF Push: Ensure we refresh token
  src/jetstream/plugins/cfapppush/deploy.go
Labels: ready for review

#4255 Fix uaa docs. Make UAA endpoint config simpler
  deploy/kubernetes/console/README.md
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#4226 Add docs for max list feature
  docs/cf-entity-scaling.md
Labels: ready for review

#4241 Ensure we filter out maxed results for local lists
  src/frontend/packages/store/src/monitors/pagination-monitor.ts
Labels: ready for review

#4252 Add nodeSelector implementation and tests to kubernetes helm deployment.
  deploy/kubernetes/console/templates/config-init.yaml
  deploy/kubernetes/console/templates/database.yaml
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/tests/config_init_test.yaml
  deploy/kubernetes/console/tests/database-test.yaml
  deploy/kubernetes/console/tests/deployment_test.yaml
Labels: in review

#4262 Helm Chart: Fix Helm 3 compatibility with Release.Time
  deploy/kubernetes/console/templates/deployment.yaml
Labels: ready for review

#4260 User Settings: Fix disabling of polling
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.html
Labels: ready for review

#4264 Helm node selector docs and values
  deploy/kubernetes/console/README.md
  deploy/kubernetes/console/templates/config-init.yaml
  deploy/kubernetes/console/templates/database.yaml
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#4269 E2E Cleanup script: clean other users
  deploy/ci/automation/e2e-clean-remnants.sh
Labels: ready for review

#4275 E2E Test improvements
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
  src/test-e2e/helpers/e2e-helpers.ts
  src/test-e2e/po/component.po.ts
  src/test-e2e/po/list.po.ts
Labels: ready for review

#4277 Add ability to provide a wildcard in path when matching urls
  docs/sso.md
  src/jetstream/default.config.properties
  src/jetstream/stringutils/utils.go
Labels: ready for review

#4276 Version bump and change log for 3.2.0
  CHANGELOG.md
  build/tools/changelog.sh
  package-lock.json
  package.json
Labels: ready for review

#4285 Fix issue where user profile is fetched on page change
  src/frontend/packages/core/src/core/core.module.ts
  src/frontend/packages/core/src/core/user-profile.service.ts
  src/frontend/packages/core/src/features/metrics/metrics.helpers.ts
  src/frontend/packages/core/src/features/user-profile/edit-profile-info/edit-profile-info.component.ts
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/store/src/actions/user-profile.actions.ts
  src/frontend/packages/store/src/effects/user-profile.effects.ts
Labels: ready for review

#4283 Fix icon alignment on service marketplace view
  src/frontend/packages/cloud-foundry/src/features/service-catalog/service-tabs-base/service-tabs-base.component.html
Labels: bug, ready for review

#4282 Only show metrics details on endpoint card/list when connected
  src/frontend/packages/core/src/features/metrics/metrics-endpoint-details/metrics-endpoint-details.component.ts
Labels: ready for review

#4291 Update change log for 3.2.0
  CHANGELOG.md
Labels: ready for review

#4289 CF Push: A better fix for the token expiry issue
  src/jetstream/plugins/cfapppush/connection_wrapper.go
  src/jetstream/plugins/cfapppush/deploy.go
  src/jetstream/plugins/cfapppush/info.go
  src/jetstream/plugins/cfapppush/main.go
  src/jetstream/plugins/cfapppush/pushapp.go
Labels: ready for review

#4068 [autoscaler] add custom metric support
  protractor.conf.js
  src/frontend/packages/cf-autoscaler/src/core/autoscaler-helpers/autoscaler-transform-metric.ts
  src/frontend/packages/cf-autoscaler/src/core/autoscaler-helpers/autoscaler-transform-policy.ts
  src/frontend/packages/cf-autoscaler/src/core/autoscaler-helpers/autoscaler-util.ts
  src/frontend/packages/cf-autoscaler/src/core/autoscaler-helpers/autoscaler-validation.ts
  src/frontend/packages/cf-autoscaler/src/core/autoscaler.module.ts
  src/frontend/packages/cf-autoscaler/src/core/autoscaler.routing.ts
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.html
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-credential/edit-autoscaler-credential.component.html
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-credential/edit-autoscaler-credential.component.scss
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-credential/edit-autoscaler-credential.component.spec.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-credential/edit-autoscaler-credential.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step2/edit-autoscaler-policy-step2.component.html
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step2/edit-autoscaler-policy-step2.component.scss
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step2/edit-autoscaler-policy-step2.component.ts
  src/frontend/packages/cf-autoscaler/src/features/edit-autoscaler-policy/edit-autoscaler-policy-step3/edit-autoscaler-policy-step3.component.ts
  src/frontend/packages/cf-autoscaler/src/store/app-autoscaler.actions.ts
  src/frontend/packages/cf-autoscaler/src/store/app-autoscaler.types.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler-entity-factory.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler-entity-generator.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler.effects.ts
  src/jetstream/plugins/autoscaler/autoscaler.go
  src/jetstream/plugins/autoscaler/main.go
  src/test-e2e/application/application-autoscaler-e2e.spec.ts
Labels: in review, ready for review

#4235 Fix table padding issue
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/manage-users-modify/manage-users-modify.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-events/cf-events-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-events/table-cell-event-actee/table-cell-event-actee.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-events/table-cell-event-action/table-cell-event-action.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-users-org-space-roles/cf-users-space-roles-list-config.service.ts
  src/frontend/packages/core/sass/components/mat-table.scss
  src/frontend/packages/core/src/shared/components/app-action-monitor/app-action-monitor.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table.component.scss
  src/frontend/packages/core/src/shared/components/list/list.component.scss
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
  src/test-e2e/po/checkbox.po.ts
Labels: ready for review

#4304 Fix autoscaler events page
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.html
  src/frontend/packages/cf-autoscaler/src/features/autoscaler-tab-extension/autoscaler-tab-extension.component.ts
  src/frontend/packages/cf-autoscaler/src/store/app-autoscaler.types.ts
  src/frontend/packages/cf-autoscaler/src/store/autoscaler-entity-generator.ts
  src/frontend/packages/core/src/shared/components/list/list.component.scss
  src/frontend/packages/core/src/shared/components/metrics-range-selector/metrics-range-selector.component.scss
  src/frontend/packages/core/src/shared/components/metrics-range-selector/metrics-range-selector.component.theme.scss
  src/frontend/packages/core/src/shared/services/metrics-range-selector.service.ts
Labels: ready for review

#4297 Update to latest Stratos icon font
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.eot
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.svg
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.ttf
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.woff
  src/frontend/packages/core/assets/fonts/stratos/stratos-icons.woff2
Labels: in review, ready for review

#4306 Allow e2e test logging to be controlled by label on PR
  deploy/ci/travis/check-e2e-pr.sh
  deploy/ci/travis/run-e2e-tests.sh
  src/test-e2e/helpers/request-helpers.ts
Labels: e2e-debug, ready for review

#4288 Fixes related to using browser back to starting point
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/shared/services/side-panel.service.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-pagination-request-pipeline.ts
  src/frontend/packages/store/src/entity-request-pipeline/pagination-request-base-handlers/pagination-iterator.pipe.ts
Labels: ready for review

#4311 Wrap check for missing env var for forked CI
  deploy/ci/travis/job-e2e-before_script.sh
Labels: ready for review

#4307 update kubernetes deploy doc to reference uaa.endpoint
  deploy/kubernetes/console/README.md
Labels: community

#4317 Fix misaligned user button
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.scss
Labels: ready for review

#4328 Check sso whitelist in more places
  src/jetstream/authuaa.go
Labels: ready for review

#4329 3.2.1 Version bump and release notes
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready for review
