Repository cloudfoundry/stratos, pull requests merged in 2020-12, with the labels that each got.

#4815 chore: remove trailing comma as this is a non standard
  src/tsconfig.json
  src/tsconfig.lib.json
  src/tsconfig.spec.json
Labels: community

#4818 Allow backup/restore plugin to be enabled/disabled
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.html
  src/frontend/packages/core/src/features/endpoints/endpoints-page/endpoints-page.component.ts
  src/jetstream/config.example
  src/jetstream/plugins/backup/main.go
Labels: in review, ready for review

#4810 Home page: Make configurable showing all endpoints or just favorites
  src/frontend/packages/core/src/features/dashboard/dashboard-base/dashboard-base.component.ts
  src/frontend/packages/core/src/features/home/home/home-page.component.html
  src/frontend/packages/core/src/features/home/home/home-page.component.ts
  src/frontend/packages/core/src/logged-in.service.ts
  src/frontend/packages/store/src/actions/dashboard-actions.ts
  src/frontend/packages/store/src/app-state.ts
  src/frontend/packages/store/src/reducers/dashboard-reducer.ts
  src/frontend/packages/store/src/selectors/dashboard.selectors.ts
  src/frontend/packages/store/src/types/auth.types.ts
  src/frontend/packages/store/src/types/dashboard.types.ts
  src/frontend/packages/store/testing/src/store-test-helper.ts
  src/jetstream/auth_test.go
  src/jetstream/config.dev
  src/jetstream/config.example
  src/jetstream/info.go
  src/jetstream/repository/interfaces/structs.go
Labels: comments-addressed, ready for review

#4820 Fix ever-increasing array of snackbar references
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-space-details/card-cf-space-details.component.ts
  src/frontend/packages/core/src/shared/services/snackbar.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/services/kubernetes.analysis.service.ts
Labels: ready for review

#4405 Persist list settings over refresh
  src/frontend/packages/cloud-foundry/src/features/applications/application-wall/application-wall.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/application-wall/application-wall.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/create-application/create-application.component.ts
  src/frontend/packages/cloud-foundry/src/features/services/services-wall/services-wall.component.html
  src/frontend/packages/cloud-foundry/src/features/services/services-wall/services-wall.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/create-application/create-application-step1/create-application-step1.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app/cf-app-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-routes/cf-routes-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instances-wall-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-org-space-service.service.ts
  src/frontend/packages/cloud-foundry/src/shared/services/current-user-permissions-and-cfchecker.service.spec.ts
  src/frontend/packages/core/src/core/permissions/current-user-permissions.service.spec.ts
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.html
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.scss
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-pagination-controller.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/packages/core/src/shared/components/list/list.component.html
  src/frontend/packages/core/src/shared/components/list/list.component.ts
  src/frontend/packages/core/src/shared/components/list/list.component.types.ts
  src/frontend/packages/core/src/shared/components/list/max-list-message/max-list-message.component.html
  src/frontend/packages/core/src/shared/components/polling-indicator/polling-indicator.component.html
  src/frontend/packages/store/src/actions/list.actions.ts
  src/frontend/packages/store/src/actions/pagination.actions.ts
  src/frontend/packages/store/src/effects/auth.effects.ts
  src/frontend/packages/store/src/helpers/local-storage-service.ts
  src/frontend/packages/store/src/helpers/store-helpers.ts
  src/frontend/packages/store/src/reducers.module.ts
  src/frontend/packages/store/src/reducers/list.reducer.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-reset-pagination.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-reset-sort-filter.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer-set-params.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination.reducer.ts
  src/frontend/packages/store/src/types/pagination.types.ts
  src/frontend/packages/store/testing/src/store-test-helper.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-page.po.ts
  src/test-e2e/endpoints/endpoints.po.ts
  src/test-e2e/marketplace/delete-service-instance-e2e.spec.ts
  src/test-e2e/marketplace/delete-ups-service-instance-e2e.spec.ts
  src/test-e2e/po/list.po.ts
Labels: ready for review

#4826 Don't use generic url validation for kube endpoints
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-entity-generator.ts
Labels: ready for review

#4827 Improvement and fix for no-content component
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-edit/table-cell-edit.component.scss
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.html
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.scss
  src/frontend/packages/core/src/shared/components/no-content-message/no-content-message.component.theme.scss
Labels: ready for review

#4829 Minor Kube Fixes
  src/frontend/packages/kubernetes/src/helm/monocular/chart-details/chart-details.component.html
  src/frontend/packages/kubernetes/src/helm/monocular/chart-details/chart-details.component.ts
  src/frontend/packages/kubernetes/src/helm/tabs/catalog-tab/catalog-tab.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/home/kubernetes-home-card.component.html
Labels: ready for review

#4822 K8s: More resource support - refinements
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.html
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.scss
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.ts
  src/frontend/packages/core/src/shared/components/json-viewer/json-viewer.component.html
  src/frontend/packages/core/src/shared/components/json-viewer/json-viewer.component.scss
  src/frontend/packages/core/src/shared/components/json-viewer/json-viewer.component.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/helpers/action-or-config-helpers.ts
  src/frontend/packages/core/src/shared/components/sidepanel-preview/sidepanel-preview.component.html
  src/frontend/packages/core/src/shared/components/sidepanel-preview/sidepanel-preview.component.scss
  src/frontend/packages/core/src/shared/components/sidepanel-preview/sidepanel-preview.component.ts
  src/frontend/packages/core/src/shared/services/side-panel.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-selector/analysis-report-selector.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/home/kubernetes-home-card.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-entity-generator.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-analysis-report/kubernetes-namespace-analysis-report.component.html
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-analysis-report/kubernetes-namespace-analysis-report.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-pods/kubernetes-namespace-pods.component.html
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-pods/kubernetes-namespace-pods.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-pods/kubernetes-namespace-pods.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-preview/kubernetes-namespace-preview.component.html
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-preview/kubernetes-namespace-preview.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-preview/kubernetes-namespace-preview.component.spec.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-preview/kubernetes-namespace-preview.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-services/kubernetes-namespace-services.component.html
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-services/kubernetes-namespace-services.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-services/kubernetes-namespace-services.component.spec.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace-services/kubernetes-namespace-services.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace.component.html
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-resource-viewer/kubernetes-resource-viewer.component.html
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-resource-viewer/kubernetes-resource-viewer.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-resource-viewer/kubernetes-resource-viewer.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-resource/kubernetes-resource-list/kubernetes-resource-list.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-ui-service.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes.module.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes.routing.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes.setup.module.ts
  src/frontend/packages/kubernetes/src/kubernetes/list-types/kubernetes-pods/kubernetes-pods-list-config.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/services/kubernetes.analysis.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/action-builders/kube-resource.action-builder.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/action-builders/kube.action-builders.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/kube-resource.actions.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/kube.types.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/kubernetes.actions.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/kubernetes.effects.ts
  src/frontend/packages/store/src/operators.ts
  src/frontend/packages/store/src/user-favorite-manager.ts
  src/jetstream/go.sum
Labels: ready for review

#4825 Add additional information to new kube resource tables
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-entity-generator.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/kube.types.ts
Labels: ready for review

#4833 Improve SSO documentation with detailed UAA setup
  website/docs/advanced/sso.md
Labels: community

#4830 Add additional kube resources to Workload page
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-entity-generator.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-resource/kubernetes-resource-list/kubernetes-resource-list.component.html
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-resource/kubernetes-resource-list/kubernetes-resource-list.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/action-builders/kube-resource.action-builder.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/action-builders/kube.action-builders.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/kube-resource.actions.ts
  src/frontend/packages/kubernetes/src/kubernetes/store/kube.types.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/list-types/helm-release-pods-list-config.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/list-types/helm-release-services-list-config.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/helm-release-tab-base/helm-release-socket-service.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/helm-release-tab-base/helm-release-tab-base.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-helper.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-pods/helm-release-pods-tab.component.html
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-pods/helm-release-pods-tab.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-pods/helm-release-pods-tab.component.spec.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-pods/helm-release-pods-tab.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-services/helm-release-services-tab.component.html
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-services/helm-release-services-tab.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-services/helm-release-services-tab.component.spec.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-services/helm-release-services-tab.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/store/workloads.actions.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/workloads.module.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/workloads.routing.ts
Labels: ready for review

#4839 Fix edit profile button visibility
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.ts
Labels: ready for review

#4840 Ensure initial/default plugins.yaml is included in build
  deploy/Dockerfile.bk
Labels: ready for review

#4841 Ensure we copy plugins.yaml for AIO and Cloud Foundry
  deploy/Dockerfile.all-in-one
  deploy/cloud-foundry/build.sh
Labels: ready for review

#4845 Fix filter by name in generic kube resource list
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-resource/kubernetes-resource-list/kubernetes-resource-list.component.ts
Labels: ready for review

#4844 Helm Chart: Ensure mariadb port value can be set
  deploy/kubernetes/console/values.schema.json
Labels: ready for review

#4846 Update changelog with latest fix
  CHANGELOG.md
Labels: ready for review
