Repository cloudfoundry/stratos, pull requests merged in 2020-04, with the labels that each got.

#4198 Fix security issue with kind-of package
  package.json
  package.md
Labels: ready for review

#4186 Fix App Redeploy
  src/frontend/packages/cloud-foundry/src/entity-action-builders/git-action-builder.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/gitscm-tab/gitscm-tab.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-step2/deploy-application-step2.component.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-steps.types.ts
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application.component.html
  src/frontend/packages/cloud-foundry/src/store/effects/deploy-app.effects.ts
  src/frontend/packages/cloud-foundry/src/store/types/deploy-application.types.ts
  src/frontend/packages/core/src/shared/components/list/list-types/github-commits/github-commits-data-source.ts
  src/frontend/packages/core/src/shared/components/list/list-types/github-commits/github-commits-list-config-app-tab.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/github-commits/github-commits-list-config-deploy.service.ts
  src/jetstream/plugins/cfapppush/types.go
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/po/deploy-app.po.ts
  src/test-e2e/po/menu.po.ts
Labels: comments-addressed, ready for review

#4196 Improvements to Manage Users Stepper
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/manage-users-modify/manage-users-modify.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/manage-users-modify/manage-users-modify.component.scss
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/users/manage-users/manage-users-modify/manage-users-modify.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cf-role-checkbox/cf-role-checkbox.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/cf-role-checkbox/cf-role-checkbox.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-confirm-roles/table-cell-confirm-role-add-rem/table-cell-confirm-role-add-rem.component.html
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-user.service.ts
Labels: ready for review

#4203 Ensure we don't loop between events and error page
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.html
  src/frontend/packages/core/src/features/error-page/error-page/error-page.component.ts
  src/frontend/packages/core/src/features/event-page/events-page/events-page.component.html
  src/frontend/packages/core/src/features/event-page/events-page/events-page.component.ts
Labels: ready for review

#4207 Fix issue where CF Quota's `Maximum Application Instance Memory Usage` not formatted correctly
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/quota-definition/quota-definition.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/space-quota-definition/space-quota-definition.component.html
Labels: ready for review

#4191 Add support for editing endpoint info
  src/frontend/packages/core/sass/mat-desktop.scss
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint-step/edit-endpoint-step.component.html
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint-step/edit-endpoint-step.component.scss
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint-step/edit-endpoint-step.component.spec.ts
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint-step/edit-endpoint-step.component.ts
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint.component.html
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint.component.scss
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint.component.spec.ts
  src/frontend/packages/core/src/features/endpoints/edit-endpoint/edit-endpoint.component.ts
  src/frontend/packages/core/src/features/endpoints/endpoint-helpers.ts
  src/frontend/packages/core/src/features/endpoints/endpoints.module.ts
  src/frontend/packages/core/src/features/endpoints/endpoints.routing.ts
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.scss
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.theme.scss
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/store/src/actions/endpoint.actions.ts
  src/frontend/packages/store/src/effects/endpoint.effects.ts
  src/frontend/packages/store/src/reducers/internal-events.reducer.ts
  src/frontend/packages/store/src/types/endpoint.types.ts
  src/jetstream/authcnsi.go
  src/jetstream/cnsi.go
  src/jetstream/main.go
  src/jetstream/repository/cnsis/cnsis.go
  src/jetstream/repository/cnsis/pgsql_cnsis.go
  src/test-e2e/endpoints/endpoints-register-e2e.spec.ts
Labels: comments-addressed, ready for review

#4182 Bump CF CLI to 6.49.0
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/build-tab/build-tab.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/deploy-application/deploy-application-deployer.ts
  src/frontend/packages/core/src/shared/components/list/list-types/github-commits/github-commits-list-config-deploy.service.ts
  src/jetstream/go.mod
  src/jetstream/go.sum
  src/jetstream/plugins/cfapppush/app-repository.go
  src/jetstream/plugins/cfapppush/deploy.go
  src/jetstream/plugins/cfapppush/info.go
  src/jetstream/plugins/cfapppush/main.go
  src/jetstream/plugins/cfapppush/progress_bar.go
  src/jetstream/plugins/cfapppush/push_actor.go
  src/jetstream/plugins/cfapppush/pushapp.go
  src/jetstream/plugins/cfapppush/pushapp/pushapp.go
  src/jetstream/plugins/cfapppush/types.go
  src/jetstream/repository/interfaces/structs.go
  src/test-e2e/application/application-deploy-e2e.spec.ts
  src/test-e2e/application/application-deploy-local-e2e.spec.ts
Labels: in review, ready for review

#4148 Add ability to show a custom component on click of a table's row
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-variables/cf-app-variables-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app/cf-apps-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-endpoints/cf-endpoints-list-config.service.ts
  src/frontend/packages/core/src/features/about/diagnostics-page/diagnostics-page.component.ts
  src/frontend/packages/core/src/shared/components/app-action-monitor/app-action-monitor.component.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source-types.ts
  src/frontend/packages/core/src/shared/components/list/list-table/app-table-cell-default/app-table-cell-default.component.html
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-expander/table-cell-expander.component.html
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-expander/table-cell-expander.component.scss
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-expander/table-cell-expander.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-expander/table-cell-expander.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-icon/table-cell-icon.component.html
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-icon/table-cell-icon.component.scss
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-icon/table-cell-icon.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-icon/table-cell-icon.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-side-panel/table-cell-side-panel.component.html
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell/table-cell.component.html
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-row/table-row-expanded-service.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-row/table-row.component.html
  src/frontend/packages/core/src/shared/components/list/list-table/table-row/table-row.component.scss
  src/frontend/packages/core/src/shared/components/list/list-table/table-row/table-row.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-row/table-row.component.theme.scss
  src/frontend/packages/core/src/shared/components/list/list-table/table-row/table-row.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table.component.html
  src/frontend/packages/core/src/shared/components/list/list-table/table.component.scss
  src/frontend/packages/core/src/shared/components/list/list-table/table.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table.types.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-status/table-cell-endpoint-status.component.html
  src/frontend/packages/core/src/shared/components/list/list.component.html
  src/frontend/packages/core/src/shared/components/list/list.component.types.ts
Labels: ready for review

#4217 Tweak text of 'Fetch All' button
  src/frontend/packages/core/src/shared/components/list/max-list-message/max-list-message.component.html
Labels: ready for review

#4218 Update changelog and version for 3.1.0
  CHANGELOG.md
  build/tools/changelog.js
  build/tools/changelog.sh
  package-lock.json
  package.json
Labels: ready for review

#4220 Fix CI pipelines
  deploy/ci/build-aio-image-canary.yml
  deploy/ci/build-aio-image-nightly.yml
  deploy/ci/build-aio-image-stable.yml
  deploy/ci/build-images.yml
  deploy/ci/console-dev-releases.yml
  deploy/ci/console-make-release.yml
  deploy/ci/console-nightly-releases.yml
Labels: ready for review

#4221 CI: Remove latest tag from tasks
  deploy/ci/tasks/build-images/build-helm.yml
  deploy/ci/tasks/build-images/generate-certs.yml
  deploy/ci/tasks/dev-releases/check-docker-image.yml
  deploy/ci/tasks/dev-releases/check-gh-release.yml
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/ci/tasks/dev-releases/create-helm-pr.yml
  deploy/ci/tasks/dev-releases/create-nightly-chart.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
  deploy/ci/tasks/dev-releases/make-release.yml
  deploy/ci/tasks/dev-releases/update-gh-release.yml
  deploy/ci/tasks/release/sync-official-release.yml
  deploy/ci/tasks/run-unit-tests.yml
Labels: ready for review

#4222 Add helm configuration for new jetstream scaling env vars
  deploy/kubernetes/console/README.md
  deploy/kubernetes/console/templates/deployment.yaml
  deploy/kubernetes/console/values.yaml
Labels: ready for review

#4225 Update 3.1.0 release notes
  CHANGELOG.md
Labels: ready for review

#4224 Fix quote issue in helm template
  deploy/kubernetes/console/templates/deployment.yaml
Labels: ready for review

#4227 Update changelog tool to also show changes for fork
  build/tools/changelog.sh
Labels: ready for review
