Repository cloudfoundry/stratos, pull requests merged in 2020-11, with the labels that each got.

#4712 Improve password input fields
  src/frontend/packages/core/src/core/core.module.ts
  src/frontend/packages/core/src/core/not-setup-guard.service.ts
  src/frontend/packages/core/src/core/show-hide-button/show-hide-button.component.html
  src/frontend/packages/core/src/core/show-hide-button/show-hide-button.component.scss
  src/frontend/packages/core/src/core/show-hide-button/show-hide-button.component.spec.ts
  src/frontend/packages/core/src/core/show-hide-button/show-hide-button.component.ts
  src/frontend/packages/core/src/features/endpoints/backup-restore/backup-checkbox-cell/backup-checkbox-cell.component.scss
  src/frontend/packages/core/src/features/endpoints/backup-restore/backup-endpoints/backup-endpoints.component.html
  src/frontend/packages/core/src/features/endpoints/backup-restore/backup-endpoints/backup-endpoints.component.ts
  src/frontend/packages/core/src/features/endpoints/backup-restore/restore-endpoints/restore-endpoints.component.html
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/auth-forms/credentials-auth-form.component.html
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/auth-forms/credentials-auth-form.component.ts
  src/frontend/packages/core/src/features/login/login-page/login-page.component.html
  src/frontend/packages/core/src/features/login/login-page/login-page.component.ts
  src/frontend/packages/core/src/features/setup/local-account-wizard/local-account-wizard.component.html
  src/frontend/packages/core/src/features/setup/local-account-wizard/local-account-wizard.component.ts
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/packages/core/src/features/user-profile/edit-profile-info/edit-profile-info.component.html
  src/frontend/packages/core/src/features/user-profile/edit-profile-info/edit-profile-info.component.ts
  src/frontend/packages/core/src/shared/components/unique.directive.ts
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-aws-auth-form/kubernetes-aws-auth-form.component.html
  src/frontend/packages/kubernetes/src/kubernetes/auth-forms/kubernetes-aws-auth-form/kubernetes-aws-auth-form.component.ts
Labels: comments-addressed, ready for review

#4728 Improve workload header
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-runner/analysis-report-runner.component.html
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-runner/analysis-report-runner.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-selector/analysis-report-selector.component.html
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-selector/analysis-report-selector.component.scss
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-selector/analysis-report-selector.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/release/tabs/helm-release-summary-tab/helm-release-summary-tab.component.scss
Labels: ready for review

#4739 Move analyzer info button into analyze drop down
  README.md
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-runner/analysis-report-runner.component.html
  src/frontend/packages/kubernetes/src/kubernetes/analysis-report-viewer/analysis-report-runner/analysis-report-runner.component.scss
Labels: ready for review

#4714 Improve filtering helm chart list by repo
  deploy/kubernetes/console/README.md
  src/frontend/packages/kubernetes/sass/_all-theme.scss
  src/frontend/packages/kubernetes/src/helm/list-types/monocular-charts-data-source.ts
  src/frontend/packages/kubernetes/src/helm/list-types/monocular-charts-list-config.service.ts
  src/frontend/packages/kubernetes/src/helm/monocular/chart-item/chart-item.component.html
  src/frontend/packages/kubernetes/src/helm/tabs/catalog-tab/catalog-tab.component.html
  src/frontend/packages/kubernetes/src/helm/tabs/catalog-tab/catalog-tab.component.scss
  src/frontend/packages/kubernetes/src/helm/tabs/catalog-tab/catalog-tab.component.theme.scss
  src/frontend/packages/kubernetes/src/helm/tabs/catalog-tab/catalog-tab.component.ts
  website/docs/developer/developers-guide-kube-local-dev.md
Labels: comments-addressed, ready for review

#4729 Fix install/upgrade chart error notifications
  src/frontend/packages/core/sass/components/mat-snack-bar.scss
  src/frontend/packages/core/src/shared/components/stepper/steppers/steppers.component.ts
  src/frontend/packages/core/src/styles.scss
  src/jetstream/plugins/kubernetes/install_release.go
  src/jetstream/repository/interfaces/jetstream_error.go
Labels: comments-addressed, ready for review

#4730 Ensure `are you still there` dialog is closed before showing logging out page
  src/frontend/packages/core/src/core/log-out-dialog/log-out-dialog.component.spec.ts
  src/frontend/packages/core/src/core/log-out-dialog/log-out-dialog.component.ts
  src/frontend/packages/core/src/core/permissions/stratos-user-permissions.checker.ts
  src/frontend/packages/core/src/logged-in.service.ts
Labels: comments-addressed, ready for review

#4743 Prevent icons from being displayed as text while font loads
  src/frontend/packages/core/sass/icons.scss
Labels: ready for review

#4737 Merge v4.2.1
  CHANGELOG.md
  deploy/kubernetes/console/README.md
  package-lock.json
  package.json
  src/jetstream/main.go
Labels: ready for review

#4718 Show source of chart if artifact hub and another repo are connected
  src/frontend/packages/kubernetes/src/helm/list-types/monocular-chart-card/monocular-chart-card.component.html
  src/frontend/packages/kubernetes/src/helm/list-types/monocular-chart-card/monocular-chart-card.component.ts
  src/frontend/packages/kubernetes/src/helm/monocular/chart-item/chart-item.component.html
  src/frontend/packages/kubernetes/src/helm/monocular/chart-item/chart-item.component.ts
  src/frontend/packages/kubernetes/src/helm/monocular/list-item/list-item.component.html
  src/frontend/packages/kubernetes/src/helm/monocular/list-item/list-item.component.scss
  src/frontend/packages/kubernetes/src/helm/monocular/list-item/list-item.component.ts
Labels: comments-addressed, ready for review

#4745 Add 4.2.1 version to docs site
  website/internal-versions.json
Labels: documentation, ready for review

#4746 Re-add password placeholder to auth form
  src/frontend/packages/core/src/features/endpoints/connect-endpoint-dialog/auth-forms/credentials-auth-form.component.html
Labels: ready for review

#4749 Highlight list filters & fix cf events list clear filter
  src/frontend/packages/cloud-foundry/src/shared/components/cloud-foundry-events-list/cloud-foundry-events-list.component.ts
  src/frontend/packages/core/src/shared/components/list/list.component.theme.scss
Labels: comments-addressed, ready for review

#4754 Version bump and changelog for 4.3.0 release
  CHANGELOG.md
  deploy/kubernetes/console/README.md
  package-lock.json
  package.json
Labels: ready for review

#4756 Ensure any existing helm chart repo filter is shown in header on nav
  src/frontend/packages/kubernetes/src/helm/tabs/catalog-tab/catalog-tab.component.ts
Labels: ready for review

#4763 Fix issue with analyzers pod stuck in CC when upgrading
  deploy/kubernetes/console/templates/analyzers.yaml
Labels: ready for review

#4759 Update CI resource images to ghcr.io
  deploy/ci/build-aio-image-canary.yml
  deploy/ci/build-aio-image-nightly.yml
  deploy/ci/build-aio-image-stable.yml
  deploy/ci/console-make-release.yml
  deploy/ci/scripts/Dockerfile.stratos-ci
  deploy/ci/scripts/build-git-tag-resource.sh
  deploy/ci/tasks/dev-releases/check-docker-image.yml
  deploy/ci/tasks/dev-releases/check-gh-release.yml
  deploy/ci/tasks/dev-releases/create-chart.yml
  deploy/ci/tasks/dev-releases/create-helm-pr.yml
  deploy/ci/tasks/dev-releases/create-nightly-chart.yml
  deploy/ci/tasks/dev-releases/generate-tag-files.yml
  deploy/ci/tasks/dev-releases/make-release.yml
  deploy/ci/tasks/dev-releases/update-gh-release.yml
Labels: ready for review

#4764 Fix issue where Stratos SSO failed to show
  src/jetstream/main.go
  src/jetstream/middleware.go
  src/jetstream/session.go
Labels: ready for review

#4770 Fix permission issue in docker all in one image
  deploy/Dockerfile.all-in-one
Labels: ready for review

#4771 Update website version, tweak github action
  .github/workflows/documentation-versioning.yml
  website/add-version.sh
  website/internal-versions.json
Labels: ready for review

#4766 Improve the presentation of advanced options in endpoint registration
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.html
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.scss
  src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.ts
Labels: ready for review

#4758 Reduce size of text and icons in page header
  src/frontend/packages/core/sass/mat-desktop.scss
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.scss
Labels: ready for review

#4386 Add support for no authentication
  src/frontend/packages/core/src/app.component.spec.ts
  src/frontend/packages/core/src/core/permissions/stratos-user-permissions.checker.ts
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.html
  src/frontend/packages/core/src/features/user-profile/profile-info/profile-info.component.ts
  src/frontend/packages/core/src/logged-in.service.spec.ts
  src/frontend/packages/core/src/logged-in.service.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.html
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/jetstream/auth.go
  src/jetstream/auth_test.go
  src/jetstream/authlocal.go
  src/jetstream/authnone.go
  src/jetstream/authuaa.go
  src/jetstream/main.go
  src/jetstream/mock_server_test.go
  src/jetstream/plugins/userinfo/main.go
  src/jetstream/plugins/userinfo/noauth_user.go
  src/jetstream/repository/interfaces/auth.go
  src/jetstream/repository/interfaces/config/config.go
  src/jetstream/repository/interfaces/structs.go
  src/jetstream/repository/mock_interfaces/mock_auth.go
  src/jetstream/session.go
  src/jetstream/setup_console.go
Labels: ready for review

#4776 Prevent password show/hide icon from receiving focus
  src/frontend/packages/cloud-foundry/src/features/home/card-cf-recent-apps/card-cf-recent-apps.component.ts
  src/frontend/packages/cloud-foundry/src/features/home/card-cf-recent-apps/compact-app-card/compact-app-card.component.ts
  src/frontend/packages/cloud-foundry/src/features/home/cfhome-card/cfhome-card.component.ts
  src/frontend/packages/core/src/core/show-hide-button/show-hide-button.component.html
  src/frontend/packages/core/src/features/home/home.types.ts
  src/frontend/packages/core/src/features/home/home/favorites-side-panel/favorites-side-panel.component.ts
  src/frontend/packages/core/src/features/home/home/home-page-endpoint-card/home-page-endpoint-card.component.spec.ts
  src/frontend/packages/core/src/features/home/home/home-page-endpoint-card/home-page-endpoint-card.component.ts
  src/frontend/packages/core/src/features/home/home/home-page.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/home/kubernetes-home-card.component.ts
  src/frontend/packages/store/src/user-favorite-manager.ts
Labels: ready for review

#3987 Create defaults list component
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cloud-foundry-organizations.component.html
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cloud-foundry-organizations.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cloud-foundry-organizations.component.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-quotas/cloud-foundry-quotas.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-orgs/cf-orgs-data-source.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-orgs/cf-orgs-list-config.service.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-orgs/cf-orgs-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces/cf-spaces-list-config.service.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-user.service.ts
  src/frontend/packages/core/src/shared/components/list/data-sources-controllers/list-data-source-config.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/entity-list-view/entity-list-view.component.html
  src/frontend/packages/core/src/shared/components/list/list-generics/entity-list-view/entity-list-view.component.scss
  src/frontend/packages/core/src/shared/components/list/list-generics/entity-list-view/entity-list-view.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/entity-list-view/entity-list-view.component.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/helpers/action-or-config-helpers.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/helpers/entity-catalogue-list-config.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/helpers/list-host.directive.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/list-config-provider.types.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/list-providers/action-list-config-provider.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/list-providers/action-or-entity-config-list-config-provider.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/list-providers/entity-config-list-config-provider.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/list-view/list-view.component.html
  src/frontend/packages/core/src/shared/components/list/list-generics/list-view/list-view.component.scss
  src/frontend/packages/core/src/shared/components/list/list-generics/list-view/list-view.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-generics/list-view/list-view.component.ts
  src/frontend/packages/core/src/shared/components/list/list.component.types.ts
  src/frontend/packages/core/src/shared/components/list/simple-list/simple-list.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/simple-list/simple-list.component.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/map-multi-endpoint.pipes.ts
  src/frontend/packages/store/src/types/pagination.types.ts
Labels: ready for review

#4783 Fix lint issue on main branch
  src/frontend/packages/cloud-foundry/src/shared/data-services/cf-user.service.ts
Labels: ready for review

#4779 Travis E2E: Don't fail if we can't access the GitHub API
  deploy/ci/travis/run-e2e-tests.sh
Labels: ready for review

#4781 Fix ngDestroy bug on list view component
  src/frontend/packages/core/src/shared/components/list/list-generics/list-view/list-view.component.ts
Labels: ready for review

#4778 Fix size and position of header notification badge icon
  src/frontend/packages/core/sass/mat-desktop.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.scss
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.theme.scss
Labels: ready for review

#4757 Tidy up and refactor user favorites
  src/frontend/packages/cf-autoscaler/src/store/autoscaler-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-catalog.ts
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/cf-favorites-helpers.ts
  src/frontend/packages/cloud-foundry/src/cf-metadata-types.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cf/cloud-foundry-tabs-base/cloud-foundry-tabs-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cf-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cf-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/packages/core/src/app.module.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.spec.ts
  src/frontend/packages/core/src/core/entity-favorite-star/entity-favorite-star.component.ts
  src/frontend/packages/core/src/features/home/home.module.ts
  src/frontend/packages/core/src/features/home/home.types.ts
  src/frontend/packages/core/src/features/home/home/default-endpoint-home-component/default-endpoint-home-component.component.html
  src/frontend/packages/core/src/features/home/home/default-endpoint-home-component/default-endpoint-home-component.component.scss
  src/frontend/packages/core/src/features/home/home/default-endpoint-home-component/default-endpoint-home-component.component.spec.ts
  src/frontend/packages/core/src/features/home/home/default-endpoint-home-component/default-endpoint-home-component.component.ts
  src/frontend/packages/core/src/features/home/home/favorites-meta-card/favorites-meta-card.component.html
  src/frontend/packages/core/src/features/home/home/favorites-meta-card/favorites-meta-card.component.scss
  src/frontend/packages/core/src/features/home/home/favorites-meta-card/favorites-meta-card.component.ts
  src/frontend/packages/core/src/features/home/home/home-page-endpoint-card/home-page-endpoint-card.component.html
  src/frontend/packages/core/src/features/home/home/home-page-endpoint-card/home-page-endpoint-card.component.ts
  src/frontend/packages/core/src/features/home/home/home-page.component.scss
  src/frontend/packages/core/src/features/home/home/home-page.component.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-favorite/table-cell-favorite.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoints-list-config.service.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/kubernetes/src/helm/helm-entity-generator.ts
  src/frontend/packages/kubernetes/src/kubernetes/home/kubernetes-home-card.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-entity-catalog.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-entity-generator.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-tab-base/kubernetes-tab-base.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/list-types/kubernetes-namespaces/kubernetes-namespaces-list-config.service.ts
  src/frontend/packages/kubernetes/src/kubernetes/services/kubernetes-endpoint.service.ts
  src/frontend/packages/store/src/effects/user-favorites-effect.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog-entity/entity-catalog-entity.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.types.ts
  src/frontend/packages/store/src/favorite-config-mapper.ts
  src/frontend/packages/store/src/operators.ts
  src/frontend/packages/store/src/public-api.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/user-favorites-groups.reducer.spec.ts
  src/frontend/packages/store/src/reducers/current-user-roles-reducer/user-favorites-groups.reducer.ts
  src/frontend/packages/store/src/selectors/favorite-groups.selectors.ts
  src/frontend/packages/store/src/types/favorite-groups.types.ts
  src/frontend/packages/store/src/types/recently-visited.types.ts
  src/frontend/packages/store/src/types/user-favorite-manager.types.ts
  src/frontend/packages/store/src/types/user-favorites.types.ts
  src/frontend/packages/store/src/user-favorite-helpers.ts
  src/frontend/packages/store/src/user-favorite-manager.ts
Labels: ready for review

#4802 Move test docker app off of docker hub to avoid rate limiting
  src/test-e2e/application/application-deploy-helper.ts
Labels: ready for review

#4799 Handle table cell get/setters better
  src/frontend/packages/cf-autoscaler/src/shared/list-types/app-autoscaler-metric-chart/app-autoscaler-metric-chart-card/app-autoscaler-metric-chart-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-instance/table-cell-cf-cell/table-cell-cf-cell.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app/table-cell-app-cforgspace/table-cell-app-cforgspace.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app/table-cell-app-status/table-cell-app-status.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-confirm-roles/table-cell-confirm-org-space/table-cell-confirm-org-space.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-feature-flags/table-cell-feature-flag-description/table-cell-feature-flag-description.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-routes/table-cell-route-apps-attached/table-cell-route-apps-attached.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-broker/table-cell-service-broker.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-cf-breadcrumbs/table-cell-service-cf-breadcrumbs.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-provider/table-cell-service-provider.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-references/table-cell-service-references.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-tags/table-cell-service-tags.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-apps-attached/table-cell-service-instance-apps-attached.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-instance-tags/table-cell-service-instance-tags.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-users/cf-permission-cell.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/service-plans/table-cell-service-plan-price/table-cell-service-plan-price.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/user-provided-service-instance-card/user-provided-service-instance-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/schema-form/schema-form.component.ts
  src/frontend/packages/core/src/features/metrics/metrics-endpoint-details/metrics-endpoint-details.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/app-table-cell-default/app-table-cell-default.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-actions/table-cell-actions.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-boolean-indicator/table-cell-boolean-indicator.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-edit/table-cell-edit.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-expander/table-cell-expander.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-favorite/table-cell-favorite.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-icon/table-cell-icon.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-radio/table-cell-radio.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-side-panel/table-cell-side-panel.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-address/table-cell-endpoint-address.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-details/table-cell-endpoint-details.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-name/table-cell-endpoint-name.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/table-cell-endpoint-status/table-cell-endpoint-status.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kube-config-registration/kube-config-import/kube-config-table-import-status/kube-config-table-import-status.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kube-config-registration/kube-config-selection/kube-config-table-cert/kube-config-table-cert.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/list-types/kubernetes-pods/kubernetes-pod-containers/kubernetes-pod-containers.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/list-types/kubernetes-pods/kubernetes-pod-status/kubernetes-pod-status.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/list-types/kubernetes-service-ports/kubernetes-service-ports.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/workloads/list-types/helm-release-card/helm-release-card.component.ts
Labels: ready for review

#4800 Fix link for metrics endpoints
  src/frontend/packages/store/src/stratos-entity-generator.ts
Labels: ready for review

#4796 Fix issue where username/password are not encoded for basic auth
  src/jetstream/authuaa.go
  src/jetstream/plugins/metrics/main.go
Labels: ready for review

#4797 Update terminology for SSO Accept List and add to Helm Chart docs
  CHANGELOG.md
  deploy/kubernetes/console/README.md
  deploy/kubernetes/console/templates/deployment.yaml
  src/jetstream/authcnsi.go
  src/jetstream/authuaa.go
  src/jetstream/config.dev
  src/jetstream/config.example
  src/jetstream/console-database.db2
  src/jetstream/main.go
  src/jetstream/plugins/metrics/cloud_foundry.go
  src/jetstream/repository/interfaces/config/config.go
  src/jetstream/repository/interfaces/structs.go
  website/docs/advanced/sso.md
Labels: ready for review

#4805 Fix double build when using ng serve
  src/frontend/packages/devkit/src/build/extensions.ts
Labels: ready for review

#4809 Fix alignment of no content messages on home page view
  src/frontend/packages/core/src/features/home/home/home-page.component.html
  src/frontend/packages/core/src/features/home/home/home-page.component.scss
Labels: ready for review

#4808 fix unicode rendering in application logstreams
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/log-stream-tab/log-stream-tab.component.ts
Labels: community, ready for review

#4798 User Favorites: Further refactoring to simplify the code base
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/cf-favorites-helpers.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/application-tabs-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cf-organization-base/cloud-foundry-organization-base.component.ts
  src/frontend/packages/cloud-foundry/src/features/cf/tabs/cf-organizations/cf-organization-spaces/cloud-foundry-space-base/cloud-foundry-space-base.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app/card/card-app.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-orgs/cf-org-card/cf-org-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces/cf-space-card/cf-space-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-cards/meta-card/meta-card-base/meta-card.component.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-entity-generator.ts
  src/frontend/packages/kubernetes/src/kubernetes/kubernetes-namespace/kubernetes-namespace.component.ts
  src/frontend/packages/store/src/entity-catalog/entity-catalog.types.ts
  src/frontend/packages/store/src/user-favorite-helpers.ts
  src/frontend/packages/store/src/user-favorite-manager.ts
Labels: ready for review
