Repository cloudfoundry/stratos, pull requests merged in 2020-01, with the labels that each got.

#4074 Separate Autoscaler E2E tests as a new job in Travis
  .travis.yml
  protractor.conf.js
  src/test-e2e/endpoints/endpoints-connect-e2e.spec.ts
Labels: ready for review

#4075 Skip autoscaler e2e tests
  .travis.yml
Labels: ready for review

#4077 Automation: Fix check that a Stratos system is responding
  deploy/ci/automation/check-stratos.sh
Labels: ready for review

#4070 edit app: fixed validation for mem and disk quota
  src/frontend/packages/cloud-foundry/src/features/applications/edit-application/edit-application.component.html
  src/frontend/packages/cloud-foundry/src/features/applications/edit-application/edit-application.component.ts
Labels: ready for review

#4072 Optionally set jetstream log output to JSON
  src/jetstream/default.config.properties
  src/jetstream/main.go
Labels: ready for review

#4049 Fix long running service actions
  src/frontend/packages/core/src/features/applications/application.service.spec.ts
  src/frontend/packages/core/src/features/service-catalog/service-tabs-base/service-tabs-base.component.ts
  src/frontend/packages/core/src/features/service-catalog/services-helper.ts
  src/frontend/packages/core/src/features/service-catalog/services.service.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/add-service-instance-base-step/add-service-instance-base-step.component.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/csi-mode.service.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/select-plan-step/select-plan-step.component.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/specify-details-step/specify-details-step.component.spec.ts
  src/frontend/packages/core/src/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/app-table-cell-default/app-table-cell-default.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service/table-cell-service.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/packages/core/src/shared/services/long-running-cf-op.service.ts
  src/frontend/packages/core/src/shared/services/long-running-op.service.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/frontend/packages/store/src/actions/service-instances.actions.ts
  src/frontend/packages/store/src/effects/service-instance.effects.ts
  src/frontend/packages/store/src/store.module.ts
  src/jetstream/passthrough.go
  src/test-e2e/marketplace/create-service-instances-bind-app-e2e.spec.ts
Labels: ready for review

#4060 Update tsconfigs for Angular 8 migration
  browserslist
  build/karma.test.reporter.js
  src/tsconfig.json
  src/tsconfig.lib.json
Labels: in review, ready for review

#4064 Blitz - Add table view to marketplace service table
  src/frontend/packages/cloud-foundry/src/features/applications/application-delete/application-delete.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/cloud-foundry.module.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/components.module.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-service-card/cf-service-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/cf-services-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-active/table-cell-service-active.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-active/table-cell-service-active.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-active/table-cell-service-active.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-active/table-cell-service-active.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-bindable/table-cell-service-bindable.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-bindable/table-cell-service-bindable.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-bindable/table-cell-service-bindable.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-bindable/table-cell-service-bindable.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-cf-breadcrumbs/table-cell-service-cf-breadcrumbs.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-cf-breadcrumbs/table-cell-service-cf-breadcrumbs.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-cf-breadcrumbs/table-cell-service-cf-breadcrumbs.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-cf-breadcrumbs/table-cell-service-cf-breadcrumbs.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-provider/table-cell-service-provider.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-provider/table-cell-service-provider.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-provider/table-cell-service-provider.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-provider/table-cell-service-provider.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-references/table-cell-service-references.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-references/table-cell-service-references.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-references/table-cell-service-references.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-references/table-cell-service-references.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-tags/table-cell-service-tags.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-tags/table-cell-service-tags.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-tags/table-cell-service-tags.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-tags/table-cell-service-tags.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/select-service/select-service.component.spec.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-quota/add-quota.component.spec.ts
  src/frontend/packages/core/src/features/cloud-foundry/add-quota/add-quota.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service/table-cell-service.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service/table-cell-service.component.ts
  src/frontend/packages/core/src/shared/components/service-instance-last-op/service-instance-last-op.component.ts
  src/test-e2e/marketplace/marketplace-create-service-instances-e2e.spec.ts
Labels: ready for review

#4063 Blitz - Add actions to app service table, add delete org button to org summary
  src/frontend/packages/cloud-foundry/src/features/applications/application-delete/delete-app-instances/app-delete-instances-routes-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application-delete/delete-app-instances/delete-app-instances.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application/application-tabs-base/tabs/services-tab/services-tab.component.spec.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.html
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-organizations/cloud-foundry-organization-summary/cloud-foundry-organization-summary.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/data-services/service-action-helper.service.ts
  src/frontend/packages/core/src/api-driven-views/features/api-endpoint-type-select-page/api-endpoint-type-select-page.component.ts
  src/frontend/packages/store/src/helpers/reducer.helper.ts
Labels: ready for review

#4031 Add support for setup UI for local admin account
  build/bk-build.sh
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/src/app.routing.ts
  src/frontend/packages/core/src/features/login/login-page/login-page.component.ts
  src/frontend/packages/core/src/features/setup/local-account-wizard/local-account-wizard.component.html
  src/frontend/packages/core/src/features/setup/local-account-wizard/local-account-wizard.component.scss
  src/frontend/packages/core/src/features/setup/local-account-wizard/local-account-wizard.component.spec.ts
  src/frontend/packages/core/src/features/setup/local-account-wizard/local-account-wizard.component.ts
  src/frontend/packages/core/src/features/setup/setup-welcome/setup-welcome.component.html
  src/frontend/packages/core/src/features/setup/setup-welcome/setup-welcome.component.scss
  src/frontend/packages/core/src/features/setup/setup-welcome/setup-welcome.component.spec.ts
  src/frontend/packages/core/src/features/setup/setup-welcome/setup-welcome.component.ts
  src/frontend/packages/core/src/features/setup/setup.module.ts
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.ts
  src/frontend/packages/core/src/shared/components/page-header/page-header.component.ts
  src/frontend/packages/core/src/shared/components/stepper/steppers/steppers.component.scss
  src/frontend/packages/core/src/shared/components/tile-selector-tile/tile-selector-tile.component.html
  src/frontend/packages/core/src/shared/components/tile-selector-tile/tile-selector-tile.component.scss
  src/frontend/packages/core/src/shared/components/tile-selector-tile/tile-selector-tile.component.spec.ts
  src/frontend/packages/core/src/shared/components/tile-selector-tile/tile-selector-tile.component.theme.scss
  src/frontend/packages/core/src/shared/components/tile-selector-tile/tile-selector-tile.component.ts
  src/frontend/packages/core/src/shared/components/tile-selector/tile-selector.component.html
  src/frontend/packages/core/src/shared/components/tile-selector/tile-selector.component.scss
  src/frontend/packages/core/src/shared/components/tile-selector/tile-selector.component.spec.ts
  src/frontend/packages/core/src/shared/components/tile/tile-selector.types.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/frontend/packages/store/src/actions/setup.actions.ts
  src/frontend/packages/store/src/effects/dashboard.effects.ts
  src/frontend/packages/store/src/effects/uaa-setup.effects.ts
  src/frontend/packages/store/src/reducers/uaa-setup.reducers.ts
  src/frontend/packages/store/src/types/uaa-setup.types.ts
  src/jetstream/auth.go
  src/jetstream/auth_test.go
  src/jetstream/main.go
  src/jetstream/setup_console.go
Labels: in review, ready for review

#4076 Enable autoscaler E2E tests
  .travis.yml
Labels: in progress

#4083 Remove out of date screenshots and update old docs
  README.md
  docs/features.md
  docs/images/screenshots/README.md
  docs/images/screenshots/app-events.png
  docs/images/screenshots/app-log-stream.png
  docs/images/screenshots/app-ssh.png
  docs/images/screenshots/app-summary.png
  docs/images/screenshots/app-wall.png
  docs/images/screenshots/cloud-foundry-space.png
  docs/images/screenshots/cloud-foundry.png
  docs/images/screenshots/endpoints.png
  docs/images/screenshots/login-page.png
  docs/roadmap.md
Labels: ready for review

#4080 Cf validation fix following v3 changes
  src/frontend/packages/cloud-foundry/src/cf-entity-generator.ts
  src/frontend/packages/cloud-foundry/src/entity-relations/entity-relation-tree.ts
  src/frontend/packages/cloud-foundry/src/features/applications/application.service.ts
  src/frontend/packages/core/src/core/entity-catalogue/entity-catalogue-entity.ts
  src/frontend/packages/core/src/shared/components/list/list-types/github-commits/github-commits-list-config-base.service.spec.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/map-multi-endpoint.pipes.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/normalize-entity-request-response.pipe.ts
Labels: comments-addressed, ready for review

#4071 Blitz - Copy component - Additional usages and fixes
  src/frontend/packages/cf-autoscaler/src/shared/card-autoscaler-default/card-autoscaler-default.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/add-service-instance/add-service-instance.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/select-plan-step/select-plan-step.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-app-uptime/card-app-uptime.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-info/card-cf-info.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-org-user-details/card-cf-org-user-details.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-space-details/card-cf-space-details.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/cards/card-cf-user-info/card-cf-user-info.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/components.module.ts
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/src/shared/components/code-block/code-block.component.theme.scss
  src/frontend/packages/core/src/shared/components/copy-to-clipboard/copy-to-clipboard.component.html
  src/frontend/packages/core/src/shared/components/copy-to-clipboard/copy-to-clipboard.component.scss
  src/frontend/packages/core/src/shared/components/copy-to-clipboard/copy-to-clipboard.component.theme.scss
  src/frontend/packages/core/src/shared/components/copy-to-clipboard/copy-to-clipboard.component.ts
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.html
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.scss
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/core/src/shared/components/metadata-item/metadata-item.component.html
  src/frontend/packages/core/src/shared/components/metadata-item/metadata-item.component.scss
  src/frontend/packages/core/src/shared/components/metadata-item/metadata-item.component.spec.ts
  src/frontend/packages/core/src/shared/components/metadata-item/metadata-item.component.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/cf-top-level-page.po.ts
  src/test-e2e/endpoints/endpoints.po.ts
Labels: in review, ready for review

#4084 Fix failing VCAP_SERVICE credentials check
  src/jetstream/datastore/database_cf_config.go
  src/jetstream/datastore/datastore.go
  src/jetstream/datastore/datastore_test.go
Labels: comments-addressed, ready for review

#4090 Reflect app title in setup screens
  src/frontend/packages/core/src/core/core.module.ts
  src/frontend/packages/core/src/core/core.types.ts
  src/frontend/packages/core/src/features/setup/local-account-wizard/local-account-wizard.component.html
  src/frontend/packages/core/src/features/setup/local-account-wizard/local-account-wizard.component.ts
  src/frontend/packages/core/src/features/setup/setup-welcome/setup-welcome.component.html
  src/frontend/packages/core/src/features/setup/setup-welcome/setup-welcome.component.ts
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.html
  src/frontend/packages/core/src/features/setup/uaa-wizard/console-uaa-wizard.component.ts
Labels: ready for review

#4091 Clean up more aggressively
  deploy/ci/automation/e2e-clean-remnants.sh
Labels: ready for review

#4092 Improve Manage Users E2E Tests
  src/test-e2e/cloud-foundry/manage-users-stepper-e2e.spec.ts
Labels: ready for review

#4094 Remove SetHeaderEvent
  src/frontend/packages/core/src/shared/components/list/list-types/endpoint/endpoint-card/endpoint-card.component.ts
  src/frontend/packages/store/src/actions/dashboard-actions.ts
Labels: ready for review

#4087 E2E Test tweaks and fixes for automated Jenkins tests
  deploy/ci/automation/cfpushtest.sh
  deploy/ci/automation/runandrecord.sh
  src/test-e2e/cloud-foundry/cf-level/manage-org-e2e.spec.ts
  src/test-e2e/cloud-foundry/cf-level/manage-quota-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/manage-space-quota-e2e.spec.ts
  src/test-e2e/cloud-foundry/org-level/mange-space-e2e.spec.ts
  src/test-e2e/cloud-foundry/quota-form-stepper-base.po.ts
  src/test-e2e/cloud-foundry/users-removal-e2e.helper.ts
Labels: ready for review

#4095 Favourite Card: Add icon for endpoints. Improve UX
  src/frontend/packages/core/sass/_all-theme.scss
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.html
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.scss
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.theme.scss
  src/frontend/packages/core/src/shared/components/favorites-meta-card/favorites-meta-card.component.ts
Labels: ready for review

#4098 Fix panic on backend error logging
  src/jetstream/main.go
Labels: ready for review

#4099 Update e2e docs
  docs/developers-guide-e2e-tests.md
  src/test-e2e/secrets.yaml.example
Labels: ready for review

#4102 Merge v2 master to master
  deploy/ci/automation/runandrecord.sh
  package.json
  src/frontend/packages/cloud-foundry/src/actions/service-instances.actions.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cell/cloud-foundry-cell.service.ts
  src/frontend/packages/cloud-foundry/src/features/cloud-foundry/tabs/cloud-foundry-cells/cloud-foundry-cells.component.ts
  src/frontend/packages/cloud-foundry/src/features/service-catalog/services-helper.ts
  src/frontend/packages/cloud-foundry/src/features/service-catalog/services.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/create-service-instance-helper.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/add-service-instance/specify-details-step/specify-details-step.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/components.module.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-instance/cf-app-instances-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-card/app-service-binding-card.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/app-sevice-bindings/app-service-binding-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/base-cf/base-cf-list-config.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-cell-health/cf-cell-health-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-cells/cf-cells-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-cells/cf-cells-list-config.service.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-routes/table-cell-route-apps-attached/table-cell-route-apps-attached.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-active/table-cell-service-active.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-services/table-cell-service-bindable/table-cell-service-bindable.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-name/table-cell-service-name.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.html
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.scss
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.spec.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-plan/table-cell-service-plan.component.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/service-instances/service-instances-data-source.ts
  src/frontend/packages/cloud-foundry/src/shared/components/list/list-types/services-wall/service-instance-card/service-instance-card.component.ts
  src/frontend/packages/core/src/core/endpoints.service.ts
  src/frontend/packages/core/src/features/cloud-foundry/cf-cell.helpers.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell-request-monitor-icon/table-cell-request-monitor-icon.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell/table-cell.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table-cell/table-cell.component.ts
  src/frontend/packages/core/src/shared/components/list/list-table/table.types.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service-last-op/table-cell-service-last-op.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service/table-cell-service.component.spec.ts
  src/frontend/packages/core/src/shared/components/list/list-types/cf-spaces-service-instances/table-cell-service/table-cell-service.component.ts
  src/frontend/packages/core/src/shared/services/long-running-op.service.ts
  src/frontend/packages/core/src/shared/shared.module.ts
  src/frontend/packages/store/src/entity-request-pipeline/entity-request-base-handlers/forced-action-type.helpers.ts
  src/frontend/packages/store/src/reducers/pagination-reducer/pagination-reducer.helper.ts
  src/frontend/packages/store/src/store.module.ts
Labels: ready for review

#4108 Fix user profile with ingress
  src/jetstream/plugins/userinfo/local_user.go
  src/jetstream/plugins/userinfo/main.go
  src/jetstream/plugins/userinfo/types.go
  src/jetstream/plugins/userinfo/uaa_user.go
Labels: ready for review

#4112 Fix for db pod being recreated with two instances
  deploy/kubernetes/console/templates/deployment.yaml
Labels: ready for review
